### ISSUE TITLE
Default SGE coredump size

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#102]
I am reminded from a matter at another shop that while CentOS sets the default core dump size to '0' SGE un-sets that to allow arbitrary core dump sizes.

I would suggest unless people are actively wanting coredumps on large memory machines they can be considerable in size. (Which was the issue I refer to elsewhere)

I can set SGE to limit default core to zero (no core dump) and if users wish to have a core they can set `ulimit -c unlimited` in their submit script.

**Comment by tatarsky** [comment]
Just seeing if anyone has a negative opinion of this or I will just do it and modify #24

**Comment by cdeboever3** [comment]
I think it's fine to turn off the core dumps.

**Comment by tatarsky** [comment]
Thanks. Made a note of it on our running SGE change issue!
