### ISSUE TITLE
Minor: Full name for user "aga"?

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#103]
I am working on additional account puppet automation so I can turn NIS finally off (its not being used if you recall due to an unknown resolution issue with SGE and its use).

I'd like to test the automation by having the full name field for `aga` be filled in and see if my "pw2puppet" script works. This should be done on fl-hn1. I am happy to enter it, I just need the full name. 

While we are in the neighborhood of that, `frauke` also does not have a full name.

**Comment by hirokomatsui** [comment]
Aga is Agnieszka D'Antonio-Chronowska, and frauke is Frauke Drees

**Comment by tatarsky** [comment]
Thanks. Using this to test.

**Comment by tatarsky** [comment]
And actually a very interesting test as I need to understand the impact of that single quote in a puppet manifest.

**Comment by tatarsky** [comment]
OK, I need to add a quick "escape single quotes" to the process...but generically its working. These mods will be on all systems shortly.

**Comment by tatarsky** [comment]
This test has worked for a few days and will shortly be added to cron. When I do so it will no longer be necessary to notify me of new accounts. They will just propagate on their hour. They currently do so on the hour which I recognize is slower than NIS, but figure its good enough for now. I can force this earlier and will add a section to the docs to do the same.

**Comment by tatarsky** [comment]
This is now in place having been manually tested several times. Next account we'll double check.
