### ISSUE TITLE
Install matlab on cluster

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#105]
Hi Paul, how's it going?

Have you had experience installing Matlab on Centos-based clusters? I wanted to run some Matlab scripts on cluster, but the installation for linux seems not support Centos. Please check this link:
[http://www.mathworks.com/support/sysreq/current_release/index.html;jsessionid=6a0683a44104042fed065d1b1799?refresh=true&sec=linux](url)

Do you think it can be installed on our cluster? before we purchase the license. 

Thanks!

**Comment by tatarsky** [comment]
Its going well. Hope your Friday is also going well. 

I have Matlab installed on other CentOS 6 based clusters so I'll confirm and check nothing has changed there. 

CentOS 6 is binary compatiable with RHEL (Red Hat Enterprise Linux) 6. 

When you see something saying it works for RHEL 6 it should work on CentOS 6. 

You sometimes need to play games with the scripts way of checking what version the OS is. 

I won't be able to work on this today but I'll keep you posted and if a module is required.

**Comment by tatarsky** [comment]
Oh, and I usually recommend the floating license method. Which is more expensive but far easier to maintain if you intend to run cluster jobs with Matlab. Otherwise you end up with a pile of node locked licenses or only certain nodes being able to run Matlab.

But let me review the 2015 version. Most of the ones I have are still 2013. 

I will mention BTW as a few folks have transitioned to it: https://www.gnu.org/software/octave/

**Comment by tatarsky** [comment]
It appears you can no longer download without requesting a trial. And I feel it best that be done by a UCSD account as in the end if you get a license you will enter it in that profile.

```
You need to be associated with a license to download products and updates

Visit the license center to associate with a license.
```

I'd suggest you make an account, request a trial. Look for the "RHEL 6 RPM" version. If you cannot locate it tell me what you see and I will assist.

**Comment by tatarsky** [comment]
And to confirm, checking another cluster I have all version 2013 there. So I've not tried 2015 but it said RHEL 6 was supported. When in doubt, email sales. 

```
$ cat /etc/redhat-release 
CentOS release 6.4 (Final)
$ matlab 

                            < M A T L A B (R) >
                  Copyright 1984-2013 The MathWorks, Inc.
                    R2013a (8.1.0.604) 64-bit (glnxa64)
                             February 15, 2013
```

**Comment by hurleyLi** [comment]
I have an account, and the trial version I can download for the latest release (R2015b) only contain Windows, Mac OS X, and linux (64-bit). Do I need to have a license to see more options? or will the linux version suffice?

**Comment by tatarsky** [comment]
I would see what options you get under Linux. Its changed since the last time I looked at it.

If it displays options for Linux distros, dump them here.

**Comment by hurleyLi** [comment]
There seem no other options under linux. 
It'll be more convenient if I give you my account name and pwd :)

hel070@ucsd.edu
Frazer00

I was following the "Trial software" link from the Matlab main page
[http://www.mathworks.com](url)

Thanks!

**Comment by tatarsky** [comment]
Under "Select Area of Trial Interest" I have clicked "Data Analytics" and "Computation Biology". Did you wish more?

**Comment by tatarsky** [comment]
I just picked a few more. Save the following.

```
Run the installer and log in as hel070@ucsd.edu and select license id 2826795.
```

**Comment by tatarsky** [comment]
OK. I've started the X11 installation on the head node. This will only be runable on the head node in trial mode IIRC. Its a large download. I will check back on it later. Once verified I'll let you know if it works and if so how to run it. 

You also might check with your central IT departments. Matlab is often bought at an institutional level or at least there are some license agreements already in place.

**Comment by hurleyLi** [comment]
Thanks Paul!

**Comment by tatarsky** [comment]
The program seems to require now an X11 session to run it and you have to login with your username/password to activate the license. 

Try logging into the head node and make sure you are running X11 back to your desktop with an xterm or something.

Then try:

```
cd /frazer01/software/MATLAB/R2015b/bin
./matlab
```

It may be possible to run as a CLI but when I do it seems to want a license file which we don't have let. But I am able to run the GUI (slowly since I am far away) which means at least it seems likely it would work once licenses are in place. I think sales contact is wise and discussion of how you intend to use it. If you do want it on cluster jobs I really recommend the floating license method.

**Comment by cdeboever3** [comment]
I believe some departments have licenses in place, though probably not any
we are directly affiliated with. Depending on how much we need to use
matlab, it may be cheaper to just run some jobs on a cluster that has
matlab already. I think Jacobs has it's own cluster that probably sports
matlab.

**Comment by tatarsky** [comment]
Generically I don't disagree with the above comment. I will repeat the comment that many of the groups I've dealt with have migrated to octave but the level of effort I'm not clear on. 
If you need the CLI I believe I have to obtain a file key which I can do perhaps shortly. Right now its using the "login to matlab" method of authorizing use and I have no idea how to do that from a command line.

**Comment by tatarsky** [comment]
The answer BTW to the original question of "Will it run" is I believe "yes". But some additional license work may be required. The trial seems to want you to use X11 and then login with @hurleyLi login above to activate the license. They've tightened that up a bit from past versions it seems. 

So advise if enough data or if further checks needed. I am heading out soon on some errands so just let me know.

**Comment by hurleyLi** [comment]
Thanks! I'll discuss with Kelly about the license. I really just need Matlab for this specific task I'm working on now, maybe we can talk to Jacobs. I also see this student account liscence, which is only $99, but not sure how does it work.

**Comment by tatarsky** [comment]
I believe this is resolved by being moved to another system and is not being pursued. Just trying to get a clearer picture of open issues for when I return.
