### ISSUE TITLE
Web server and public_web directories

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#11]
What are the plans for running a web server from one of the head nodes? I'd like to be able to host files over the web and run my [Jupyter notebooks](http://jupyter-notebook.readthedocs.org/en/latest/public_server.html). 

Can we add a directory like `public_web` in each home directory that points to a particular URL for each user? For instance, if I create a file /home/cdeboever/public_web/test.txt, I'd like to be able to view that file on the web at www.fl-hn1.ucsd.edu/cdeboever/test.txt.

**Comment by tatarsky** [comment]
The plans are for you to define it and we can go from there. My suggestion is perhaps the secondary head node would be a good place for Apache and I can start with the basic UserDir item you request above. 

The domain URL you describe however is not wise. You do not want to try to turn a host DNS record into a subdomain. I would recommend something more common like a lab domain such as:

```
frazerlab.ucsd.edu
```

And then populate URLs and web items in there. As that involves working with UCSD Networking folks it is up to you folks to pursue that. I cannot make DNS entries on the campus side.

**Comment by tatarsky** [comment]
Do you know if anything you need requires a newer Apache than 2.2? CentOS 6.X default is that series of Apache. I can use newer but doesn't sound like more than basic items are required. I will likely add PHP for Ganglia and Nagios.

**Comment by cdeboever3** [comment]
> My suggestion is perhaps the secondary head node would be a good place for Apache and I can start with the basic UserDir item you request above.

That's fine. I guess if we want to run notebooks on both head nodes we'll need Apache running on both. The domain URL is unimportant. @hirokomatsui can likely set up a lab domain.

> Do you know if anything you need requires a newer Apache than 2.2? 

I'm not aware of anything, I just need basic stuff. @hirokomatsui might have some requirements.

**Comment by tatarsky** [comment]
I will run apache on both! If we need more recent Apache its trivial to upgrade.

**Comment by tatarsky** [comment]
Do we feel that the regular DocumentRoot (not your personal UserDir) requires a great deal of space? I guess we can always alter that down the road. Note that the default UserDir URL involves a tilde character ala:

```
flh1.ucsd.edu/~cdeboever3/something.html
```

While mod_rewrite can be used to allow other variations of that the tilde triggers the UserDir expansion to look by default into ~/public_html of the username in question.

If the directory is made, it will begin serving files there. Note the user that serves the files is `apache` not your userid. So make sure its readable. 

I will setup a quick instance to play around. There are many options with Apache, but the above is the quickest.

**Comment by cdeboever3** [comment]
This is fine.

**Comment by tatarsky** [comment]
So I am going to start with "opt in" UserDir configs. They have two flavors of the module.
One says give me a list of users that we will expand ~username and one a list of who we won't do that for.
https://httpd.apache.org/docs/2.2/mod/mod_userdir.html

So I've started with just you and I for testing. Make a directory public_html and place an index.html there and see if you can see it at:

http://flh1.ucsd.edu/~cdeboever

**Comment by cdeboever3** [comment]
Yep that works for me.

**Comment by tatarsky** [comment]
OK. We should probably put something basic or a redirect to somewhere else for the actual DocumentRoot at:

http://flh1.ucsd.edu/

Currently its just the "new install" page. Perhaps a redirect to your lab pages for now? 

http://frazer.ucsd.edu/

**Comment by tatarsky** [comment]
I will be placing one of my "dashboards" on that page for now. With links to Ganglia and other tools when I finish those per #14

**Comment by tatarsky** [comment]
Believe we have a start on this conceptually. Closing until next request related to Apache.
