### ISSUE TITLE
flh2 down

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#110]
It went down at the same time that a lot of wait CPU showed up on FrazerLab Grid. What are those?

**Comment by tatarsky** [comment]
I tried to get answers to several items being run on flh2 I feel with poor levels of memory and cpu use via Git #109 . Nobody answered those queries and so I can only assume similar behaviors are involved until I can look at the logs. 

I will see if what you refer to is actually on flh2. (cpu wait is simply that...cpu time spent waiting on something...usually I/O)

I will look at the unit shortly but am not available right now.

**Comment by cdeboever3** [comment]
Thanks. I was confused about the different headings on the ganglia page but
I understand now. FrazerLab Grid includes both nodes and lustre machines.

**Comment by tatarsky** [comment]
Correct. The unit is actually in the process of rebooting but had kdump enabled and it was a kernel panic situation. So the dump of that image is still in process. When I get a few moments I will perform some investigations.

**Comment by cdeboever3** [comment]
Thanks I was working on flh2 but not doing anything intensive. It seems
that all of the opt queue nodes changed to all wait time all of a sudden
when flh2 went down, but the jobs didn't change at all (I'm running many
small jobs on there right now). Is it expected that these would be affected
by flh2 going down?

**Comment by tatarsky** [comment]
That would be due to them waiting on NFS from flhn2. flhn2 provides Lustre to the 1G only cnX nodes via NFS. 

Lustre is only available to systems with 10G at this time via direct Lustre mounts. As the CNX nodes are 1G only they are using flhn2 as a "middle man" for their access. 

See long discussion about non-10G lustre nodes and path to data in #83 

Cure is getting a 10G switch with copper ports so that the older 1G copper can be connected to the same subnet Lustre is served from directly.

**Comment by tatarsky** [comment]
That BTW was what I felt was the most _useful_ cure. Right now the cnX nodes are all basically bottlenecked at 1G max for all I/O. Besides the matter that they have no 10G connectivity to talk to Lustre via that subnet.

While I could attempt to bring Lustre to 1G directly the conversations I had with Intel was that it was a bit more complex than what I would prefer of having the storage kept to the storage 10G subnet....

So my prefered path is to bring the CNX nodes to that subnet and solve both performance and access at the same time.

Obviously I'd also like flhn2 to not crash. I'll look at that shortly. I believe from quick looks this is a delayed reaction to whatever occurred on the 18th....

**Comment by cdeboever3** [comment]
Ah ok I didn't realize they were going through flh2. Looking into this I
realized that there were some STAR indexes loaded into shared memory on
some nodes and flh1. We've removed them all now but I wonder if there was
one loaded on flh2 that was contributing to the memory problems.

**Comment by tatarsky** [comment]
I'll see if I can spot that. Usually Ganglia will state "shared" memory in use on its mem_report graph.
I also can clean such orphaned shared memory items from cron based on the "nattach" field being zero. 

I believe basically on the 18th the unit got hit hard in terms of ram use and my attempts to fix the items that were crashed out by that probably didn't really cleanly recover from that. 

Next time I will simply reboot it.

**Comment by cdeboever3** [comment]
Sounds good.

I see that qstat isn't working on flh2 (-bash: qstat: command not found).
Just wanted to bring that to your attention if it's unexpected. I'm going
to be away for a few hours, thanks for your help.

**Comment by tatarsky** [comment]
Logout/back in. /opt/sge mount restored and added to fstab.

**Comment by tatarsky** [comment]
Closing this in this form but making a new one to note the NFS -> Lustre plans.
