### ISSUE TITLE
High system CPU on n15 and n16

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#112]
I'm running a bunch of jobs that are all doing the same thing. I'm running 8 jobs per node on both the new nodes and old nodes. Looking at cpu_report, n15 and n16 are almost all system CPU while most of the other jobs are User. This seems weird to me because all the nodes are basically doing the same thing. 

It's also interesting that the newer nodes but not the older nodes have spikes of system CPU when they use the network:

![graph](https://cloud.githubusercontent.com/assets/755960/13380528/a2c9b21c-ddfa-11e5-80c4-ce35425a1974.png)
![graph 1](https://cloud.githubusercontent.com/assets/755960/13380531/b7b18bc8-ddfa-11e5-9e66-07f41bf04de5.png)

I don't remember seeing this when I've run these types of jobs in the past. 

I just wanted to point this stuff out because the behavior seems odd to me. I guess the n15/n16 system CPU is the larger issue because I don't think my jobs are doing much, but I can run the jobs again later.

**Comment by tatarsky** [comment]
Well for starters don't compare please the old nodes and the new nodes as the old nodes have no 10G or Lustre. 

I'll see if there is some reason for the difference in system cpu level on the new nodes.

**Comment by tatarsky** [comment]
Please confirm that this `pEmmax` process was being compared on all the nodes. I am attempting to strace it but we may need to try to reproduce with less of them running.

**Comment by tatarsky** [comment]
I have made one change on n15 based on a bug report involving the items I saw happening on n15. Can you please verify if n15 is performing more "work" than the NON-changed n16 now?

This may be a kernel bug. I disabled hugepage defrag

https://bugzilla.redhat.com/show_bug.cgi?id=879801

**Comment by cdeboever3** [comment]
Yeah I can see the change you made around 7am on the ganglia graphs. The
jobs started working and quickly finished it looks like. n16 is still
struggling. I ran a 4 jobs on both headnodes last night for testing
purposes and it looks like hn1 seems to have the same problem (lots of sys
cpu time) but hn2 doesn't.

Each job consists of a python process that spawns these pEmmax processes
over and over (between 1k and 10k times). Before each time pEmmax starts, I
have to delete and write a couple files (I'm writing the into /dev/shm).
The pEmmax part is fast, I think the bottleneck is more the file
operations. I run 8 jobs per node because I found that more than 8
generally decreases the overall amount of user CPU.

**Comment by tatarsky** [comment]
It seems whatever that is doing is triggering this fragmentation bug. I am not clear what the "cure" is at the moment compared to a workaround. Let me issue the same disabling command on n16.

**Comment by tatarsky** [comment]
Same command now also run on fl-hn1. Seems similar.

**Comment by tatarsky** [comment]
So I suspect depending on the size of these /dev/shm files that is creating the memory fragmentation that is triggering this bug. My question is can the files be re-used perhaps? Or do you really have to create/delete them? What "goes on in those files"?

**Comment by cdeboever3** [comment]
Unfortunately I think I need to create them for now. Running pEmmax
consists of running the "reml" step and then the "assoc" step. The reml
step creates a file that is needed as input for the assoc step. Both of
these steps require input files. Every time I run pEmmax, I'm permuting my
data beforehand, so I have to regenerate some of the input files that and
re-run the reml step. My python script does the permutations and runs both
steps.

I think it should be possible to implement the permutations in C, pass
pEmmax what it needs, and run both steps without ever writing to a file.
However, I don't know C and so I haven't tried to do this. I'm almost done
with pEmmax I hope, but if the lab continues to use it with permutations
then someone should try to fix this. For reference, the pEmmax source is in
/software/EPACTS-3.2.6/src (the EPACTS software is a wrapper around pEmmax
that I bypassed but was useful in understand how pEmmax works). My wrapper
for running pEmmax using permutations is at
/projects/CARDIPS/analysis/cardips-ipsc-eqtl/scripts/run_emmax.py.

**Comment by tatarsky** [comment]
Well basically I can disable this defrag on nodes and see if we see other issues. I've never had to do that but I've not encountered this before ;)
If its fixed in a newer kernel revision that requires some downtime per node and debug. So for now I will disable the defrag.

**Comment by tatarsky** [comment]
Disabled on the head nodes and new nodes. I left it alone on the old nodes for now out of curiosity. The bug report seems to blame some esoteric combination of cores and memory levels.

**Comment by tatarsky** [comment]
So the implication here is "go do this more ;)"

**Comment by cdeboever3** [comment]
Thanks, I've run this analysis several times and this is the first time
I've ever seen the problem. At some point in the near future (~1 month)
I'll know that I don't need to do this again and we can re-enable if you'd
like.

**Comment by tatarsky** [comment]
Its not set to retain on reboot so sounds good. Added to "things I've seen" file ;)

**Comment by cdeboever3** [comment]
> So the implication here is "go do this more ;)"

I probably will be running similar analyses this week although without the permutations (so the python script just runs one pEmmax reml and assoc and then is done) so we can see how those go.

**Comment by tatarsky** [comment]
Ack'd.

**Comment by tatarsky** [comment]
I believe this is resolved from the graphs but I'll monitor for it. May be able to make a Nagios check....

**Comment by cdeboever3** [comment]
I didn't see the problem anymore when I was running this stuff several days ago so I think it's fine to close if you'd like.

**Comment by tatarsky** [comment]
Leaving open to try to find a Nagios check to detect it happening rather than spot it on the graph.

**Comment by tatarsky** [comment]
OK. I have one in test that will warn me if sys goes above 10%. I'll tune that if its too high or too low. Closing for now.
