### ISSUE TITLE
SQLite file I/O error

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#113]
I'm having a problem to run perl SQLite module on compute nodes. The following perl script works on the head nodes:

> perl
> use DBI;
> my $dbh = DBI->connect("dbi:SQLite:dbname=/frazer01/publicdata/polyphen-2.2.2/ucsc/hg19/genes/knownGene.sqlite", "","");
> my $sth = $dbh->prepare("SELECT \* FROM knownGene");

but not on the compute nodes with the error:
DBD::SQLite::db prepare failed: disk I/O error at - line 3.

When I copy the db file to the local drive, it works fine:

> perl
> use DBI;
> my $dbh = DBI->connect("dbi:SQLite:dbname=/scratch/knownGene.sqlite", "","");
> my $sth = $dbh->prepare("SELECT \* FROM knownGene");

It behaves same even when I run the SQLite with the read only modes. Probably the files on the shared drive, frazer01, are looked somehow. Any idea?

**Comment by tatarsky** [comment]
I suspect this is the same "localflock" v.s. "flock" mount option we discussed back here in Git #25.

We changed the lock default only on the head nodes and many of these file based databases depend on flock to ensure cluster filesystem access. And Lustre by default I believe answers "I am not going to guarantee a locking method until you tell me to do so"

So same basic question as #25 . 

Will you be using this database and expect locking to function from multiple nodes at the same time?

Then we would have to schedule a time to change the lock mount per node or gradually over time.

**Comment by tatarsky** [comment]
BTW, if you decide before people notice the Lustre nodes are quite idle the remounting could be pretty quick. But the key question remains:

Do you need coherent locking between nodes to the same file....

**Comment by tatarsky** [comment]
I will also repeat here the manpage sentence about performance gains if the sqlite locking is all within the same node. 

"Lustre supports posix locking semantics and usually Lustre clients are mounted with "-o flock" option to have cluster wide locking consistency. If you know that multiple processes on same client node will be writing to a file (instead of processes on different client nodes) then consider mounting Lustre client with "-o localflock" instead of "-o flock". This will reduce amount of RPCs sent to MDS for Lustre operations. "

**Comment by hirokomatsui** [comment]
I will work on this on the flh1 or flh2 for now. Since SQLite is not a server/client software, it makes more sense that using it on only on the head nodes.
Also for the future, there's an option sqlite_use_immediate_transaction in newer version of DBD::SQLite, which probably can avoid this problem. The current installed version is 1.27 and the option's available later than 1.30_02.

**Comment by tatarsky** [comment]
We're currently just running the "stock" DBD-SQLite RPM.

```
perl-DBD-SQLite-1.27-3.el6.x86_64
```

I can take a look at bumping that or you can always build your own Perl module tree and change your include path in the script.
