### ISSUE TITLE
MySQL data directory

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#114]
Probably it's similar problem with the previous SQLite, I have a problem to create MySQL data files on /frazer01 instead of on the local drive on flh1.
I've tried the two ways:
https://dev.mysql.com/doc/refman/5.7/en/symbolic-links.html
https://dev.mysql.com/doc/refman/5.7/en/tablespace-placing.html
both did not work with errors.

**Comment by tatarsky** [comment]
We were going to look at the options for this under #62. I won't have time this week or next.

**Comment by hirokomatsui** [comment]
OK, I'm closing this issue then.

**Comment by tatarsky** [comment]
Although wait, you said you tried this in flh1?

**Comment by tatarsky** [comment]
flh1 already is mounted localflock....where did you try to place the database dirs? And what permissions?

**Comment by hirokomatsui** [comment]
I've tried to create the files under
/home/hiroko
with the full permission and only to the owner of mysql:mysql

**Comment by tatarsky** [comment]
OK. Let me look at that for a moment.

**Comment by tatarsky** [comment]
OK, noting the use of the example for alternate dirs produces:

```
ERROR 1030 (HY000): Got error 168 from storage engine
```

Will investigate a bit more later today. Unsure if that is a similar lock matter or not.

**Comment by hirokomatsui** [comment]
Yes, that's exactly the same error I saw.

**Comment by tatarsky** [comment]
I'm trying to determine if its InnoDB v.s. Lustre or MyISAM v.s. Lustre. As I believe the default is InnoDB now.

**Comment by tatarsky** [comment]
Try now. Its actually because the mysql account isn't on the metadata server and so the attempt to write gets blocked. Without that as long as the dir is `mysql:mysql` owned its been working.

```
> ls -al /frazer01/mysql/
total 12
drwxrwxr-x  3 mysql mysql 4096 Feb 29 16:24 .
>  create database paultest;
Query OK, 1 row affected (0.00 sec)
mysql> use paultest
mysql> CREATE TABLE t1 (c1 INT PRIMARY KEY) DATA DIRECTORY = '/frazer01/mysql';
Query OK, 0 rows affected (0.27 sec)

> ls -al /frazer01/mysql/paultest/
total 104
drwxr-x--- 2 mysql mysql  4096 Feb 29 16:24 .
drwxrwxr-x 3 mysql mysql  4096 Feb 29 16:24 ..
-rw-r----- 1 mysql mysql 98304 Feb 29 16:24 t1.ibd

```

I'm curious how well it works but that gets a test done. Going to close #62 and track effort here. The fact we already had locking on fl-hn1 means I believe this was the bottleneck. There is another error when locking is disabled. 

Also be very very sure from what I've read you don't just point another Mysql daemon at the same dir. Its apparently not that easy....

**Comment by hirokomatsui** [comment]
That worked for me as well. Thanks!

**Comment by tatarsky** [comment]
I am very very curious how well it works performance wise. If you give it some large data sets please let me know what you think.

**Comment by hirokomatsui** [comment]
Sure, Naoki and I will work on that soon.
