### ISSUE TITLE
loading R modules

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#115]
loading specific R modules doesn't change my path sometimes,

For example module add R/3.1.1 will not change my R environment from R 3.2.2.  
Can this be fixed in some way?

**Comment by tatarsky** [comment]
I am on a project right now but I'll send you a set of items to debug this when I get a little bit of extra time. Just letting you know I saw it and will assist.

**Comment by tatarsky** [comment]
Are you doing the following? Note the unload of the default R module:

```
$ module add R
$ which R
/frazer01/software/R-3.2.2/bin/R
$ module unload R
$ module load R/3.1.1
$ which R
/frazer01/software/R-3.1.1/bin/R
```

**Comment by djakubosky** [comment]
I think the problem was that there was another R in my anaconda/bin that
kept appearing in the path

On Monday, March 14, 2016, tatarsky notifications@github.com wrote:

> Are you doing the following? Note the unload of the default R module:
> 
> $ module add R
> $ which R
> /frazer01/software/R-3.2.2/bin/R
> $ module unload R
> $ module load R/3.1.1
> $ which R
> /frazer01/software/R-3.1.1/bin/R
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/115#issuecomment-196432673.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
Module will not remove or replace paths you have added. Only ones it knows it set. 

What adds that personal path?

If you _append_ that path in a bash config file, module by default _prepends_ paths. 

So module will always win. Or should...

**Comment by djakubosky** [comment]
So what adds that is actually configuring an R kernal in the jupyter notebook.  Following the default instructions will install a copy of R in your anaconda/bin which I didn't realize.  Apparently there are ways around this.  

I had my module adds above the 
`export PATH="/frazer01/home/djakubosky/software/anaconda/bin:$PATH"`
statement added by the anaconda installer thereby making this priority

This is good to keep in mind as people start running many types of kernals in the jupyter notebooks.

**Comment by tatarsky** [comment]
What I mean by _append_ is this. You would have to test that it still does what you want.

```
 export PATH="$PATH:/frazer01/home/djakubosky/software/anaconda/bin"
```

**Comment by djakubosky** [comment]
gotcha, I could do that
