### ISSUE TITLE
I believe you folks are in a break???

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#116]
I might want to attempt a item with Lustre config at some point this week. I show one job running and while I believe my item will not impact said job might be nice to consider a maintenance window. 

But it also might just be a quiet Monday. So advise if perhaps there is a good time to consider about lets say 4 hours of possible interruption.

**Comment by cdeboever3** [comment]
I think it's more a quiet Monday, but I personally am fine with setting up
a maintenance window this week. I don't know of any times that are better
than others so maybe throw at a time that works for you?

**Comment by tatarsky** [comment]
Basically I wanted to try two things:
1. Test a failover manually of the Metadata servers
2. Attempt to see if I can do a direct Lustre mount from an old CNXX node via a different method.

Neither will likely cause problems but I didn't want a full load of jobs out there. Maybe Wednesday morning?

**Comment by cdeboever3** [comment]
Wed. morning fine with me, anyone else have anything important during that
time?

**Comment by nariai** [comment]
I'm fine anytime this week.

**Comment by tatarsky** [comment]
OK. Currently I'll attempt the items Wednesday morning early. If I see a bunch of jobs I may skip it.

**Comment by tatarsky** [comment]
Sorry for the lack of status. I have completed the one item with risk. Took me awhile to do it.

**Comment by tatarsky** [comment]
I have been unable to figure out the second item. So my opinion on that remains the best way to solve is bring the older nodes to the 10G "side" via a 100/1000/10000 CAT6 switch.
