### ISSUE TITLE
Try to install pysam

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#117]
Hi guys, @tatarsky @cdeboever3 @djakubosky , I'm trying to install the python pysam package. The conda install gives old version, so I tryied 
`pip install pysam`
But I got this error:

```
 gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ipysam -I. -Ihtslib -I/frazer01/home/hel070/anaconda3/include/python3.5m -c htslib/hfile_libcurl.c -o build/temp.linux-x86_64-3.5/htslib/hfile_libcurl.o -Wno-unused -Wno-strict-prototypes -Wno-sign-compare -Wno-error=declaration-after-statement
    htslib/hfile_libcurl.c: In function ‘easy_errno’:
    htslib/hfile_libcurl.c:93: error: ‘CURLE_NOT_BUILT_IN’ undeclared (first use in this function)
    htslib/hfile_libcurl.c:93: error: (Each undeclared identifier is reported only once
    htslib/hfile_libcurl.c:93: error: for each function it appears in.)
    error: command 'gcc' failed with exit status 1
```

Did any of you have this error before? Do you have any idea how should I fix it. 

Thanks!

**Comment by cdeboever3** [comment]
Did you try loading the gcc module? module load gcc

**Comment by tatarsky** [comment]
is there something wrong with the pysam module?

 python/2.7/pysam/0.8.3

**Comment by hurleyLi** [comment]
@cdeboever3 yes, I load gcc `/frazer01/software/gcc-4.8.5/bin/gcc`
@tatarsky I'm using the python from conda, is python/2.7/pysam/0.8.3 a general python package on the cluster? Can I run this from by conda python somehow?

**Comment by tatarsky** [comment]
The pysam module is part of the system python collection. So no, you can't use it from conda.
That error looks like some dependency not being met.

**Comment by tatarsky** [comment]
Make sure the "pip" you are using BTW is the one you think it is. `which pip` is a good idea.

**Comment by hurleyLi** [comment]
this is my pip: `~/anaconda2/bin/pip`
along the thought of some dependency not being met, I found this
"The system curl from 10.7.5 doesn't define CURLE_NOT_BUILT_IN, whereas everything from 10.8 seems to do so."
Maybe because the version of libcurl ?

**Comment by tatarsky** [comment]
Its possible. I'll look more later. Or compile a local libcurl and link to it. System curl is 7.19. If enough people want a module for a new curl let me know.

**Comment by cdeboever3** [comment]
I do have pysam 0.8.3 installed in several of my conda environments so I
was able to do it at some point. I would've used pip because the conda
version is old as you mentioned. Maybe they've changed something since I
installed it.

**Comment by tatarsky** [comment]
I'm happy to toss up a recent libcurl but you'd have to manually handle adding the libraries and includes.

**Comment by hurleyLi** [comment]
The current pip pysam version is 0.8.4, let me try to manually install the pysam 0.8.3 version first.

**Comment by tatarsky** [comment]
Ah, interesting. Pysam historically has been a "amusing" piece of code.

**Comment by hurleyLi** [comment]
Joaquin had problem installing pysam before, so he just directly copy the package folder from Chris's anacodna folder `/frazer01/home/cdeboever/software/anaconda/envs/cardips/lib/python2.7/site-packages/pysam`, and it works for him. 
I also copied the folder under my anaconda, and it looks like it works for now. Not sure whether it needs any dependent folder or not when the program is running, I'll wait to see if the program can finish normally.

**Comment by cdeboever3** [comment]
Did installing 0.8.3 not work? I think you can specify the version via pip
as well. Just wondering for future reference.

**Comment by hurleyLi** [comment]
This is what I got from from `pip search pysam`
`djangosaml2 (0.13.0)           - pysaml2 integration in Django
djangosaml2-dj16 (0.10.0)      - pysaml2 integration in Django 1.6
djangosaml2-knaperek (0.14.0)  - pysaml2 integration for Django
pysam-arm-linux (0.8.3)        - pysam for ARM (armv7l) Linux GNUroot Debian on Nvidia Shield Tablet [Tegra K1]
pysaml2 (4.0.2)                - Python implementation of SAML Version 2
pysamstats (0.24.2)            - A Python utility for calculating statistics against genome position based on sequence alignments from a SAM, BAM or CRAM file.
pysam (0.8.4)                  - pysam
djangosaml2_tenant (0.1.0)     - pysaml2 integration for multi-tenant in Django
djangosaml2-bernii (0.11.2)    - pysaml2 integration in Django
pysample (0.1)                 - A python package than can be used as a model/template for writing, testing and deploying python packages.
pysamlsp (0.1.4)               - A service provider implementation for SAML2.0.`
It looks like it only has the 0.8.4 version. 
or should I use "pysam-arm-linux (0.8.3)"

**Comment by hurleyLi** [comment]
```
djangosaml2 (0.13.0)           - pysaml2 integration in Django
djangosaml2-dj16 (0.10.0)      - pysaml2 integration in Django 1.6
djangosaml2-knaperek (0.14.0)  - pysaml2 integration for Django
pysam-arm-linux (0.8.3)        - pysam for ARM (armv7l) Linux GNUroot Debian on Nvidia Shield Tablet [Tegra K1]
pysaml2 (4.0.2)                - Python implementation of SAML Version 2
pysamstats (0.24.2)            - A Python utility for calculating statistics against genome position based on sequence alignments from a SAM, BAM or CRAM file.
pysam (0.8.4)                  - pysam
djangosaml2_tenant (0.1.0)     - pysaml2 integration for multi-tenant in Django
djangosaml2-bernii (0.11.2)    - pysaml2 integration in Django
pysample (0.1)                 - A python package than can be used as a model/template for writing, testing and deploying python packages.
pysamlsp (0.1.4)               - A service provider implementation for SAML2.0.
```

**Comment by cdeboever3** [comment]
I created a new anaconda environment (`conda create -n test anaconda
--yes`) and was able to successfully install using `pip install
pysam==0.8.3`. Does that work for anyone else? There is also a version
0.9.0 on pypi although pip isn't seeing that one. I'd just stick with 0.8.3
for now.

**Comment by hurleyLi** [comment]
Yes `pip install pysam==0.8.3` works for me. 
It looks like it's the version problem.

Thanks guys, I'll close this issue now.
