### ISSUE TITLE
new lab member

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#119]
Hi Paul,
we have a new rotation student in the lab, who should get access to the cluster.

Thank you!

**Comment by s041629** [comment]
What do you need from her to give her the access?
Her name is Margaret Donovan and her email ismkdonova@eng.ucsd.edu

thanks

**Comment by tatarsky** [comment]
In the past I have not made the accounts. Only propagated them. 

Please ask @hirokomatsui to make the account with I assume this persons username and name on the fl-hn1 system. Then I make sure puppet picks it up.

**Comment by tatarsky** [comment]
And I actually have that in cron. So if the account is made puppet will make it available in at most an hour. If its needed faster than that just advise when the account is made.

**Comment by tatarsky** [comment]
And I don't mind making the account but I seem to recall the last ones were made in that way. Just advise if not the case. Usually you would provide a confirmation if she wishes to match that email address as a username. `ismkdonova` or something shorter like `margaret`

**Comment by hirokomatsui** [comment]
I'll work on that. The cron runs hourly?

**Comment by tatarsky** [comment]
Yep. I can force it however if speed is desired. 

Only item remaining you need to inform me on new accounts is a subtle bug in puppet 3.X (corrected in 4.X apparently but I'm not ready for 4.X) is if the username contains an apostrophe I need to make a special cleanup rule for it as puppet does not escape it properly. 

The last account (aga) is an example of such a situation.

**Comment by hirokomatsui** [comment]
Got it, Thanks!
