### ISSUE TITLE
Installing the boost library

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#121]
I'm trying to install a library (boost) for a program I am trying to install (FGWAS) and I am getting some errors.  The install output is in my home directory in the libCompile.out file.  I think the important line is

...failed gcc.compile.c++ bin.v2/libs/container/build/gcc-4.4.7/release/link-static/threading-multi/pool_resource.o...
...skipped <pbin.v2/libs/container/build/gcc-4.4.7/release/link-static/threading-multi>libboost_container.a(clean) for lack of <pbin.v2/libs/container/build/gcc-4.4.7/release/link-static/threading-multi>pool_resource.o...
...skipped <pbin.v2/libs/container/build/gcc-4.4.7/release/link-static/threading-multi>libboost_container.a for lack of <pbin.v2/libs/container/build/gcc-4.4.7/release/link-static/threading-multi>pool_resource.o...

**Comment by joreynajr** [comment]
In an installation for something else I saw that Chris mentioned using module load gcc. The system gcc  and the module load gcc (newer one) are different versions and you may need the module version instead.

**Comment by cdeboever3** [comment]
Did you load the gcc module?

**Comment by billgreenwald** [comment]
I did not (thought that it was default active)--that seems to have fixed the error I was hitting

**Comment by tatarsky** [comment]
A note on this even though its closed:

gcc the default is a stock gcc that comes with RHEL 6.X. It is rather old now 4.4.7 

This is left there to support any situation in which the OS requires a certain version of gcc most often for kernel modules.

I can make the newer module gcc 4.8.5 a USER default via an /etc/profile.d script but I like everyone to agree on that as a concept first.

**Comment by tatarsky** [comment]
Boost BTW may be of enough interest for a common module or at least a clean build of it out in /software. Advise if you would like one to all share.
