### ISSUE TITLE
zlib-dev

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#123]
Paul can you install zlib-dev.  It's on yum.

**Comment by tatarsky** [comment]
Where are you not seeing it? I have it on the head nodes (we install devel packages on head nodes not nodes)

```
zlib-devel-1.2.3-29.el6.x86_64
```

**Comment by billgreenwald** [comment]
My bad.  I missed an earlier thread on pysam and thought this may be the problem.  Hurley's fix worked for me.

**Comment by tatarsky** [comment]
no prb
