### ISSUE TITLE
May need to re-locate some Mysql Data

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#124]
The `/var/lib/mysql` on fl-hn1 is getting pretty big and will fill the root partition if it continues. It seems to involve a very large "ibtmp1" which was recently created.

```
-rw-r-----   1 mysql mysql 365219020800 Apr  4 10:00 ibtmp1
```

I'm actually not sure what that is.

```
df .
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/md1       944153020 788370124 107815972  88% /
```

703G    mysql

The `/scratch` partition on fl-hn1 is larger and basically empty.

```
Filesystem              1K-blocks         Used    Available Use% Mounted on
/dev/sdc1              3845577736        69636   3650157268   1% /scratch
```

My suggestion would be shutdown Mysql and change the datadir to that location.  Or make a "mysql" subdir there for the use of databases. We'd have to be careful as /scratch is world write. (We could remount it as something less open)

Alternately if Lustre based databases were working perhaps migrating some of the larger ones would be wise.

**Comment by nariai** [comment]
For my project (t2d), I started creating mysql database in Lustre area, and it is working very efficiently as far as I know. So I think it makes sense to move "big"  mysql data into Lustre area.

**Comment by tatarsky** [comment]
This is now becoming urgent as the file is growing quickly.

**Comment by tatarsky** [comment]
We need to determine what is involved in this `ibtmp1` file before we run out of space.

**Comment by tatarsky** [comment]
Does anybody know what this query involves?

```
| 482 | retina | localhost | retina_develop | Query   | 4183 | Sending data | SELECT `cnv_gs`.`id`, `cnv_gs`.`chr`, `cnv_gs`.`pos`, `cnv_gs`.`ref`, `cnv_gs`.`end`, `cnv_gs`.`gcfr |
| 484 | retina | localhost | retina_develop | Query   | 4000 | Sending data | SELECT `cnv_gs`.`id`, `cnv_gs`.`chr`, `cnv_gs`.`pos`, `cnv_gs`.`ref`, `cnv_gs`.`end`, `cnv_gs`.`gcfr |
```

**Comment by tatarsky** [comment]
The file in question appears to be a 5.7 enhancement to do InnoDB temp tables. So I suspect the query involved above is creating a very large temp table.

**Comment by tatarsky** [comment]
Query will be killed if we get down to 5GB. Please try to determine if this query is correct ASAP.

**Comment by tatarsky** [comment]
10GB left. Killing query in a moment. We need this stopped.

**Comment by tatarsky** [comment]
It was definitely involved. I would like the "retina" account person to join this discussion.

**Comment by tatarsky** [comment]
```
| 482 | retina | localhost | retina_develop | Killed  | 4521 | removing tmp table | SELECT `cnv_gs`.`id`, `cnv_gs`.`chr`, `cnv_gs`.`pos`, `cnv_gs`.`ref`, `cnv_gs`.`end`, `cnv_gs`.`gcfr |
| 484 | retina | localhost | retina_develop | Killed  | 4338 | removing tmp table | SELECT `cnv_gs`.`id`, `cnv_gs`.`chr`, `cnv_gs`.`pos`, `cnv_gs`.`ref`, `cnv_gs`.`end`, `cnv_gs`.`gcfr |
```

**Comment by tatarsky** [comment]
We are still in  a very dangerous spot. The `ibtmp1` file did not automatically clear. I am attempting to determine whats involved. Mysql may need to be shut down.

**Comment by hirokomatsui** [comment]
They are mine. You meant the two queries are still running? It's ok to kill them if so.

**Comment by tatarsky** [comment]
Queries are killed but problem remains.

**Comment by tatarsky** [comment]
I need to shutdown Mysql and set a variable to locate these large temporary files somewhere else.

**Comment by hirokomatsui** [comment]
OK. Please shut it down.

**Comment by tatarsky** [comment]
I am trying to read the correct method of dealing with it.

**Comment by tatarsky** [comment]
Shutting mysql down to see if it recreates at this size.

**Comment by tatarsky** [comment]
OK. So it is dropped on shutdown. Now I'm trying to make sure this doesn't happen again. The default placement of the file is `/var/lib/mysql`

**Comment by tatarsky** [comment]
Really not well documented new feature. Taking a guess on how to control it from extending like this. We may end up mounting /scratch as /var/lib/mysql.

**Comment by tatarsky** [comment]
Still working on it. Cannot figure out my.cnf syntax to alter the default.

**Comment by hirokomatsui** [comment]
ibtmp1 is used for temporary table. None of my program create temporary tables, but I do often manually. I will use regular tables instead of temporary for big ones, then mysqld uses Luster.

**Comment by tatarsky** [comment]
OK. I've attempted for a debug pass to limit the size of these temp tables to 256MB. I suspect that syntax is correct but if you could try your query again let me know.

In the end I still believe we will need more space for the Mysql area on this system and suggest we re-purpose /scratch for that role. 

For our records:

```
Previous value and default
| innodb_temp_data_file_path | ibtmp1:32M:autoextend |
```

Means it can grow without bounds. 

```
| innodb_temp_data_file_path | ibtmp1:32M:autoextend:max:256M |
```

I believe this limits temp tables on disk to 256MB.

**Comment by tatarsky** [comment]
Please note BTW this all started due to a Nagios alert that the root disk was almost filled ;)

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
I'm not just sitting around watching Mysql tmp file sizes ;)

**Comment by tatarsky** [comment]
OK. Looking at the original quote I'm actually going to suggest we consider buying another drive or perhaps two for Mysql data. 

The boot drives on the head nodes are mirrored (RAID1) but the extra /scratch disk similar to all the systems is a SINGLE drive. Intended for non-permanent storage.

So it would likely be best for long term growth to add a couple of reasonably fast drives for the Mysql data (and use RAID1 to protect the data)

Alternately we could try to run _ALL_ the data from Lustre. We just really want to make sure that works 100% for all cases. 

Mull this over at your convenience. I believe for now we have a workaround.

**Comment by cdeboever3** [comment]
Is mysql up and running again? I get this

```
[/p/C/d/d/20160404]fl-hn2 $ mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)
```

**Comment by cdeboever3** [comment]
Sorry forgot mysql is not available on flh2. Do we have plans to make it available on flh2?

**Comment by tatarsky** [comment]
Compared to talking to the network socket on fl-hn1?

**Comment by cdeboever3** [comment]
I didn't realize we could do this. @hirokomatsui or @tatarsky, what would the syntax look like for doing something like `mysql cardips -e "SELECT * FROM baseline_analyte" > baseline_analyte.tsv` from flh2? Thanks!

**Comment by hirokomatsui** [comment]
I think the port for MySQL is open on flh1. We need to add privileges on the user and database to be accessible from flh2.

**Comment by tatarsky** [comment]
The above is correct. The syntax involves an extra `--host=name` to the Mysql or a my.cnf entry for the user. If you need help with the grant syntax advise.

**Comment by tatarsky** [comment]
(updated comment above for "two dashes")

**Comment by tatarsky** [comment]
I see many of the Mysql accounts with the host column set to `%` which implies "from anywhere, any protocol"

`localhost` is a socket level connection only. Aka you have to be on the system with the `/var/lib/mysql/mysql.sock` file.

**Comment by hirokomatsui** [comment]
Can I increase the max from 256M to ~8G or so:
| innodb_temp_data_file_path | ibtmp1:32M:autoextend:max:256M |

Some queries don't work with the limit.

**Comment by tatarsky** [comment]
Can try but will require Mysql restart. Assume now is OK?

**Comment by tatarsky** [comment]
To be clear I've already modified /etc/my.cnf. You just need to restart mysql which I or you can do at convenience.

**Comment by hirokomatsui** [comment]
I've restarted mysqld and working fine for now. Thanks!

**Comment by tatarsky** [comment]
Quick review of this after a space of time shows disk seems fine. I will be opening a "things we should discuss" ticket for perhaps a few summer improvements.
