### ISSUE TITLE
sftp only user account

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#127]
Is it possible to create a SFTP only user account on the cluster? or it can be only either flh1 or flh2.
We will have a collaborator who need upload data to our system.

**Comment by tatarsky** [comment]
Yes. Will it be shared by other collaborators or just one?

**Comment by hirokomatsui** [comment]
It will be multiple users sharing one directory.

**Comment by tatarsky** [comment]
Do you care if they can see each others uploads?

**Comment by tatarsky** [comment]
Oh and how much data do you think will be uploaded? (To determine if it would be chroot'd into Lustre or local disk)

**Comment by hirokomatsui** [comment]
No, or they should be able to see each other.
I'm not sure how much data for now, but am expecting to use Luster.

**Comment by tatarsky** [comment]
OK. I'll take a pass at a config to test. Do you have a username you would like?

**Comment by hirokomatsui** [comment]
Thanks. Can you use some arbitrary username for now, say frazer_guest1 or some. I guess just guest is not good for attackers.

**Comment by tatarsky** [comment]
yeah its best to not use `guest`

**Comment by tatarsky** [comment]
I will likely test on fl-hn2 as I do need to modify the sshd_config to do the chroot part.

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
Can you place a password for this account in perhaps a file so I can copy it? Just something in your homedir or something. Almost done with config on fl-hn2 for now.

**Comment by hirokomatsui** [comment]
Can you use the same one as the root user, then I'll change it later.

**Comment by tatarsky** [comment]
OK. So I've sort of tried to make this similar to another location but we can tweak it a bit.
Test out:

```
sftp frazerguest1@flh2.ucsd.edu
```

You will see a directory there called frazerguest1
If you cd into that directory you can upload items to that. The root directory I don't believe is writable in sftp chroots. 

You should also not be able to cd anywhere else. 

The gist being at another location we actually made various directories there like `timdata` or whatever to keep them separate.

The uploaded data ends up in:

```
/frazer01/home/sftp/frazerguest1
```

I've left the frazerguest1 account in group users so its easier for folks to pickup the data. 

Tell me if that works or if we need some other refinements. 

Please note I have an appointment in an hour so there may be a delay.

**Comment by tatarsky** [comment]
Oh, and SSH is blocked:

```
ssh frazer2 -l frazerguest1
frazerguest1@flh2.ucsd.edu's password: 
This service allows sftp connections only.
```

**Comment by hirokomatsui** [comment]
Thanks, that's exactly what I wanted.

**Comment by tatarsky** [comment]
Cool. Yeah our similar area elsewhere has like the name of the institution in that second level. Just be sure if you want to add a directory to match the permissions as such:

```
drwxrwxr-x  2 root users 4096 Apr 20 13:40 frazerguest1
```

So for example if you were working with stanford:

```
cd /frazer01/home/sftp/
mkdir stanford
chgrp users stanford
chmod 775 stanford
```

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
Closing for now. If you want it on fl-hn1 let me know. Doesn't really matter where it is but the part that makes it work is in `/etc/ssh/sshd_config` under the following:

```
#Subsystem      sftp    /usr/libexec/openssh/sftp-server
Subsystem sftp internal-sftp
```

You comment out the one sftp method and switch to internal which supports the Chroot concept.

```
# Support Upload
Match User frazerguest1
    ChrootDirectory /frazer01/home/sftp
    AllowTCPForwarding no
    X11Forwarding no
    ForceCommand internal-sftp
```

That says if the user `frazerguest1` connects do the chroot sftp only. That can be done with a group or other `Match` methods but for now we'll just do a user. Enjoy.
