### ISSUE TITLE
trying to install MitoSeek

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#128]
I am trying to install MitoSeek (https://github.com/riverlee/MitoSeek). It's a program in Perl and I would need root permissions to install the modules needed for it to work. I have tried to follow the instructions to get my own version of the Perl modules, but it doesn't work.

MitoSeek requires the following modules to be installed (many of these are required to run Circos, which is included):
fail GD is not usable (it or a sub-module is missing)
fail GD::Graph::boxplot is not usable (it or a sub-module is missing)
fail GD::Graph::lines is not usable (it or a sub-module is missing)
fail GD::Text::Wrap is not usable (it or a sub-module is missing)
fail Statistics::KernelEstimation is not usable (it or a sub-module is missing)
fail Statistics::Multtest is not usable (it or a sub-module is missing)
fail Text::NSP::Measures::2D::Fisher::left is not usable (it or a sub-module is missing)
fail Config::General is not usable (it or a sub-module is missing)
fail GD is not usable (it or a sub-module is missing)
fail GD::Image is not usable (it or a sub-module is missing)
fail GD::Polyline is not usable (it or a sub-module is missing)
fail List::MoreUtils is not usable (it or a sub-module is missing)
fail Math::Bezier is not usable (it or a sub-module is missing)
fail Math::Round is not usable (it or a sub-module is missing)
fail Math::VecStat is not usable (it or a sub-module is missing)
fail Params::Validate is not usable (it or a sub-module is missing)
fail Readonly is not usable (it or a sub-module is missing)
fail Regexp::Common is not usable (it or a sub-module is missing)
fail Set::IntSpan is not usable (it or a sub-module is missing)
fail Text::Format is not usable (it or a sub-module is missing)

Is it possible to install them?

Thanks!

**Comment by hirokomatsui** [comment]
Can you install them on local and set the environmental value, PERL5LIB

**Comment by s041629** [comment]
I set the variable and I am trying to install the modules locally, but it does not work. Every time I try to download and install a module I get the message "Could not read ..."

**Comment by tatarsky** [comment]
I will look in the morning what perl modules I can add as RPMS and the rest I usually recommend what @hirokomatsui said to set a PERL5LIB path. I often do so combined with a module. But let me look at the collection in the morning and give you more precise advice.

**Comment by tatarsky** [comment]
Got a few moments this evening and had done this before elsewhere so got a good start on them from RPMS. 

Not all the way done, but I've got the Circos modules on fl-hn1 for starters and will do the Mitoseek extra ones in the morning. But nothing overly difficult and then will puppet the rpm list to the nodes. 

``` ./test.modules
ok   Carp
ok   Config::General
ok   Cwd
ok   Data::Dumper
ok   Digest::MD5
ok   File::Basename
ok   File::Spec::Functions
ok   File::Temp
ok   FindBin
ok   GD
ok   GD::Image
ok   GD::Polyline
ok   Getopt::Long
ok   IO::File
ok   List::MoreUtils
ok   List::Util
ok   Math::Bezier
ok   Math::BigFloat
ok   Math::Round
ok   Math::VecStat
ok   Memoize
ok   POSIX
ok   Params::Validate
ok   Pod::Usage
ok   Readonly
ok   Regexp::Common
ok   Set::IntSpan
ok   Storable
ok   Sys::Hostname
ok   Text::Format
ok   Time::HiRes
```

**Comment by tatarsky** [comment]
OK. So some of the Mitotek ones required some custom RPM work but that is now done and I'm adding all the RPMS to puppet so they will appear on the nodes.

```
MitoSeek-1.3]$ ./test.modules 
ok   Convert
ok   Cwd
ok   File::Basename
ok   File::Path
ok   FindBin
ok   GD
ok   GD::Graph::boxplot
ok   GD::Graph::lines
ok   GD::Text::Wrap
ok   Getopt::Long
ok   List::Util
ok   Math::SpecFun::Beta
ok   Mitoanno
ok   Statistics::KernelEstimation
ok   Statistics::Multtest
ok   Text::NSP::Measures::2D::Fisher::left
```

Please try your build again. I believe at least from the basic run of the mitoSeek.pl you should be at least close. Report missing perl modules and I'll do the same process.

```
perl mitoSeek.pl 
[Fri Apr 22 06:04:52 2016] [ERROR] input bam file (-i) has not been defined yet

Usage: perl mitoSeek.pl -i inbam 
-i [bam]                Input bam file
-j [bam]                Input bam file2, if this file is provided, it will conduct somatic mutation mining, and it will be 
                        taken as normal tissue.
-t [input type]         Type of the bam files, the possible choices are 1=exome,

(etc)
```

**Comment by s041629** [comment]
I am running the example analysis and it seems to be working fine. Thanks!

**Comment by tatarsky** [comment]
Cool! Closing for now. Should work on all nodes by now but advise if not.
