### ISSUE TITLE
pysam error

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#129]
Hi Paul, 
I'm getting a pysam error that I can't figure out. 
I've installed various versions of pysam with and without the gcc module loaded and still have issues importing pysam that look like this 

> > > import pysam 
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/pysam/**init**.py", line 1, in <module>
> > >     from pysam.libchtslib import *
> > > ImportError: No module named libchtslib

this is my pysam version 
pysam                     0.6                      py27_0    defaults

when I use a more updated pysam I get another error : Pysam requires glibc 2.14 
I don't know why this is happening and I'm not in the pysam package directory (which is reported online as causing this problem) anyway let me know what you think

**Comment by tatarsky** [comment]
I will look tomorrow. pysam is usually very version dependent on the python it was built under. 

Note I am not working Friday but will see if I see anything obvious tomorrow.

**Comment by djakubosky** [comment]
thank you! the primary goal is for me to be able to use the python package pybedtools 0.7.7 (newest), there has been a strange thing happening where the latest pybedtools works in the jupyter notebook but cannot be loaded when running python scripts instead, forcing me to revert to older pybedtools.  Newer pybedtools has certain pysam requirements (0.8.3 I think) so this has been problematic.  

Another option might be to just not import pysam in the newest pybedtools (comment it out) as I never use any methods that need pysam I don't think but that seemed hacky to me.

**Comment by tatarsky** [comment]
How are you installing things to your anaconda distro? (Which I am assuming is the python you are referring to from above)

There is a difference in what is being reported installed that suggests perhaps a conflict somewhere. Conda (the preferred method IIRC) shows 0.6:

```
> conda list
pysam                     0.6                      py27_0    defaults
```

But then pip is showing:

```
> pip list
pysam (0.8.4)
```

A find down your library tree indeed shows multiple versions of pysam:

```
> pwd
/frazer01/home/djakubosky/software/anaconda
> find . -name "*pysam*"
./conda-meta/pysam-0.6-py27_0.json
./.index/pysam-0.6-py27_0
./pkgs/pysam-0.6-py27_0
./pkgs/pysam-0.6-py27_0/.index/pysam-0.6-py27_0
./pkgs/pysam-0.6-py27_0/lib/python2.7/site-packages/pysam-0.6-py2.7.egg-info
./pkgs/pysam-0.6-py27_0/lib/python2.7/site-packages/pysam
./pkgs/pysam-0.8.3-py27_1.tar.bz2
./pkgs/pysam-0.6-py27_0.tar.bz2
./pkgs/pysam-0.8.3-py27_1
./pkgs/pysam-0.8.3-py27_1/lib/python2.7/site-packages/pysam
./pkgs/pysam-0.8.3-py27_1/lib/python2.7/site-packages/pysam/pysam_stream.h
./pkgs/pysam-0.8.3-py27_1/lib/python2.7/site-packages/pysam/pysam_util.h
./pkgs/pysam-0.8.3-py27_1/lib/python2.7/site-packages/pysam/include/samtools/pysam.h
./pkgs/pysam-0.8.3-py27_1/lib/python2.7/site-packages/pysam-0.8.3-py2.7-linux-x86_64.egg-info
./lib/python2.7/site-packages/pysam-0.8.4.dist-info
./lib/python2.7/site-packages/pysam-0.6-py2.7.egg-info
./lib/python2.7/site-packages/pysam
```

This may cause what we loosely call in the sysadmin game "weirdness" I suspect and you may wish to consider removal of pysam from these trees. 

I can attempt that for you but ideally we'd not have jobs or programs running. Let me know if that is the case and I will make a quick backup of this tree and attempt to clean it up.

**Comment by djakubosky** [comment]
Wow, I guess my pip uninstall commands weren't really doing what I thought they were...
This is probably not a good situation.  I'd love to clean this tree up, but I think it could screw up some ongoing scripts that will take a day to finish (and I may need to rewrite them to cope with the changes).  Maybe we can fix this next week.

To clarify I installed pysam through both pip and conda, but thought my pip versions had been uninstalled.  I intentionally reverted to pysam 0.6 having heard that there could be some centOS issues with newer versions

**Comment by tatarsky** [comment]
Sounds good for next week.
Yes, you will likely hit a glibc minimum version requirement on newer pysam.

**Comment by djakubosky** [comment]
Hi Paul, would it be possible for you to help clean up this tree? I'm out of town and don't need to use them much right now so maybe it would be a good time

**Comment by tatarsky** [comment]
You are talking about your personal anaconda tree I assume.

**Comment by djakubosky** [comment]
Yep!

**Comment by tatarsky** [comment]
Alright so this is based on previous efforts for somebody else on this cluster. 

Pysam has rather complex ways of working. 

So I built awhile ago a generic Python 2.7.3 portable version 0.8.3 module. Which uses PYTHONPATH to be added to your environment. 

I REMOVED the pip and conda added versions of pysam from your anaconda tree. And I'd like you to try to determine if this works past the level I show below of simply importing it.

```
you$ module add python/2.7/pysam/0.8.3
you$  python
Python 2.7.12 |Anaconda 2.3.0 (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import pysam
>>> 
you$
```

Please note I made a backup of your entire anaconda tree before the removal so if something else broke we can roll it back.

**Comment by tatarsky** [comment]
And to be very clear that is version 0.8.3 as compiled by the PUIAS (Princeton) folks for their python 2.7 RPMS. Which we also have installed. 

But as its "portable" as long as you are running a 2.7.X python I believe it should work. Please tell me if it does not.

**Comment by tatarsky** [comment]
As an aside, to confirm the supported system "python27" the same items should work fine:

```
$ module add python/2.7/pysam/0.8.3
$ python27
Python 2.7.8 (default, Jun 30 2015, 14:28:51) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> 
```

**Comment by tatarsky** [comment]
Oh and please note that module is only on head node one at the moment. I can expand that and make it easier to load. Its just a PYTHONPATH item.

**Comment by djakubosky** [comment]
Okay, I'll try this out, I have a question though.  In my anaconda tree I have something called pybedtools which needs pysam, will I be able to use this pysam from my personal python load?  If not my things will break.

**Comment by djakubosky** [comment]
This seems to work so I answered my own question haha thanks Paul

**Comment by tatarsky** [comment]
I am showing above two examples: your anaconda and the server default python.

The key question remaining is if you need this module (pysam) on the nodes just advise. Easy to add but is NOT there at the moment.

**Comment by djakubosky** [comment]
If we do continue to use it this way it would be helpful for it to be on the nodes, because I often use this package in jobs

**Comment by tatarsky** [comment]
I will set that up shortly.

**Comment by tatarsky** [comment]
So after looking at the best way to place that RPM based module into the cluster I am trying just a copy of it into the `/frazer01/repos/environments/modulefiles`

In theory you should now from any node be able to add this rather long module but there is a point to it apparently in reading the PUIAS folks docs. 

```
module add  python/2.7/pysam/0.8.3 
```

Testing on a node to confirm seemed to work. Be sure you are using a python based on 2.7 (be it the system or your own Anaconda)

**Comment by tatarsky** [comment]
Believe you should be good to go here. If you are not, just re-open.
