### ISSUE TITLE
mysql server on head node

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#13]
We need mysql server running on head node.
Ideally, the setting should be similar to the one running on the old cluster.

Naoki

**Comment by cdeboever3** [comment]
And we would like to be able to connect to the server from either headnode
or the compute nodes.

**Comment by nariai** [comment]
Yes, this is very important point.
(can connect to the mysql server from both headnodes and all the compute nodes)

**Comment by tatarsky** [comment]
Do you want to attempt to clone the one on the old cluster?

**Comment by tatarsky** [comment]
The internal connection items are easy. Mostly I need to know if you want connections from the external (UCSD) side for security reasons.

**Comment by nariai** [comment]
From my perspective, we will use internal connections only.

**Comment by hirokomatsui** [comment]
I will export the database on flc in text format, then import to flh1.
I want internal connection from flh2 and all the compute nodes, but I don't think we have to change any security setting for that.
Once myseql daemon starts running, I can setup the mysql user account to e accessible from all internally.

**Comment by tatarsky** [comment]
Sent you mysql root password. I am validating clients can connect. 
Mysql 5.7 has all sorts of new features including password complexity requirements. We may have to turn that down a bit.

**Comment by tatarsky** [comment]
Mysql client and libs loaded on nodes.
Development environment on head nodes.

**Comment by tatarsky** [comment]
I believe you are all set with this. Re-open if not the case.
