### ISSUE TITLE
Circos

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#131]
A few weeks ago I asked you to install some Perl modules, which I needed to run MitoSeek. It has an old version of Circos included, but it doesn't work. 

Now we are trying to make the newest version of Circos work, but some Perl modules are missing:

missing            Clone
missing            Config::General
missing            Font::TTF::Font
missing            SVG
missing            Set::IntSpan

May they be installed?

Thanks!

Matteo

**Comment by tatarsky** [comment]
If you provide me a path to the Circos you are using I can double check as I add them Monday that I have the right ones. (They provide a nice perl module check tool I believe you are cutting/pasting from above). I can guess the location but if multiple versions the full path always useful to have.

**Comment by tatarsky** [comment]
OK. So assuming you are trying the circos in:

`/frazer01/home/matteo/software/circos/circos-0.69-2/bin`

I am tracking down why it still says the following:

```
missing            Config::General
missing            Set::IntSpan
```

As those are not missing. It may be a versioning issue which is more complex to properly solve.

**Comment by tatarsky** [comment]
From my notes from another location it is a versioning issue but I've moved those perl modules the few minor revisions up to deal with both. So I get a clean circos -modules at this point. Please test as well.

```
./circos -modules
ok       1.11 Carp
ok       0.31 Clone
ok       2.54 Config::General
ok        3.3 Cwd
ok      2.124 Data::Dumper
ok       2.39 Digest::MD5
ok       2.77 File::Basename
ok        3.3 File::Spec::Functions
ok       0.22 File::Temp
ok       1.50 FindBin
ok       0.37 Font::TTF::Font
ok       2.44 GD
ok        0.2 GD::Polyline
ok       2.38 Getopt::Long
ok       1.14 IO::File
ok      0.413 List::MoreUtils
ok       1.21 List::Util
ok       0.01 Math::Bezier
ok       1.60 Math::BigFloat
ok       0.06 Math::Round
ok       0.08 Math::VecStat
ok    1.01_03 Memoize
ok       1.17 POSIX
ok       0.92 Params::Validate
ok       1.36 Pod::Usage
ok       1.03 Readonly
ok 2010010201 Regexp::Common
ok       2.49 SVG
ok       1.16 Set::IntSpan
ok     1.6611 Statistics::Basic
ok       2.20 Storable
ok       1.11 Sys::Hostname
ok      2.0.0 Text::Balanced
ok       0.52 Text::Format
ok     1.9721 Time::HiRes
```

**Comment by tatarsky** [comment]
Assuming all good here. Advise if not by re-open.
