### ISSUE TITLE
cannot log in to cluster

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#132]
Hi @tatarsky , I can't login to the cluster somehow. I also got errors earlier today when I do qstat, I couldn't retrieve any information, not sure whether these errors are related or not.

**Comment by hurleyLi** [comment]
now it works... might just be some temporary issue.

**Comment by tatarsky** [comment]
Somebody consumed all the RAM on fl-hn1. It resulted in several key processes needing restart. I did that late last night as I am warned by Nagios for several of them.

However it may be time for head node memory limits for users. I will attempt to determine a good value and discuss it in another Git issue.
