### ISSUE TITLE
Old nodes down?

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#134]
I remain on the road but getting alerts that look like a switch failure perhaps in the old rack.

All the "CN" nodes (older nodes) are down. Can somebody perhaps check the I believe Cisco switch they are attached to?

**Comment by hirokomatsui** [comment]
If you have any good picture to explain SDSC, can you ask them to check it?
Otherwise, I'll go there later in today or Monday. Thanks for catching this up.
I believe that we don't have any big jobs to fill them up for now.

**Comment by tatarsky** [comment]
Hmm. I will attempt to recall the name of the old rack and I believe I know the switch type. If I gather that you will see an SDSC ticket. I do notice that "flc" is up but I do not recall if that system is on the same switch...I suspect not.

**Comment by hirokomatsui** [comment]
The old rack is K36.
Yes, I believe flc is not on the same switch with cnXs.

**Comment by tatarsky** [comment]
Attempted description but flc is showing for its 10-net (private) side a down link at the same time as the alerts. So I asked SDSC to check what I believe is a 24 port Cisco Small Business Switch for signs of wedging or failure.

**Comment by tatarsky** [comment]
The port on the managed switch in CC36 (new) also shows no link over to that rack.

**Comment by tatarsky** [comment]
Sounds from COLO that the switch is dead. Might be a good time to review the options to get these old systems on the 10G side even if also via 1G ports.

**Comment by hirokomatsui** [comment]
Did you mean that the switch on the old rack (K36) was dead? If so, can we ask COLO to reboot the switch.
Also could you please remind us the options?
Thanks!

**Comment by tatarsky** [comment]
Yes, the COLO folks actually tried to power cycle it and said "no lights at all". I suspect the power supply died. 

The options depend on if you want to try to bring faster networking to this rack (aka 10G). Might be a good time to discuss growth options over there....

**Comment by hirokomatsui** [comment]
So you think the power supply on the switch was dead?

**Comment by tatarsky** [comment]
Based on what the COLO person said. I had him remove power to see and he said more or less "I still don't see any lights at all".

**Comment by tatarsky** [comment]
This BTW is the Cisco Small Business switch in that rack. Which has an internal power supply only.

**Comment by hirokomatsui** [comment]
OK, them most likely we have to replace the switch itself. Our options will be
1. buy a 1G switch
2. buy a 10G switch with adapters x 17 (I believe 2 of 19 nodes were dead)
Do you have any ballpark figure?

**Comment by tatarsky** [comment]
I believe so. Happy to try to re-diagnose though. My discussions with COLO were when I was traveling. And of course I can't actually see the switch. 

I can look around at the latest prices on 10G switches. Last time we talked about this was awhile ago. 

I would consider using a copper 10G switch over in this rack so you can also connect 1G copper ports from older gear. (copper 10G switches can usually do 1G/10G speeds, fiber SFP ones often just do 10G)

**Comment by hirokomatsui** [comment]
We've decided to replace the switch with 1G for quick short term purpose.
The broken one is Cisco SG 102-24 24-Port Gigabit Switch.
I'm looking for a replacement similar with the broken one:
https://www.amazon.com/s/?ie=UTF8&keywords=netgear+24-port+gigabit+switch&tag=googhydr-20&index=aps&hvadid=65996770877&hvpos=1t1&hvexid=&hvnetw=g&hvrand=3224205568656754468&hvpone=&hvptwo=&hvqmt=b&hvdev=c&ref=pd_sl_9lrb8ik3yk_b
Do you have any recommendation?

**Comment by tatarsky** [comment]
Ah, sorry I was getting you a price on a 10G.

Pretty much any 24 port switch will work for 1G. We don't do anything fancy. 

If I had to pick from that Netgear list this one I have a few of:

https://www.amazon.com/Netgear-GS724T-ProSAFE-24-port-Gigabit/dp/B00I5W5EGA/ref=sr_1_3?ie=UTF8&qid=1466622242&sr=8-3&keywords=netgear+24-port+gigabit+switch

Alternately, the Cisco equiv is:

https://www.amazon.com/Cisco-SG200-26-Ethernet-Mini-GBIC-SLM2024T/dp/B004GHMU5G/ref=sr_1_1?ie=UTF8&qid=1466622315&sr=8-1&keywords=cisco+small+business+switch

**Comment by tatarsky** [comment]
This BTW was the cheapest 10G switch I could locate and I've never used one:

https://www.amazon.com/Netgear-ProSAFE-10-Gigabit-Ethernet-XS728T-100NES/dp/B0147FL4BW

So it would be a ~ $3000 experiment....

Dell doesn't seem to provide prices anymore online for their 10G switches. But they were 48 port units. 

Still have not come across any used 10G switches in my travels.

**Comment by hirokomatsui** [comment]
Thanks, that's good to know!

**Comment by tatarsky** [comment]
This switch also just crossed my radar and while not 100% matching what you need its interesting as it provides a mix of copper and fiber ports.

http://www.newegg.com/Product/Product.aspx?Item=33-122-831&utm_medium=BehEmail&utm_source=EMCCP-062716-Netgear&cm_mmc=EMCCP-062716-Netgear-_-NetgearSwitches-_-Item-_-33-122-831&et_cid=27430&et_rid=11232298&et_p1=&email64=c3VwcG9ydEB0YXRhcnNreS5jb20=

its also cheaper in the 10G small switch game.

**Comment by tatarsky** [comment]
Oh, and they have a 24 port model (12 copper/12 SFP) as well. Perhaps not this batch but something to keep in the back of our minds for mixed speed/mixed cabling type rack needs.

**Comment by hirokomatsui** [comment]
I'm trying to replace the switch to a new one we just bought, Netgear GS724T v3.
I believe that DHCP server is not running on flh1, is that right?
Maybe I'm doing something wrong:
![netgear](https://cloud.githubusercontent.com/assets/15457142/16399518/010f609c-3c88-11e6-9535-3f85ef285da5.png)
I've added 10.0.0.20 cn-switch in the /etc/hosts on flh1, and am not sure if it's really needed.
flh1 can see cn-switch but not others.

**Comment by tatarsky** [comment]
DHCP is reservation only on flh1. To prevent Kickstart accidents.

I'm fine with a static IP on a switch and often its wise.

Netgears management tool can only see other Netgear switches on the same subnet.

I can see the switch IP. So I believe since the default config of a Netgear is a single Vlan all you need to do is move cables from the old one to the new one.

**Comment by tatarsky** [comment]
To be clear: this is the only Netgear switch on the subnet. So I believe what you see there is correct.

**Comment by tatarsky** [comment]
And at the moment I see `cn9` so if that matches cabling you moved you are on the right track. I am back from dinner. Just advise if you have problems.

**Comment by hirokomatsui** [comment]
Thanks, I got it! I've tried to restart cn9 just before leaving there. I will do the others tomorrow morning.

**Comment by tatarsky** [comment]
Cool. Yeah cn9 is back in SGE. The others I suspect will need a reset. Thanks!

**Comment by hirokomatsui** [comment]
Everyone got back onlinke except cn7's dead by hardware problem. Thanks Paul!

**Comment by tatarsky** [comment]
Cool. I will do the mounts and SGE start. (I do not do that automatically in case the node is in a reboot loop and eating jobs)

**Comment by tatarsky** [comment]
All nodes that were up before are back in action. Closing for now!

**Comment by tatarsky** [comment]
Interestingly `cn12` is now available after vanishing a long time ago during our build kickstarts ;)
Its never been fully configured. 

I am attempting to bring it into the fold.
