### ISSUE TITLE
Installing software

### ISSUE THREAD

**Issue by Terciera** [frazer-lab/cluster#135]
Hey Paul,

I am trying to install academic software (polyTest) that I received from Kyle Gaulton. He sent me a link to download the .tar.gz file from DropBox.
I used wget to download it into /frazer01/projects/VTE/Software
I can then unzip it, but when I try to run it, I get the following two errors:
./polyTest: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./polyTest)
./polyTest: /usr/lib64/libstdc++.so.6: version`CXXABI_1.3.5' not found (required by ./polyTest)

I know that we have libc.so.6 and libstdc++.so.6 on the server.
I think this is due to the software being built from source on Kyle's computer, and not on our server.
This is now out of my depth with software.

I would prefer that this software stays in /frazer01/projects/VTE/Software as it is confidential software at this point.

**Comment by tatarsky** [comment]
The software has been compiled on an OS that is newer in the core glibc than our systems. We run CentOS 6.X. Can the software be provided as source or a binary distribution provided for that release?

**Comment by tatarsky** [comment]
Which BTW, if the code source can be provided, I'm happy to help compile it. If by some chance the code _requires_ features of GLIB 2.14 (which I don't usually see) alternate methods may need to be discussed.

**Comment by tatarsky** [comment]
Oh, and I show source in that dir....tell me if you would just like me to try to compile it or there may a working version located here.

```
$ cd /frazer01/projects/VTE/Software/polytest
$ ./polyTest_unix 
options:


ERROR:Must supply GWAS file via the --gwas-file flag

usage: polyTest --gwas-file gwas_filename --annot-files annot_filename(s)
additional useful options:
        --min-pv pv: remove SNPs with p value below the given pv
        --max-pv pv: remove SNPs with p value above the given pv
        --maf F: remove SNPs with MAF below F
        --out fn: write output to fn

(etc)

```

Is that a different binary?

**Comment by Terciera** [comment]
Oh! Yup, that works just fine. Sorry about that.

**Comment by tatarsky** [comment]
Ah cool! Sorry I got slammed today with post trip fun ;) Glad it worked out ok!
