### ISSUE TITLE
Homer module

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#139]
Do we have a system in place for modifying a module file and documenting the change?

I want to make it so that the weblogo module autoloads when you load the homer module, as without it none of the images get made.

Is this ok with everyone?

**Comment by nariai** [comment]
I'm fine with the change. Thanks!

**Comment by joreynajr** [comment]
The module files actually have a Frazer github repo. Sometimes I'll update it so that's a way to document changes.

**Comment by billgreenwald** [comment]
I edited the file and pushed it to github.  I'm going to close this, but feel free to reopen it if it doesn't work for someone.

**Comment by cdeboever3** [comment]
In case someone stumbles across this thread and wants more info, the repo for managing modulefiles is [environments](https://github.com/frazer-lab/environments). This is located at `/repos/environments` on the cluster. There is a description of how to [commit modulefiles on the wiki](https://github.com/frazer-lab/cluster/wiki/module-and-modulefiles#adding-to-git-repo).

**Comment by cdeboever3** [comment]
Also, it may make sense once in a while to check whether things are being committed. For instance, these files/directories are currently not being tracked:

```
    modulefiles/R/.Rhistory
    modulefiles/R/2.12.2
    modulefiles/bowtie/
    modulefiles/python/
    modulefiles/seq2hla/
```

**Comment by joreynajr** [comment]
Most of those module I created. I went ahead and add, commit, and pushed the ones I know about. The only one I'm not sure of is python. It looks like Paul made it. I'm not 100% sure what it's used for. It only contains pysam 0.8.3. Maybe @djakubosky knows?

**Comment by tatarsky** [comment]
I will look in a moment. Yes, thats the pysam abstraction module I just did recently.

**Comment by joreynajr** [comment]
Can you push that module up to git? I'd push it but I'm not 100% sure what to put in the commit message.

**Comment by tatarsky** [comment]
the .Rhistory file has been removed. Thats not part of the module.

**Comment by tatarsky** [comment]
Please confirm my commit looks OK to you.

**Comment by joreynajr** [comment]
Looks good. It's good to go!

**Comment by tatarsky** [comment]
I will endeavor to remember to commit on changes/adds.
