### ISSUE TITLE
Installing Inkscape

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#140]
Hi @tatarsky,

I was hoping you could help me with this one. Inkscape is a gui application but it also has a CLI that I want to use. Right now I have the software in /software/inkscape-0.91 and I get the following error when running ./configure:

configure: error: --enable-lcms was specified, but appropriate LittleCms development packages could not be found

Can you help me out?

**Comment by tatarsky** [comment]
I added the lcms-devel package to just fl-hn1 to make sure that is what it wants. We have just the runtime loaded.

There is also a lcms2 package. I'm not sure if it have a preference so will start with just that. 

Advise if it gets further and we'll go from there. (We load -devel items on request for the head nodes but not the nodes)

**Comment by tatarsky** [comment]
BTW, inkscape is an RPM if you want it via binary install. Not sure what version but its in the repos and can load it that way as well.

```
inkscape-docs.x86_64 : Documentation for Inkscape
inkscape.x86_64 : Vector-based drawing program using SVG
inkscape-view.x86_64 : Viewing program for SVG files
```

**Comment by joreynajr** [comment]
Actually can we do that instead. It'll cut a lot of these little compile issues.

**Comment by tatarsky** [comment]
Woo. its pretty old. You sure you want it? 

```
inkscape.x86_64                           0.47-6.el6           base                 
inkscape-docs.x86_64                  0.47-6.el6           base                 
inkscape-view.x86_64                  0.47-6.el6           base           
```

I'm happy to compile and make a module if too old....

**Comment by joreynajr** [comment]
Nevermind! Can you please compile a newer one and make a module.

**Comment by tatarsky** [comment]
Sure.

**Comment by joreynajr** [comment]
Thanks!

**Comment by tatarsky** [comment]
Mind if I take over that directory? /software/inkscape-0.91

**Comment by joreynajr** [comment]
No problem. I didn't get very far with it anyhow.

**Comment by tatarsky** [comment]
Yeah, its got a fair chunk of depends. Dealt with it a few places.

**Comment by tatarsky** [comment]
Amusingly 0.48 WAS the version before that version ;)
Quite a leap in version numbers.

Still attacking 0.91 for grins.

**Comment by joreynajr** [comment]
So strange! I always wondered how people came up with these funky version #'s and sub #'s. Like will Inkscape ever get to 1?

**Comment by tatarsky** [comment]
Many open source projects will never get to one. 

So some of these dependencies for 0.91 are pretty cutting edge and may be more work than is needed for the CLI version (lots of graphics libs needed)

I loaded the RPM version on fl-hn1 to see if that is quicker for you.

Do you have a way to see if that works for what you want? 

I can still tilt at the 0.91 windmill but it might be a bit given the dependency pile.

**Comment by joreynajr** [comment]
I will trying running the command I need and let you know in a couple.

**Comment by joreynajr** [comment]
It worked! Thanks Paul!

**Comment by tatarsky** [comment]
OK. (insert relived image of not compiling all those dependencies)

Is that something you need on nodes for compute jobs? Or just head nodes. Not a problem to have on nodes just advise.

**Comment by joreynajr** [comment]
This is something that can stay on the head nodes. The CLI is pretty fast and I don't think we'll ever have to include this directly in one of our pipelines.

**Comment by tatarsky** [comment]
Done on Fl-hn1 and fl-hn2!
