### ISSUE TITLE
RStudio Server

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#141]
Hi Paul, 
I would like to install R Studio Server on our cluster, but it looks like I need some privileges that I don't have- perhaps you could help with this? 

I think @s041629 and @hurleyLi may also want to use this capability to view R Studio from the cluster (if they aren't already?) 

https://www.rstudio.com/products/rstudio/download-server/

Thanks!

**Comment by s041629** [comment]
I've never used Rstudio, but I am using R with the jupyter notebook

**Comment by tatarsky** [comment]
I'll see whats involved. Appears to have a CentOS 6.X RPM. Will not be today as my work day is over here but I'll update what I find in the morning.

**Comment by djakubosky** [comment]
Sounds great, no rush on this item, just wanted to present the idea.

**Comment by tatarsky** [comment]
I have loaded the Rstudio RPM for eval on the first head node only. 

It can be reached from some of the UCSD subnets we allow access from (we have a firewall on fl-hn1) at:

http://flh1.ucsd.edu:8787

If you do not see a connection you are probably NOT on the subnets we allow. We can expand that list but for now thats a reasonable start as I don't know the security of this product. 

Your login appears to be your UNIX login. It appears to run by default the system default version of R which at the moment is R 3.2.2.  (aka not a module, not your personal version).

I don't know if that is changable or not.

**Comment by djakubosky** [comment]
Thanks! Looking forward to checking it out, I'm remote but will try via proxy.

**Comment by djakubosky** [comment]
This works great, and is accessible if logged into Cisco AnyConnect for anyone working remote.  To clarify though, only one person at a time can use this correct?

**Comment by tatarsky** [comment]
I have no idea. Try more than one ;)

**Comment by tatarsky** [comment]
I've literally loaded the RPM. I did zero reading past that ;)

**Comment by djakubosky** [comment]
will do!

**Comment by tatarsky** [comment]
I assume you are good to go here. If you need it modified or on the second head node advise.
