### ISSUE TITLE
Installing multcomp, survival on R distro

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#142]
I'm having issues installing the R package multcomp on my R distro.  It seems to have something to do with another package survival being the wrong version but I can't get the right version downloaded either due to these issues 

ERROR: installing package DESCRIPTION failed for package ‘survival’

any ideas?

**Comment by tatarsky** [comment]
If you provide the full path to your R distro I will look in the morning. I am not at home.

**Comment by djakubosky** [comment]
/frazer01/home/djakubosky/software/anaconda/lib/R/

Thanks!

**Comment by tatarsky** [comment]
Something is wrong with the R package "survival". Its either not compatible with R 3.2 or its distribution tar ball is broken. I will try in the R 3.3 system module to see if its the only one I can solve. Otherwise you'd have to contact the author.

**Comment by tatarsky** [comment]
survival 2.39-5 installed fine in R 3.3 so its a question of your personal R build is too old for it. I can add multicomp as well to the R/3.3.0 module if desired but otherwise I suspect you'll need a newer personal R for this collection.

**Comment by djakubosky** [comment]
Ahh I see, thanks, I'll try to upgrade it if I can
