### ISSUE TITLE
week / short queue job takes the long queue node

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#143]
Hi Paul @tatarsky , 
right now the jobs were arranged in a way that any job would take the long queue node (i.e. n15, n16). I often have the situation that when I try to submit a long queue job that use large memory (256G), I have to wait until the week/short queue job on n15/n16 to finish, even though there're empty slots on other nodes. Could you please change the set up of the week/short/all queue jobs so that they'll take the n1-n14 first if they're empty, rather than block the long queue jobs. 

Thanks,

Hurley

**Comment by tatarsky** [comment]
I'll take a look but it will probably not be this week at the current load. I believe there is a concept for this type of job placement ordering in SGE but I have to locate it. 

If its an immediate need I can disable n15/n16 from the week/short/all queues.

**Comment by hurleyLi** [comment]
Thanks Paul, it's not in urgent, next week would be fine.

Sent from my iPhone

On Jul 21, 2016, at 4:28 AM, tatarsky <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll take a look but it will probably not be this week at the current load. I believe there is a concept for this type of job placement ordering in SGE but I have to locate it.

If its an immediate need I can disable n15/n16 from the week/short/all queues.

**Comment by tatarsky** [comment]
I have _attempted_ a form of this in which the n1-n14 nodes are I believe given a lower sequence number (preference) from n15-n16 for deciding to schedule on them when that queue is involved. 

I've only done it to `all.q` at the moment as I see if my memory on this is correct. If correct I would add the same statement to `week.q` and `short.q`.

Note clearly this does not (should not) prevent jobs from eventually if no other places to run spilling onto those last two nodes.

**Comment by hurleyLi** [comment]
Thanks Paul!

**Comment by tatarsky** [comment]
I will now add the same priority settings to `short.q`. Making a change at a time just to see if I can spot it working/not-working.

**Comment by tatarsky** [comment]
OK. and I've added the same settings to `week.q` .

So, in theory if I did this right the nodes besides 15 and 16 will fill completely (compared to the all node load balance method that is the default) for those queues BEFORE they start to use those high memory nodes.

Again, "if I did this right" is a key statement. If you spot it NOT working as expected please try to save a qstat out. I will rig up my loop script to watch that same data. 

It seemed to do what I wanted in some basic tests.

**Comment by tatarsky** [comment]
I've not seen any issues with this as of yet. So unless you have I'll close it shortly.

**Comment by tatarsky** [comment]
Assume this was good to go. Advise if you feel otherwise by a re-open.
