### ISSUE TITLE
local version of the UCSC Genome Browser

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#144]
Hi Paul,
We have decided to have a local version of the genome browser, because we have been getting a lot of data (RNA-seq, ChIP-seq and ATAC-seq) which we want to be able to easily visualize. We would like to download only only the human genomes hg19 and hg38. I have been looking at the instructions online and it seems that you need admin privileges and there are other things that are not very clear. Can you help us?

Here are the instructions for the installation of a minimal browser (not installing all the organisms present in the genome browser, which we will never use): http://genomewiki.ucsc.edu/index.php/Minimal_Browser_Installation

here are all the readmes for the installation: http://genome-source.cse.ucsc.edu/gitweb/?p=kent.git;a=tree;f=src/product

Thank you!

**Comment by hirokomatsui** [comment]
We also have to think about where to install the browser and database.
MySQL server on flh1 is used for Cardips, Retina projects and others, and sometimes searched heavily. Also multiple web servers are running on flh1.
Perhaps we can install both of the browser and database on flh2, and use Luster for the database files? The database files will be to big to hold on the local drive.

**Comment by nariai** [comment]
I agree with Hiroko.
Let's try to install it on flh2, and use Lustre for the db files.

Naoki

**Comment by tatarsky** [comment]
Having done this many times over the years (I ran the only real Mirror for many years) I would encourage you to be fully sure you need a fully separate browser instance compared to their support of remote grabs of data (I believe they have now several methods now). 

I will help you with what I know but I will clearly state: it often is a moving target to keep running and not all features often work on mirrored copies. Please note clearly I am a contracted resource and each task you ask me to do results in a bill. This will add up from past experience.

**Comment by tatarsky** [comment]
I also strongly suggest you run by what you want to do with the UCSC Genome Browser folks. They are quite helpful. To make sure what you want to do will actually be doable....tell them I say hello ;)

**Comment by tatarsky** [comment]
Oh and yes @nariai and @hirokomatsui there is no way this will fit on the local drives unless you want to add some local drives to the head nodes. (Which is possible, just requires an order)

**Comment by s041629** [comment]
we have thought about getting our own local mirror because we are now starting to have to much data to take care of, and and the next period this amount of data will keep on increasing. So our idea was to create tracks for all our ChIP-seq, ATAC-seq, Hi-C and RNA-seq data in our local mirror. The alternative would be to build our own set of custom tracks (which at this point would already be close to 300, and continuously growing) and save it to a session shared by the whole lab. 

I have never used this approach. It may be easier for now (it's just a matter of creating a session and associating our set of custom tracks to it: with a well defined header for each file it shouldn't be complicated) and we can think about the local mirror later. 

Do you have any other suggestions that we don't know?

Thanks!

**Comment by tatarsky** [comment]
I stopped working with mirrors of the UCSC Genome Browser about four years ago. The primary reason for that was the groups I did mirrors for had found less data and time intensive ways to accomplish what they wanted. I do not know if your needs will match those groups. You may indeed need to maintain a mirror. 

They did that transition however by talking to the UCSC folks for what features items like you describe were possible via the "main" genome.ucsc.edu site and either sessions or these remote data fetch protocols I believe they added. (I would have to review the current state of the browser code for those features)

Lets take the primary thing to check as "Is there a way to scale up lots of custom tracks on a shared lab basis via the main genome.ucsc.edu site?". What do you think "continuously growing" means? 3000? 30000? 

But my advice is lets see if we can arrange an email or chat with the browser group (will dig up the email alias) and see what they have to say for the "2016" version of the browser and your needs.

They are a great group of people and may have some clever way or they will say "you need to mirror". 

I'm happy to initiate the email to them. Just want to cc the right people as well for any elaboration.

**Comment by tatarsky** [comment]
Oh, and one thing to also state: does this data have confidentiality requirements? That drove the mirror for at least one group I worked for.

**Comment by s041629** [comment]
by "scaling up" I mean that we will probably arrive at 1000 in the next year. At this moment my estimate is that we have around 300 (not counting the fact that we will need multiple tracks, at least peaks and raw coverage, for each file that we have). 

And yes, the data cannot be public (at least before publication). It will make sense to write to the UCSC people and listen to their suggestions: for sure there are other labs around in conditions similar to ours, so they probably have easy solutions. 

In the long run it would be great to have our data as one of the track sets readily available on the genome browser.

**Comment by tatarsky** [comment]
I'll make a couple of inquiries tomorrow of some of my old friends there. Then we'll go from there!

**Comment by cdeboever3** [comment]
FWIW, the RNA-seq and ATAC-seq pipelines automatically create the necessary headers and make links so the files can be viewed as custom tracks on the UCSC genome browser. For instance, the file `/projects/CARDIPS/pipeline/RNAseq/sample/103cac6a-527b-4196-8d39-b0cf452eef32/alignment/103cac6a-527b-4196-8d39-b0cf452eef32_links_tracklines.txt` contains genome browser tracklines and URLs. The pipelines make these `*_links_tracklines.txt` automatically.

Everything is password protected for privacy. Small bed files are uploaded to UCSC but larger bams and bigwigs never leave our server. Making the headers/tracklines is not hard to do, I imagine you would still have to make them for a local install anyway. If we added one more step of automatically updating the custom session as the pipeline ran, it would require no human input. That said, it would also be pretty easy to add the track lines/URLs into a database indexed by the sample's unique UUIDs and let people choose the samples they want and create their own custom sessions. [Track hubs](https://genome.ucsc.edu/goldenpath/help/hgTrackHubHelp.html) may be useful for these purposes. I've had success making these.

If you really want to run something locally, I think trying something more lightweight would make sense, perhaps IGV.

**Comment by tatarsky** [comment]
Thank you for saying the current word for "remote data fetch": Track hubs. This was the area folks I worked with on mirrors had been looking it.

I will check if that is what people moved to in my questions. That if I recall the design is just a web server for the locally generated tracks and most folks do what you describe.

**Comment by s041629** [comment]
Thanks Chris! 
I knew it would not be complicated to create tracklines, but I didn't know about track hubs: they don't seem too complicated to make and it should be easy to make them automatically. 

This is probably the best thing to do right now. I will probably start working on this tomorrow or Friday. Once I have a test set running, we can discuss about the best way to scale up to all our datasets and how to organize them

**Comment by tatarsky** [comment]
The recommendation from my long term Genome Browser friend at UCSC is "try trackhubs first". It probably does MOST of what you want and has security features. So I concur with your plans to go down that road first. 

After that they actually recommend now a virtual machine image that contains most of the config and just requires the data shared to it as a first pass of a need for a "truly separate mirror"

https://genome.ucsc.edu/goldenpath/help/gbib.html

He does NOT recommend attempting the procedure for a standalone mirror unless neither of those paths meet your needs.

**Comment by cdeboever3** [comment]
If it's useful as an example, I create a very simple hub for each RNA-seq sample for QC purposes: `/projects/CARDIPS/pipeline/RNAseq/sample/108eaa96-6360-4bf9-ad71-2a1d6ebe2155/alignment/108eaa96-6360-4bf9-ad71-2a1d6ebe2155_rna_hub`

If you do

```
cd /projects/CARDIPS/pipeline/RNAseq/sample/108eaa96-6360-4bf9-ad71-2a1d6ebe2155/alignment
grep hub.txt 108eaa96-6360-4bf9-ad71-2a1d6ebe2155_links_tracklines.txt  | sort | uniq | head -n 1
```

you'll get the URL (with username/password included) that you can pass to the genome browser to upload the track hub.

**Comment by s041629** [comment]
Ok. Then we'll go with the track hubs and install gbib if necessary. Chris's data will provide a great test set and we will build from that. 

Chris, do you have a function in your package that creates the _links_tracklines.txt files? (I am just wondering if we can recycle it for ATAC-seq and ChIP-seq data)
