### ISSUE TITLE
sge job memory reserve 

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#145]
Hi Paul @tatarsky , 

Just to confirm one thing. 
Say if I reserve h_vmem=128G, and reserve 4 CPU cores, and my job is running on n1, is it still possible that other jobs can still run on n1? In other words, if I want to avoid memory overflow and want to occupy the whole node, should I reserve 32 CPU cores, even though I actually only use 4 CPU cores? 
Because I see there're three jobs running on n16 now, two with h_vmem=128G, and one job (1575849) with h_vmem=8G, for 4 cores.

Best,
Hurley

**Comment by tatarsky** [comment]
We oversubscribe the nodes SGE max scheduled memory (h_vmem) just a bit for memory to allow for historically many jobs don't really use what they request. Leaving jobs that could actually run waiting. 

You oversubscribe to increase job throughput in such cases. Esp. in mixed large/small mem situations. 

The nodes would swap if folks really consumed the reserved memory allowed. 

I look periodically at the Ganglia graphs to determine if that is a common situation. To date it has not been suggesting our use of such oversubscription remains wise. 

We allow up to 140G of reserved vmem on the 128G nodes IIRC
We allow up to 280G of reserved vmem on the 256G nodes IIRC

This number was discussed back a bit and could be tuned up or down if desired or if we see excessive swapping or out of memory errors. 

CPU slots however are a strict limit and there is no oversubscription of them. The scheduler will only place jobs up to the defined slots of the node.

So as you describe if you REALLY want a node all to yourself you would ask for the 32 cores.

I would argue unless you really think you are going to go right up to that 128G line you might not need to.

**Comment by tatarsky** [comment]
Sorry, wrong cluster.

We allow as our overage on the 128GB nodes up to 150GB to be requested. 
And up to 300GB on the 256GB.

This again based on the currently supported at least by Ganglia view that folks are asking for more than they are using. (Or we would see periods of swap)

Happy to tune that up or down. But we also try to avoid swap for performance reasons.

**Comment by hurleyLi** [comment]
Current setting works OK, thanks for the clarification!
