### ISSUE TITLE
Failed RAID battery in controller 1 on OST1

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#146]
FYI I have opened a ticket with Advanced HPC to get Dell service on a RAID battery in Controller 1 on the OST1 array. 

The arrays have two controllers, but we do not want to operate in that manner for long. I am determining if we need to shutdown for its replacement but I hope thats not that case. 

Can somebody also check if SDSC power outages that I heard for Barry's group on the 30th are going to happen to your racks? I don't think they are but I'd like to check.

**Comment by tatarsky** [comment]
Battery coming by Monday. Advanced HPC will detail what steps are next at that point.

**Comment by hirokomatsui** [comment]
I've heard that the power outages on 30th will only affect to the servers with UPS. Ours are not.

**Comment by tatarsky** [comment]
Thank you. That is also what I believed true but wanted to double check. I will let people know if Advanced HPC requires a shutdown to fix this battery matter as soon as I get the information. I hope it not to be necessary at this time.

**Comment by tatarsky** [comment]
It is currently believed that this can be done safely as the controllers are redundant. However just for the record I am stating clearly in the outside chance the second controller failed in some way while the other controller was being repaired (having its battery replaced) we would have a Lustre un-mount. 

If that is not worth the risk even whatever the odds are we should disable jobs and un-mount Lustre ahead of times.

AHPC is still waiting on the part and will contact me when they have it.

**Comment by tatarsky** [comment]
Part arrived late in the day. Replacement scheduled for 11:00AM your time tomorrow. If possible reduced activity would be nice but we will attempt hot.

**Comment by tatarsky** [comment]
We believe this work completed correctly and I am just waiting now for the new battery to charge completely to confirm the final fix of the matter.

**Comment by tatarsky** [comment]
battery showing this morning its been fully charged so this is resolved.
