### ISSUE TITLE
Samba Server for Mappable Drives on Windows 

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#147]
Hi All,

I was interested in starting a Samba server. This is Windows specific. Sorry Mac people but I believe you already have a way of doing this without Samba (check out http://osxdaily.com/2010/09/20/map-a-network-drive-on-a-mac/) . This allows you to make a flh server directory mappable on your local machine. This is pretty useful when you’re generating figures and you need to view them on your local machine instantly or maybe you need to drag a particular file from your mapped directory to an email. 

If you’re interested please let me know. I’ll ask @tatarsky  if he can help us with this. 

Thanks,

Joaquin

**Comment by tatarsky** [comment]
I am closing this if no further comment. While Samba support is possible it adds some security requirements to the head nodes if used and it would need to be firewalled to a limited range. I also do not support Windows systems in any form on this agreement so all client side debugging would be up to the user there. Re-open if it was desired and just never asked for!
