### ISSUE TITLE
Old old processes on fl-hn1

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#150]
Folks, we've been up for awhile on the head node (nearly a year) and as a result I believe we have a fair pile of items running that people have forgotten.

I am shortly going to kill head node processes that are over a year old. 

Then I will be killing slowly January, February and March aged processes. 

If you wish to see if you are involved consider:

`ps aux|grep Jan`

`ps aux|grep Feb`

If you have something you know is that far back and ACTIVE please let me know. 

We may need to set bash timeouts of a month or something.

**Comment by tatarsky** [comment]
These items will be killed shortly as they are from January.

```
djakubosky    6815  0.0  0.0 124300  1004 ?        Ss   Jan25   0:01 SCREEN
djakubosky   6816  0.0  0.0 106800   448 pts/7    Ss+  Jan25   0:01 -bash
nnariai  11611  0.0  0.0 417512     8 ?        Sl   Jan28   0:03 /frazer01/home/nnariai/anaconda2/lib/R/bin/exec/R --slave -e IRkernel::main() --args /frazer01/home/nnariai/.local/share/jupyter/runtime/kernel-9caf91a5-7903-4743-9504-7ac6528ff667.json
djakubosky     16889  0.0  0.0 124364  1008 ?        Ss   Jan04   0:09 SCREEN
djakubosky     16890  0.0  0.0 106756   416 pts/31   Ss+  Jan04   0:03 -bash
nnariai  17908  0.0  0.0 6559852    8 ?        Sl   Jan27  12:55 /frazer01/home/nnariai/anaconda2/lib/R/bin/exec/R --slave -e IRkernel::main() --args /frazer01/home/nnariai/.local/share/jupyter/runtime/kernel-2b10ceb6-3849-4209-bd7d-646c9b816192.json
hiroko   21357  0.0  0.0  27484     8 ?        Ss   Jan06   0:00 SCREEN
hiroko   21875  0.0  0.0   9716     8 pts/46   Ss+  Jan06   0:00 /bin/bash
nnariai  26049  0.0  0.0 127976  5344 ?        Ss   Jan21  24:09 SCREEN
hiroko   31778  0.0  0.0   9716     8 pts/37   Ss   Jan06   0:00 /bin/bash
hiroko   32021  0.0  0.0  58824     8 pts/37   S+   Jan06   0:00 ssh igm-storage1.ucsd.edu
```

**Comment by billgreenwald** [comment]
Is there a way to leave jupyter notebook servers running, or should we be restarting them more frequently so that it doesnt become an issue?

**Comment by tatarsky** [comment]
Well, I'm debating the energy involved in this if #149 is unrelated. Basically people should review their process listings periodically and if they aren't using something, they should go kill it. I am unlikely to police old processes unless I determine in #149 we have a resource issue. My initial pass at it I was concerned we were out of ports for them to run. 

I don't mind long running processes.

**Comment by tatarsky** [comment]
What may help (and what I may be seeing but I'm not sure) if you have multiple notebooks open that you've perhaps forgotten are open you might shut them down (Running Tab, Notebooks). 

I'm still trying to debug what is being reported in #149.

**Comment by tatarsky** [comment]
I am dropping this concept for now.
