### ISSUE TITLE
Spare RAM from Barry Demchak

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#151]
Barry (who I work with on his cluster) has generously offered some of the older RAM from their recent upgrade to consider for adding in the CN older nodes. Those nodes have 64GB of ram in them. Depending on the banking rules we could probably push some of them more towards 128GB. 

This would require some coordination and off-lining of nodes. He suggested also that I contact the SDSC operators to see if they wanted to do the work for us. If they do not, I'd pursue some other options. 

If anyone _OBJECTS_ to me asking SDSC about that can you please say so here? I am of the belief that the CN older nodes are sporadically used and off-lining one or two at a time to perform updates would not be a big deal.

**Comment by tatarsky** [comment]
Will contact SDSC shortly and see whats involved!

**Comment by hirokomatsui** [comment]
Thanks, please let us know.
It's nothing harmful go get more RAM, just will be involving 1-2 people half a day work to install them.

**Comment by tatarsky** [comment]
Do you mind asking the SDSC operators to do it or would you like Barry to give to you? 

I have no preference. Barry suggested asking the SDSC operators would be interested. My goal is to not generate any costs though....

**Comment by tatarsky** [comment]
Sorry and in the above comment I meant I will ask the operators unless you want to!

**Comment by tatarsky** [comment]
This BTW is not a high priority....but donated RAM is always a good thing ;)

**Comment by hirokomatsui** [comment]
I'm not sure if they can install them without anyone's there to direct the detail, slots and etc.
Can you ask them?
If they cant, can you ask Barry to leave the RAMs at SDSC asking to hold them for Hiroko. I'll get them later.

**Comment by tatarsky** [comment]
I will ask and I have the motherboard manual but agree that is the complex part with motherboards like these older nodes. (Quad socket).

**Comment by hirokomatsui** [comment]
Thanks, yea I'm sure they will help me to install it once I get there anyway.

**Comment by tatarsky** [comment]
I will use the last ticket email I have to start the conversation.

**Comment by tatarsky** [comment]
I sent a request to see if thats something they do!

**Comment by tatarsky** [comment]
Barry has dropped off the RAM. The plan remains to see if its a big deal to move CN1 to 128GB and proceed from there. I've tried to mark CN1 with its identify light but can also shut it down. I don't know if its labelled.

**Comment by tatarsky** [comment]
CN1 update successful. Continuing to work with SDSC Ops to do others as they have time:

```
HOSTNAME                ARCH         NCPU NSOC NCOR NTHR  LOAD  MEMTOT  MEMUSE  SWAPTO  SWAPUS
----------------------------------------------------------------------------------------------
global                  -               -    -    -    -     -       -       -       -       -
cn1                     lx-amd64       32    4   32   32  0.16  126.0G  906.4M   31.5G     0.0
```

Will adjust h_vmem limit on node appropriately and re-enable queue.

**Comment by hirokomatsui** [comment]
Great! Thanks!

**Comment by tatarsky** [comment]
I believe this is as complete as reasonable. A couple of nodes are in bad shape and we may part them out soon.

cn4 didn't see all the ram but also has a failed BIOS battery and keeps loosing its clock on power disconnect. Its also reporting its boot disk is about to fail. So this system may not be with us much longer so I did not have the SDSC fight with the DIMMS. I believe these units are out of warranty. 

cn11 didn't see one 4GB dimm. While I could ask them to reseat perhaps I catch that another time. I think its OK to put back with it short that one but advise if you feel otherwise. I view these nodes as a form of "overflow" for low priority things.

Also I noted cn7 was actually still turned on. We know that unit doesn't boot anymore. I turned it off via IPMI.

But basically 10 of the old nodes now have 128GB of RAM. 7 remain 64GB.

I've adjusted the h_vmem max for the larger ones. All remain in the `opt.q`

**Comment by tatarsky** [comment]
cn4 I am holding out of SGE as basically S.M.A.R.T. says that drive isn't going to make it much longer:

```
smartctl -A /dev/sda
  5 Reallocated_Sector_Ct   0x0033   017   017   036    Pre-fail  Always   FAILING_NOW 3415
196 Reallocated_Event_Count 0x0033   017   017   036    Pre-fail  Always   FAILING_NOW 3415
```

Unwise to run a box in that state as it can produce unpredictable results. If the drives are easily swappable we could grab one from cn7 and Kickstart it. Low priority I feel. Up to you folks.

**Comment by hirokomatsui** [comment]
It's out of warranty. We will keep cn4 off.
Thanks!

**Comment by tatarsky** [comment]
I don't know the warranty terms of these nodes....but I suspect its at least 4-5 years old. 
I will shutdown `cn4`

**Comment by tatarsky** [comment]
Asked if they have time to move the RAM they added to cn4 to cn13.

**Comment by tatarsky** [comment]
This is done! So I believe at this point the effort is completed!

**Comment by hirokomatsui** [comment]
Thanks! Will SGE recognize that itself?

**Comment by tatarsky** [comment]
SGE does and I've already adjusted our h_vmem oversubscription for the ones with more memory to the same level as we do on the other 128GB machines. If you see that not being the case just let me know the node.

**Comment by hirokomatsui** [comment]
OK, Thanks!

**Comment by tatarsky** [comment]
No problem!
