### ISSUE TITLE
date/time on NAS

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#152]
I found that there's a problem with data/time. For the confluence analysis, we take pictures of cells and predict when they will be ready based on the time when the pictures are taken.
We have just found that something weird is going on. If I copy something now from /nas/Projects/CARDIPS/2_CARDiPS_SubProjects/Production/Cardips_tissue_culture/Microscopy/Cardips_production_confluence_automatic/confluence_images file creation date is 1:30 AM on 9/26 (it's 5:30 PM now). If I use -p the date is still wrong: it doesn't correspond to the right date (the creation date of the files I am interested in is 8PM tonight). 
If I check the date however, I get the right time:
Sun Sep 25 17:31:44 PDT 2016

It's very important to have the right date/time to correctly predict when cells will be ready.

How is it possible to adjust the right date/time? It doesn't matter much about the files already analyzed, but we need to set it right for the next analyses.

Thank you

**Comment by tatarsky** [comment]
I have no access to the NAS device. The cluster is NTP sync'd to these three SDSC timeservers. If the NAS could be verified to do the same that would be ideal to use the same ones.

```
ns1.sdsc.edu
ns0.sdsc.edu
moe.sdsc.edu
```

**Comment by tatarsky** [comment]
@hirokomatsui just checking if you saw this. I don't know if you manage the NAS device but I will close this if handled.

**Comment by hirokomatsui** [comment]
Thanks, I will work on that.

**Comment by tatarsky** [comment]
Assuming that is the problem....if its not, can look closer at the output of "stat" on a sample file.

**Comment by hirokomatsui** [comment]
I've set the NTP server and started the client. It will be fine for now on.

**Comment by tatarsky** [comment]
@s041629 confirm the above fixed your matter please at your convenience and then can close.
