### ISSUE TITLE
python on flh1 vs flh2

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#154]
Does anyone know why when I run python scripts on flh1 it takes significantly longer than on flh2?  My database query script can finish on flh2 by the time flh1 is still loading the first module.

Every time I have tested it, the flh1 has not been full on core use, or RAM use, only very high on swap memory.

**Comment by tatarsky** [comment]
This would require some debugging with you to see whats going on. There should not be any difference but I'd have to understand what the script is doing to see if any resources are overwhelmed. Might be time for an flh1 boot. I will check the swap situation. I noted last time I looked we had some very old processes that people may have forgotten about. 

More debugging than that however would have to be next week as I am heading out for the day.

**Comment by tatarsky** [comment]
Generically somebody might locate and ask the user `mdonovan` why they have 155 R processes on fl-hn1. I believe they are leftover notebooks. 

Some other users have lower counts but that user definitely could use a check they know how many items they are running and clean up a bit.

Everyone might consider on a Friday a check for strays:

`ps ux`

Is a useful command to type periodically. 

Or I can start killing old processes again. But I'd prefer people police their own....

**Comment by tatarsky** [comment]
Also just curious...any reason you don't want to use a node for the script? As in a qlogin?

**Comment by hirokomatsui** [comment]
The nodes don't have access to the MySQL server on flh1. We could set that up though.

**Comment by tatarsky** [comment]
The network socket is listening. Did you restrict the Mysql accounts to particular hosts?
If the accounts are not restricting, the Mysql server can be reached via a construct like this:

```
mysql --host=fl-hn1-fast --user=XXX --password=YYY
```

Thats talking to the 10G side on purpose for speed. But the login is subject to proper Mysql host/user/db table entries. Happy to help with it just advise.

**Comment by billgreenwald** [comment]
The script is extremely light weight--it runs in a matter of seconds and uses less than a few MB of ram.  It's just a wrapper for querying the database (which I have only tried on the head nodes, seems like there may be a problem if it runs on a different node?)

**Comment by tatarsky** [comment]
A quick check shows most mysql user accounts list `%` as the hostname (compared to localhost which WOULD restrict access). `%` however should work from any node as I describe. 

Try your Mysql account as such from a qlogin to see what occurs and work with @hirokomatsui if the account is restricted to localhost access compared to '%'

```
mysql --user=yourusername --password=yourpassword --host=fl-hn1-fast databasename
```

**Comment by tatarsky** [comment]
Somebody however needs to contact mdonovan. Or I can kill off all these jobs.

**Comment by tatarsky** [comment]
@djakubosky also please take a look at your process count. It is very high.

**Comment by billgreenwald** [comment]
I'll let mdonovan know

**Comment by hirokomatsui** [comment]
I found MySQL "cardips" user on the compute nodes have access to flh1 MySQL server.

**Comment by tatarsky** [comment]
Should by default unless you are restricting it using the "host" table. '%' = all hosts that can connect to the socket.

**Comment by tatarsky** [comment]
Please remember network Mysql speeds may be less than native disk speeds, but its an option to consider if you need more memory or wish to turn your item into a cluster job.

**Comment by tatarsky** [comment]
I can elaborate more later. I need to get my daughter from the airport. Have a good weekend. I'll check back on any process overloads on `fl-hn1` and we can consider limits or killing old strays.

**Comment by tatarsky** [comment]
One more thing ;)

basically if people that show up in:

```
 ps aux|grep IRkernel
```

Could all be asked to check their notebook kernel counts it would greatly help fl-hn1 which is running low on memory. if I have to implement user memory limits I will but I would prefer people clean up after old jobs. Bye for now!

**Comment by billgreenwald** [comment]
It is worth noting that David only has 6 ipython notebooks running--for some reason the process log duplicates iPython notebooks about 10-30 times each.  They are a single process though, only using the resources listed by a single process (ie 6 GB of ram, not 6x20=120GB of ram)

**Comment by tatarsky** [comment]
You might also strace your script and see if you see anything interesting. Or give me a way to take a look without altering your data....(for when I get back...off now).

**Comment by tatarsky** [comment]
Let me know if you have a way for me to look at this difference. I've cleared a few obviously stray processes but don't want to start to kill idle notebooks unless we prove this is a memory issue. I did force Linux to drop caches this morning which I've seen sometimes help on systems with long long uptimes. Which we have:

```
uptime
 11:49:32 up 347 days, 17:55, 44 users,  load average: 0.68, 0.42, 0.36
```

**Comment by tatarsky** [comment]
Just checking if this remains a problem or not. If not, I'll mark that dropping the caches helped....

**Comment by tatarsky** [comment]
Going twice....

**Comment by billgreenwald** [comment]
It's still taking longer on flh1 than flh2, but I haven't looked into why and it isn't a big deal since I can hop over to flh2 to call the script.

Im not sure if we want to put the time in to figuring it out?

**Comment by tatarsky** [comment]
I am more than happy to look if you can give me a way to run the command without messing up your data. I'd like to understand the resource problem compared to just rebooting the system to see if the behavior changes.

**Comment by tatarsky** [comment]
If thats a pain BTW to give me a small way to reproduce it, I'll keep looking for some causes as I can.

**Comment by billgreenwald** [comment]
I just retried the script on both--it took longer on flh1 the first time but seems to be back down to normal thereafter.

Seems resolved?

If you want to test for yourself the script is at /home/bill/database_wrapper/wrapper.py

Use the command "python queryDatabase.py -data data_id -dataType atacs".  It outputs a tsv to std.out so nothing will be messed up if you use it

**Comment by tatarsky** [comment]
That sounds indeed like memory caching issues if it alters speed between first/second runs. 

The memory on fl-hn1 is allocated all over the place due to idle and abandoned shells and notebooks as a result of its long uptime. 

I will attempt to prove that with your example but we may need to implement some head node process cleanup and timeouts and such. More on that shortly. Thanks for the example!

**Comment by billgreenwald** [comment]
Quick aside, mdonovan has a ton of R kernels running as mentioned earlier, but when we tried to shut them down, they wouldnt die from a kill signal in htop.

They were launched from an iPython R notebook kernel, but they have all been shut down.  None of us in the lab know how to fix this orphan problem.

**Comment by tatarsky** [comment]
Did you send `kill -9` ? 

I forget what htop signal gets sent but they should die with -9 sent. (Aka SIGKILL)

it probably sends 15 (SIGTERM) which depends on the process properly trapping that signal and exiting. There are many cases of situations where that will not work. 

So see if you can send -9 SIGKILL.

**Comment by billgreenwald** [comment]
It was SIGTERM, we will try SIGKILL and let you know.  thanks

**Comment by tatarsky** [comment]
If SIGKILL doesn't work, please let me know the PID as thats interesting.

**Comment by tatarsky** [comment]
As a mini "graphic" of the goal, I am trying to end the processes on the head node that I know are swapped out. The purple in this case. The large drop off was when I dropped the caches. Something that will build back up but your original complaints I believe result from being over on the far left side of this where ram was very fragmented and consumed. 

http://flh1.ucsd.edu/ganglia/?r=week&cs=&ce=&m=load_one&c=FrazerNodes&h=fl-hn1&tab=m&vn=&hide-hf=false&mc=2&z=medium&metric_group=ALLGROUPS

**Comment by tatarsky** [comment]
As another source of memory loss I've noted some folks are not cleaning up after jobs that use shared memory. I can cron a cleaner but be aware things like this can cause problems. If you don't know what shared memory is I can elaborate:

This is on a node. The fact is says "nattch 0" means no process is using it. But its still allocated.

```
------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status      
0x1780b760 2785280    matteo     666        1          0                       
0x1780b75f 2818049    matteo     666        30214456941 0                       
```

**Comment by tatarsky** [comment]
I have cleaned up the above on several nodes. Please consider checking any qsub that uses IPC shared memory for proper deletion of the segments on job exit. I will likely cron a cleaner as I have on other clusters as often these remnants come from other people's code and are hard to locate/debug how best to remove.

**Comment by tatarsky** [comment]
The result BTW that due to 30GB of shared memory consumed on several nodes, the active jobs on the nodes were swapping resulting in slower runtime. Hopefully that will help a bit.

**Comment by tatarsky** [comment]
One item that might add impact on a memory cache impacted machine I note that your PYTHONPATH includes areas that aren't needed:

```
PYTHONPATH=/frazer01/home/bill:/frazer01/home/bill/software/anaconda/bin:/frazer01/software/git/2.6.2/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
```

I believe that is a result from this .bashrc item:

```
export PYTHONPATH="/frazer01/home/bill:$PATH"
```

PYTHONPATH normally only needs to contain locations that would have python modules. Not binaries. And since I believe you are using Anaconda I believe already has compiled into it the module path...(please check...I'm not 100% sure)

This shows up a bit if you strace your python run and compare the number of open and stat syscalls. With the long PYTHONPATH its doing about 10000 more searches for python modules which I believe is being impacted by a slow inode/directory cache situation on fl-hn1. 

Still looking but wanted to mention that variable may not be correct and would speed python on ANY system, not just fl-hn1.

**Comment by tatarsky** [comment]
Generic followup on this. I've monitored memory on fl-hn1 and am of the opinion we might consider attempting to get some more.

**Comment by tatarsky** [comment]
Folding into #172 for discussion of head node use in general and memory requirements.
