### ISSUE TITLE
Head up as we approach 90% full on /frazer01

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#155]
We are down to 61TB free. Cleanup might be in order soon.

```
df -h /frazer01/
Filesystem            Size  Used Avail Use% Mounted on
10.8.16.29@tcp0:10.8.16.30@tcp0:/frazer01
                      524T  437T   61T  88% /frazer01
```

**Comment by hirokomatsui** [comment]
I'm going to move a lot of retina project's data to the new storage once it's ready. Thank you for catching this up.

**Comment by tatarsky** [comment]
Sounds good! Closing as folks are aware....
