### ISSUE TITLE
Connect to flh1 via cyberduck

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#16]
Having issues connecting to flh1 via cyberduck, no issues connecting via direct ssh.

Curious as to why this would be

**Comment by tatarsky** [comment]
What protocol do you have cyberduck set to use?

**Comment by djakubosky** [comment]
Just FTP, which worked fine for the old cluster.

**Comment by tatarsky** [comment]
FTP is insecure. 

I recommend you use SFTP which is really SSH based. 

If you require FTP I would like it approved by Kelly before enabling it. I consider it a security risk.

**Comment by djakubosky** [comment]
No, no problem, this will work great, thanks!

**Comment by tatarsky** [comment]
Ok. I would advise real care if FTP is still being used in the modern era. Your password travels in the clear with regular FTP. And while intercepting it is dependent on network locations and conditions I would be very very cautious using it. SFTP is so much safer.
