### ISSUE TITLE
nfsd processes on flh2

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#160]
It seems like there are lot of nfsd processes on flh2 (I see them in top) and things are going pretty slow for me. Any ideas @tatarsky ?

**Comment by tatarsky** [comment]
flh2 provides access to Lustre for the older nodes which have no 10G card to get to the Lustre directly.
This may mean that somebody is running jobs on the `opt.q` which are using heavier I/O to that than we discussed. The `opt.q` was for compute heavy BUT low I/O items.

It appears @hurleyLi is running something called `macs2_down` on the opt.q and perhaps can explain its I/O.

I cannot provide direct Lustre from the old nodes over 1G. So best to confine heavy I/O to the new nodes.

**Comment by tatarsky** [comment]
To be clear it provides Lustre via an NFS redirect to fl-hn2.

**Comment by tatarsky** [comment]
Be aware the entire max I/O from the old nodes regardless is limited to 1G as thats all that is connected to the other rack. I see a fair level of I/O coming from those nodes so am suspecting these jobs may need to be rethought a bit for placement.

**Comment by tatarsky** [comment]
BTW see #120 for additional information.

**Comment by hurleyLi** [comment]
I see. will run on other queues

**Comment by tatarsky** [comment]
Basically the old nodes make fairly good systems for qlogins or other interactive/compute class of work. Without a real network connection from that rack they don't make good I/O platforms to the Lustre filesystem. If we wish to change that, we need to invest in getting them on the 10G side of the network.

**Comment by cdeboever3** [comment]
Thanks, I forgot that the old nodes go through flh2. Everything is working fine for me now.
