### ISSUE TITLE
reptyr

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#162]
Hi Paul,

I have been reading up on how to transfer processes to screen if I forget to launch them in a screen/a process takes longer than I was expecting, and the methods I see all use the program "reptyr"

Its on apt-get.  Could you install it?  Or should I be doing it for just me?

Thanks

**Comment by tatarsky** [comment]
apt-get is an Ubuntu/Debian concept. We are RHEL/RPM based. 

I will look if there is an RPM however and if not I'll build a module for you in the morning.

**Comment by tatarsky** [comment]
I loaded reptyr from EPEL on fl-hn1. Can you confirm that is recent version enough and works? If so I'll add to the default puppet package list. 

It appears to be a 0.3 version. His Github is up to a 0.6.

If too old I will make a module for you tomorrow.

**Comment by billgreenwald** [comment]
I can run it, but when I am trying to transfer a test process as soon as I disowned the process it was killed.  The message was "-bash: warning: deleting stopped job 1 with process group 12513"

**Comment by tatarsky** [comment]
Manually try this source build....no module yet:

`/frazer01/software/reptyr-0.6.2/bin/reptyr`

I just moved a top process to my screen. Nice.

**Comment by billgreenwald** [comment]
It worked for me.  Can't locate reptyr anymore

**Comment by tatarsky** [comment]
Whacked the RPM (too old) and making you a module ;)

**Comment by tatarsky** [comment]
Try this out:
`module add reptyr`

```
reptyr -v
This is reptyr version 0.6.2.
 by Nelson Elhage <nelhage@nelhage.com>
```

**Comment by billgreenwald** [comment]
module worked

I get "Timed out waiting for child stop. Unable to attach to pid 23934: Operation not permitted"

Edit:  Seems like it was the wrong vcftools.  I just get a time out error with the corerct one

**Comment by billgreenwald** [comment]
So I ran 

`reptyr [process number]`

 and I have a hang--no output is written but the shell is waiting.  also, it spawned another process with the same name, but it is marked as defunct.

we can trouble shoot more tomorrow, no rush

**Comment by tatarsky** [comment]
I would scan the Git issues for similar items and I'll take a look more tomorrow. I've never used the tool.

**Comment by billgreenwald** [comment]
I just tried it with python and it worked fine.  I think it actually worked fine but vcftools doesn't write anything out while running, thus the blank screen.

We can probably close this for now and assume it is working

**Comment by tatarsky** [comment]
Okey doke. Thats a nice find!
