### ISSUE TITLE
Frazer-share (the NAS) appears to be busy or having issues

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#164]
The mount of /nas on the headnodes is hanging trying to talk to frazer-share.

I have no access to this unit so if possible please check it. It might just be busy so I'll check back in a bit. 

`nfs: server frazer-share.ucsd.edu not responding, still trying`

**Comment by hirokomatsui** [comment]
We've moved frazer-share to the new building so as the IP address and VLAN were changed.
It was 172.16.163.54, and is now 172.16.200.40
I can't find if there's any setting with the IP, flh1 can solve the IP address by the name though.
I am trying to solve the NFS mount on flc to frazer-share, but couldn't fix it. It's getting a lot of attack via network now.

**Comment by tatarsky** [comment]
Ah OK. Its wise to umount a NFS mount when a system changes its IP. 

Let me see if I can force umount it and re-mount. I will send the instructions if that works out. Otherwise we may have to reboot the head nodes to clear the mount.

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
OK, a `umount -l /nas` worked on fl-hn1 but we may have a few defunct processes from items that were using that share. 

You should try the following first (a force umount) on flc. 

`umount -f /nas`

**Comment by tatarsky** [comment]
And I have remounted it on fl-hn1 as /nas. I note it was not on fl-hn2. Advise if that is wanted.

**Comment by hirokomatsui** [comment]
I could re-mount /nas on flc. Thanks!

**Comment by tatarsky** [comment]
Cool. Then we are good to go.
