### ISSUE TITLE
syntax error near unexpected token `('

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#165]
Hi @tatarsky 
I my script I have some kind of syntax like this (not the exact command, but the same syntax, somehow I need to pipe two input to paste)
```
paste <(echo a) <(echo b)
```
It runs fine on the flh1, but when I submit this command to sge, it gave me error:
```
syntax error near unexpected token `('
```
Do you know why this happened? any way to work around this if I want to this kind of syntax?

Thanks,
Hurley

**Comment by tatarsky** [comment]
I assume this is in a qsub of a script. 
qsub does have some limitations IIRC in terms of some shell redirects which I'll have to look up workarounds. 

I dimly recall using a construct like this however on some cases:

```bash -c "paste <(echo a) <(echo b)"```

But I'd have to see the whole context of your item.

**Comment by tatarsky** [comment]
Closing. No additional information provided.
