### ISSUE TITLE
Installing pypy

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#166]
Hi Paul,

Could you install pypy for me?  It is another python compiler that gives a large speed boost to programs written without python libraries.  It would be helpful for the software I just wrote (both for running and testing).

Perhaps a module would be useful?  It should be available on yum via "yum pypy"

Thanks!

**Comment by tatarsky** [comment]
Modules are not needed for items loaded as RPMs as they are in the default paths.

I've loaded to confirm the EPEL version does what you want on fl-hn1. 

Confirm its working and I'll add to puppet for all nodes in a bit. 

fl-hn1> which pypy
/usr/bin/pypy

**Comment by billgreenwald** [comment]
Yep thats perfect

**Comment by billgreenwald** [comment]
If you can put it on the nodes and flh2 as well, I would like to try it with some jobs

**Comment by tatarsky** [comment]
Sorry, I added it a bit ago but got pulled into a battle. 

Checking its "everywhere" seems to say "all set"! 

Advise if you see otherwise by system.

**Comment by billgreenwald** [comment]
Seems to have worked, thanks!

**Comment by tatarsky** [comment]
Most excellent. Closing for now! Advise if problems!
