### ISSUE TITLE
Install Docker on the cluster

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#168]
Hi Paul, 
I would like to install docker on the cluster so we can access docker images. 

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-getting-started

I think someone with admin access will be required to set it up. 
Let me know what you think

**Comment by tatarsky** [comment]
Docker does not work well on CentOS 6 kernels. (Believe me I've dealt with attempts) and adds considerable complexity to an environment and security holes. 

 So I decline to support Docker on this cluster. 

However, I have recently been deploying Singularity which was far better designed for HPC use by LBL and does many of the same concepts and also can import docker images. 

http://singularity.lbl.gov/

If you have a docker image to test I can provide you some steps to take a look if it meets your needs.

**Comment by djakubosky** [comment]
Understood, I've never used it before, but have found that tools are increasingly offered with docker images as an alternative to install.  

I have an example docker image here. 


I have been attempting to test out something called beakerlab (a type of polyglot notebook that can support translation of data between languages automatically)

https://hub.docker.com/r/beakernotebook/beaker/

I'm not entirely sure how you actually run a docker file

https://github.com/twosigma/beaker-notebook/blob/master/Dockerfile

I think that is the real one

**Comment by tatarsky** [comment]
I understand the need but basically Docker requires a newer distro (3.X kernels being the main requirement) to support well and even then its a bit problematic. SDSC for example supports Singularity for the same reasons I am encouraging we take a look at it. 

I will take a look at the items above tomorrow and see if they can map to Singularity. 

If that doesn't work, I would propose we consider some nodes to update to CentOS 7 and make "docker nodes" but that would require some discussion of the issues I have run into and the time it would take to support.

**Comment by tatarsky** [comment]
This appears to be heavily focused on web based use of the software. This may be a better fit for some standalone system. Did you intend to use this via the scheduler?

**Comment by tatarsky** [comment]
This BTW has been imported into singularity format but I have to figure out how to actually use it. That probably won't be today given over workloads but I've got a fairly good start and am keeping notes. Please advise when you can anything you know about "how this gets used". Seems like a Notebook web page....

**Comment by djakubosky** [comment]
I intended to use it the same way as the jupyter notebooks that we are currently running on the head nodes.

**Comment by djakubosky** [comment]
From what I understand, this works the same way as a jupyter notebook, the annoying thing may be configuring what port the notebook runs through, as I'm not really sure how the config settings work here.

**Comment by tatarsky** [comment]
Docker is an entire chroot image running system. And when you get a docker image its configured whatever way they wanted to do it in that chroot image. You can sometimes mess around with the settings but think of it sort of like a tiny Virtual Machine. Its not quite that in reality but its easier to think about that way I feel. 

Singularity doesn't really alter that last bit. But may if we get lucky remove the need for the rather baroque docker infrastructure involved and the large security holes it adds to service docker requests. 

More after I understand a bit more of the services this docker image supports. I do not fully understand them yet.

**Comment by djakubosky** [comment]
Thanks for the clarification, maybe its possible to just install beakernotebook without a docker image instead?  Shows support for mac, windows and linux, but I dunno about CentOS..

**Comment by djakubosky** [comment]
I have some doubts about getting the docker image to work anyway, considering I have been unsuccessful getting it to work properly using docker on my Mac.  UPDATE: I did get it running using the instructions here

https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container

**Comment by tatarsky** [comment]
Interesting. I will see if that works in Singularity. If it doesn't I'll check the build instructions for the non-docker use. Might be easier overall.

**Comment by tatarsky** [comment]
Given its a web service BTW, my suggestion after that is we consider a head node for more of this class of item perhaps running CentOS 7 to support docker. Items with web services don't map well to cluster jobs as the nodes are not exposed directly. Perhaps we have a meeting to discuss a few other enhancements at some point soon.

**Comment by tatarsky** [comment]
So with some wrangling I have at least this going:

https://flh2.ucsd.edu:8800/

The password for now is as they generate: `7q72oj54vge9ds1h8bol`

Note you will have to accept an SSL certificate security exception. Looks like a self-signed. 

This port is for now open to the world and there are additional security items I will have to do in order to allow "you" to run this image under singularity. But if you could confirm the web items _work_ as you expect we can devote further effort.

**Comment by tatarsky** [comment]
Something may still require more tweaks as this popped onto the "console"

```[I 16:25:44.793 NotebookApp] The Jupyter Notebook is running at: http://127.0.0.1:8814/```

Which means its binding some of its items to localhost. I doubt we'd want that. I'll look more shortly. Test as you can other items.

**Comment by djakubosky** [comment]
It appears to work correctly, but unlike in the docker container on my Mac computer, it doesn't look like we have access to "host" files, I assume this is by design?  Otherwise the functionality seems fine for me.  I have some questions about Singularity, does a user have to commit changes to containers in singularity also (like you do in docker)?  I'll do a bit of googling and try to learn about it, but it wasn't clear looking immediately at its docs.

**Comment by tatarsky** [comment]
What do you mean "host" files? Arbitrary access to any path on the host? Or items owned by your UID? This image is running under my UID which may alter what it connects to what so an example will be needed for me to explore that.

Singularity images in "write" mode I believe commit on exit.

**Comment by djakubosky** [comment]
Yah what I meant is access to paths on the host.  When I go to open or save a file in a beaker notebook using my docker image on my mac, there is a folder /home/beaker/host which has paths from my local computer.  The way I understand it, you can either save new files to the docker image container, seemingly unaccessible when the docker image isn't running, or to your local machine.  I wanted to know if this behavior is similar on singularity.

**Comment by tatarsky** [comment]
Yeah, that may require some extra games. But I'll look at what they "mount" on docker for this image and it may just be some extra flags. I'll see if I can get the precise same option. 

Yes, when you shutdown a docker (or singularity image) the files contained in that image are NOT in a normally accessible way. Think again like a Virtual Machine. The files are in a large disk image not the regular filesystem.

**Comment by tatarsky** [comment]
Also note: I am going to shutdown this singularity image for a bit and poke around at its internals.

**Comment by tatarsky** [comment]
Placing this here as the way singularity defaults items...working on making this "beaker" daemon account a more automatic item. 

http://singularity.lbl.gov/image-environment

**Comment by tatarsky** [comment]
OK. So Singularity definitely tries to keep these chroots secure! Experiment now in progress should make /frazer01 available from the running image. Please see if what I see is what you see.

Current password for the same URL as before is: `3dalgme76q29e39gei01`

**Comment by tatarsky** [comment]
Note clearly BTW that the /home/beaker/home area is NOT linked at the moment. Go to the little hard drive that shows the whole image....
![beaker](https://cloud.githubusercontent.com/assets/6439722/21330273/5667802a-c602-11e6-8029-91355af8faf0.png)

**Comment by djakubosky** [comment]
I am testing this now, looks like I see what you see, one thing that is weird is that now it can't seem to initialize the ipython kernal (python 2) when I launch a default notebook.  Not sure why that might happen.  

EDIT: The first time (under the old password) the python kernal launched correctly and I was able to use it in testing

**Comment by tatarsky** [comment]
OK. Well I'll look some more a bit later. Some errors going by on the command output. Unsure what they mean. 

The from source build BTW appears targeted to a Ubuntu system. So I'm not even going to try that path.

**Comment by djakubosky** [comment]
Also, I think it is preferable to keep the image of our filesystem separate, as it is now, so paths from existing python notebooks will still work when run in a beaker notebook.

**Comment by tatarsky** [comment]
Makes sense.

**Comment by tatarsky** [comment]
The "New Default  Notebook" opening seems to for whatever reason bind to 127.0.0.1 and some higher port from 8800. 

That's probably not 100% correct for use from a server that is not the "same" as the system you are sitting on. (Aka your mac). So it seems like some additional settings need to be made for what I believe they call "public server" mode. It may also involve additional iptables work.

**Comment by djakubosky** [comment]
Thanks for looking into this! hopefully it is possible to make it server compatible.

**Comment by tatarsky** [comment]
Some of their Git issues seem to state this is seen on docker as well sometimes. I'll be shutting it down in a bit to take a look at another item I saw mentioned.

**Comment by tatarsky** [comment]
I believe I see the best way for folks to run this. I would like to make a directory in your homedir called `singularity` or something similar and place a copy of this image there for you to then issue some command on fl-hn2.

At the moment I have the image configured to "public_server" mode on just that host since it sort of wants you to issue a hostname. I will provide the commands to issue once you confirm its OK for me to make a directory in your homedir.

I believe I solved the "new default notebook" matter but its tied in part to the running user.

**Comment by djakubosky** [comment]
I think that sounds great, go ahead and make the directory it needed.
Maybe it is possible to let a user use their anaconda install for python
kernels

**Comment by tatarsky** [comment]
Probably not the way this image is designed. If you want that kind of flexibility you would be altering the image. What you refer to is your _own_ environment. Docker images are a self-contained environment.

**Comment by djakubosky** [comment]
I think generally this should be ok if we can figure out how to install a
few additional packages to the image

**Comment by tatarsky** [comment]
Please try the following as yourself on ONLY `flh2`

```
module add singularity
singularity run -w singularity/beakerlab2.img
```

It will kick out a URL based on an IP which is actually flhn2. I don't know why it uses an IP. It will also provide a password.

This service will also have I believe your homedir connected by default. Singularity tries to only provide access to what a user can see by default. 

Errors and such I'll look as I have time.

**Comment by djakubosky** [comment]
Will test shortly, will we be able to access files/folders in
Frazer/projects?? Just wondering.

**Comment by tatarsky** [comment]
Try it. 

Its running as your UID in singularity. So in theory if the bind mount works you will see /frazer01. Note that the "/home/beaker/home" thing isn't something that will work in Singularity. But you should see your homedir and if you expand to the computer icon you should see /frazer01. 

I did when I tested the same.

**Comment by djakubosky** [comment]
Ok, is there a way to save changes to a disk image?

**Comment by djakubosky** [comment]
What you have put together works fine for me, this is great! only thing left would be attempting to install a few python packages.  I was able to install them into the docker images like this 

docker exec $container_id /home/beaker/py3k/bin/pip install redis

I dunno if this will be possible through singularity or not

https://github.com/twosigma/beaker-notebook/wiki/Running-the-Docker-Container

this is where I found instructions on customizing the container.  There are some common bioinformatics packages we would need to install into the python to make this image more useful to everyone.  With the right setup, it would be possible to run most existing python notebooks right in the docker image and work on them with beakernotebook

**Comment by djakubosky** [comment]
Just wanted to add that it doesn't seem possible to access /frazer01/projects as of yet.  Otherwise functions seem to work well.

**Comment by tatarsky** [comment]
So the singularity work flow for image creation is usually done on a workstation where the person building the image has root. This is consistent with their security model. While you can save changes to the image I gave you (the `-w` flag means its writable) under the cluster you are doing all operations as your userid. So adding software and such won't work probably the way you think it will.

Docker "works around this" by simply having all operations be done by root. Which is why its a security hole and I won't support it.

So for you, two main choices: learn singularity and place it on your workstation. Root requiring operations then can be done by you anytime and you just rsync over the image to the cluster when ready.

Have me do what you want to do. 

Most people opt for number 1. Its not overly difficulty and most of the commands are "the same" as docker.

**Comment by tatarsky** [comment]
I will look into the /frazer01/projects item. It showed up when I ran it.
