### ISSUE TITLE
flh1 error

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#170]
In the case if you're not in the holiday vacation yet, flh1's acting weird.
It looks like sge server module's down. I see the lines in the /var/log/messages:

Dec 22 16:50:23 fl-hn1 kernel: Out of memory: Kill process 9638 (sge_qmaster) score 167 or sacrifice child
Dec 22 16:50:23 fl-hn1 kernel: Killed process 9638, UID 0, (sge_qmaster) total-vm:47925340kB, anon-rss:47047612kB, file-rss:24kB

also the error on the prompt after qstat command:

error: commlib error: got select error (Connection refused)
error: unable to send message to qmaster using port 6444 on host "fl-hn1": got send error

I will come back to check it tomorrow.

**Comment by nariai** [comment]
I submitted a fair amount of jobs minutes ago, which might be the cause of this error. In the future, I will avoid this with array_jobs.

**Comment by tatarsky** [comment]
Something caused all the memory on fl-hn1 to be consumed. What you see above is the kernel out of memory manager deciding that _killing_ sge_qmaster would be a good way to solve it. 

I do not know at the moment if that the submitting of jobs caused it as thats not usually a high memory item but I will check the logs. 

I have restarted sge_qmaster. 

If necessary I will limit the process memory of items on the head node or you can ask for some more memory to be purchased.

**Comment by tatarsky** [comment]
Appears to have happened again. Checking the processes on the head node. High memory items there really should be on the nodes unless there is a compelling need for them to be exposed.

**Comment by tatarsky** [comment]
Lots of python notebooks again. Users should be asked to check if they are truly needed.

**Comment by tatarsky** [comment]
While the number of jobs is fairly high in the queue the overall issue is that we need a chat at some point about resource use on the head nodes. We have people not cleaning up stray screens and notebooks and shells. We might also consider more memory in the head node as a relatively cheap improvement.

**Comment by tatarsky** [comment]
The user matteo has a set of Notebooks that are consuming a fair level of memory each. Those should just also be checked if they are all needed.

**Comment by tatarsky** [comment]
And yes array jobs would be a bit more efficient. I am adding some swap for now until we get a few things cleaned up which I doubt will happen in the next few days due to the holidays.

**Comment by nariai** [comment]
Dear all,

Please remember that flh1 and flh2 are shared resources, and they need to be alive for logging in / manage jobs / web servers / databases. Hence, please do not occupy a large portion of memory space (and cpu cores) for a long time on head nodes. If you have some unnecessary python/R notebooks or other processes running on head nodes, please kell them and free memory / cpu resources for other people to use. If you really need to run a job that consumes a large memory (especially with python/R notebooks), please run it on compute nodes. Both flh1 and flh2 are supposed to be used primarily for gateway / job management, and for some small-scale interactive jobs (which do not consume a lot of memory space), if any.

I understand that for standard users, it is difficult to monitor / manage resources by themselves. Also, I don't think anybody wants to be a manager on how people are running processes. Hence, I propose to impose a maximum memory per user on head nodes. I would say, something like 16GB per user. If you need to use more memory than that, you should use compute nodes. Please consider this idea (imposing maximum memory per user on head nodes), and let's discuss when people come back after holidays in early January. Have a nice holiday!

**Comment by tatarsky** [comment]
Memory limits (ulimit -a) are per process (not per user) enforceable. But you are on the right track ;) Usually a hard limit on process memory acts to encourage the use of a node to get around that limit. 

I am happy to describe this further when you discuss it. 

Declaring a policy on long running processes would also be worthwhile on the head nodes where the scheduler is not enforcing such things. Just remember limits are usually per process.

**Comment by nariai** [comment]
Thanks @tatarsky, a memory limit per process should be OK.
I'm hoping this limit will encourage users try not to run heavy jobs on head nodes.

I also think that a policy on long running processes is worth considering.
Maybe we can set, something like, one month per process.
Let's also discuss this after the break!

**Comment by tatarsky** [comment]
We seem to have recovered more or less and appears to have been some cleaning! Leaving open for now to be discussion area on limits.

**Comment by nariai** [comment]
I tried to submit jobs again, but it looks like it went something wrong:

> qstat
error: failed receiving gdi request response for mid=1 (got syncron message receive timeout error).

When you have time, could restart sge_qmaster again?

Thank you.

**Comment by tatarsky** [comment]
That is not the same error. But restarted. How many jobs are you submitting?

**Comment by tatarsky** [comment]
I show nearly 11000 jobs. It is timing out trying to present data from them. Did you submit that many?

**Comment by nariai** [comment]
Yes, I submitted something like 20k with dependencies among each.
I'm trying to kill them, but I cannot kill them for some reason.
Could you kill all the submitted job (by nnariai)?
Next time, I will start from small scale jobs.

**Comment by tatarsky** [comment]
I am seeing if the timeout can be adjusted. Have you ever submitted this many before?

I'm trying to determine basically while I am on a holiday if the head node is damaged to the point a reboot is needed. But if you've never submitted that many before, we may have a memory requirement increase instead.

**Comment by nariai** [comment]
Yes, I had submitted about the same number before (20k), and it went through in the past. However, this time, it is with dependencies (-hold_jid). I'm guessing this might have caused some problem.

I will re-start from small-scale jobs to optimize how I submit jobs.

**Comment by tatarsky** [comment]
I have a dim dim memory that the -hold_jid concept does indeed consume a large chunk of memory tracking all those jobs and the dependencies. 

I believe your jobs are running but that the default timeout of the qstat concept is 60 seconds and the qmaster/qexecd on the nodes is too busy to respond.

I would like to let your jobs drain and then I will adjust the timeout. But I am out and the above action is non-trivial from a phone. 

So when this batch is done, please consider a smaller batch and I will update this when the timeout is adjusted and perhaps we can test again with that.

**Comment by nariai** [comment]
I see. Probably "-hold_jid" is the problem. Thanks, I will try to kill the jobs that I submitted, and will start from small-scale jobs.

**Comment by tatarsky** [comment]
OK. I am back "at keyboard" for a bit. Attempting to adjust timeout. I note qstat is instantly responsive now.

**Comment by tatarsky** [comment]
I have adjusted what is called the qmaster "gdi_timeout" to quadruple its value. Which may mean under heavy job load like that the command hangs instead of that error. 

I've made no other change for now. I will be around for another hour and then out for a bit and then back later tonight if you wish to try to reproduce.

**Comment by hirokomatsui** [comment]
Thanks Paul. I will be running some jobs over the holiday and will be fine as knowing how to restart qmanager.

**Comment by nariai** [comment]
Thanks, so far, SGE is working good.

**Comment by tatarsky** [comment]
To be very clear: the item reported today should NOT involve restarting the qmaster. 

As it was busy, not dead. 

So I'd rather NOT restart it and instead see if we can narrow down the cause which I currently believe is due to the number jobs _combined_ with job dependency tracking. (Which I am trying to locate the item I recall about the memory footprint of doing that). 

The qmaster should only be restarted if its actually dead.

**Comment by tatarsky** [comment]
Dead =  ```error: commlib error: got select error (Connection refused)``` and the qmaster process not there. Yesterday that was because its memory requirement grew so high the kernel had to kill it to not kill other processes. I have since then marked its OOM killing priority lower. (Aka the kernel will kill something else before it kills qmaster).

Busy = ```error: failed receiving gdi request response```

I am trying to tune a bit for the later.

**Comment by tatarsky** [comment]
I can confirm that its _likely_ that the memory hit is indeed caused by the non-array jobs combined with `-hold_jid`. Right now the sge_qmaster is holding ~1GB of memory and is basically idle as I normally see it. 

When I was looking at it this morning it was > 50GB. And consuming a great deal of CPU as well. 

So I will see if I can determine if there is some formula that would allow us to size such things better but I think the lesson learned is that construct does indeed appear to be memory and cpu intensive.

**Comment by nariai** [comment]
Thanks for taking a look. I made a change in my code try not to use -hold_jid for submitting many jobs.

**Comment by tatarsky** [comment]
I am still curious about it. Perhaps when we are all around a bit more. Leaving this open. Thanks for the mod!

**Comment by tatarsky** [comment]
I have not seen any repeat of this and note only that I am around for a few days this week and then on my longer vacation as noted in #167. The memory consumption on fl-hn1 has been normal over the last few days.
