### ISSUE TITLE
Early warning of Lustre disk remaining going under 100TB

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#171]
I alert at 100TB and during my flight home we crossed that. Just be aware:

```
df -h
Filesystem            Size  Used Avail Use% Mounted on
/frazer01             524T  399T   99T  81% /frazer01
```

**Comment by tatarsky** [comment]
95T now.

**Comment by hirokomatsui** [comment]
I'm using a lot for Retina's CNV calling, will keep on my eyes on them and remove files as it's done.
Thanks!

**Comment by tatarsky** [comment]
OK. Closing. Just wanted to make sure folks were aware! Thank you!
