### ISSUE TITLE
flh1 and flh2 process policy

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#173]
We have discussed in the group today and agreed on the following:
1) We set a memory limit (8GB) for each process on headnodes
2) We set a time limit (1 month) for each process on headnodes

What would be the best way to implement it?

**Comment by tatarsky** [comment]
#1 is doable with UNIX limits (cgroup or limits.conf) I can set that up tomorrow. 

#2 is not quite with UNIX limits if time = clock time. 

There is no clock time concept in setrlimit or cgroups (that I've seen anyway). 

Only CPU time limits. Which is not equivalent to "real clock time" (sometimes called wallclock).

Its equivalent to the number of seconds a process is actually consuming CPU. (An idle process does not consume CPU time....so its not a 1:1 mapping)

So I can set it to 30 days of CPU time but depending on the process that might be in terms of real time longer than 30 days of actual time. 

But its a start compared to "forever" so I am happy to create that limit as well and/or explain it further.

**Comment by tatarsky** [comment]
Oh, and I will likely use cgroups to implement it. As thats the more modern method.

**Comment by nariai** [comment]
Thank you, yes, CPU time would be OK.

**Comment by tatarsky** [comment]
Cool. Thanks for discussing it and I'll probably prototype it on fl-hn2 and then bring it over to fl-hn1. 
I'll update this when done.

**Comment by tatarsky** [comment]
Initial draft of cgroups memory limit of 8GB only in test on fl-hn2. Any user in group "users" (which by default we are placing all users in that group) should not be able to malloc/swap out more than 8GB. 

If we need further refinements we will go from there and I will add the CPU item shortly. The processes that exceed this are logged in the same way as the out of memory (OOM) killer so I can see folks hitting it.

I'll leave this for a bit on just fl-hn2 before doing the same on fl-hn1 as its a Friday (don't like to make too many changes on Fridays)

**Comment by billgreenwald** [comment]
Is this 8GB per process or 8GB allocated total to a user.

**Comment by tatarsky** [comment]
Per process. There is no feature to do "per user" that I am aware of in the Linux kernel.

**Comment by billgreenwald** [comment]
That's what I thought, but just wanted to double check, thanks!

Also, is it possible to make certain processes exempt from the CPU clock timeout?  Jupyter notebook servers take very little resources--could we possibly make them exempt?

**Comment by tatarsky** [comment]
I can look. 30 days of CPU time is from my experience a very very very long time ;)

**Comment by tatarsky** [comment]
As in a process that isn't solid CPU won't rack up those seconds....

**Comment by billgreenwald** [comment]
Ok then it may be a moot point

**Comment by tatarsky** [comment]
I'll still look. Cgroups has some new features but they may be 3.X kernels only.

**Comment by tatarsky** [comment]
8GB memory limit will go into fl-hn1 at noon or so today. CPU limits shortly after once I check some concepts there one more time. I see no processes above it.

**Comment by tatarsky** [comment]
Memory policy added fl-hn1. Monitoring. CPU policy I will do shortly. Looks like shell limits is the way to handle that one and I will set to a hard limit of 30 days of CPU time. Remember CPU time != actual time if process has idle periods.

**Comment by tatarsky** [comment]
CPU time limit in test on fl-hn2. This one will appear as a shell limit:

```
ulimit -a
...
cpu time               (seconds, -t) 2592000

```
2592000 seconds = 30 days.

**Comment by tatarsky** [comment]
Done as well on fl-hn1. Re-open if adjustment or issues!
