### ISSUE TITLE
error log when exceed memory limit on head node

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#174]
Hi @tatarsky , 

The new restriction on the head node that limit user's memory usage works well. Just wondering is it possible that the system notifies the users whenever their program exceed the memory limit, rather than just quit the program without error. It looks like the program doesn't generate any output, and users might not immediately realize it's actually out of memory. 
Thanks
Hurley

**Comment by tatarsky** [comment]
I'm not aware of any additional warning from a OOM killed process (which is what cgroups do) beyond at most if run on a tty you will see "Killed". I can poke around a bit but I believe that is all you get. 

The signal sent is also SIGKILL which you can't trap. That may be more strict that setrlimit soft/hard but actually results in a real enforcement. 

There is a syslog entry made that the process was killed but it does not contain a username. It does contain a process name and I could make some sort of readable extract cron from that if desired. 

Looks like bedtools is being killed today. There are some documented options to reduce bedtools memory (the whole sorted concept which I can forward a link to). 

Do you know who is running said tool?

**Comment by hurleyLi** [comment]
I'was running the bedtools for some tests, that's why I noticed this issue. I thought my command didn't generate any output, and spent quite a while to figure out that's the memory problem. 
I think a simple "Killed" will suffice as a reminder that the command exceed memory usage, and we need to run on compute node.

**Comment by tatarsky** [comment]
The output can depend on the way the code is run in terms of pipes and ttys and such. Code that checks malloc exit codes may also produce different results. "It depends" is a fair answer overall. 

I will add a file extract for killed processes people can check and see if they recognize names of killed items. 

A generic item for tests is that qlogin still makes sense for tty based items. Even with just one slot something like this you get a test environment on a node that will behave the same as when you submit a script via qsub:

```qlogin -l h_vmem=8G```

I usually strongly recommend the use of qlogins for tests. They keep the head nodes less impacted and replicate the final environment of most items better. Assuming you are planning on submitting as a job.

**Comment by hurleyLi** [comment]
yes qlogin is what I did after I got this issue, just sometimes I won't realize the program would take that much memory so I run it on head node. But anyway, I think if it's not a immediate err output after the program is being killed, my first response won't be that the program exceed the memory limit. So it's probably not worth to spend effort to add a file to check such errors later, coz by that time you already realized that's caused by memory.

**Comment by hurleyLi** [comment]
I guess if it's hard to implement a error log right after the program is killed due to memory, just leave it like this, and we'll get used to it eventually.

**Comment by tatarsky** [comment]
Noted. Or as we say in the systems world: RAM is cheap up to a point. Still an option for the head nodes to go fairly easily with 8 added 32GB DIMMS to 512GB. After that it gets more expensive as we'd be replacing and moving to higher capacity ones which still are expensive. 

I'd periodically add up the cost of enforcement/training/confusion to "just add memory". Closing for now. Advise if you wish to see the cost of that path.
