### ISSUE TITLE
install plotly

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#176]
Hi Paul, 

I've been trying to install plotly https://plot.ly/r/getting-started/. However, it requires Pandoc, which I can't get installed. https://github.com/jgm/pandoc

Could you please help me install pandoc

Thanks
Hurley

**Comment by tatarsky** [comment]
Loaded pandoc from RPM as pandoc is a large animal built on Haskell. See if you get further. fl-hn1 only. Added -devel RPMs for it as well. If that doesn't work I will look at it next week.

**Comment by hurleyLi** [comment]
the plotly manual says "Make sure that both pandoc.exe and pandoc-citeproc are available in your local python installation folder (or Jupyter environment if you have setup a separate environment)."
Could you please point me to the paths to these files

**Comment by tatarsky** [comment]
pandoc.exe?  UNIX is not a big fan of ".exe" concepts. Is that UNIX relevant? The pandoc binary is in the system path: /usr/bin/pandoc. I don't know what pandoc-citeproc is. I will look further at the install instructions next week.

**Comment by hurleyLi** [comment]
Sorry that's for R-Studio ... Let me try with the /usr/bin/pandoc

**Comment by tatarsky** [comment]
Sounds good. If it doesn't work from RPM I'll look at the source build but its a large one so unlikely today. Its an older version but I've seen it work in other situations where pandoc is needed. 
```pandoc -v
pandoc 1.12.4.2
```

I added the pandoc-citeproc RPM. 

```
 which pandoc-citeproc
/usr/bin/pandoc-citeproc
```

Again, only on fl-hn1. If these worked would be added to puppet for systems that need them.

**Comment by tatarsky** [comment]
You just want this in R right? What R module are you using?

**Comment by hurleyLi** [comment]
I link the two files under my python folder, and now it works! Thanks for the help!

**Comment by tatarsky** [comment]
W00T! Excellent. Do you need pandoc on other systems or is it just used to generate something during the build? I have no problem adding it elsewhere but if it is just for building I'll leave it as is.

**Comment by hurleyLi** [comment]
I think it's good for now, it's just used for this specific package in R to be able to use in r notebook.
