### ISSUE TITLE
kernel panic fl-hn1

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#177]
I am unable to obtain diagnostics information from remote as to the cause of the current issue. 

I require the help of the local sysadmins to check on consoles at SDSC if we cannot determine the cause.

**Comment by tatarsky** [comment]
If I had to guess we have a possible 10G switch failure. That is based on what little connectivity I have.

**Comment by hirokomatsui** [comment]
I can see flh2 via network but log in (maybe too slow). flh1 is unreachable.
So I think the problem is not on the servers by themselves. Maybe power, network or switch?

**Comment by tatarsky** [comment]
See above comment. It feels like the 10G switch is down.

**Comment by billgreenwald** [comment]
I am logged in to flh2 and was able to do so again

**Comment by tatarsky** [comment]
Weird. Just did the same for be. Investigating.

**Comment by billgreenwald** [comment]
i can't log in to flh1 from flh2 (if that means anything different)

**Comment by tatarsky** [comment]
We lost flhn1 during whatever happened:
```
[root@fl-hn1 ~]# uptime
 14:02:43 up 4 min,  2 users,  load average: 0.15, 0.16, 0.08
```

**Comment by tatarsky** [comment]
We are down for a bit until root cause is found.

**Comment by tatarsky** [comment]
Noting items as I look at them.
10G did not go down. Its been up for 400+ days.

**Comment by hirokomatsui** [comment]
They are up. Looks like flh1 was down, and flh2 was too busy to find flh1.

**Comment by billgreenwald** [comment]
Everyone can ping flh1 but we get the "could no chdir to home directory" error

**Comment by tatarsky** [comment]
Yes folks, I am aware of the above and am working on the Lustre mount.

AFTER I look at the system. I am disabling logins.

**Comment by tatarsky** [comment]
Kernel panic on fl-hn1. Delays in logins to fl-hn2 caused by /opt/sge NFS mount hang. Checking for possible hardware matters. Unit was up > 465 days.

**Comment by tatarsky** [comment]
Leaving unit logins disabled for a moment to collect some data. Use `fl-hn2`.

**Comment by tatarsky** [comment]
Re-enabling logins. Processing kernel dump.

**Comment by tatarsky** [comment]
Hub code restarted. Does not appear related but we'll see.

**Comment by hirokomatsui** [comment]
Can we re-start MySQL server, or let me know if we'd better to wait.

**Comment by tatarsky** [comment]
Yes, go ahead.

**Comment by tatarsky** [comment]
If anyone recalls anything intensive being done ON the fl-hn1 system this afternoon let me know. The crash dumps however are not overly revealing.

**Comment by tatarsky** [comment]
Ganglia shows nothing particularly interesting either.

**Comment by tatarsky** [comment]
Estimated uptime 480 days.

**Comment by tatarsky** [comment]
Nothing particularly interesting in Lustre load either. No cause at this time.

**Comment by hirokomatsui** [comment]
It's happening again, looks like the situation's same. flh1 is down and flh2's slow.

**Comment by tatarsky** [comment]
Waiting to see if it reboots. Alert was seen. I am leaving the hub down until morning. If somehow that is involved we need to understand why. But seems unlikely.

**Comment by tatarsky** [comment]
Its not rebooting. Attempting SDSC ticket to check it. 

Otherwise contact me in the morning from SDSC so we can try to determine what is causing this.

**Comment by tatarsky** [comment]
The fl-hn2 mount hang has timed out and I am trying to see if I can see whats going on via IPMI console.

**Comment by tatarsky** [comment]
Confirmed kernel panic but unit did not reset. Attempting to reset.

**Comment by tatarsky** [comment]
If anyone is doing something that seems correlated please advise. Unit is resetting.

**Comment by tatarsky** [comment]
Unit is back up. Lustre mounted. Will review more in the morning. We need to determine the cause of this and only a few items have changed. The Jupyter Hub has NOT been restarted on purpose.

**Comment by tatarsky** [comment]
Only other recent change is cgroups. I propose leaving the Hub down for the rest of the week. If it panics during that time, we will roll back out the cgroup activation on fl-hn1. Those are the only changes in recent history. Short of that, its possible the system has some kind of hardware fault but I don't see evidence of that in the logs. I may ask for an SGE shutdown to move the spool.

**Comment by tatarsky** [comment]
I have moved SGE. I am just waiting on a risk/impact statement from @hirokomatsui about Mysql when fl-hn1 crashes. Once that is thought about I will likely re-enable the Hub. If it crashes again, Cgroups are set to NOT come back into play on reboot to start ruling that out.

**Comment by hirokomatsui** [comment]
I found a couple of Mysql table files were crushed on Thursday, and tried to recover them by restarting mysqld sometime.
Let me make back up for some of tables and I will let you know.

**Comment by tatarsky** [comment]
InnoDB or MyISAM? But yes, this is the class of issue I seek to avoid if we have another crash.

**Comment by tatarsky** [comment]
I will mention we could move the hub over to `fl-hn2` to get it away from Mysql. Assuming its involved....it may be coincidence. We would not know until we saw similar behavior there or `fl-hn1` crashed without the Hub meaning it was probably something else triggering this.

**Comment by hirokomatsui** [comment]
MyISAM, but I don't think the fail tables were due to the flh1 crush because of the timing. They should have been crushed at least a week before.

**Comment by tatarsky** [comment]
OK. Just checking. InnoDb I've seen more severe impact from kernel panics. But I still want to minimize impact to your work if we proceed in bringing back the hub. We've not crashed since we shut it down. So there is at least some signs of it being related.

**Comment by hirokomatsui** [comment]
I've made a backup so it's safe to change the settings.

**Comment by tatarsky** [comment]
OK. Shall we restart the Jupyter Hub then on fl-hn1 and see what happens? I guess you might want to warn anyone running items directly on fl-hn1. SGE I believe will survive a crash now due to spool move. But if its a bad time to see if we can figure this out, let me know. 

Otherwise in an hour or so I will restart the hub and monitor closely.

**Comment by hirokomatsui** [comment]
Yea, I think it's good to go.

**Comment by billgreenwald** [comment]
I'm find either way--if you guys want to launch it sounds good to me.

**Comment by tatarsky** [comment]
Running. System had been running for on start of Hub code:

`12:20:10 up 4 days, 17:24, 14 users,  load average: 0.87, 1.17, 0.901`

**Comment by tatarsky** [comment]
Unit crashed in the early hours of the morning. Roughly 12 days without a panic.

Rebooted on its own and SGE failed over as noted in #178 . 

I have disabled cgroups as the only other recent change besides the Hub and restarted the Hub. Hoping to rule in/our cgroups as a cause of a panic based on kernel dumps.

**Comment by tatarsky** [comment]
Noting that the unit has remained up 9 days/12 hours. Just for reference.

**Comment by tatarsky** [comment]
Unit paniced again without cgroups. So likely that possible cause is not it. ~14 days uptime.

Will analyze and make next suggestion. If anyone knows of anything interesting done this afternoon please update this git issue.

**Comment by billgreenwald** [comment]
Genome strip was launched and then killed. The killing of it lined up with the loss of connection to lustre.

**Comment by tatarsky** [comment]
The "loss of connection to Lustre" is the machine crashing. Just to be 100% clear.

Lustre does not mount on boot for reasons related to wanting to be sure a system isn't causing problems to the cluster. I mount it manually on reboot. 

We've been up less than an hour.
```
fl-hn1 [~]$ uptime
 17:10:15 up  1:19,  9 users,  load average: 0.36, 0.34, 0.28
```

So can this program be run again?

**Comment by tatarsky** [comment]
Nothing overly useful in the logs or Ganglia so far. Basically lets pick a time perhaps tomorrow in which if possible this program and the killing of it could be tested. It would be odd whatever it would be if somehow it is involved as its rare for userspace items to cause panics.

 I don't suppose the past crashes have correlated to such actions.

**Comment by tatarsky** [comment]
Some signs of Lustre timeouts.

**Comment by tatarsky** [comment]
Yet no obvious signs from server side of high load at the times the Fl-hn1 system was reporting them. Or on the other systems. So I'd love to know when convenient any information about this program.

**Comment by tatarsky** [comment]
Generically this panic is very different looking than the previous ones. This one is very Lustre centric involving loss of communication to the OSTs. 

That was not present in previous crashes in this ticket. 

But all crashes are bad, but its possible we are dealing with multiple items.

Enough for tonight. When there is a good time to consider trying to reproduce this please advise.

**Comment by tatarsky** [comment]
Reference only: approaching 8 days of uptime on the re-test of "is cgroups involved"

**Comment by tatarsky** [comment]
Reference only: 16 day uptime. Will close at 30 days. Seems likely cgroups is somehow involved. No idea why fl-hn2 (where its still on) has not shown same issue.

**Comment by tatarsky** [comment]
Reference only: 27 day uptime.

**Comment by tatarsky** [comment]
30 days of uptime with no crash. Reasonable probability its a cgroups kernel bug as mentioned before. And while I'm sure closing this will jinx that I am doing so. 

Cgroups left disabled on fl-hn1. Will use old style limits if we need them anymore. Will discuss a bit in #179. Will update kernel when we discuss and schedule a generic round of updates perhaps this summer.
