### ISSUE TITLE
Unable to add/load modules

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#18]
(test)[~]fl-hn1 $ module add git
+(0):ERROR:0: Unable to locate a modulefile for 'git'
(test)[~]fl-hn1 $ module load git
+(0):ERROR:0: Unable to locate a modulefile for 'git'

Not sure why this is happening. I'm looking into it but am still learning about modules.

**Comment by tatarsky** [comment]
If your session is old you need to logout/login as I changed the path to the modules. Long story but basically "module" is a shell function.

**Comment by tatarsky** [comment]
Basically make sure in any shell running you see the following:

```
$ module avail

------------------------ /usr/share/Modules/modulefiles ------------------------
dot         module-git  module-info modules     null        use.own

------------------------------- /etc/modulefiles -------------------------------
compat-openmpi-psm-x86_64 compat-openmpi-x86_64

------------------- /frazer01/repos/environments/modulefiles -------------------
EPACTS/3.2.6(default) bedtools/2.25.0       root/5.34.20(default)
R/3.1.1               git/2.6.2(default)
```

If you don't see that last stanza of `/frazer01/repos/environments/modulefiles` start a new shell. Including screen....

**Comment by cdeboever3** [comment]
My mistake, it's working now. I was making new sessions in screen.

**Comment by tatarsky** [comment]
Yeah, I think then the shell function of the original shell gets used...its not going to relocate again ;)
