### ISSUE TITLE
Luster's gone from flh1

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#183]
Paul, could you check that Luster's not mounted by flh1.

**Comment by tatarsky** [comment]
unit crashed will look when i am available.

Paul Tatarsky
paul@clusterguys.com

**Comment by tatarsky** [comment]
remounted and will look more when I am home and update panic ticket.

**Comment by hurleyLi** [comment]
just a note, jupyter-hub is still down

**Comment by tatarsky** [comment]
Flaw in startup script. Believed fixed.
