### ISSUE TITLE
Jupyter hub still not working

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#184]
When I connect, I get this error:

Permission failure checking authorization, I may need a new token

**Comment by tatarsky** [comment]
Hmm. I don't get that. I see this in the logs:

```
[W 2017-03-21 08:45:58.230 JupyterHub base:165] Invalid or expired cookie token
[W 2017-03-21 08:45:58.234 JupyterHub base:165] Invalid or expired cookie token
```

Can you make sure you are completely logged out and perhaps clear cache in browser?

I can restart it if that doesn't work to see if something else involved.

**Comment by tatarsky** [comment]
Try again. I restarted it based on some Git comments.

**Comment by s041629** [comment]
It works now.
Thanks!
