### ISSUE TITLE
flh1 issues yesterday

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#185]
Hi Paul, 
I wanted to explain what had happened yesterday with flh1, since I'm sure you were notified when things when haywire.  I wrote a pipeline that produced a bunch of jobs to be launched to the compute nodes as well as a script to automate launching jobs.  These were jobs were genome strip pipeline jobs, which have a process that runs on the head node monitoring output and launching things as needed to the compute nodes.  Unfortunately, I put my script to launch the jobs in the same folder with the jobs by accident, and essentially it recursively called itself (whooooops), infinitely looping and launching the same jobs and filling the head node with processes.  I killed everything as fast as I could but I guess it was too late.  Apologies, that definitely won't happen again.

**Comment by tatarsky** [comment]
Ahhh. OK that is actually relatively somewhat good news ;) As we can correlate it ;)

I can actually limit what are called fork bombs (loops of processes) but I'm trying to isolate the previous cause of the fl-hn1 panics in #177  so I won't add anything new and this definitely doesn't match the situation. 

So I think we'll call this an unrelated event for now and reset the kernel panic days up counter and try again. 

I appreciate the update!
