### ISSUE TITLE
Node 6 down a hard drive in its boot RAID1

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#189]
One of the mirrored boot drives has failed in Node 6.

I will get Advanced HPC started on an RMA. I will leave the node running on one drive for now and will suspend jobs to it when I get closer.

**Comment by tatarsky** [comment]
To be very clear: Node 6 = compute node. There is no critical storage on this node.

**Comment by hirokomatsui** [comment]
I see. Thanks!

**Comment by tatarsky** [comment]
Ticket#1008491

**Comment by tatarsky** [comment]
Please note also "suspending jobs" to it is just to speed the RAID1 rebuild process with no local I/O. If we really need the node in service we can skip that.

**Comment by tatarsky** [comment]
Will notify SDSC of Cesar coming at some point today.

**Comment by tatarsky** [comment]
Drive replaced but waiting for jobs to drain for next steps of MD raid rebuild as its faster to rebuild without I/O. (And just in case something happens don't want jobs on the node)

**Comment by tatarsky** [comment]
Rebuilding MD raid1. Eta a couple of hours.

**Comment by tatarsky** [comment]
Rebuilt. SGE queue re-enabled. Matter resolved.
