### ISSUE TITLE
Luster working

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#194]
Hi Paul, could you check if anything wrong on the Luster?
Some commands, such as ls and df, cannot come return.

**Comment by tatarsky** [comment]
Already got the alerts. Is anyone doing anything "interesting" I am looking at the servers.

**Comment by hirokomatsui** [comment]
I don't think that's related but was running df command for large directories, such as "/projects", from a compute node on Friday.
I'm not hearing anything else.

**Comment by tatarsky** [comment]
Looks like something on the oss-1-1 machine. Rebooting it. Uptime 557 days.

**Comment by tatarsky** [comment]
Unclear what the problem is. We are down until I figure it out or call Intel.

**Comment by hirokomatsui** [comment]
OK, thanks.

**Comment by tatarsky** [comment]
I have recovered I believe from oss-1-1 having a problem. I would like people to reduce usage on the filesystem and I'd like to schedule a meeting to discuss getting some updates in place for this environment. We've run basically 600 days off the initial distribution. There are likely bugs in many locations (centos/lustre/etc)

**Comment by tatarsky** [comment]
Notes for myself: for whatever reason fl-oss-1-1 issue did not result in complete failover of its OSS.
Required hard reboot. Unclear why. Suspect heartbeat failure/bug. Not much to go on.

**Comment by hirokomatsui** [comment]
Are you going to reboot it?

**Comment by tatarsky** [comment]
I already did. I had to hard reset it though which concerns me.

**Comment by tatarsky** [comment]
I am assuming "it" in that sentence is fl-oss-1-1.

**Comment by hirokomatsui** [comment]
Thanks. We'll go back to work on the cluster.
Can you email me about the issues we'll have to talk about. I will look for hard drive usage.

**Comment by tatarsky** [comment]
Just did ;) Basically "care and feeding" may be wise as we approach the 1.5 year mark.
