### ISSUE TITLE
adding a user account

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#195]
I just added a user account, andre, with "useradd" command, but did not work with a permission problem.
Should I do something else? Or let me know if it's better to ask you to add users.

**Comment by tatarsky** [comment]
I'll take a look. Remember it takes a few minutes for the new account to appear on the Lustre servers....

**Comment by tatarsky** [comment]
Which to be clear is needed for the metadata to start working for their uid/gid....

**Comment by tatarsky** [comment]
I forced the puppet early. Is it working as expected now? Otherwise it runs on the hour as we don't make accounts that often.

**Comment by hirokomatsui** [comment]
It's working. I thought that the user account works on the flh1 soon after the useradd command even not active on the other nodes. Thanks!

**Comment by tatarsky** [comment]
The account is made but until the Metadata servers pick up the UID/GID pair it will deny permissions. 
Which is not really "useful" to the user.

I can run the process to sync more than once an hour....but the user accounts have been fairly static so figured thats reasonable. But up to you.

**Comment by tatarsky** [comment]
Basically in three minutes it should exist everywhere (Tue May 16 15:57:33 PDT 2017)

**Comment by hirokomatsui** [comment]
Does the sync process run in once an hour, or three minutes? Is that cron?

**Comment by tatarsky** [comment]
Once an hour at the top of the hour via /etc/cron.hourly/p2puppet
If you wish to get it out there "quickly" as root just run /etc/cron.hourly/p2puppet

**Comment by tatarsky** [comment]
On fl-hn1....

**Comment by tatarsky** [comment]
Sent you an email with some steps spelled out if once an hour is too slow...happy to adjust however.

**Comment by tatarsky** [comment]
I'm heading out now but let me know if you have further questions!

**Comment by hirokomatsui** [comment]
I've added a user account and run,
/etc/cron.hourly/pw2puppet

I saw the lines of:
do_ypcall: clnt_call: RPC: Unable to receive; errno = Connection refused

Around 10 minutes later, I still get "Permission denied" error when su
Am a missing anything else?

**Comment by hirokomatsui** [comment]
Never mind. I just had to wait a bit more.

**Comment by tatarsky** [comment]
Yep. The rpc error is just noise. Will fix when I return though.

Paul Tatarsky
paul@clusterguys.com

**Comment by hirokomatsui** [comment]
I've added a new user account, jennifer, on flh1 and the account has not been proliferate on other nodes after running, /etc/cron.hourly/pw2puppet
Can you please check it. Thanks!

**Comment by tatarsky** [comment]
You've used a UID already in use:
```
Error: /Stage[main]/Main/User[jennifer]/ensure: change from absent to present failed: Could not create user jennifer: Execution of '/usr/sbin/useradd -g 100 -d /frazer01/home/jennifer -p $6$ZfWIlaqk$VN9qb.tRIcj6MnoBjkJ8FwNe/swb04thD9jghMxLjivM2MZdo3EbVqK7UgD3TeoESJj2XF2INKjYJ0mGbifdR1 -s /bin/bash -u 1055 -M jennifer' returned 4: useradd: UID 1055 is not unique
```

That account is showing as these out on the nodes:

janae:x:1055:100:Janae Waugh:/frazer01/home/janae:/bin/bash

Did that account get deleted? As pw2puppet needs some help if you re-use accounts.

**Comment by tatarsky** [comment]
I am getting rid of "janae" account. And forcing the puppet run. Will handle it.

**Comment by hirokomatsui** [comment]
Thanks!

**Comment by tatarsky** [comment]
Please test. 

I'll try to add some logic to pw2puppet to detect this situation but I'm very careful with "deluser" from scripts ;) Can produce "exciting" results ;)

**Comment by hirokomatsui** [comment]
It looks like jennifer is proliferated. 
I totally understand to be careful to delete users. I think the deleted user's files and home directory won't be deleted without adding some option to do, so it'll be still fine in the worst case.

**Comment by tatarsky** [comment]
Yeah I seldom get to actually delete homedirs of past users in my shops so the accounts never go away. Just disabled. I'll work up a puppet detect of it for pw2puppet.
