### ISSUE TITLE
Installing wkhtmltopdf

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#196]
Hi Paul,

Can you help me install wkhtmltopdf?

Thanks!

**Comment by tatarsky** [comment]
Let me look at RPM v.s. source build first. Will be a little bit today but yes I'll look at it.

**Comment by tatarsky** [comment]
RPM version (slightly older 0.12.2) loaded on fl-hn1 for test. Advise if that works OK and I'll add to other headnode (and nodes if needed).

**Comment by joreynajr** [comment]
Hi Paul,

Thanks. I will have to take a look later. Using wkhtmltopdf is something a little experimental. I want to see how well HTML tables can be converted/visualized into a PDF.

**Comment by tatarsky** [comment]
Closing this for now. If you need it on other systems let me know!
