### ISSUE TITLE
Possible runaway git process on head node

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#198]
Does anyone know  what this process is doing? Its been doing it for quite awhile. I suspect its a runaway. 

30208 matteo    20   0 25.2g  23g 1440 S 400.1  9.4 367:38.94 git

**Comment by tatarsky** [comment]
Oh and I meant to @s041629 that question.

**Comment by s041629** [comment]
I was trying to push some updates to my github, but the process got closed. 
do you know how I could do it without "Delta compression using up to 32 threads."?

thanks!

**Comment by tatarsky** [comment]
Is that an error message or a setting?

**Comment by s041629** [comment]
it's a message. Here are all the messages:

Counting objects: 552, done.
Delta compression using up to 32 threads.
Connection to github.com closed by remote host.
fatal: The remote end hung up unexpectedly

**Comment by tatarsky** [comment]
How quickly do you get that Connection closed part? That seems a problem with the connection.

What does `git remote -v ` say? Is it ssh git or https?

I believe you can reduce the number of threads but I'm not sure that message has anything to do with the problem....

**Comment by s041629** [comment]
with git remote -v I get
origin  git@github.com:s041629/Matteo_notebooks.git (fetch)
origin  git@github.com:s041629/Matteo_notebooks.git (push)

**Comment by tatarsky** [comment]
So I have dim memories and a quick google confirms that these may help spot issues.

GIT_CURL_VERBOSE=1 GIT_TRACE=1  (your git command)

And if its ssh (which I don't think the above is) you can do:

GIT_SSH_COMMAND="ssh -vv" (your git command)

See if any of those gives you a bit more data. Otherwise I'd have to try to reproduce and unlikely today.

**Comment by s041629** [comment]
it's SSH:

GIT_CURL_VERBOSE=1 GIT_TRACE=1 git push
10:52:42.489278 git.c:348               trace: built-in: git 'push'
10:52:42.498237 run-command.c:338       trace: run_command: 'ssh' 'git@github.com' 'git-receive-pack '\''s041629/Matteo_notebooks.git'\'''
Enter passphrase for key '/frazer01/home/matteo/.ssh/id_rsa': 
10:52:56.906022 run-command.c:338       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
10:52:56.906560 exec_cmd.c:128          trace: exec: 'git' 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
10:52:56.914414 git.c:348               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 552, done.
Delta compression using up to 32 threads.
Compressing objects:   3% (17/552)   

I am trying to redo it now

**Comment by joreynajr** [comment]
Hey @s041629 is this the same issue we resolved yesterday? If so we can close this issue.

**Comment by s041629** [comment]
yes, thanks!

**Comment by joreynajr** [comment]
I thought I would leave a comment just for the record. Matteo had an extremely large .git file (~64GB) and maybe a few other very large files. I'm not sure what would have caused the large files but this was definitely slowing down the "git push" process.

**Comment by tatarsky** [comment]
Yes, I saw that and I believe "git repack" might be a possible item to investigate. But carefully. I am not a git expert.
