### ISSUE TITLE
Personal Backups

### ISSUE THREAD

**Issue by joreynajr** [frazer-lab/cluster#200]
Hi @hirokomatsui and @tatarsky,

For the personal backup I would simply like to make a directory in everyone's home directory named "personal_backup". I have two questions about this:

1. Is there a way the root user can make this directory for all current users and make the corresponding  user the owner of that file (I could go around instructing everyone but maybe you had a faster way)?
2. Can we also configure the creation of new users so the "personal_backup" directory is made automatically?

**Comment by tatarsky** [comment]
The above can certainly be both scripted and automated. But before doing so please get consensus for the concept and then the actual details of the destination of the backups must be decided. (We have no location for said backups settled on fully yet...possibly a system being used to archive data for the short term)

**Comment by joreynajr** [comment]
I'll discuss with @hirokomatsui and see what she think about both of these things.

**Comment by tatarsky** [comment]
But basically "yes, I can do what you describe very quickly" ;)

**Comment by tatarsky** [comment]
Simple concepts like this BTW is good. The more complex a backup include/exclude process becomes the more likely people will "miss" something important in those types of lists. That is why often times "backup everything" happens as a result of not being able to keep that process simple and safe.

**Comment by joreynajr** [comment]
We ended up coming up with a very simple solution. Hiroko and I generate some instructions for backing up on the flc server: https://github.com/frazer-lab/cluster/wiki/Backing-up-on-the-flc-Server
