### ISSUE TITLE
installing deepsea

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#203]
I am trying to install DeepSEA (http://deepsea.princeton.edu/help/), but already the first instruction in the readme gives errors:

cd ~/torch; bash install-deps;

Only CentOS 7 is supported for now, aborting.

I have downloaded the standalone version of DeepSEA in /frazer01/home/matteo/software/deepsea/DeepSEA-v0.94

Thank you

**Comment by tatarsky** [comment]
We don't run CentOS 7 yet. So if the software needs it, thats required. We are on CentOS 6. 

I'll perhaps take a look Monday on the test CentOS 7 machine referenced in #201 or feel free to try there.

**Comment by s041629** [comment]
I have already managed to start part of torch before (with the previous version). 

After installing torch I saw that there are some operations that need sudo. 

You can find the README to install DeepSEA in /frazer01/home/matteo/software/deepsea/DeepSEA-v0.94/README

**Comment by tatarsky** [comment]
Are you asking me to install this or perform a list of actions needed as root. Because I don't see any root sudo commands in that README. Are you asking me to build this for you?

**Comment by tatarsky** [comment]
And in general regardless of the answer: I will look at it Monday.

**Comment by s041629** [comment]
it's not urgent. I can wait until we have centos7 installed (also the second step HDF5 installation requires centos7.

Thanks

**Comment by tatarsky** [comment]
Yeah, I've battled HDF5 in CentOS6 and Torch. But my impression was pursuing it under that distro was unsupported and buggy. So I'll take a swag at it on Monday but I wanted to confirm if you wanted my time to actually do the work. Have a nice weekend.

**Comment by s041629** [comment]
it's not worth it now, since we are going to upgrade to centos7 soon anyway. For what I need, I will use the web version for now.

**Comment by tatarsky** [comment]
OK. Leave this here though as it would make a nice test software case for #201.

**Comment by tatarsky** [comment]
Closed due to no updates but retry under CentOS 7 and open a new issue if problems.
