### ISSUE TITLE
can't start Jupyter hub with 4 cores 32 GB

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#205]
not a big deal, but I can start the 4 cores 16 GB

**Comment by s041629** [comment]
now I can only start a 1 core 4 GB, but it stays in the "Your server is starting up. 
You will be redirected automatically when it's ready for you." page and doesn't go on.

Margaret has the same problem

**Comment by tatarsky** [comment]
Yeah I'm seeing some errors in restarting the hub after the Lustre update.
I'm looking at the logs.

**Comment by tatarsky** [comment]
Give it another try while I'm in debug mode....I got mine to run but had to restart the hub.

**Comment by s041629** [comment]
now it seems to be working fine

**Comment by tatarsky** [comment]
Yeah, I don't fully understand the "API key" portion of this code and how it lives between restarts (or doesn't for that matter). I will look at the docs again shortly. Focused on CentOS 7 efforts.

**Comment by s041629** [comment]
Now jupyterhub works but I cannot access to mysql:

mysql -u matteo -h localhost pan_cancer
mysql -u matteo -h h1 pan_cancer

Both give the same error:

ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock'

**Comment by tatarsky** [comment]
Mysql was shutdown for the upgrade. I will restart it.

**Comment by tatarsky** [comment]
Please try again.

**Comment by s041629** [comment]
it works.
Thanks

**Comment by tatarsky** [comment]
Will add a Nagios check for that after consultation with @hirokomatsui to make sure I have the right my.cnf flags.
