### ISSUE TITLE
old nodes not mounting Luster

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#207]
I see the error when qsub with -l opt:
07/17/2017 14:07:32 [1009:39849]: error: can't chdir to /frazer01/home/hiroko: No such file or directory

Have you unmounted on purpose sometime? I don't see any issue on the nodes though.

**Comment by tatarsky** [comment]
Checking. Its not on purpose. I suspect some may have crashed.

**Comment by tatarsky** [comment]
Or its a leftover from the update...which I thought I did but perhaps I forgot some. Remounting on a few.

**Comment by tatarsky** [comment]
Must have been oversight after the update. I thought I did them all but didn't appear to....confirmed mounted on all now.

**Comment by hirokomatsui** [comment]
Thanks!

**Comment by tatarsky** [comment]
Yeah sorry, I must have skipped some as I did have to umount it during the upgrade. I could have sworn I re-mounted but perhaps something went wrong. We should eventually decide just how useful these older 1G max bandwidth nodes are.
