### ISSUE TITLE
JupyterHub Table of Contents

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#208]
Hi Paul,

Can you install the table of contents add-on[ from here ](https://github.com/minrk/ipython_extensions)for the jupyterhub?  I have installed it for my personal notebook; should be straightforward.

Separately, is it possible for you to give someone in the lab these permissions so we don't need to bother you with installing something like this?  Or is it better to leave it with you?

Thanks!

**Comment by tatarsky** [comment]
Sure on the add on. Do you mind if I restart the hub to try the item I mention at the end of #188 ?

Can plugins be installed by non-root users? I'll look at where the parts end up. I believe they end up in the python 3 module. 

Note clearly @hirokomatsui has root and is considered the primary sysadmin of this environment. My contract was to be a backup sysadmin. So I personally do not care if there are additional local sysadmins but have certain items in puppet that need to be not messed with. 

So lets see where this module ends up and what delegation can occur.

**Comment by billgreenwald** [comment]
Don't restart the hub right now, people are mid-analysis.  Perhaps tonight would be a good time for the restart; I will check with people and post a confirmation later today.

Let me know where the plugin ends up.

**Comment by tatarsky** [comment]
OK. I will take a look after my next meeting and if its just a python module I can chown/chgrp the python tree!

**Comment by tatarsky** [comment]
So for our reference:

The "jupyter" that is the hub control code lives in `/frazer01/software/python-3.3.6/bin` area and the python libs for it are in the site-packages of that same tree.

I propose I make a group called "hubadmins" or something and give that group write permissions to that whole python module tree.

And we try to see if _you_ (being made a member of this group) can do the install. 

What do you think of that plan? I am in meetings until 3:00PM CDT today but if that worked it would allow easy additions judging from the docs...and if the hub requires a restart we will schedule it or rig a sudo ability of the init script.

**Comment by billgreenwald** [comment]
That sounds good to me.

The hub shouldn't require a restart to enable the plugin, so if you give me access I can let you know how it worked by 3:00PM CDT

**Comment by tatarsky** [comment]
So you are now in a group `hubadmins`. Pop a new shell/ssh session and confirm with `groups` that is true. 

I'm reading right basically this install consists of dropping a toc.js and toc.css file into:
`/frazer01/software/python-3.3.6/share/jupyter/nbextensions` which you should have write access to (and other parts of the tree in a moment)

And I believe that jupyter command will work as your user but if it doesn't tell me what it says and I'll chmod more parts of the tree (being careful because I don't want to break running items)

**Comment by tatarsky** [comment]
Oh, and be sure to: `module load python/3.3`. Sorry, thats important to the process.

**Comment by tatarsky** [comment]
And just FYI...meeting postponed 40 mins so am around if you try it and get some kind of "permission denied".

**Comment by billgreenwald** [comment]
I am getting an error which is indicating that it is sourcing my local .jupyterPersonalServer during the first installation step instead of the global hub config site.

My python, jupyter, and ipython are all coming from /software/python-3.3.6/ though.

**Comment by tatarsky** [comment]
Hmm. Let me try it just to compare and see what the flags are.

**Comment by tatarsky** [comment]
So if you leave off their --user you seem to get what we expect but I don't have that  .jupyterPersonalServer file.

```
jupyter nbextension  install https://rawgithub.com/minrk/ipython_extensions/master/nbextensions/toc.js
Downloading: https://rawgithub.com/minrk/ipython_extensions/master/nbextensions/toc.js -> /tmp/tmp3cjlfz/toc.js
Copying: /tmp/tmp3cjlfz/toc.js -> /usr/local/share/jupyter/nbextensions/toc.js

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable <the entry point>
```

Adding the other one and I guess we test to see if it works first.

**Comment by tatarsky** [comment]
Not 100% sure if I have the toc.css file in the right place. If you follow his commands it ends up in `/root/.local/share/jupyter' as a prefix.

But I also did the enable part. Does it work? (goes to look as well)

**Comment by tatarsky** [comment]
Not seeing anything obvious but perhaps I don't know where to look. Be back home shortly and can iterate over it a bit. Going to look at where it ends up as a user as well.

**Comment by billgreenwald** [comment]
Did you do the 
```jupyter nbextension enable ```
line?

**Comment by tatarsky** [comment]
Ya. But I have a feeling I am doing something for the "user" and not the system:

```jupyter nbextension enable toc
Enabling notebook extension toc...
      - Validating: OK
```
So it seems happy, but check out the "list" output:
```
jupyter nbextension list      
Known nbextensions:
  config dir: /root/.jupyter/nbconfig
    notebook section
      toc  enabled 
      - Validating: OK
  config dir: /frazer01/software/python-3.3.6/etc/jupyter/nbconfig
    notebook section
      jupyter_dashboards/notebook/main  enabled 
      - Validating: OK
```
Notice how it seems to mention "root". I have no idea if thats correct....ideas?

**Comment by tatarsky** [comment]
In that later dir is some json which doesn't seem to include "toc"

```
{
  "load_extensions": {
    "jupyter_dashboards/notebook/main": true
  }
```

Looking to see what the right way to enable a extension is...I don't recall ever manually editing that file.

**Comment by tatarsky** [comment]
Yeah, the root user one contains 
```
{
  "load_extensions": {
    "toc": true
  }
}
```
Some that command he gives must be for "user" extensions or something. Reviewing the command. More shortly.

**Comment by tatarsky** [comment]
And just mentioning I came across this.

https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/toc2

**Comment by tatarsky** [comment]
This may be the solution to our overall goal: (adding extensions and allowing the hub web admins to enable and configure them)

https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator

**Comment by tatarsky** [comment]
Tried this in the meantime:
```
jupyter nbextension enable --system toc
```
Checking...

**Comment by tatarsky** [comment]
Nope. Something funny going on but not sure what causes it. Will look more in a bit. I feel its perhaps placing config in the wrong place. But I don't want to manually edit with running notebooks.

**Comment by tatarsky** [comment]
So I have a feeling based on your notebook.json we need to have this:
```
{
  "load_extensions": {
    "toc": true, 
    "jupyter_dashboards/notebook/main": true
  }
}
```
But I'll be darned if I can figure out how to convince the `jupyter` command to do that for me via its install option.

I'm more than happy to manually edit it, but I'd sort of like to understand what doesn't work right and also make sure I'm not going to break anyones active sessions. I'm calling it a day but am around all day tomorrow to see if can figure this out!

**Comment by billgreenwald** [comment]
Ok so I read the jupyter nbextension install manual and checked the comman for TOC against the dashboard we sucessfully installed earlier, and changed the command:

```
jupyter nbextension install https://rawgithub.com/minrk/ipython_extensions/master/nbextensions/toc.js --config=.jupyter_Hub_Configuration/
```

This no longer gave me python errors, but now gives me 
```
Permission denied: '/usr/local/share/jupyter'
```

I think this has to do with the hubadmins group you set up?

**Comment by tatarsky** [comment]
Ah, I have not changed the permissions on that directory. I wonder why it wants to use that area instead of the `frazer01/software/python-3.3.6/(blah blah)`

Granted "hubadmins" write to `/usr/local/share/jupyter` and all files below.

**Comment by tatarsky** [comment]
Still happy BTW to try adding `"toc": true, ` to the json file that is in the python 3.3. tree...but want to not damage running notebooks (I have no idea if it would or not)

**Comment by billgreenwald** [comment]
I just tried that, and when I did a list I got a ton of errors.  Feel free to try it and see if it works on your end?

by list i mean
```
jupyter nbextension list
```

**Comment by tatarsky** [comment]
Sure.

When I do the above, I get this:

```jupyter nbextension list
Known nbextensions:
  config dir: /frazer01/software/python-3.3.6/etc/jupyter/nbconfig
    notebook section
      jupyter_dashboards/notebook/main  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      toc  enabled 
      - Validating: OK
```

Adding to the json....

**Comment by tatarsky** [comment]
OK, with manually modified JSON file I get different output...
```
Known nbextensions:
  config dir: /frazer01/software/python-3.3.6/etc/jupyter/nbconfig
    notebook section
      jupyter_dashboards/notebook/main  enabled 
      - Validating: OK
      toc  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      toc  enabled 
      - Validating: OK
```

Now seeing if anything shows up....

**Comment by billgreenwald** [comment]
It works now.

We must have different permissions or something.  It's fine to leave how it is for me though, thanks for getting int running

**Comment by tatarsky** [comment]
Yeah, I think the issue is the "nbextensions" command isn't putting stuff in the right place for the "enable" part. I don't know why its looking in /usr/local/share anything.

I'll look into that but if it works, we know what to do next time if we don't figure it out.

**Comment by billgreenwald** [comment]
Works meaning installed and functional for me and at least one other person

**Comment by tatarsky** [comment]
Worked for me as well ;0

**Comment by billgreenwald** [comment]
I'm going to close in that case

**Comment by tatarsky** [comment]
Noted. I'll drop a note if I find anything interesting.
