### ISSUE TITLE
backup01 luster

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#209]
Do you run any backup program to copy to
/backup01/lustre

**Comment by tatarsky** [comment]
It was a manual rsync test.

It was primarily a test of the compression rates for the homedirs and some other areas. 

I believe we no longer intend to use this however. If we do I can make it a cron job. 

Would you like that?

**Comment by hirokomatsui** [comment]
No, it's ok. We'll copy the files manually which needed.

**Comment by tatarsky** [comment]
OK. I can delete that area in a moment as I believe we were going to backup to the old host....

**Comment by hirokomatsui** [comment]
Yes. I copy files to:
/backup01/projects

Other files are copied by themselves mostly to the old hosts.

**Comment by tatarsky** [comment]
Okey doke. I won't touch that area.

**Comment by tatarsky** [comment]
All test areas removed. Compression was actually pretty good for the homedirs and repos. Similar results as elsewhere for the public data and software due to those items often containing already compressed items. 

Its just your backups now on that volume!
