### ISSUE TITLE
n6 and n11

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#214]
The two nodes are not mounting Luster. Can you please check if there's anything wrong on them and re-mount.

**Comment by tatarsky** [comment]
Hmm. n6 crashed while I was driving home. n11 just crashed. Removing both from SGE. I thought I had SGE set to not attempt to start until a check was done of a crash node. So checking that as well.

**Comment by tatarsky** [comment]
Interestingly thats our first node crash on these. Most remain up for >677 days. 
Anything new and interesting being run? Or just they got tired?

**Comment by tatarsky** [comment]
Autostart of SGE removed on all nodes which is my usual practice but must have missed it. Looking at both systems for reasons they crashed. Nothing found yet.

**Comment by tatarsky** [comment]
Jobs in state `Eqw` I can clear for re-run if desired. That means they could not execute due to paths usually.

**Comment by tatarsky** [comment]
Leaving both units out of SGE while I run some tests. I show a kernel panic of varying reasons on both. We are due for some kernel revs but if we are going to move to C7 soon not worth the effort unless it is something a job is triggering. Node uptime average ~563 days.

**Comment by tatarsky** [comment]
putting both units back in SGE as nothing is pending and I can monitor them closely. 

No hardware issues found that would correlate to the panic so suspecting long long runtime and some bug. Memtester returned no issues.

**Comment by tatarsky** [comment]
Not seeing anything odd. Will re-open if they crash again.
