### ISSUE TITLE
Moving fl-hn2 to CentOS 7

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#216]
I am making this a separate Git issue just in case I need to make additional announcement of changes.

I am disabling logins to the system. 

Bring it down will also bring down the Lustre -> NFS exports to the `opt.q` nodes. I assume that is fine for now. I am disabling those nodes in SGE.

**Comment by tatarsky** [comment]
Initial pass at the system is complete. A few more items to update the puppet maninfest for a C7 head node. I am done for now but if anyone tests items on it please ask for additional items here. So that puppet rules can be added. 

I would ask that people not fire up anything long term on it yet until I can confirm I don't need a reboot for any additional config. That however would be in the morning as I am done now for the day.

**Comment by tatarsky** [comment]
Looking at Jupyter Notebook config on this system to allow us to migrate `fl-hn1`. Will take a bit.

**Comment by tatarsky** [comment]
While I cannot think of any conflict in running the Jupyterhub code from the same module as `fl-hn1` if you have some kind of super critical notebook open I guess I would make sure its saved. I am being very careful on these tests on `fl-hn2` but I don't really know if there is some kind of shared state. Doesn't look like it, but just a caution to consider checkpoint or save (assuming there is such a thing)

I don't plan on firing it up today as I have an appointment but I was going to experiment in the morning. 

Please advise if you are worried about that and I'll do more checks.

**Comment by billgreenwald** [comment]
It seems that the update removed the soft links from the root directory of the system, and many people have scripts and modules that reference either 

/projects
or
/software

rather than

/frazer01/software
or
/frazer01/projects

could you or @hirokomatsui please re-softlink those?

Or, if you are not ready to do that yet, that is fine too.  Just wanted to bring it up

**Comment by tatarsky** [comment]
Puppet rules corrected for head node links to properly deploy. Re-check when convenient.

**Comment by billgreenwald** [comment]
Works now, thanks.

**Comment by tatarsky** [comment]
I am currently stuck on trying to make a JupyterHub on flhn2 due to this error when connecting back to the spawned singleuser notebook via the proxy.

`Permission failure checking authorization, I may need a new token`

I've Googled excessively and not come up with a solution yet. It may be awhile.

**Comment by tatarsky** [comment]
Ruled out it being something in my personal configs by making another user. Same error. Now building a separate python and jupyter hub to try. Something in the old one is not working with C7.

**Comment by tatarsky** [comment]
No clue at the moment what this error involves. I can get the regular spawners to work (ones that spawn notebooks on the same host as the hub) but the Batchspawner (the one that talks to SGE) seems to be missing some concept to provide authentication between the hub and the node that gets the notebook. 

A few other people out there have definitely fought with this but they don't seem to have a solution either. 

I will check out the development version of the hub shortly just to see if it works. Again, all of this is on fl-hn2. I'm trying to not touch the existing hub.

**Comment by tatarsky** [comment]
Progress. After thinking about something else ;)

Testing for the C7 Hub will be moved to a new Git. I do have to rev a few items so we may need to redeploy some things. But I am again able to spawn.

**Comment by tatarsky** [comment]
Followup on Hub needs to #217 . 

Added an SGE shadow master to this system so that in theory we can keep jobs running if we update fl-hn1 to CentOS 7. We should however consider a small test of that before trying it with say hundreds of running jobs.

Rebooting fl-hn1 would probably suffice. Bearing in mind all fl-hn1 Jupyterhub jobs would exit.

**Comment by tatarsky** [comment]
Corrected two default SGE qstat and qsub settings on new environment to match old. (qstat shows all users jobs by default and passing module parameters by default to qsub/qlogin)

**Comment by tatarsky** [comment]
Closing this issue for now. Unit is operational.
