### ISSUE TITLE
echo git SHA when loading a module

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#22]
I'd like to echo the SHA of the /repos/environment repo when loading some modules. For instance, this is some python that does what I want:

```
def _git_info():
    """Get current git version"""
    # Necessary to pipe to cat because git will open the result in less
    # otherwise.
    d = os.path.sep.join(os.path.abspath(__file__).split(os.path.sep)[0:-2] +
                         ['.git'])
    command = ('git --git-dir {0} log -1 --pretty=oneline --decorate | '
               'cat'.format(d))
    res = subprocess.Popen(command, shell=True,
                           stdout=subprocess.PIPE).communicate()
    res = res[0][:-1].strip()
    return res
```

**Comment by tatarsky** [comment]
Sorry I've never really commented on this but I've basically looked at this off and on and I'm not sure if this can be done with the `system` construct in the modulefile. If you still want to try this I'm a little less loaded down so far in 2017 than I was in 2016 ;)

Module is a shell function and I'm not sure if the path parsing item you do here is going to work.

In modules, stdout is considered SHELL environment to include going forward in that environment. Your item would need to be run as a helper script via the "system" modulefile construct. 

man modulefile contains all the constructs and I believe you can also issue native TCL commands.
