### ISSUE TITLE
Moving fl-hn1 to CentOS 7

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#221]
This Git will track the process of upgrade of `fl-hn1` to CentOS 7 and deal with any issues. 
Process is underway this morning.

**Comment by tatarsky** [comment]
Phase two of puppet based changes has begun.

**Comment by tatarsky** [comment]
Restoring Mysql data. Performance a bit reduced due to the RAID1 resyncing.

**Comment by tatarsky** [comment]
Mysql is running but would like @hirokomatsui to validate it looks correct before use. So please avoid it for now.

**Comment by tatarsky** [comment]
Waiting now for some of the RAID1 sync I/O to finish before additional steps and allowing logins to test config.

**Comment by hirokomatsui** [comment]
I've ran some queries on MySQL, and it looks fine.

**Comment by tatarsky** [comment]
Cool. Then Mysql is I believe ready for additional test. Doing some minor items still on fl-hn1 and then will open for logins to test as a basic submit host.

Final step is we would move the SGE spool back to the redundant mode but that requires an SGE shutdown. So if its still a good day for that sort of "everyone off SGE" let me know. 

Otherwise we can catch that step later.

**Comment by tatarsky** [comment]
I have opened `fl-hn1` to logins but be aware I may determine some additional step could require a reboot. So do not start long running items on that system until an all clear is given.

But you are welcome to login and test the basics. Please report missing items so I can add them to puppet.

**Comment by tatarsky** [comment]
I will be shortly moving the rest of the new nodes to CentOS 7 and then I will start in on the old nodes. For now the opt.q is one node (cn12).

**Comment by tatarsky** [comment]
report any remaining issues as a new Git. Migration is believed complete. Any additional item let me know and I'll add to the head-node class in puppet.
