### ISSUE TITLE
flh1 httpd

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#223]
I'd like to use the old setting of httpd.conf, which is copied at:
/home/hiroko/httpd.conf.171023

When I simply replace it, it did not work. Can you take a look?

**Comment by tatarsky** [comment]
Is the default one still in the same location? 

Apache has moved to version 2.4 and there are several items that need change in such configs. I will look after dinner.

**Comment by hirokomatsui** [comment]
Yes, I've moved it back.

**Comment by tatarsky** [comment]
Thanks. I'll look in about an hour!

**Comment by tatarsky** [comment]
So to summarize basically what I see:

Some userdir enables with authentication for a handful of users

Some top level Aliases with authentication. The syntax of authentication changed a fair chunk in 2.4.

Do you object to me making these part of the concept called:

/etc/httpd/conf.d/(somename).conf

Which allows us to spot the mods to defaults a bit better and also not risk overwrite?

I'll probably make a stab at it as "frazer.conf" for now. And you can verify what existed before does now.

**Comment by hirokomatsui** [comment]
OK, sounds good.

**Comment by tatarsky** [comment]
Phase one. I've taken the top level aliases and placed them into:

/etc/httpd/conf.d/frazer.conf

And reloaded Apache. Can you verify that part works? Seems to but you want to make sure the passwords function. There have been some syntax changes and I may need to still make them.

I will work on the other diffs in a moment.

**Comment by hirokomatsui** [comment]
Worked:
http://flh1.ucsd.edu/hipsci/

Not worked:
http://flh1.ucsd.edu/~hiroko

**Comment by tatarsky** [comment]
Yep, the "UserDir" items changed in 2.4 IIRC. 
Remembering what they changed to!

**Comment by tatarsky** [comment]
Ah yes, they didn't change the module but its another "conf.d" item:
/etc/httpd/conf.d/userdir.conf

Merging your mods into that. One moment.

**Comment by tatarsky** [comment]
OK. I've enabled userdir in I believe the same way as before but these four people should CHECK to be safe:

    UserDir enabled cdeboever paul hiroko matteo

I do not see cdeboever having any security on his directory. I am actually disabling mine. I don't need it. 

This part of Apache 2.4 is controlled by: /etc/httpd/conf.d/userdir.conf

**Comment by tatarsky** [comment]
Looking for any other diffs from the old file that might be needed so just advise if things are closer.

**Comment by hirokomatsui** [comment]
Worked. Thanks!

**Comment by tatarsky** [comment]
Cool! Marking these two files as "modified". Did not see any other major changes but just re-open if missing something. Have a nice evening.

**Comment by billgreenwald** [comment]
Mine still does not work.  I get "You don't have permission to access /~bill on this server."

**Comment by tatarsky** [comment]
Odd, you were not in the list of people that supported this access. Did it work before? Looked like a specific list of people were being maintained but perhaps I mis-read it.

Do you want your public_html to ask for a password? Thats not a default...and you'll need to have a password file for it.

**Comment by tatarsky** [comment]
@hirokomatsui how did you want this maintained BTW: ask for UserDir access via you or just turn on for all...I have no preference.

**Comment by tatarsky** [comment]
Also minor issue. I believe when you store the password file in the UserDir as I see being done, in theory it can be taken by anyone with a password and offline cracked. Its often wise to consider placing such password files _outside_ of the areas being shared if you worry about such things. Just mentioning. 

@billgreenwald I added your userdir to the allow list WITHOUT a password file so just advise if you want one!

**Comment by tatarsky** [comment]
(and I can explain how to maintain said password file if you've not done that before)

**Comment by billgreenwald** [comment]
No password is good for me.

It used to just work as soon as someone created a folder.  I know a few people you didn't specify had it up and running

**Comment by tatarsky** [comment]
Ah, ok. It might have been 2.2 was default allow for UserDir....checking. Just don't want to expose stuff by accident ;)

**Comment by hirokomatsui** [comment]
Yes, I remember that was, but changed at some version.

**Comment by tatarsky** [comment]
OK. So basically then I'm going to turn on with access. So if people have a ~/public_html it will be exposed. Do you want to warn people? 

```
<Directory "/frazer01/home/*/public_html">
    AllowOverride FileInfo AuthConfig Limit Indexes
    Options MultiViews Indexes SymLinksIfOwnerMatch IncludesNoExec
    Require method GET POST OPTIONS
</Directory>
```

Here's the people with public_html dirs.

```
bill/public_html
cdeboever/public_html
djakubosky/public_html
ensmith/public_html
hel070/public_html
hiroko/public_html
joreyna/public_html
matteo/public_html
mdonovan/public_html
nnariai/public_html
paola/public_html
```

And please re-check that the folks that HAD passwords still have them. In case I need to alter the inheritance of the directory stanzas.

**Comment by tatarsky** [comment]
Appears to allow access to everyone except @hirokomatsui and @s041629 who have password files defined. Please double check. I do not wish to expose data that is not desired exposed.

**Comment by tatarsky** [comment]
@hirokomatsui please also double check 

/etc/httpd/conf.d/userdir.conf

For sanity....

**Comment by billgreenwald** [comment]
went thru the drylab and asked paola, matteo, margaret, and joqauin, and no one had passwords before

**Comment by hirokomatsui** [comment]
Matteo should have passwords

**Comment by tatarsky** [comment]
Yep. Matteo is defined with passwords.

**Comment by hirokomatsui** [comment]
I don't want to open everyone's directories without password.
Can you use wild card to set AuthUserFile entity?

**Comment by tatarsky** [comment]
I'll check. I'm not sure actually. Do you want me to disable (while I check)?

**Comment by hirokomatsui** [comment]
Do you know 
<Directory "/frazer01//home/*/public_html">
works?

**Comment by tatarsky** [comment]
Yes, thats how things are currently enabled with no password. But I do not believe you can wild card a password file in that stanza. I believe you have to separately do what you were doing....per user.

**Comment by tatarsky** [comment]
Checking module docs though.

**Comment by s041629** [comment]
I am trying to find my password

**Comment by tatarsky** [comment]
You define it in public_html/.htpasswd

Thats controlled by the "htpasswd" command (consult man page for details or I can explain).

it is NOT your UNIX password and should not be for safety. That format is quite crackable. 
In fact I just cracked yours. (its your username)

**Comment by s041629** [comment]
found and updated it

**Comment by tatarsky** [comment]
I do not know of a way to "pattern expand" an AuthUserFile in a Directory Stanza @hirokomatsui 

So would you like me to revert the open of dirs while these are made?

**Comment by hirokomatsui** [comment]
I think we can open Bill's. I'll open others by request.

**Comment by tatarsky** [comment]
Ok. So reverting back to a list of users and a stanza per user with the needed auth or non-auth!
Then I'll defer to you as controller of this file and concept!

**Comment by hirokomatsui** [comment]
Thanks!

**Comment by tatarsky** [comment]
OK. So the key parts of the file /etc/httpd/conf.d/userdir.conf:

```
UserDir enabled hiroko matteo bill
```
If you are not there, your dir is not available. You must list the user there. (Confirmed with mine)

Then the stanzas per said users with the various auth v.s. non-auth config. 

Advise if questions and please re-check all exported UserDirs.
