### ISSUE TITLE
open port for http

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#225]
Can you open a port, 7071?
7070 is open now, but I don't know why. I cannot find it on iptables.
Anyway, we will use both 7070 and 7071.
http://flh1.ucsd.edu:7070/
is active for now.

**Comment by tatarsky** [comment]
Actually I think I forgot 7070/tcp was open...fixing and adding both to the world.

**Comment by tatarsky** [comment]
The master file BTW is:

`/etc/sysconfig/iptables`

Edit and then `service iptables reload`

I use the "older" iptables management in CentOS 7. I'm not a fan of the "UFW" or whatever the new one is called.

Added both ports and advise if not working. Assume just flh1.

**Comment by hirokomatsui** [comment]
Mmm, 7070 works fine but 7071:

November 09, 2017 - 23:12:47
Django version 1.11.7, using settings 'web.settings'
Starting development server at http://flh1.ucsd.edu:7071/
Quit the server with CONTROL-C.
Invalid HTTP_HOST header: 'flh1.ucsd.edu:7071'. You may need to add u'flh1.ucsd.edu' to ALLOWED_HOSTS.
[09/Nov/2017 23:12:49] "GET / HTTP/1.1" 400 67095

It's denied at somewhere?

**Comment by tatarsky** [comment]
That message isn't coming from me ;)

I can see the port open. Is there a config file that spells out the port.

**Comment by tatarsky** [comment]
Here's the iptables rules...they saw packets first column....where is the django config file?
```
 6   312 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:7070
   54  2768 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            state NEW tcp dpt:7071
```

**Comment by tatarsky** [comment]
I can connect and I get the same error from my network. So its talking to the application, but the application feels something needs to be told its available on perhaps that other port?

**Comment by hirokomatsui** [comment]
It's not by any config file. I'm running a command:
fl-hn1:/projects/CARDIPS/database/Cardips2/web> ../bin/python manage.py runserver flh1.ucsd.edu:7071

**Comment by tatarsky** [comment]
Googling on the error points to a few python files being involved. Can look in a bit. Here's one discussion:

https://stackoverflow.com/questions/40565188/django-disallowedhost-error

**Comment by hirokomatsui** [comment]
No solution there. I'll look at that more. It should be a Django problem.

**Comment by tatarsky** [comment]
Settings.py contains which looks OK....

ALLOWED_HOSTS = ['flh1.ucsd.edu:7071',]

**Comment by tatarsky** [comment]
I am getting "it worked now" just FYI. I see the port is removed...I have a very dim memory of something like this but sounds like you got it!

**Comment by hirokomatsui** [comment]
Yes, thank you!

**Comment by tatarsky** [comment]
Well done. Let me know if you need anything else I'll be back around-ish after dinner.
