### ISSUE TITLE
root user sessions

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#226]
I was looking at the log file for some other reason, but found there are too many root user's sessions were started:
/var/log/messages

Is that normal?
Maybe related with the other message:
check_nrpe: Remote 10.0.16.28 does not support Version 3 Packets

**Comment by tatarsky** [comment]
What system? 
I'll check but remember some of it is ssh brute forcing against the permit any ssh on the head nodes. And starting a session is not the same as succeeding. 

And we automatically shun source IPs using fail2ban.

I'll check the NRPE item, but thats nagios making sure SSH is running.

**Comment by hirokomatsui** [comment]
Sorry, it's flh1.

**Comment by tatarsky** [comment]
You can see some of the brute forcing in /var/log/secure. 

Are you referring to the "systemd: Started Session" lines?

**Comment by hirokomatsui** [comment]
Yes

**Comment by tatarsky** [comment]
Thats root cron I believe when in /var/log/messages. 

systemd does some fascinating things in its logs. Those are the system slice creates for cron. I'll confirm but that is NOT ssh.

**Comment by tatarsky** [comment]
I'll fix the nrpe item. I believe I know what that is but nrpe= nagios checks.

**Comment by hirokomatsui** [comment]
OK, I'm wondering that because the message's as the same as when ssh. Thanks!

**Comment by tatarsky** [comment]
Yeah, I'm pretty sure its cron jobs but I'll confirm that belief. I think in a few places I filtered it out as it was confusing based on writeups recommending that. 

One thing to consider: we could disable password SSH to root and force the use of SSH keys or sudo. I do that many places and its a nice feature but if you've not done it before its a change. I can explain more in email.

**Comment by tatarsky** [comment]
BTW, to see the systems currently blocked for SSH brute forcing:

```
fail2ban-client status sshd
Status for the jail: sshd
|- Filter
|  |- Currently failed: 2
|  |- Total failed:     74423
|  `- Journal matches:  _SYSTEMD_UNIT=sshd.service + _COMM=sshd
`- Actions
   |- Currently banned: 44
   |- Total banned:     1829
   `- Banned IP list:   (long list)
```

**Comment by tatarsky** [comment]
Highly recommend fail2ban BTW on any exposed SSH box. We block for eight hours and could make it higher.

**Comment by hirokomatsui** [comment]
Can you block root user's ssh from external, and allow internal network? There won't be any problem.

**Comment by tatarsky** [comment]
I think there is a construct for that in sshd_config. Let me check. 

But still allow non-root from ANY right?

**Comment by hirokomatsui** [comment]
We can ban all the access from off-campus as proposing the idea in the lab, and use VPN from off-campus.
Do you recommend that?

**Comment by tatarsky** [comment]
Depends on the needs. SSH is very convenient for data transfer scripting. If you know that most people use SSH for interactive needs a VPN is fine. But it hard to script many VPNs.

Personally I feel SSH keys remove any threat of brute forcing of passwords. As there are not any passwords then allowed via SSH connection.

I minimally start with root login only via keys or sudo from a user (there are cases during problems where root access is needed without a user involved) and then go from there. 

We could certainly limit the subnets we allow to connect to fl-hn1 and fl-hn2 to "campus" and see how it goes. How about fl-hn1 to try a list?

**Comment by hirokomatsui** [comment]
Sure, that sounds good.

**Comment by tatarsky** [comment]
OK. I'll make a Git issue so if people get blocked we can discuss if we wish to add their range to the list. I'll do that in the morning however.

**Comment by tatarsky** [comment]
You are seeing cron runs in that log. Thats a feature of systemd slices.

**Comment by tatarsky** [comment]
SSH root security changed to only allow via proper keys. Other items over to your email for now!
