### ISSUE TITLE
qsub on compute nodes

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#231]
Please check it after your vacation.
Can't we submit jobs from compute nodes anymore? Sorry if I forgot any previous conversation.

fl-n-1-1:~> echo "hostname" | qsub -cwd
Unable to run job: denied: host "fl-n-1-1.local" is not submit host
Exiting.

**Comment by tatarsky** [comment]
I'm not on vacation yet ;)
I'll add the nodes as submit hosts in just a moment. Oversight from upgrade.

**Comment by tatarsky** [comment]
Think I got them all. Please retest while I verify.

**Comment by tatarsky** [comment]
Ah, my "migrate SGE" script actually doesn't contain a check of the before and after submit hosts. 
Updated my script for the future. And I believe all head nodes, compute nodes and old nodes are submit hosts now.

**Comment by hirokomatsui** [comment]
Just tested on one nodes, n1, and works fine. Thank you!

**Comment by tatarsky** [comment]
You are very welcome! Have a wonderful holiday!

**Comment by hirokomatsui** [comment]
You too, happy holiday!
