### ISSUE TITLE
cant communicate with cluster

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#232]
Hi Paul,

paola and I both cannot log in to the cluster right now.  Neither flh1 nor flh2.  I tried a ping from the command promt as well and I get 100% loss with time outs.

Others are currently at a talk, so only two test cases for now.

Thanks!

**Comment by billgreenwald** [comment]
The Gaulton lab cannot reach their server's either, so it may be an SDSC problem

**Comment by billgreenwald** [comment]
seems to just be slow now, issuing a ping reaches the server

**Comment by billgreenwald** [comment]
seems SDSC fixed it, nevermind.

**Comment by tatarsky** [comment]
Was an SDSC outage but be aware I am on vacation and in transit back home via plane for the next 24 hours or so.

**Comment by hirokomatsui** [comment]
Check the page:
http://status.externsdsc.org/
