### ISSUE TITLE
storage and compute node costs

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#233]
Hi Paul,
we are writing a couple of grants and we would like to have a quick rough estimate of the cost for doubling our storage space (500 TB) and for getting additional compute nodes.

Thanks!

**Comment by tatarsky** [comment]
Sure. The quickest would be to grab the same prices from the original quote. But bear in mind in reality I would have you folks review your node core counts and such for new nodes.

We would also discuss the fact Intel no longer sells or supports Lustre so if we do expand we would be moving to the open source version or another filesystem. (Or seeing if Whamcloud has returned to supporting Lustre...Intel bought them...I am not sure what their current plans are)

But for your grant purposes I can review that older data and provide a summary shortly.

**Comment by tatarsky** [comment]
OK First item is the nodes. We used a "quad node in 2RU" solution to provide 4 nodes per chassis.

They were 20K each for those chassis. So by rough extrapolation think $5K a "node". We do this to save rack space as there isn't much in a node beyond the CPUs. 

Bear in mind those were each Dual E5-2640 v3 2.60 GHz Eight-Core (16 thread) 90W Processors. So that would be something better most likely now for similar prices. 

Storage estimate in a moment.

**Comment by tatarsky** [comment]
Storage expansion would take advantage of existing resources as was designed. 

I see no need for additional metadata space unless you tell me you are planning on literally millions of small files (current metadata array is half full and that is with 276,948,154 files).

If you take the path of just wanting more space without additional parallel Lustre performance we would add additional 60 bay arrays to the current OSS (storage) servers. 

We bought those arrays with 60 X 6TB drives for $34000 back in 2015. 
Today I believe a similar array with 8TB drives would be close in price from a more recent purchase.

10TB and 12TB is an option as well but I'd have to check the price as I've not gotten one recently.

I can actually get a budgetary quote if you want quickly if it helps. 

I normally add arrays in pairs but given the larger usable space from the bigger drives you might not need to. We can talk about that if you want. 

One 60 drive array with 8TB drives would provide around 348TB (6 x RAID6 2+8 LUNS)
   (twelve drives get used for RAID6 parity)
One 60 drive array with 10TB drives would provide around 480TB
One 60 drive array with 12TB drives would provide around 576TB

Let me know if you want a budgetary quote on the above for 10 and 12. Happy to help.

**Comment by s041629** [comment]
Thank you Paul, 
For grant writing purposes the information you wrote is more than enough. 

Thank you
