### ISSUE TITLE
adding jupyterlab to jupyter hub

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#236]
Hi Paul,

JupyterLab (an improved version of the jupyter notebooks) went stable today (though still in beta), and some members of the lab are interested in trying it.  Seemed like the easiest (hopefully) way to me would be to integrate it into jupyterhub, as everyone has access to it.

I think I figured out how to do it, but before getting to those directions, could you also in your reply let me know where
1) JupyterHub lives
2) The batchspawner to JupyterHub lives

This way, if we want to try to change some things, I can run through it with Hiroko first.

Anyway, for installing lab, I think we need to do the following:

1)  install [jupyter lab](https://github.com/jupyterlab/jupyterlab) in the Python install that has jupyter hub installed
2)  install the [jupyterlab-hub extension](https://github.com/jupyterhub/jupyterlab-hub) to allow for the creation of a lab style notebook from the hub.
3)  I have read the readme from 2 a lot, and I am unable to tell if this lets you immediately use the lab instead of a notebook from the hub.  Let me know what you think.  Assuming it does not, it looks like to enable lab as the default value, we would add 
```
c.Spawner.cmd = ['jupyter-labhub']
```
to our batchspawner.  However, this seems like something we could easily make optional, by using an environment variable for the batch spawner instead, and have that be set by the type of hub instance we load.  Then we could just make other hub instances on that list, ie
```
low-lab (1 core, 2GB ram, JupyterLab)
low-lab2 (1 core, 4GB ram, JupyterLab)
```
This could make it so that you choose to launch default jupyter notebooks, or the jupyter lab.

As we made the RAM use and other things specific to the instance, it seemed easily transferable via
```
c.Spawner.cmd = [args['lab']]
```
or however the args get specified (which I haven't checked because I cant find the batchspawner location).

Thanks, and of course happy to work through this with you.

**Comment by tatarsky** [comment]
Happy to go over what is where on `fl-hn2`. Its a blend of a python tree (located in `/frazer01/software/python-3.3.7/bin`) and some config files in `/etc/jupyterhub`. Perhaps tomorrow we can chat or something to get you and/or @hirokomatsui the perms you need.

**Comment by tatarsky** [comment]
"I am unable to tell if this lets you immediately use the lab instead of a notebook from the hub. Let me know what you think."  

I am not able to tell either ;)

Worst case we can experiment. But restarting the hub as you know creates some impact. 

Alternately I don't mind spinning up another instance if it helps.

**Comment by billgreenwald** [comment]
Spinning another instance up that we can develop on is better if easy. Plus
that way we don't have a potential issue of breaking the current hub during
the process

On Feb 20, 2018 6:32 PM, "tatarsky" <notifications@github.com> wrote:

"I am unable to tell if this lets you immediately use the lab instead of a
notebook from the hub. Let me know what you think."

I am not able to tell either ;)

Worst case we can experiment. But restarting the hub as you know creates
some impact.

Alternately I don't mind spinning up another instance if it helps.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/frazer-lab/cluster/issues/236#issuecomment-367193933>,
or mute the thread

**Comment by tatarsky** [comment]
Sure. Main thing is we should probably build a whole separate python tree to prevent clobbering the "active" one. But that may be useful anyway to update parts of it from the latest. We can go over the steps tomorrow but lets plan on a separate instance.

**Comment by billgreenwald** [comment]
Sounds good

**Comment by tatarsky** [comment]
Note I will start work on the above this afternoon unless I misunderstand and you and @hirokomatsui wish to do the work. I don't mind if you want to maintain the python tree, just tell me thats what you want to do. I have to handle the root part on the head node for now and I'm checking that the SGE part won't conflict between the two on its "delete hub" section.

**Comment by billgreenwald** [comment]
Can we make it a separate python install for the development, and then give hiroko and I edit access to the files?  For now though, could you take a stab at the earlier steps and we can see if they work, and if they don't hiroko and I will trouble shoot it further?

**Comment by tatarsky** [comment]
Sure. So I just did the following based on just the lab install to validate it comes up on its own (non-Hub)

https://github.com/jupyterlab/jupyterlab

I built a fresh clean Python. I went with 3.6.4 as it seems the latest stable:

`/frazer01/software/python-3.6.4`

I made that first in my path:

```export PATH=/frazer01/software/python-3.6.4/bin:$PATH```

And I ran `pip3 install jupyterlab` which brings in a collection of items to that tree (since I own it)

```
pip3 list  
bleach (2.1.2)
decorator (4.2.1)
entrypoints (0.2.3)
html5lib (1.0.1)
ipykernel (4.8.2)
ipython (6.2.1)
ipython-genutils (0.2.0)
jedi (0.11.1)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.2.2)
jupyter-core (4.4.0)
jupyterlab (0.31.8)
jupyterlab-launcher (0.10.5)
MarkupSafe (1.0)
mistune (0.8.3)
nbconvert (5.3.1)
nbformat (4.4.0)
notebook (5.4.0)   <--- Note this is a bump from our hubs version 5.3 in other Python
pandocfilters (1.4.2)
parso (0.1.1)
pexpect (4.4.0)
pickleshare (0.7.4)
pip (9.0.1)
prompt-toolkit (1.0.15)
ptyprocess (0.5.2)
Pygments (2.2.0)
python-dateutil (2.6.1)
pyzmq (17.0.0)
Send2Trash (1.5.0)
setuptools (28.8.0)
simplegeneric (0.8.1)
six (1.11.0)
terminado (0.8.1)
testpath (0.3.1)
tornado (4.5.3)
traitlets (4.3.2)
wcwidth (0.1.7)
webencodings (0.5.1)
```

Then, with the above still in my path for items I run:

```jupyter lab```

Which gives me a bound to localhost lab web server which via SSH tunnel I get to and its definitely running lab. So feel free to play with that a bit while I now attempt to make a hub instance on `fl-hn1` that calls that as the spawner as you describe.

**Comment by billgreenwald** [comment]
i dont have the most experience in tunneling; could you send over the command you used to tunnel forward.

**Comment by tatarsky** [comment]
Does your browser support proxy settings easily? Because thats the more complex part.

The tunnel I do is a SOCKS proxy. I use:

```ssh -D localhost:9506 flh1.ucsd.edu```

Then I set my browser to proxy SOCKS5 to localhost on port 9506. (Firefox, under Network Proxy)
And then I enter the URL that the `jupyter lab` command kicks out.

**Comment by billgreenwald** [comment]
im having issues, but its not the most important thing.  i can work on it while we progress further.

**Comment by tatarsky** [comment]
OK. Well, I'm working on the hub so hopefully not long.

**Comment by tatarsky** [comment]
Moving along. Hub running but just "stock" at the moment for notebooks on `fl-hn1` directly. No batch spawner. No Lab integration yet. Going down the steps however to make it as similar as possible while reviewing some old assumptions for correctness.

**Comment by tatarsky** [comment]
OK. based on my reading of the https://github.com/jupyterhub/jupyterlab-hub page I've done steps 1 and 2 only I did them one at a time to see what they did.

The new "beta hub" is located at:

https://flh1.ucsd.edu:9000

self-signed cert for now. We'll get some campus ones shortly as I learned the InCommon SSL process recently for UCSD. 

It runs a lab instance directly on flh1 for now. (I am working on SGE part)

The second command added a menu under Help to "Launch Classic Notebook"

Again it is NOT hooked to SGE yet. Working on it. But feel free to login and look around. But I reserve the right to ctrl-C in case I need to do something ;)

**Comment by billgreenwald** [comment]
The PDF part makes sense, I recommended a change on the github and they said they implemented in a while back

**Comment by tatarsky** [comment]
In theory we can just pip3 update the old one but lets leave it alone for a bit as we experiment with Lab.

**Comment by billgreenwald** [comment]
Seems to work correctly.  Once we get queues up I am happy to test more.  I am going to grab lunch in ~10 mins so I'll be out for a bit

**Comment by tatarsky** [comment]
Cool. I'm just reviewing the SGE settings.

**Comment by tatarsky** [comment]
Oh and I believe by default the question "lets you immediately use the lab instead of a notebook from the hub?"

Is "yes" it defaults to the Lab interface but allows you to spawn a "legacy Notebook". Seeing if batch spawner can alter what gets spawed or if that is good enough (aka the lab is running and if you want the older interface you can still get it from same spawn)

**Comment by billgreenwald** [comment]
I meant from spawning options, yes.  The current effect of running the lab and then opting to swap to default notebooks is a fine backup options

**Comment by tatarsky** [comment]
Okey doke. Some changes in spawner config. Stand clear ;)

**Comment by tatarsky** [comment]
Chasing an odd one that appears to match this one. Something in the wrapspawner with the 0.8 hub. (We run the 0.7.X hub on fl-hn2 so I'm just seeing if we can rev that or not)

https://github.com/jupyterhub/wrapspawner/issues/11

**Comment by tatarsky** [comment]
Got me for now on the correct solution for this. Reading various Gits that match. Will work on it more shortly.

**Comment by tatarsky** [comment]
For my reference. When the spawned item runs via SGE, this appears in the error output.
```
Traceback (most recent call last):
  File "/frazer01/software/python-3.6.4/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'oauth_client_id'

(trace)

ValueError: oauth_client_id cannot be empty.
```

Several folks mention patching things involving that but trying numbers of such items has NOT changed that result.

**Comment by billgreenwald** [comment]
would just rolling back to the 0.7.x version be a fine workaround?  I dont know if we need the newest version of hub if it has issues.

**Comment by tatarsky** [comment]
It did not fix it.

**Comment by tatarsky** [comment]
Seemed like the broken part is in wrapspawner. So I'll see if I can roll that back as well.

**Comment by tatarsky** [comment]
Attempting for my reference:
```pip3 install git+https://github.com/jupyterhub/wrapspawner@9527df3802f83cf377d2bcc143740402ae1d2b9d#diff-f4f7007b6154f4b0501aede1c67e2c87```

**Comment by tatarsky** [comment]
Well, different error now. Thats it for today for me. I'll look more tomorrow.

**Comment by billgreenwald** [comment]
could you point me to the spawner file you are working with and ill do some reasearch

**Comment by tatarsky** [comment]
So the crux of the matter seems to involve:

/frazer01/software/python-3.6.4/lib/python3.6/site-packages/wrapspawner/wrapspawner.py

Which comes from the previously mentioned Git package:

https://github.com/jupyterhub/wrapspawner

Which allows us to do the menu item to choose which spawner. (See config file on fl-hn1 /etc/jupyterhub/jupyterhub_config.py)

There are several comments about wrapspawner needing some Oauth support for the 0.8.X series of the hub which apparently has started to use Oauth for communication back and forth to the spawned notebook. And there are commits which claim to add that support to wrapspawner. But the error I mention up a few continues even if you use them.

https://github.com/frazer-lab/cluster/issues/236#issuecomment-367503062

**Comment by tatarsky** [comment]
And as mentioned this is almost exactly the same matter, but the solutions here don't seem to work.

https://github.com/jupyterhub/wrapspawner/issues/11

**Comment by billgreenwald** [comment]
thanks

**Comment by tatarsky** [comment]
Basically it looks like within the last month there was a good chunk of change in this area.

**Comment by tatarsky** [comment]
And just so you know: That python tree at the moment contains both the rolled back hub to 0.7.2 as most folks did and the pre-commit of the "fix" to wrapspawner to support 0.8.0.

So you won't see the code mentioned. As I've tried to not include it. The issue I'm getting now is the "I need a new token" error which I've seen before but don't recall where it came from.

**Comment by tatarsky** [comment]
This is the crux of the current matter. We both are getting this:
```
[E 2018-02-21 15:18:40.851 bill auth:180] I don't have permission to verify cookies, my auth token may have expired: [403] Forbidden
```

I've seen that at one point but I don't recall what it was. Googling seems to involve the sqlite DB. Its possible I have things in a mixed 0.8.1 and 0.7.2 state. I may just clear it all and start over.

**Comment by billgreenwald** [comment]
no need to look at these now, just writing down options of what seems like a potential fix/workaround

1)  copy the base files from the hub on flh2 and set up a new hub on flh1, reinstall the jupyterlab addons to this instance of the hub (ie try to circumvent reinstalling)
2)  reinstall hub version 0.7.x.  wrap spawner says its back compatible (though reading your comments, perhaps its not)?
3)  delete the sql database for the hub on flh1
4)  add a default user to the child class for wrapspawner (perhaps try me as that user first?)

separate points:
1) is this the same issue we encountered before where we had to set up a special 
2) do we want to be using wrapspawner and not batchspawner?  I see they used to be the same, but I dont remember working on wrapspawner.  Fwiw, wrapspawner appears to be installed for python-3.3.7 but not batchspawner.

**Comment by billgreenwald** [comment]
posted that and will edit as I see you are active and wanted to give you a heads up on what i was working on.

i remember a workaround that we created for the sqlite DB on the other hub.  one sec

**Comment by billgreenwald** [comment]
it was this
```
echo "c.HistoryManager.hist_file = u'/tmp/${USER}_ipyhist.sqlite'" >> ~/.ipython/profile_default/ipython_config.py
```

do you know which profile or config file is getting pulled from the logs?

also, not sure if this is the same issue, or unrelated issue still involving sqlite

**Comment by tatarsky** [comment]
wrap spawner I believe is needed to display the "choice list". 

Looking on your history item. I'm going to make the live logs from the hub appear at:

/var/log/jupyterhub on fl-hn1.

**Comment by tatarsky** [comment]
OK logs are readable. I will be stopping now for dinner. I'll respond if I have some time on the permutations I've tried.

**Comment by tatarsky** [comment]
One more try as food not finished...I am checking the token of the API....

**Comment by tatarsky** [comment]
(the sound of a head banging on a desk)

I have fought with this before. The concept of the HUB API token (which is I believe what they replaced with Oauth) gets stored in the sqlite database once at start and is saved then. I did not change it in the qsub arguments when I cleared that DB. I can now spawn an SGE lab instance.

@billgreenwald can you confirm? You might have to kill your SGE job.

I am going to do one more stop/start to add another "choice" and fix an item in the qdel.

**Comment by tatarsky** [comment]
OK. I may need to kill your job and have you restart but then I'm reasonably confident you will get a spawned "lab".

This to be clear is a partial roll back to 0.7.2 for the hub code and the wrapspawner before oauth was added. My issue was the older style API key was not correct following the hub sqllite db clear. (which had to be done as 0.8 has different format)

**Comment by billgreenwald** [comment]
I tried to kill that and wasnt able to.  go ahead

**Comment by billgreenwald** [comment]
killed it thru the cmd line. lab is up and running thru SGE

**Comment by tatarsky** [comment]
Cool! So do some additional tests and I'll check back after chicken is done ;)

**Comment by billgreenwald** [comment]
honestly, it may be easier for everyone to just leave flh1 as a hub that launches Labs, and flh2 as a hub that launches notebooks.

that way we dont double the number of queues to select, and people could have both running if they wanted.

thoughts?

**Comment by tatarsky** [comment]
I believe that should be fine and I like having a "dev" hub and a "prod" hub with this code. 

The item I was concerned about in the "qdel" part of this was making sure that two hubs that share the same backend SGE cluster don't get confused (and kill the wrong job or something)

But at the moment I show you having an "old" and "new" hub running out there:

```
qstat -u bill
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID 
-----------------------------------------------------------------------------------------------------------------
5238734 0.50367 jupyterhub bill         r     02/08/2018 14:14:44 juplow.q@fl-n-1-7                  2        
5244587 0.47742 jupyterhub bill         r     02/21/2018 16:00:42 juplow.q@fl-n-1-2                  1        
```

And I saw in the sqlite as I was wading around the job id is what is stored (and killed via qdel when you shutdown your server instance)

Perhaps we just want to change the job name to help us know which one is which.

**Comment by billgreenwald** [comment]
thats fine.  if you want to change that to jupyterhub-lab for the new server, give it a reboot, and then close this issue until something new changes in the coming months, that seems fine with me

**Comment by tatarsky** [comment]
Eh, I show that the "name" is already quite long (`jupyterhub-singleuser`) and I have other ways to determine who is running including the admin URL (which you are an admin BTW)

https://flh1.ucsd.edu:9000/hub/admin

So lets let it ride and do some tests. I may attempt a systemd startup script but that won't be tonight as I have to call it a day.

**Comment by billgreenwald** [comment]
do i/can i have/get access to install plugins to the jupyterLab setup?  I want to [get widgets installed,](https://github.com/jupyter-widgets/ipywidgets/tree/8ad4824b41c375c06839ffa8f279e99abd64e8c1) but figure I can do this and future ones myself so that I dont take your time.

**Comment by tatarsky** [comment]
So I assume that boils down to write permission on the python tree where all this is. We made a group awhile back called "hubadmins" with you in it for such an idea. I'm going to change the permissions of that tree to be group write "hubadmins" (/frazer01/software/python-3.6.4/)

Then I would manually add it to your path (we can make a module if it helps)

```export PATH=/frazer01/software/python-3.6.4/bin:$PATH```

And then you have the needed python. Tell me if that doesn't work. Give me 5-10 minutes to make the changes.

**Comment by billgreenwald** [comment]
module would be useful simply because it makes loading and unloading the python quick.  perhaps we can just make a module called jupyterlabhub

**Comment by tatarsky** [comment]
I will do so. One moment.

**Comment by tatarsky** [comment]
Permissions should be done. Module in a second.

**Comment by tatarsky** [comment]
```
$ module load jupyterlabhub
$   which jupyterhub
/frazer01/software/python-3.6.4/bin/jupyterhub
```
Note you will still have to talk to me to restart the hub. I'll work on a systemctl service shortly which I can grant sudo to or @hirokomatsui can do as well.

Advise if you are blocked from doing something. Please note I use "pip3" from that same tree to do most of the work in that python in terms of adding/updating/etc.

**Comment by tatarsky** [comment]
Note many of the install writeups call out "pip" as the method to load it. Be sure to use "pip3" and I always double check with `which pip3` to make sure I'm going into the tree I think. Probably redundant advice but FYI regardless. 

$ which pip3
/frazer01/software/python-3.6.4/bin/pip3

**Comment by billgreenwald** [comment]
yea i ran pip3, and it installed fine.  looks good, have to see if it works in the actual notebooks.  but write permissions worked, thanks!

**Comment by tatarsky** [comment]
Cool. happy to restart the Hub. If its not quite in use I can mess with the systemd startup script in an hour or so.

**Comment by billgreenwald** [comment]
i dont think its necessary for these but ill let you know.

**Comment by tatarsky** [comment]
We'll want to probably check umask on folks or cron a permission fixer if its more than you and I
```
drwxr-sr-x  2 bill hubadmins  4096 Feb 22 10:39 widgetsnbextension-3.1.4.dist-info
drwxr-sr-x  4 bill hubadmins  4096 Feb 22 10:39 widgetsnbextension
drwxr-sr-x  5 bill hubadmins  4096 Feb 22 10:39 ipywidgets
drwxr-sr-x  2 bill hubadmins  4096 Feb 22 10:39 ipywidgets-7.1.2.dist-info
```
The write bits are yanked there I suspect due to umask. I'll prepare a "cron permission fixer"

**Comment by billgreenwald** [comment]
ok so for lab I need different permissions it seems

```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
> /usr/bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.33.2.tgz

Errored, use --debug for full output:
PermissionError: [Errno 1] Operation not permitted: '/frazer01/software/python-3.6.4/share/jupyter/lab/staging/index.js'
```

**Comment by tatarsky** [comment]
I assume the first command is calling npm there. Not a series of commands. 

I use the system nodejs (/usr/bin/npm) as its more stable I found.

But that requires root to modify its items. Confirm the above is true and I will run the first command.

**Comment by billgreenwald** [comment]
yep should be.  all jupyterhub packages install via npm.

hiroko can write these too in the future, correct?  please run that command for now :)

**Comment by tatarsky** [comment]
Yep. @hirokomatsui has root privs in the environment. 

I'm not 100% sure if its possible to delegate npm module installs. I can Google around. 

The main thing to remember is from the root environment making sure that python module is loaded. 

Will load them in a moment.

**Comment by tatarsky** [comment]
Just for @hirokomatsui reference. Here is all I did:
On fl-hn1 become root
```
# module load jupyterlabhub
# which jupyter
/frazer01/software/python-3.6.4/bin/jupyter
# jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

That produced rather copious output with some items flagged but seemed to complete.

```
> /bin/npm pack @jupyter-widgets/jupyterlab-manager
jupyter-widgets-jupyterlab-manager-0.33.2.tgz
> node /frazer01/software/python-3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
â  @jupyterlab/application@^0.15.4
â  @phosphor/widgets@^1.5.0
â  safe-buffer@~5.1.0
â  es6-promise@~4.1.1
â  @jupyterlab/codemirror-extension@^0.15.4
â  @jupyterlab/completer@^0.15.4
â  @jupyterlab/notebook@^0.15.4
â  @jupyterlab/docmanager@^0.15.4
â  rw@1
â  @jupyterlab/faq-extension@^0.15.5
â  @jupyterlab/fileeditor-extension@^0.15.4
â  @jupyterlab/imageviewer@^0.15.4
â  @jupyterlab/json-extension@^0.15.4
â  @jupyterlab/mainmenu-extension@^0.4.5
â  @jupyterlab/mathjax2-extension@^0.3.4
â  @jupyterlab/rendermime-extension@^0.9.4
â  @jupyterlab/running-extension@^0.15.4
â  @jupyterlab/settingeditor-extension@^0.10.4
â  @jupyterlab/terminal@^0.15.4
â  @jupyterlab/theme-dark-extension@^0.15.4
â  @jupyterlab/tooltip-extension@^0.15.4
â  @jupyterlab/vega2-extension@^0.15.5
â  boom@5.x.x
â  semver@^5.1.0
â  graceful-fs@^4.1.6
â  align-text@^0.1.1
â  yargs-parser@^4.2.0
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react@^15.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.10.9" has unmet peer dependency "react-dom@^15.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.2" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has unmet peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
[1/2] â  spawn-sync
[-/2] â¢ waiting...
[2/2] â¢ canvas: node@4.8.7 | linux | x64
[-/2] â¢ waiting...
[-/2] â¢ waiting...
warning Error running install script for optional dependency: "/frazer01/software/python-3.6.4/share/jupyter/lab/staging/node_modules/canvas: Command failed.\nExit code: 1\nCommand: node-gyp rebuild\nArguments: \nDirectory: /frazer01/software/python-3.6.4/share/jupyter/lab/staging/node_modules/canvas\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.4.0\ngyp info using node@4.8.7 | linux | x64\ngyp ERR! configure error \ngyp ERR! stack Error: Command failed: /bin/python2 -c import platform; print(platform.python_version());\ngyp ERR! stack   File \"/frazer01/software/python-3.6.4/lib/python3.6/site.py\", line 177\ngyp ERR! stack     file=sys.stderr)\ngyp ERR! stack         ^\ngyp ERR! stack SyntaxError: invalid syntax\ngyp ERR! stack \ngyp ERR! stack     at ChildProcess.exithandler (child_process.js:200:12)\ngyp ERR! stack     at emitTwo (events.js:87:13)\ngyp ERR! stack     at ChildProcess.emit (events.js:172:7)\ngyp ERR! stack     at maybeClose (internal/child_process.js:862:16)\ngyp ERR! stack     at Socket.<anonymous> (intesuccess Saved lockfile.Done in 25.98s.> node /frazer01/software/python-3.6.4/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.3.2
$ webpack --config webpack.prod.config.js
Hash: 2d80caf60cba6415bfce
Version: webpack 2.7.0
Time: 34590ms
                                 Asset     Size  Chunks                    Chunk Names
        vendor.ccd7720fae88b2517d76.js  1.55 MB       4  [emitted]  [big]  vendor
  674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]         
 fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]         
  b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]         
  912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]  
             0.fc72ede5dda944bf9bfd.js   135 kB       0  [emitted]         @jupyter-widgets/controls
             1.4036acca592e79ef3fda.js   602 kB       1  [emitted]  [big]  vega2
             2.ae7201435e2768dca4ec.js   458 kB       2  [emitted]  [big]  
          main.1adc6c43018abba99b2b.js  1.59 MB       3  [emitted]  [big]  main
af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]         
      manifest.7f475335320daa80f654.js  1.67 kB       5  [emitted]         manifest
         0.fc72ede5dda944bf9bfd.js.map   446 kB       0  [emitted]         @jupyter-widgets/controls
         1.4036acca592e79ef3fda.js.map  2.23 MB       1  [emitted]         vega2
         2.ae7201435e2768dca4ec.js.map  1.34 MB       2  [emitted]         
      main.1adc6c43018abba99b2b.js.map   5.3 MB       3  [emitted]         main
    vendor.ccd7720fae88b2517d76.js.map  5.64 MB       4  [emitted]         vendor
  manifest.7f475335320daa80f654.js.map  8.34 kB       5  [emitted]         manifest
                            index.html  1.53 kB          [emitted]         
[+HaM] ./~/@phosphor/messaging/lib/index.js 18.5 kB {4} [built]
[8U58] ./~/codemirror/lib/codemirror.js 352 kB {4} [built]
[CUbq] ./~/@phosphor/signaling/lib/index.js 18.1 kB {4} [built]
[GiK3] ./~/react/index.js 190 bytes {4} [built]
[O27J] ./~/react-dom/index.js 1.36 kB {4} [built]
[Vszx] ./~/@phosphor/domutils/lib/index.js 636 bytes {4} [built]
[cYMN] ./~/@phosphor/virtualdom/lib/index.js 21 kB {4} [built]
[lMhA] ./~/@phosphor/dragdrop/lib/index.js 33.7 kB {4} [built]
[nh00] ./~/@phosphor/disposable/lib/index.js 4.24 kB {4} [built]
[qzHn] ./~/@phosphor/coreutils/lib/index.js 721 bytes {4} [built]
[ug+F] ./~/xterm/lib/xterm.js 52.7 kB {4} [built]
   [6] multi @phosphor/algorithm @phosphor/application @phosphor/commands @phosphor/coreutils @phosphor/datagrid @phosphor/disposable @phosphor/domutils @phosphor/dragdrop @phosphor/messaging @phosphor/properties @phosphor/signaling @phosphor/virtualdom @phosphor/widgets ajv ansi_up codemirror comment-json es6-promise marked moment path-posix react react-dom sanitize-html url-parse xterm 328 bytes {4} [built]
   [7] multi whatwg-fetch ./build/index.out.js 40 bytes {3} [built]
[wr2+] ./~/@phosphor/properties/lib/index.js 6.58 kB {4} [built]
[y7VK] ./~/@phosphor/algorithm/lib/index.js 1.03 kB {4} [built]
    + 1534 hidden modules
Child html-webpack-plugin for "index.html":
    [3IRH] (webpack)/buildin/module.js 517 bytes {0} [built]
    [DuR2] (webpack)/buildin/global.js 509 bytes {0} [built]
    [GTAU] ./~/html-loader!./templates/partial.html 420 bytes {0} [built]
    [M4fF] ./~/lodash/lodash.js 540 kB {0} [built]
    [vxCX] ./~/html-webpack-plugin/lib/loader.js!./templates/template.html 1.41 kB {0} [built]
Done in 39.81s.
```

**Comment by tatarsky** [comment]
Note there is some complaint in there about something not building. I have no idea what it is.  It got turned into a giant single line.

**Comment by tatarsky** [comment]
Ah, OK. I sort of see what it does but I don't fully understand "node" and where its modules live. Its weird it complained about that one file. As I show you should have been able to write to it. So it must be more than that.
```
$ ls -al /frazer01/software/python-3.6.4/share/jupyter/lab/staging/index.js
-rw-rw-r-- 1 root hubadmins 5271 Feb 22 11:50 /frazer01/software/python-3.6.4/share/jupyter/lab/staging/index.js
$ groups bill
bill : users hubadmins
```

Some googling seems to suggest that npm is something that really likes root privs. I can look more but @hirokomatsui also has root.

**Comment by tatarsky** [comment]
So I glanced through a few pages of "NPM version control" and the gist I got was its a big ball of wax ;)
And may require a newer nodejs than what I've settled on (nodejs-4.8.7-1)

So if "non-root" npm is needed its looking like a learning experience. (Aka will be a bit)

So just advise if you feel the above worked and my explanation for Hiroko is clear enough.

**Comment by billgreenwald** [comment]
it makes sense to me, and I can work with Hiroko to run it with her.  Other stuff came up so this is gonna be tabled for a while, but I'll let you know if it worked or didnt when i get around to it

**Comment by tatarsky** [comment]
Cool. Happy to help but also happy to share the fun with @hirokomatsui  ;) 
Looks like an interesting evolution of the Notebooks though.

**Comment by billgreenwald** [comment]
can you do a restart of the labHub?  didn't seem to fix it, but as jupyterlab handled the install via npm, perhaps this will require a restart to work.

**Comment by tatarsky** [comment]
For now its in a screen as root so providing steps for @hirokomatsui 

As root on `fl-hn1`
```
screen -x hub
(you will see the debug output of the hub which is why I'm doing it this way)
Ctrl-C
Up arrow to: `jupyterhub -f jupyterhub_config.py`
```

**Comment by tatarsky** [comment]
Which BTW I have done. Just documenting.

**Comment by tatarsky** [comment]
Any luck? As I'm off to an appointment for a bit soon. But will check back for ya if I'm needed.

**Comment by billgreenwald** [comment]
i have a git post in to jupyter lab for some help since this problem was reportedly fixed already.  table for a week or so till i talk to them :)

**Comment by tatarsky** [comment]
Tabled! You know where to find me.

**Comment by billgreenwald** [comment]
I had to update my own ipywidgets install, which fixed the issue.  

The other plugin we used, table of contents, is going to be natively installed into lab soon, so I think we can leave it for now.

 should be good to close I think.

**Comment by tatarsky** [comment]
OK. Happy to help with any other item and have a great weekend.
