### ISSUE TITLE
jupyter lab server connection error

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#237]
I get this error every time I try to execute something or save a notebook:

Server Connection Error
Unexpected token < in JSON at position 3

**Comment by s041629** [comment]
I don't know if it is related, but when I try to run somethings, it takes ages, even if it is "1+1"

**Comment by tatarsky** [comment]
I assume you mean the the one on `fl-hn1`. I'll look when I have time but basically thats a beta and I don't consider it something I'm going to look at after hours.

**Comment by s041629** [comment]
We can look at it on Monday.
I tried also on FLH2 (jupyter hub) and it doesn't work either: no error message but after a while the jupyter hub job dies.

**Comment by tatarsky** [comment]
I am not able to reproduce using my account on either server. 

So I looked quickly at your SGE output files (remember they are in ~/.jupyterHubQueueLogs)

You appear to have something "interesting" going on but I have no idea what as you have a nearly 70GB error log around the time you made this report (the first one here)

```
-rw-r--r-- 1 matteo users 73553391448 Mar  2 16:49 jupyterhub-singleuser.e5257841
-rw-r--r-- 1 matteo users           0 Mar  2 17:02 jupyterhub-singleuser.e5257877
-rw-r--r-- 1 matteo users        5290 Mar  2 17:02 jupyterhub-singleuser.o5257877
-rw-r--r-- 1 matteo users        5280 Mar  2 17:04 jupyterhub-singleuser.o5257878
-rw-r--r-- 1 matteo users           0 Mar  2 17:04 jupyterhub-singleuser.e5257878
-rw-r--r-- 1 matteo users        5284 Mar  2 17:06 jupyterhub-singleuser.o5257880
-rw-r--r-- 1 matteo users        5993 Mar  2 17:12 jupyterhub-singleuser.e5257880
-rw-r--r-- 1 matteo users        5294 Mar  2 17:14 jupyterhub-singleuser.o5257881
-rw-r--r-- 1 matteo users       11804 Mar  2 17:21 jupyterhub-singleuser.e5257881
-rw-r--r-- 1 matteo users        5276 Mar  2 17:26 jupyterhub-singleuser.o5257883
-rw-r--r-- 1 matteo users        5290 Mar  2 17:26 jupyterhub-singleuser.o5257882
-rw-r--r-- 1 matteo users        7577 Mar  2 17:29 jupyterhub-singleuser.e5257883
-rw-r--r-- 1 matteo users       38992 Mar  2 17:40 jupyterhub-singleuser.e5257882
```

That file is not overly helpful to debug from a brief glance. 

The LAST one (jupyterhub-singleuser.e5257882) contains this which may or may not be interesting.
```
*** Successfully loaded .Rprofile ***
Error: cannot allocate vector of size 7.7 Gb
Execution halted
```

I would suggest considering stopping all your hub jobs (if you need me to do so let me know) and starting a new one and we'll debug from there on Monday.

**Comment by s041629** [comment]
I don't know how it can try to load a 7.7 Gb vector. At that point I had restarted the hub job and was trying to create a new notebook and run something like "1+1"
Should I remove the 70 Gb error file?

Thank you

**Comment by tatarsky** [comment]
So I show your spawned hub is the 4GB one:
```
qacct -j 5257882
category     -l h_vmem=4G,juplow=TRUE -pe jupsmp 1```
```
And whatever was going on, something involving your R kernel seems to keep hitting above that.

I don't know much about R and Notebooks. Feels like something is trying to exceed that cap. Have you attempted to spawn with larger memory? Might at least produce additional debug information.

Yes, you can delete old error files. I'm unlikely to dig through 70Gb of text ;0

**Comment by s041629** [comment]
what I don't understand is I haven't changed anything in my R (no new packages or anything) and I was working on a single notebook (which I had been working on for the whole day)

**Comment by tatarsky** [comment]
All I can see is your kernel is crashing in that particular one. 

If you wish to debug further I guess I'd fire up one in a larger memory and do some profiling on it.

I did notice when I was looking at the node it appears other users are using your R install. And that the permissions on your R install are wide open. Is it possible that other things have been added by those others? By accident or something? 

```ls -al /home/matteo/software/R-3.2.2/lib64/R           
total 84
drwxrwxrwx  10 matteo users  4096 Nov 13  2015 .
drwxrwxrwx   4 matteo users  4096 Nov 13  2015 ..
```
Sample folks using your R:

```
fl-n-1-8: mdonovan 25097  0.0  1.0 1892556 1346764 ?     Ssl  Feb28   6:26 /home/matteo/software/R-3.2.2/lib64/R/bin/exec/R --slave -e IRke
```
```
fl-n-1-1: bill     27936  0.0  0.7 1360064 1020812 ?     Ssl  Feb22   0:55 /home/matteo/software/R-3.2.2/lib64/R/bin/exec/R --slave -e IRkernel::main() --args /frazer01/home/bill/
```

Perhaps check that the tree has no recent additions?

**Comment by tatarsky** [comment]
Remember BTW that the way the spawner works is that a SINGLE hub job handles all your notebooks per spawn. So if there is a leak or something you could see it down the road as it were.

You can check on memory use of its subshells over on a node. 

For example one of your hubs is on fl-n-1-1. And I can see that your kernel is fairly high memory:

```
matteo    8979 87.6 19.3 25971572 25554548 ?   Ssl  08:46  12:28 /home/matteo/software/R-3.2.2/lib64/R/bin/exec/R --slave -e IRkernel::main() --args /frazer01/home/matteo/.local/share/jupyter/runtime/kernel-ac075077-8b99-4048-956b-b52458126022.json
```
```
 ps aux|grep R
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
matteo    8979 75.2 19.3 25971712 25555188 ?   Ssl  08:46  12:28 /home/matteo/software/R-3.2.2/lib64/R/bin/exec/R --slave -e IRkernel::main() --args /frazer01/home/matteo/.local/share/jupyter/runtime/kernel-ac075077-8b99-4048-956b-b52458126022.json
```

Viewed with another tool:
 
```
PID    TID  MINFLT  MAJFLT  VSTEXT   VSLIBS   VDATA  VSTACK   VSIZE    RSIZE   PSIZE   VGROW   RGROW   SWAPSZ  RUID      EUID       MEM   CMD       1/33
 8979      -  5363e3       0      4K   46936K   24.4G    272K   24.8G    24.4G      0K   24.8G   24.4G       0K  matteo    matteo     19%   R
```

**Comment by s041629** [comment]
now jupyter hub works fine (I haven't modified anything)

**Comment by tatarsky** [comment]
Nor have I.

**Comment by s041629** [comment]
I will ask them, but I don't think they installed anything new on Friday afternoon

**Comment by tatarsky** [comment]
What spawner BTW did you select (the choice list when you first start a hub). Looks like a larger one.

**Comment by s041629** [comment]
8 cores, 32 GB

**Comment by s041629** [comment]
(I had tried also with 128 GB on Friday and the kernel kept on crashing anyway)

**Comment by tatarsky** [comment]
If you have a job id for that I can look in your output files. 

The one I saw crashing Friday had 4G and 1 thread. 
```
acct -j 5257882
category     -l h_vmem=4G,juplow=TRUE -pe jupsmp 1```
```

Which means h_vmem would have killed it at 4GB of ram use. Which it seemed to do so when it tried to "get 7GB" if that makes sense.

The ones I see this morning have 8 threads with 4G. But that is an SMP slot so you really get up to 32GB.
```
hard resource_list:         juphigh=TRUE,h_vmem=4G
parallel environment:  jupsmp range: 8
```

And I show SGE feels you are consuming a peak of 24GB.

```
usage         1:            cpu=00:12:32, mem=9084.28625 GB s, io=0.91986 GB, vmem=24.436G, maxvmem=24.436G
``

**Comment by tatarsky** [comment]
On Friday I also show a few hitting 32GB and being killed. Still looking for a 128GB.
```
5257881
-l h_vmem=8G,juphigh=TRUE -pe jupsmp 4
maxvmem      32.013GB
failed       37  : qmaster enforced h_rt, h_cpu, or h_vmem limit
```
So something is consuming enough to kill a 8 x 4GB.....

**Comment by s041629** [comment]
what I don't understand is why it needs that much memory to start.
And jupyter lab (I don't care much about it right now, as long as jupyter hub works) still doesn't let me do anything with 32 GB (or 128)

**Comment by tatarsky** [comment]
I'd have to dig around for ways you could profile your R kernel memory usage. 

But its definitely asking for a pretty good sized chunk of ram. 

Sorry I cannot locate a 128GB request on Friday. But the bottom line is its probably worth more time to try to figure out what R is doing with all that ram.

**Comment by billgreenwald** [comment]
Hey paul, I worked with matteo this morning, quick update:

It seems to be a lab problem, not a labhub problem.  When we swap the lab launcher to the classic notebook from the help menu, the problem goes away.  If we then leave the kernel running and open it in the lab, the kernel runs fine.  Matteo is using this workaround for now.

This is also a reported problem, so I am reaching out to check with them on how to fix it.

IN the mean time, matteo and I are going to compare irkernel versions, to see if I am using his R but a different version of the irkernel, and we can see if that fixes it.

Additionally, it seems to me like a workspace loading problem; as soon as the kernel launches thru the lab side, it reserves 8 GB of ram and starts loading; not sure how to fix this or why it only happens lab side.

**Comment by tatarsky** [comment]
Interesting. 

So all I was going to see was if you can issue R memory commands such as `memory.profile()` you might see at least what part of R was grabbing all that. And then I believe there are modules you can load to further drill down into what library item might be doing so. I don't do much R. 

But perhaps something in the launcher is _telling_ it to do this in some way is what you seem to be saying. Do you have a link to the report you mention? 

I'll poke about the lab side settings if there is something obvious in its memory settings.

**Comment by s041629** [comment]
I removed .rData and everything now works fine

**Comment by tatarsky** [comment]
Whoa. What was in that file?

**Comment by s041629** [comment]
I had saved a previous session, otherwise it would have taken more than one hour to re-produce the data. It was more than 20 GB of data and (I still don't know how and haven't found a satisfactory explanation online) every time I would start my R (in a notebook of through the terminal) it would first load this data, which took a long time.
Now I simply re-saved a new empty .Rdata and the problem is solved

**Comment by tatarsky** [comment]
That is very very interesting. Thanks for the detailed description as I'll add it to the "things to check" list.
