### ISSUE TITLE
Rack CC36 has lost power for important parts of it. OUTAGE 

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#239]
I am not sure at the moment what is going on but I have gotten several alerts.

I am trying to get on a system.

@hirokomatsui if you have any information about outages let me know.

**Comment by billgreenwald** [comment]
Just checked an ssh. Seems like our connection is still available, but is
slow.

**Comment by billgreenwald** [comment]
Unworkably slow

**Comment by tatarsky** [comment]
We appear to have lost a chunk of the rack. I cannot even get into the environment at all.

I have emailed @hirokomatsui to contact SDSC for any issues in progress.

**Comment by hirokomatsui** [comment]
It possibly only our cluster or around.
Our old cluster and IGM servers are fine which are located on the other side of the co-location.
Retina project server's fine as well which in the rack close to our new cluster.
I'll ask SDSC if anything's happening. They were working on UPS yesterday and should be done for now.

**Comment by tatarsky** [comment]
I just opened a ticket to them. Both the 1G and 10G switch are not reachable. It looks like some kind of issue in CC36.

**Comment by hirokomatsui** [comment]
That's right. Thanks

**Comment by tatarsky** [comment]
The campus links to the head nodes are functioning but the backend network is gone.

**Comment by hirokomatsui** [comment]
I see this on flh2 but flh1:

Message from syslogd@fl-hn2 at Mar 29 09:59:20 ...
 kernel:BUG: soft lockup - CPU#7 stuck for 22s! [socknal_reaper:17549]

**Comment by tatarsky** [comment]
Yeah the kernel is quite angry it can't reach the lustre servers. Because there is no link.

**Comment by tatarsky** [comment]
No response from SDSC yet.

**Comment by tatarsky** [comment]
Attempts to talk to things from the old rack (KK36) show dead air. So without somebody in front of the CC36 rack not much I can tell you at this point. Feels like power has been lost or both switches failed. (Which seems unlikely)

**Comment by hirokomatsui** [comment]
That sounds unlikely. I'll wait a bit for SDSC's response.

**Comment by tatarsky** [comment]
Agreed.

**Comment by tatarsky** [comment]
No response still. Can try to call. But its looking like a visual is going to be needed if they aren't responding.

**Comment by tatarsky** [comment]
Tim is going to look.

**Comment by tatarsky** [comment]
We have lost power in some way that has brought down large chunks of the rack (CC36)
Tim is looking in more detail if its the PDU or something else but probably going to require some cleanup help and further evaluation @hirokomatsui

**Comment by hirokomatsui** [comment]
I'm heading there soon.

**Comment by tatarsky** [comment]
He's trying to find what has failed. The breakers did not trip. But most of the gear is dark.

**Comment by tatarsky** [comment]
Advise when you get there. I believe we will need to reset a head node so I can at least see what damage has been done.

**Comment by tatarsky** [comment]
PDU failure. Tim has done something to restore power. I am asking for fl-hn2 to be reset as its wedged and I need some way to diagnose any impact of this hard bounce. No ETA

**Comment by tatarsky** [comment]
I'm keeping notes here to try to understand the root cause of the impact of a failed PDU.

The Lustre systems did not go down. All are dual PSU.
Nodes did not go down. All are dual PSU. 
Looking at the array logs.

**Comment by hirokomatsui** [comment]
Seems like Tim's done it. Do you want to me reboot flh1? It looks fine for now.

**Comment by tatarsky** [comment]
No leave flh1 alone. I am trying to determine the root cause of that much impact.

Can you tell me if the 10G switch (the one with the SFPs) has dual power supplies? It doesn't want to talk to me at the moment to query it.

**Comment by hirokomatsui** [comment]
10G switch has dual power supplies.

**Comment by hirokomatsui** [comment]
DELL N4032F

**Comment by tatarsky** [comment]
Yes and it never went down either.

**Comment by tatarsky** [comment]
I suspect the 1G switch has only a single power supply. Can you confirm that?

**Comment by tatarsky** [comment]
I confirmed from the CLI.

**Comment by hirokomatsui** [comment]
Can't see power cables. It's N1548

**Comment by tatarsky** [comment]
So that is our issue I believe. It does show it reset when power was lost. And it does perform many critical functions so we should see if we can improve that. Its out first power outage in this rack. The 10G switch claims its been running for > 800 days. Since basically deployment.

**Comment by hirokomatsui** [comment]
Yap, it has a single.

**Comment by tatarsky** [comment]
OK. I will see if we can fix that. We don't want that much impact from a PDU outage.

**Comment by tatarsky** [comment]
If you see any fault lights on anything while there advise. I believe all dual PSU items remained fine.
Might ask Tim on the way out what happened to the PDU. Just so we can be prepared if this is going to happen again.

**Comment by hirokomatsui** [comment]
Everything looks fine. I'm heading back to my office.

**Comment by tatarsky** [comment]
the ZFS box went down. Can you see if when it was racked that both power supplies were placed into the same PDU?

**Comment by tatarsky** [comment]
Oh sorry, next time!

**Comment by hirokomatsui** [comment]
I'm still here

**Comment by tatarsky** [comment]
Might be worth checking that ZFS box power cords. I suspect they are both going to the same PDU....as it also went down.

**Comment by hirokomatsui** [comment]
You mean fl-oss-1-1 and 2, which are right above the PDU?

**Comment by hirokomatsui** [comment]
Both power cables go into the right side of the outlets.

**Comment by tatarsky** [comment]
No, I mean the box we do backups to. fl-nas1.

**Comment by tatarsky** [comment]
I can try to turn on some lights on its drives....

**Comment by hirokomatsui** [comment]
Oh, the Microway

**Comment by tatarsky** [comment]
No, I have it as a Supermicro we ordered. Should have LOTS of drives.

**Comment by tatarsky** [comment]
I tried to make it blink ;)

**Comment by hirokomatsui** [comment]
I got it the one we've bought later. Both of the two power cables go into the same left side or outlets.

**Comment by tatarsky** [comment]
We should have those into different PDUs

**Comment by tatarsky** [comment]
Can you move one to an open port on another one?

**Comment by hirokomatsui** [comment]
There are two PDUs on both sides they are labeled as PDU1 and PDU2. Right now the two cables go to left side of PDU2. Can I switch the one to the left side of PDU1?

**Comment by tatarsky** [comment]
Yes. I believe so.

**Comment by tatarsky** [comment]
I am asking AHPC about getting a secondary PSU for the 1G switch. Its not a common thing in those units but I will ask.

**Comment by tatarsky** [comment]
I would also like to get a 10G connected SGE spool server. I'll talk to you about ways we could do this.

**Comment by tatarsky** [comment]
Ah and that 1G switch uses a weird method to get a second PSU. Thats why it doesn't have one.
We'll talk about this as well.

**Comment by hirokomatsui** [comment]
Anything else I can do here?

**Comment by tatarsky** [comment]
No I think thats it. We have one weak spot and it got hit today after 884 days of power being fine.
We can decide if we want to make that weak spot stronger (the 1G switch). 
Might ask Tim if he thinks the PDU will "do this again". He didn't say what happened.

**Comment by hirokomatsui** [comment]
I did not hear any either, but am guessing something happened since they did UPS maintenance yesterday.

**Comment by tatarsky** [comment]
I have two items we can discuss to make it even less likely a single PDU failure would make a mess. The fact all the dual PSU stuff didn't go down is great but our single PSU item (1G switch) made too much impact with it going down. I can explain what we can improve even if we don't have an issue for another 900 days. I'll send an email with some suggestions. I'm asking what the odd "external" PSU costs for that 1G switch we have.

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
Thanks for your help!

**Comment by tatarsky** [comment]
@joreynajr BTW if you wish to clear the error bit on some of your jobs that look like this:
```
5271486 0.47325 job_SAMEA2 joreyna      Eqw   03/29/2018 07:39:10                                    8        
```
You can issue: `qmod -cj (jobid)`

They are probably in that state from the long pause.

`qstat -explain a -j (jobid)` might tell you more.

**Comment by tatarsky** [comment]
I order an RPS-720 to see what all I get. Closing this and will work with @hirokomatsui when I get the part and decide its worth deploying.
