### ISSUE TITLE
account with limited directory access

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#242]
We have a collaborator who want to upload their data on our cluster.
Is it easy to create a user account who has a writing permission and access only under the home directory/or a specific directory?
If not (if we have to install some service or etc), I'll just give them a full access account temporarily.
Thanks!

**Comment by tatarsky** [comment]
We had a guest account IIRC that used the built in features of SSHD to do that. Let me go find it. I emailed about it awhile back.

**Comment by tatarsky** [comment]
Ah here we had this going. Would that work? It uses the chroot feature.
```
# Support Upload
Match User frazerguest1
     ChrootDirectory /frazer01/home/sftp
     AllowTCPForwarding no
     X11Forwarding no
     ForceCommand internal-sftp
```

**Comment by tatarsky** [comment]
I have to re-enable it if you DO want that BTW and since it used SSH remember at the moment we are firewalled now for SSH to limited UCSD ranges unless you give me an external range.

**Comment by hirokomatsui** [comment]
That's right. I'll ask them their IP.

**Comment by tatarsky** [comment]
Do you want them to go to `fl-hn1` or `fl-hn2`? Only matters for where I re-enable and make the iptables allow.

**Comment by hirokomatsui** [comment]
Either one's fine. We'll let them upload the files on Luster.

**Comment by tatarsky** [comment]
OK. I will add it to fl-hn2 in a moment and if you have the password you can test. When they provide a source IP we can allow that and have them test. Feel free if it helps to just cc me on an email to them.

**Comment by tatarsky** [comment]
OK. Re-enabled. Be aware that in that dir is something from a past upload. Don't know if you care but mentioning.
```
[root@fl-hn2 sftp]# pwd
/frazer01/home/sftp
[root@fl-hn2 sftp]# ls -al
total 12
drwxr-xr-x  3 root users 4096 Apr 20  2016 .
drwxr-xr-x 24 root root  4096 Apr  2 10:39 ..
drwxrwxr-x  2 root users 4096 Jan 18  2017 vteexome_meta_analysis
```

**Comment by tatarsky** [comment]
Done!

**Comment by hirokomatsui** [comment]
Can you set the account to re-use? We want let a person to upload files to Luster.
Is it possible with no IP address limit, and user/password as you pick.
Thanks!

**Comment by tatarsky** [comment]
The account is frazerguest1. It is setup with the prior password although I do not remember it.
Its only on fl-hn2. 

No IP limit however means "no IP limit on SSH in general on fl-hn2".

I can remove that limit for a period of time but if they could provide a range they are coming from it would be far safer with all the brute forcing.

I can make it a very wide range though. If they go to https://www.whatismyip.com/ for example I can add the range for any IP they come from.

If you do want SSH "permit from any" just confirm and perhaps when uploaded we can remove that again.

**Comment by tatarsky** [comment]
If you don't remember the password BTW I can just reset it and email you.

**Comment by hirokomatsui** [comment]
Can you reset the password, any random strings would be fine. And the limit for a period for 3 months.
Thank you!

**Comment by tatarsky** [comment]
OK. 
Steps coming to your email.

**Comment by tatarsky** [comment]
Confirmed working. Will revisit in 3 months!
