### ISSUE TITLE
fl-oss-1-1 has lost a SAS path because HBA card failed

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#244]
For reasons unclear fl-oss-1-1 is not running both SAS paths. I got an alert about it this morning.
Thats not overly good. I will try to ask SDSC if they can eyeball the SAS cables in case one got bumped.

**Comment by tatarsky** [comment]
We probably have a failed HBA card. We'll discuss on Monday the repair process.

**Comment by tatarsky** [comment]
Confirmed we have a failed HBA card. Will open a AHPC ticket to see if warranty covered or will ask for order to replace.

**Comment by tatarsky** [comment]
Unit has `2 x LSI 9300-8e External 12Gb/s SATA/SAS Host Bus Adapters`. One is not showing on the PCI-E bus so its probably died.  Cost used $328 as its EOL from Avago. 

Lets see if we get one for free as part of warranty.

**Comment by tatarsky** [comment]
Ticket opened with AHPC (1010374). I believe we are under 3 year support. Which BTW we should add to our discussion as we are I believe coming up on that quickly.  (Cluster was deployed 11/2015)

**Comment by hirokomatsui** [comment]
Thanks for catching this up. We'll wait for AHPC answering.

**Comment by tatarsky** [comment]
They are working on timing. We might take a maint window at the same time but I believe I can fail things over gracefully to the other server if we cannot.

**Comment by tatarsky** [comment]
AHPC has the card in stock and can replace anytime we want. Do we want to do this ASAP? Might be safest to have the filesystem quiet or even unmounted. @hirokomatsui what is the compute load coming up this next few days?

**Comment by hirokomatsui** [comment]
We want to do that ASAP, and wait to run a large jobs. Can you ask them how long it will take?

**Comment by tatarsky** [comment]
Yep. I can ask. Its a PCI-E card replacement so the server needs to come all the way down. I can see if I can fail over to the other system starting now.

**Comment by tatarsky** [comment]
I have confirmed I can failover all the LUNS to the other server for the replacement.  So we do not have to umount. 

But I'm holding for a confirm they intend to get here either today or tomorrow.

**Comment by tatarsky** [comment]
AHPC can do the swap tomorrow. No time yet but I will fail over some additional targets in the morning. I did half of them.

**Comment by hirokomatsui** [comment]
Thanks. We'll be keep using the system, but only waiting for a large jobs to be submitted in the case.

**Comment by tatarsky** [comment]
We are scheduled for 11:00AM tomorrow. Cesar@AHPC will come do the work per the terms of our support (onsite). I will migrate the rest of the mounts before that. Probably first thing in the morning.

**Comment by tatarsky** [comment]
All OSTs are failed over to the other server. Expect reduced performance but should be functional while the work is done.

**Comment by tatarsky** [comment]
AHPC is onsite working on the unit. It is shutdown and they are unracking it.

**Comment by tatarsky** [comment]
HBA fixed (replaced that is). Will failback OSTs in a moment after some checks. There will be a pause when that happens.

**Comment by tatarsky** [comment]
Failback complete. Lustre running on both OSS servers again. Multipaths are green. Closing.

**Comment by hirokomatsui** [comment]
Thank you!

**Comment by tatarsky** [comment]
You are very welcome.
