### ISSUE TITLE
remove cn17 from SGE nodes

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#245]
The node is not responding. We'll just let it die. Can you remove it from SGE management?

**Comment by tatarsky** [comment]
Yep. I was trying to get on it since the alerts this morning.

**Comment by tatarsky** [comment]
I've disabled it in SGE. I'll send it a reset just in case it comes back and it was just life but I suspect the older nodes are going to start dropping off as they continue to age.

**Comment by tatarsky** [comment]
Note: I will NOT re-enable it in SGE. Just curious if it comes back.

**Comment by hirokomatsui** [comment]
It looks like restarted some minutes ago. Some jobs will go on the node, I'll see how it goes.

**Comment by hirokomatsui** [comment]
Oh, OK. I did't see your last two comment.

**Comment by tatarsky** [comment]
I'm looking at its error logs. I am concerned its going the way cn8 went....

**Comment by tatarsky** [comment]
It was having considerable trouble dealing with the memory requests of a STAR process. But it seemed upset by access to disk swap. Unsure if hardware involved. You make the call if you want it back in the pool but I won't be shocked if its failing in some way.

**Comment by tatarsky** [comment]
No obvious signs of components failing but some log entries for one of the fans in the unit possibly failing. The IPMI error message is not clear and does not tell you which location fan. Older Supermicros don't give you much that way. Up to you. As of now it remains out of SGE.

**Comment by tatarsky** [comment]
Still leaving it out of SGE. But running a memtester for the weekend to see if it has issues.

**Comment by tatarsky** [comment]
NO memtester issues. Might have just been overloaded with something. Can leave out/retire or put back in. We have a record (now) it did this once. Perhaps "one more strike".
