### ISSUE TITLE
June projects for me

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#246]
This is a Git version of the email I sent to kelly and @hirokomatsui just for information and to warn of some periods to expect reduced response levels. 

I will be in the Bay Area and then the Seattle Area for a few weeks.

Starting tomorrow 6/5 I will be driving to the Bay Area. I will be taking some small vacation and handling some family matters during that time. Expected reduced response during this time. 

I will be in the Bay Area 6/10 -> 6/19. Working on some upgrades for a firm there. I will however have solid Internet so I will respond if not dealing with that project. 

On 6/20 I will head north and be attending my little sisters wedding in the Seattle area. Then the 25th I will starting heading home to resume a regular summer schedule. Expect some reduced response during this period. 

Thanks!

**Comment by hirokomatsui** [comment]
I got it. Have a nice trip and great vacation!
Thanks,
Hiroko

**Comment by tatarsky** [comment]
And this road trip is now done. 6195 miles.
