### ISSUE TITLE
Ipython Notebook Problems

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#25]
@cdeboever3  and I are having trouble with launching jupyter notebooks- although we can connect to the jupyter interface when you try to create a notebook from here it will fail with this error: 

[I 16:20:36.143 NotebookApp] Creating new notebook in 
[E 16:20:36.150 NotebookApp] Error while saving file: Untitled.ipynb disk I/O error
    Traceback (most recent call last):
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 387, in save
        self.check_and_sign(nb, path)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/nbformat/sign.py", line 246, in sign
        self.store_signature(signature, nb)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/nbformat/sign.py", line 249, in store_signature
        if self.db is None:
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 439, in **get**
        value = self._validate(obj, dynamic_default())
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/nbformat/sign.py", line 127, in _db_default
        self.init_db(db)
      File "/frazer01/home/djakubosky/software/anaconda/lib/python2.7/site-packages/nbformat/sign.py", line 139, in init_db
        )""") 
    OperationalError: disk I/O error
[W 16:20:36.157 NotebookApp] Unexpected error while saving file: Untitled.ipynb disk I/O error

I am not sure if this something related to luster or web interface -currently have modified the ~/.ipython/profile_default/ipython_config.py to store our history database in temp like so:

uncommented this
c.HistoryManager.hist_file = u'/tmp/djakubosky_ipyhist.sqlite'
- note that I can make text files but not notebooks (.ipynb) from the web interface.

**Comment by cdeboever3** [comment]
My anaconda environment looks like this:
/repos/environments/anaconda/cardips.yml. I've documented how we set up the
notebook environment here:
https://github.com/frazer-lab/cluster/wiki/Installing-software#jupyter-notebooks.
We also had to make a change to IPython's command history db that is
detailed in the section above.

**Comment by tatarsky** [comment]
If its sqlite format I need to remount /frazer01 on HN1 with POSIX locks supported. Sqllite when used with Lustre must use flock I believe which by default is not available on Lustre.

This would require everybody off HN1 I believe although I will check if I can remount without umount. 

Alternately, I have already done this on HN2 if you want to test over there to confirm.

**Comment by tatarsky** [comment]
"not available" should have read "not enabled for performance reasons"

**Comment by tatarsky** [comment]
And I am reviewing the relative level of those performance reasons if its just on the head nodes. Do you intend to store/use Sqllite on Lustre from the nodes?

**Comment by tatarsky** [comment]
To be more clear on the above: 

Will sqlite databases be simultaneously accessed from multiple nodes? Or just from one node aka the head node?

There are two lock options, one intended for access from multiple nodes, one from a single one:

"Lustre supports posix locking semantics and usually Lustre clients are mounted with "-o flock" option to have cluster wide locking consistency. If you know that multiple processes on same client node will be writing to a file (instead of processes on different client nodes) then consider mounting Lustre client with "-o localflock" instead of "-o flock". This will reduce amount of RPCs sent to MDS for Lustre operations. "

I believe for your current needs `-o localflock` is the correct option. 

But I will I believe need to kick folks off to remount with either option.

**Comment by tatarsky** [comment]
This setting also appears to be correct if we want to store Mysql databases on Lustre. So we should probably schedule a time to add the option to the mount. I do not appear to be able to do a remount in my test on HN02. So we'd have to kick folks off for a few seconds. Running jobs should not be impacted.

**Comment by cdeboever3** [comment]
> Alternately, I have already done this on HN2 if you want to test over there to confirm.

I'm able make a notebook correctly on hn2.

> Will sqlite databases be simultaneously accessed from multiple nodes? Or just from one node aka the head node?

I'm not sure. If the only database is the IPython history database, we are currently storing that on the local disk. We will definitely launch notebooks from both head nodes and its conceivable we may want to launch from the compute nodes although that's not in any current workflow that I know of.

> This setting also appears to be correct if we want to store Mysql databases on Lustre. So we should probably schedule a time to add the option to the mount. I do not appear to be able to do a remount in my test on HN02. So we'd have to kick folks off for a few seconds. Running jobs should not be impacted.

Let's try that then. I can coordinate a time to make sure everybody is logged off if you like.

**Comment by tatarsky** [comment]
Basically lets start with the `localflock` as I'm going to be surprised if the same sqlite datafile is shared between all thoes nodes. But if we need it we can switch to `flock`. Here's another description of the options:

 flock  Enable full flock support, coherent across all client nodes.   (aka multiple nodes talking to the same file assuming the code can handle it)

localflock  Enable  local  flock  support,  using  only  client-local  flock (faster,  for  applications that require flock but do not run on multiple nodes).

Pick a time and I'll do the remount.

**Comment by cdeboever3** [comment]
I'll coordinate a time tomorrow.

**Comment by cdeboever3** [comment]
Does having everybody off flh1/flh2 4-5pm PST today work for you Paul?

**Comment by tatarsky** [comment]
Yes.

**Comment by tatarsky** [comment]
Remounted. Please re-test ASAP in case I need to try a different method.

**Comment by cdeboever3** [comment]
I can access notebook servers and start notebooks from both head nodes so
that seems to have solved this.
