### ISSUE TITLE
flh2 frozen

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#250]
Hi Paul,

I accidentally used subprocess.Popen instead of subprocess.call in python and launched 246 simultaneous instances of samtools.

Flh2 is unreachable so no one can kill my tasks.  If you can kill everything running on my username, could you? And if you cannot, can you issue a reboot for flh2?  Everyone is fine with a reboot happening.

Thanks

**Comment by tatarsky** [comment]
I'm trying to reach the unit as well.

**Comment by billgreenwald** [comment]
no one can log in from here which is why hiroko suggested sending a reboot signal

**Comment by tatarsky** [comment]
Yeah, I require access as well to reboot a server.

**Comment by billgreenwald** [comment]
Any other options?

**Comment by billgreenwald** [comment]
can you send a reboot to flh2 from flh1?

**Comment by tatarsky** [comment]
Bill, I'm working on it.

**Comment by tatarsky** [comment]
IPMI reset sent. Took awhile to get a shell to do so. Unit will reboot now.

**Comment by billgreenwald** [comment]
Thanks.  Sorry didn't mean to pester, just felt bad that i bombed it for everyone.

**Comment by tatarsky** [comment]
Its OK. I was just waiting for my shell to return a prompt. I'm not sure what the dependency was delaying it.

**Comment by tatarsky** [comment]
Unit is hanging in BIOS for reasons unclear. Will be down until I determine why.

**Comment by tatarsky** [comment]
@hirokomatsui this may require a console trip. I will let you know if I cannot solve it from the KVM.

**Comment by tatarsky** [comment]
Unit is not fully passing POST. Its reporting a bad DIMM. P2-DIMMG1. Its going to have to sit for a bit to see if it can get past that otherwise I suspect that DIMM needs to be pulled. I can probably get some Ops help but we'll also issue a warranty request to AHPC. 

Unit is down until further notice.

**Comment by tatarsky** [comment]
Opening ticket with the SDSC ops to see if they have time to pull that DIMM. Otherwise may require @hirokomatsui to pay it a visit. Attempting to triage `fl-hn2` dependencies.

**Comment by tatarsky** [comment]
No response from SDSC. @hirokomatsui if you can I would head over to SDSC and attempt to remove the DIMM I list in the ticket with them. If you need my help doing so we can Facetime or something. Unit will not pass POST.

**Comment by hirokomatsui** [comment]
I see flh2's back. Maybe they just did.

**Comment by tatarsky** [comment]
No. You are seeing my stealing the IP to reduce the impact of it being down.

**Comment by tatarsky** [comment]
Puppet is pushing out non-balanced references to fl-hn1/fl-hn2 (the two head nodes act as shared sources of some internal services)

**Comment by tatarsky** [comment]
opt.q down until its NFS access via fl-hn2 restored. Not going to move that.

**Comment by tatarsky** [comment]
Virtual IP removed from fl-hn1 following confirm all puppet config files appear to be out there. 

When fl-hn2 is repaired/DIMM pulled I'll restore the other services and the load balancing.

**Comment by hirokomatsui** [comment]
Sill you don't hear from SDSC?

**Comment by tatarsky** [comment]
Sadly no. I guess you could call first. They responded to the ticket only with "We've seen the ticket" automation. Forward that email in case you don't get automatically cc'd.

**Comment by tatarsky** [comment]
I tried again BTW to bring it up just in case the electrons had settled down. It hangs in the same place after the warning of P2-DIMMG1 failing. Turning it back off.

**Comment by hirokomatsui** [comment]
I'm not sure what exactly we need to do.
Do we open flh2's chassis and pull the DIMM card out?

**Comment by tatarsky** [comment]
Yep. Bearing in mind its going to be a bit tricky to find this "G1" slot. Hopefully its painted on the motherboard but I often find them written in stunningly hard to read locations. 

If not comfortable with it we can open the ticket with AHPC instead. But they won't be likely to get there until next week. 

Or we can wait for SDSC ops to respond. We are still running but these items are down for now:

the older Jupypter Hub.
The CN nodes. (old) and the opt.q

**Comment by tatarsky** [comment]
Oh, and other method is I've done a few Facetime server surgeries. I don't know if you have an iPhone though. Or Skype works. I can usually spot the DIMM label if there is enough light. Up to you. I'm around for a bit more.

**Comment by hirokomatsui** [comment]
Can you open a ticket with AHPC?
I think there're no body in the SDSC operation room since we don't get any response. I need someone's help to pull flh2 out anyway.

**Comment by tatarsky** [comment]
OK. I'll open a ticket.

**Comment by hirokomatsui** [comment]
I got someone to go there together. Will call from my cell.

**Comment by tatarsky** [comment]
Cools. Ticket opened as well though!

**Comment by tatarsky** [comment]
I've turned off `fl-hn2` and am trying to find a motherboard manual quickly on the Supermicro site.

**Comment by tatarsky** [comment]
So if looking down on the motherboard from the top with the back of the computer facing away from you. It appears that the DIMM reporting in error is located toward the top right of the board. Circled here in yellow. 

![p1](https://user-images.githubusercontent.com/6439722/43667519-d9e09762-973d-11e8-8941-cb7d9ee12944.png)

**Comment by tatarsky** [comment]
Replacement DIMM coming Monday. Unit left down until that time.

**Comment by tatarsky** [comment]
Vendor coming at 10AM or so. Will diagnose and hopefully have unit back shortly.

**Comment by tatarsky** [comment]
Memory swapped. Unit rebooted. Services back online I believe. Working on opt.q re-add.

**Comment by hirokomatsui** [comment]
It's so quick. Thank you!
