### ISSUE TITLE
Full power loss SDSC all units in recovery as a result ETA unsure

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#253]
As of a few minutes ago I don't see connectivity to any of your systems. I'm assuming some sort of upstream network matter. 

flh1, flh2 and flc all appear down. 

I'm listing this here to state any information would be useful. I'll scan the usual status areas for SDSC.

Note I am checking from UCSD networks (Idekerlab) and other locations.

**Comment by tatarsky** [comment]
Well now I don't have Idekerlab connectivity either. So something exciting going on somewhere!

**Comment by billgreenwald** [comment]
Its down from (physically) inside as well at UCSD campus.

**Comment by tatarsky** [comment]
Thanks @billgreenwald. I can see little islands of things but seems like something central is sad. 
No notice yet on status.sdsc.edu or the internal Sysadmin-L mailing list. If I get further information I'll let folks know.

**Comment by billgreenwald** [comment]
I'll retry every 10-20 minutes as well and let you know if anything changes on our end

**Comment by tatarsky** [comment]
SDSC Outage Notification – Power Outage – 30 Aug 2018, 08:15

Events, Incident Notification

08/30/2018

A general power outage occurred this morning, Thursday 8/30/2018, at SDSC around 8:15 AM PT. Partial power was restored to the building at 8:45 AM but some outages remain.

The cause is being examined. Some services may have been interrupted. Operations is looking into the power issue and engineers are identifying affected services and restoring them.

Updates will be posted here. Please email support@sdsc.edu for any urgent issues. Apologies for the inconvenience.

**Comment by tatarsky** [comment]
http://status.externsdsc.org/2018/08/30/sdsc-outage-notification-power-outage-30-aug-2018-0815/

**Comment by tatarsky** [comment]
I show power coming back but our rack lost power. It will be a bit before I start all services again. I want to make sure everything is back on safely first.

**Comment by tatarsky** [comment]
Lustre is in recovery. NO logins until that completes hopefully without incident. All systems lost power completely.

**Comment by billgreenwald** [comment]
I see it back up, but the directory tree isn't linked properly

**Comment by tatarsky** [comment]
Lustre is in recovery. Thats a very serious situation in which the entire filesystem is scanned following it dropping all the way to a reboot due to complete power loss. I will provide updates as it continues. But its going to be awhile.

**Comment by billgreenwald** [comment]
Do you have a ballpark estimate of how many hours we are looking at?  People in the lab are trying to plan the best way to spend our work time :)

**Comment by tatarsky** [comment]
At the moment I have no ETA. This full power loss at SDSC had made a mess. I'm doing my best to clean it up. P

**Comment by billgreenwald** [comment]
Sounds good, thanks for looping us in and i hope its not too bad in the long run

**Comment by tatarsky** [comment]
I am pleased at least I have all the servers running. I don't have that with other groups at SDSC. So at the moment you have that going better than others. I am dealing with about 50 systems impacted by this. I've lost about 6 it appears.

**Comment by tatarsky** [comment]
Status update: metadata target now in recovery. Was having issues getting it to mount.

**Comment by tatarsky** [comment]
I am showing some signs of recovery completing. I'm not quite ready to mount but thats a good sign.

**Comment by tatarsky** [comment]
The data OSTs are out of recovery and I'm triggering the MDT (Metadata) recovery now. I don't have a precise ETA but I believe that goes fairly quickly if all goes well.

**Comment by tatarsky** [comment]
FYI from status update

Update 8/30/2018 10:00 AM PT:

A general power outage occurred this morning, Thursday, 8/30/2018, at SDSC around 8:10 AM PT. Power was restored by campus FM around 9:40 AM PT.

Individual systems in the data center may need to be powered back on if they were affected by the outage. Generator-backed systems should have remained powered throughout the outage, but UPS systems would have lost power around 8:40 AM PT when battery power was depleted.

Please contact colosupport@sdsc.edu for assistance with powering on colocated systems or any other outstanding colocation service issues.

Please contact support@sdsc.edu for any outstanding managed service issues.

The cause is being examined, but the initial diagnosis from campus FM is a transformer failure and a flaw in switching gear. We are continuing to investigate with FM to address any potential future issues before they occur.

**Comment by tatarsky** [comment]
I am mounting the filesystem but I'd ask folks please wait a bit before running jobs. I still have things to do.

**Comment by billgreenwald** [comment]
I'll let people who dont follow this to know not to run jobs

**Comment by tatarsky** [comment]
I will disable the queues as well. Just trying to do lots at the same time.

**Comment by hirokomatsui** [comment]
Thanks Paul for dealing with this. I'm having some trouble on IGM servers as well, and doubting if SDSC got power back fully.
Please keep post it if you hear anything.

**Comment by tatarsky** [comment]
The only data I have is from this page. This was a full drain of all power (including UPS). So many systems are physically off. I'm able to turn on Frazer cluster systems via what is called IPMI but I know many servers do not have that. 

http://status.externsdsc.org/2018/08/30/sdsc-outage-notification-power-outage-30-aug-2018-0815/

**Comment by tatarsky** [comment]
Attempting to restart hubs.
Mysql will also need to be checked and restarted.

**Comment by tatarsky** [comment]
Hubs should be running. Queues enabled. Still cleaning up some old nodes that are sad. 
Report missing items here so I don't miss them.

**Comment by tatarsky** [comment]
At this time I believe all services are running as expected. If they are not, please tell me what so I can make a Nagios check for it. Thanks for the help during this major SDSC event.
