### ISSUE TITLE
Lost a drive in node 6

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#254]
Disabled the queue on it. Will open ticket with AHPC.

**Comment by tatarsky** [comment]
I am suspending this node to allow us to prepare for replacement soon.

**Comment by tatarsky** [comment]
Forgot to put the ticket number in here. 1011018
Just waiting for the replacement drive to show from the manufacturer.

**Comment by tatarsky** [comment]
Ah, and speak of it and it gets delivered. We are working on a tomorrow swap. I am leaving the node out of SGE just in case I need to reboot it. The dead drive is very very dead and sometimes that hangs the bus when removing it.

**Comment by tatarsky** [comment]
Drive replaced. Performing rebuild before back in SGE.

**Comment by hirokomatsui** [comment]
Thank you!

**Comment by tatarsky** [comment]
You are welcome @hirokomatsui . Rebuilt and re-added back in SGE.
