### ISSUE TITLE
Cluster Down/Offline

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#255]
Just wanted to report that the cluster appears to be either down or offline at the moment.  I don't know the reason behind it.

**Comment by tatarsky** [comment]
SDSC Scheduled Network work apparently. Its completed. Cluster never went down but networking to the headnodes was interrupted for a bit. 

http://status.externsdsc.org/2018/09/13/revised-schedule-sdsc-planned-maintenance-networking-upgrades-12-sept-2018-1900-2300/

**Comment by tatarsky** [comment]
From other postings it was not expected to be that long an outage but something went wrong.
