### ISSUE TITLE
connection to DNS seaver

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#258]
It's not a problem for now, but I'm wondering if anything else's wrong related.

fl-hn1:~> ssh igm-storage1.ucsd.edu
ssh: Could not resolve hostname igm-storage1.ucsd.edu: Temporary failure in name resolution

Do you think there's a problem on the server side? It's fine if so.
I don't have any problem to see all the servers from my PC, but flh1. flh2's fine too.

**Comment by tatarsky** [comment]
Looking.

**Comment by tatarsky** [comment]
Hmm. Not exactly sure what happened here. Restarted named. Seemed to fix it but unsure what happened.
 
Tons of dnssec errors in the logs starting sometime on 10/13. 

I'm looking into it. Something may have changed or something ran out of resources.

**Comment by hirokomatsui** [comment]
SDSC had some problem last week maybe because of rain (you know that rain's such a big deal in San Diego), so that might leave something on our server too.

**Comment by billgreenwald** [comment]
there was that ICANN update that happened this weekend

**Comment by tatarsky** [comment]
Yes, you folks do get tons of rain ;)

Well, basically it seemed isolated to fl-hn1. Same exact config on fl-hn2. I'll dig around but it definitely stopped working right on the 13th. Quite odd. Leaving this open until I understand it better.

**Comment by hirokomatsui** [comment]
Thank you!

**Comment by tatarsky** [comment]
Sorry got a reference to that item @billgreenwald ?

**Comment by billgreenwald** [comment]
Heres an article about it from a (no idea about the quality) website.

https://www.networkworld.com/article/3313341/internet/icanns-internet-dns-security-upgrade-apparently-goes-off-without-a-glitch.html

it was the first hit off my google for it so seems like its a well read article?

**Comment by tatarsky** [comment]
I found what you meant right after I typed it.
Odd that would impact us as we don't have DNSSEC enabled. But I'll definitely see if thats 100% accurate as the DNSSEC errors seem to imply thats possible.

**Comment by tatarsky** [comment]
Further odd as I have about 200 systems with the exact same config ;)

**Comment by tatarsky** [comment]
Might be a bug in the version we've got as the caching bind on the head nodes. I'll debug it with the same version elsewhere and will likely slide it up a version anyway. Interesting.

**Comment by tatarsky** [comment]
Patched but still unclear why it was impacted. Not seen again so until next odd DNS event. Added an alert for non-resolution of common DNS names.
