### ISSUE TITLE
Recent Vim

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#26]
Is it possible to build a more recent vim- and load this as a module?
(Vim 7.3.584 with python2 support)

**Comment by tatarsky** [comment]
Yep! Probably in the morning. But yes.

**Comment by tatarsky** [comment]
See if I've compiled with all the things you want. Happy to add more items...

```
$ module add vim
$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Nov  5 2015 07:03:11)
```

**Comment by djakubosky** [comment]
Will this use my extant .vimrc?  can we add YouCompleteMe, Powerline and vim-flake8

https://github.com/Valloric/YouCompleteMe
https://powerline.readthedocs.org/en/master/installation.html
https://github.com/nvie/vim-flake8

**Comment by tatarsky** [comment]
The .vimrc question I believe the answer is "yes"

```
vim --version
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/frazer01/software/vim-7.3/share/vim"
```

I will look at those other items in a bit.

**Comment by tatarsky** [comment]
And for some reason my cut/paste of what I wanted didn't come out:

```
system vimrc file: "$VIM/vimrc" 
 user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
```

**Comment by djakubosky** [comment]
I'm going to have a go at getting them working myself- will advise if things fail

Thanks Paul!

**Comment by tatarsky** [comment]
Noted.

**Comment by djakubosky** [comment]
This vim is actually not a high enough version- need Vim 7.3.598+

**Comment by tatarsky** [comment]
That is the version on their web site as 7.3. Not a heavy vim user so I'm curious how you even get the minor minor revision ;)

They seem to feel 7.4 is current. I'm going off this page BTW so if you have an alternate suggestion advise.

ftp://ftp.vim.org/pub/vim/unix/

**Comment by tatarsky** [comment]
Oh, dim memory this is one of those packages that doesn't bundle its millions of patches....

**Comment by djakubosky** [comment]
Well, honestly I've never attempted this type of set-up- attempting to build a python IDE in vim.  If we can't get it working it isn't high priority, just would be cool.  

Vim 7.4 would probably work fine if we can build that one?

**Comment by djakubosky** [comment]
Note- I have most of those vim plugins ready to go to quickly test

**Comment by tatarsky** [comment]
Either way. I just need to grab the patches. 7.4 has 900+ patches. 7.3 has 999 ;)

**Comment by tatarsky** [comment]
Oh, I missed the git repo for it. Let me build it from that.

**Comment by tatarsky** [comment]
OK. See how this one does. its "the latest greatest" from Git. If that is too new I can tag down to something.

```
$ module rm vim
$ module add vim
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov  5 2015 14:38:27)
Included patches: 1-909
```

**Comment by djakubosky** [comment]
This worked perfectly with the plugins thanks!

**Comment by tatarsky** [comment]
Cool! Deleting old version then. Need anything else?

**Comment by djakubosky** [comment]
No I think thats it, starting to troubleshoot the SpeedSeq and GenomeStrip (which I installed myself).

**Comment by tatarsky** [comment]
Okey doke. Closing for now. Feel free to re-open.
