### ISSUE TITLE
Just checking on fl-hn2 memory use

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#265]
Confirming that the use of memory on fl-hn2 is known. It appears to be related to processes running there and not a leak of something but advise if a runaway or something and I'll kill things.

Otherwise I'll just ack the alert.

**Comment by billgreenwald** [comment]
Yea they finished up today so I released what wasn't needed.  Thanks for the check in though

**Comment by tatarsky** [comment]
Cool. Thank you.
