### ISSUE TITLE
Please check I/O from opt.q jobs

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#268]
Getting alerts of very high NFS load on the system `fl-hn2` that provides the NFS version of Lustre /frazer01 to the old nodes (They cannot actually do Lustre due to no 10G networks)

Consider using local /scratch areas if you need I/O from those nodes.

I am not going to do anything at the moment as its late but make sure you don't overload things from opt.q nodes.

**Comment by s041629** [comment]
I am just reading/writing small files from the old nodes. If this is the problem, I will stop them

**Comment by tatarsky** [comment]
Hmm. Well, it does seem to be driving up the load on fl-hn2. All NFS. 

Are there lots of small files involved? It may be the number of NFS operations.

In general the best thing to do on the old nodes is write to /scratch and at the end of the job copy back.

Leave it for now. Perhaps can review a bit with you tomorrow.

**Comment by tatarsky** [comment]
Please stop your jobs. See #269.

While I'm not sure of cause and effect something is impacting fl-hn2.

**Comment by tatarsky** [comment]
It appears to be a massive number of open files. (As noted in #269 )
Is that your jobs @s041629 or has something else gone wrong (very difficult to diagnose at the moment as the machine is quite unhappy)

**Comment by tatarsky** [comment]
Note to me: 34696128 open files.

**Comment by tatarsky** [comment]
Attempting to remediate.

**Comment by tatarsky** [comment]
I've for now upped the max but its a very high maximum file count.

Whatever started this happened around 6:34PM.
```Feb  6 18:34:48 fl-hn2 kernel: VFS: file-max limit 26227160 reached```

Thats a very high file count. I don't have time this evening to debug what was the cause but at the moment it appears related to these jobs. In the morning we can review what is being done but there was definitely 34 million open files when I looked.

Leaving open so I can resume tomorrow.

**Comment by tatarsky** [comment]
So some analysis shows its most likely the file handle count that caused all this. File handles relate to open files and I believe in this case were all via NFS which means the nodes were opening this many files.

![filehandles](https://user-images.githubusercontent.com/6439722/52414838-fda88f00-2aaa-11e9-9d67-0e40b705974a.png)

That graph normally is not 34 million file handles. In fact for several years the high water mark was 15K.

So something "different" was done yesterday evening. I would like to review what you are doing and prevent impact like this.

**Comment by tatarsky** [comment]
`fl-hn2` is not happy still about this item. I will probably be rebooting it if I cannot recover from it.

**Comment by tatarsky** [comment]
Unit rebooted. 125 days uptime. NFS server was not functioning correctly. Please provide what you were doing when you can.

**Comment by s041629** [comment]
I stopped everything last night. But the number of open files seems too high: I was running an array job (300 jobs, one core each) that create 3 temporary files each and two output files. So I should have had 1500 open files at the same time

**Comment by tatarsky** [comment]
Perhaps a bit later we can run one of these jobs and I can look. lsof would not even return last night. Its also possible there was a malfunction and handles did not close. I see a rapid ramp in allocated handles and none of the usual drop. Thats quite odd. Thanks for stopping your jobs.

**Comment by s041629** [comment]
I have added a "closeAllConnections()" to call at the end of my script. I will start running my jobs now and check if they work

**Comment by tatarsky** [comment]
Noted. As one other data point I show at the moment on a sample node (cn13) roughly 1700 files open as your UID over the NFS. 

Some of those are R libraries and such. Some are the CARDIPS data files.

Still well short of several million but if was indeed a non-closed descriptors we'll know shortly as we'll see the same pattern. 

fl-hn2 reports ~3000 open file handles.

**Comment by s041629** [comment]
I think that for 300 jobs running in parallel, 3000 open files including R source files is normal

**Comment by tatarsky** [comment]
Yep on the open files. 

I think you found it. If you _do_ want to confirm deny it was that close item you could remove it ;)

Or, it looks good to me if you just want to close. I'm adding Nagios alerts for open file counts as I don't have them.

**Comment by tatarsky** [comment]
This showed no signs of happening again so either it was that "close" item or something else. I have added alerts to catch rapid open file counts.
