### ISSUE TITLE
fl-hn2 reporting CE on DIMM P1-DIMMB1

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#270]
We appear to have a bad DIMM in fl-hn2. I am attempting to get past that fact but it will likely require a support call to AHPC.

**Comment by tatarsky** [comment]
I have managed to get it to boot but will still issue the call for a scheduled replacement. It was a correctable error but we still do not want such DIMMS around.

P1-DIMMB1

**Comment by hirokomatsui** [comment]
So, our plan is that AHPC will inspect the error, then replace DIMM in the case?

**Comment by tatarsky** [comment]
Yep. But when I have more time for the process. The head nodes are under warranty still.

Its a correctable error (CE) but I still like to get those out when I see them.

**Comment by billgreenwald** [comment]
I followed this on and off last night -- can we use flh2 for computing still, or should we avoid it?

**Comment by tatarsky** [comment]
This is not related to the problems last night. Just something I noted on rebooting it it.

**Comment by tatarsky** [comment]
Handling via #275
