### ISSUE TITLE
KNOWN  /frazer01 sudden jump to nearly 100%...cleaning being done

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#271]
This happened very quickly this morning:

```
Filesystem                               Size  Used Avail Use% Mounted on
10.8.16.29@tcp:10.8.16.30@tcp:/frazer01  524T  498T   41G 100% /frazer01
```

Please urgently clean up.

**Comment by tatarsky** [comment]
If anyone has any reason to keep:

```/home/patrick```

Please advise ASAP.

**Comment by tatarsky** [comment]
And `/home/nnariai`

There are no backups of this data so please be certain.

**Comment by hirokomatsui** [comment]
Not really, are they big?

**Comment by tatarsky** [comment]
I'm looking. Not much but we are in bad shape here.

**Comment by hirokomatsui** [comment]
I know... Trying to find removeable.

**Comment by tatarsky** [comment]
Somebody is writing at a brisk pace.

**Comment by hirokomatsui** [comment]
Yea, I'm emailing asking, but nobody's here  yet except me and Matteo.

**Comment by tatarsky** [comment]
Patrick is only 14GB. Doing a du for nnariai.

**Comment by hirokomatsui** [comment]
They might not have much, I've checked before.

**Comment by tatarsky** [comment]
62GB for nnariai

Somebody cleaned up something but its still really dangerous:

```
Filesystem                               Size  Used Avail Use% Mounted on
10.8.16.29@tcp:10.8.16.30@tcp:/frazer01  524T  497T  596G 100% /frazer01
```

**Comment by tatarsky** [comment]
basically somebody is filling it quicker than I can clean it.

Is it the @s041629 jobs? Thats all I see out there.

**Comment by tatarsky** [comment]
Write has stopped so whatever was stopped was involved.

**Comment by hirokomatsui** [comment]
I've removed a big one!

**Comment by s041629** [comment]
my jobs write ~20000 files, <1 MB each

**Comment by tatarsky** [comment]
Hmm. was seeing 2GB/sec write.

**Comment by billgreenwald** [comment]
I can do some cleanup for HiC but need to talk to people. Give me 15 mins

**Comment by tatarsky** [comment]
Example of the rates I was seeing. We don't have much to chew throught at these rates. 
![lustre](https://user-images.githubusercontent.com/6439722/52494268-302db700-2b93-11e9-8422-be8245ed3861.png)

**Comment by tatarsky** [comment]
Thanks @billgreenwald

**Comment by tatarsky** [comment]
OK. I think @hirokomatsui gave breathing room.

```Filesystem                               Size  Used Avail Use% Mounted on
10.8.16.29@tcp:10.8.16.30@tcp:/frazer01  524T  492T  5.3T  99% /frazer01
```

**Comment by tatarsky** [comment]
5TB at 2.2GB/sec though is 41 minutes assuming that was related. Thats faster than we can do something about this always being at 99%.

**Comment by tatarsky** [comment]
I'm checking the /software area in case there are some obsolete and large items there as well.

**Comment by tatarsky** [comment]
@hirokomatsui I'd like to delete /home/patrick and /home/nnariai anyway as they are gone from the password file. Can you OK that?

**Comment by tatarsky** [comment]
Writes began at 7:22AM.

**Comment by tatarsky** [comment]
If any of these software packages are not used there is around a 1TB there:
```
509G    CADD_v1.3
223G    homer_4.7_cardips
51G     gemini-20151103
```

Rest are in the noise. (aka small)

**Comment by hirokomatsui** [comment]
Had a brief meeting, we'll keep eyes on that and start removing/moving

**Comment by tatarsky** [comment]
I'm seeing if the graphical "disk usage" tool will return in real time. Might help find "old stuff"
Last time I tried though it took a long long time.

**Comment by hirokomatsui** [comment]
That will help. Thanks

**Comment by tatarsky** [comment]
Thanks for the 5TB ;)

**Comment by tatarsky** [comment]
Brief reminder when living on the edge of full:

"20000 files, <1 MB each"

The "time" involved there is missing. And thats the variable that matters. I assumed you are talking "for the total of your job" in which case that is at most 20GB (if <1MB is some range up to 1MB) and its not involved. 

But if its "per some short time period" that is another story. Something was writing fast. Would be good to find out what it was.

If folks are writing at say 2GB/sec you can consume that 5Tb in less than an hour. 

Its a fast filesystem and it can fill fast as a result ;)

**Comment by s041629** [comment]
20000 files, one file/job, every job takes ~10 minutes. At most ~300 files written at the same time

**Comment by tatarsky** [comment]
That then seems unlikely as the cause! I cannot see what client was doing that speed. I'll have to add some switch port monitoring although I see another 2TB freed up. Thank you.

**Comment by hirokomatsui** [comment]
My jobs writing much. I'll keep watching.

**Comment by tatarsky** [comment]
Ah. OK. As long as you know!

**Comment by tatarsky** [comment]
We have a much more safe level of fill now and the alerts are not firing.
```
Filesystem                               Size  Used Avail Use% Mounted on
10.8.16.29@tcp:10.8.16.30@tcp:/frazer01  524T  434T   64T  88% /frazer01
```

I'm going to try to make these weekly. They are a form of space graph designed to make the larger uses up to four dirs deep more findable. They are merely for information. This should be viewable on campus but tell me if I've forgotten and firewalled it.

http://flh1.ucsd.edu/duc/

I am closing this for now. Thanks for the cleaning!
