### ISSUE TITLE
jupyter unavailable

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#272]
I am trying to access to the Jupyter Lab notebook and keep on getting a blank page with the message "Service Unavailable". I can access to the cluster via SSH, though.

Do you know if there is any issue with the cluster?

Thanks!

**Comment by tatarsky** [comment]
We run two services. You seem be be referencing the Lab beta. 

Please provide the URL for me to be 100% sure but I am checking the state of both.

**Comment by tatarsky** [comment]
Confirmed you mean Lab on fl-hn1. Looking. 
Seems like its SSL cert expired as well.

**Comment by s041629** [comment]
Hi Paul, here are the two URLs:
https://flh1.ucsd.edu:9000/hub/
https://flh1.ucsd.edu:9000/user/matteo/tree/

**Comment by tatarsky** [comment]
Yep. Working on it. Its mad about something.

**Comment by tatarsky** [comment]
Well, if it was mad about the certificate I've made a new one for another two years. (The other one expired yesterday night). But it looks like it dumped core at some point as well so which is chicken and which is egg not clear. But restarted...try again and you'll have to accept the self-signed SSL cert.

**Comment by s041629** [comment]
it works. Thanks!

**Comment by tatarsky** [comment]
OK. Adding a calendar entry for 2/18/2021 if that was it.
