### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#274]
Hi Paul, do you see anything wired related with MySQL server?
I've restarted the server once after experiencing too slow connection and connections refused.

**Comment by tatarsky** [comment]
I can look around. fl-hn1 looks pretty quiet.

**Comment by tatarsky** [comment]
Innodb seems angry about something. Any recent changes to settings?

**Comment by hirokomatsui** [comment]
I'm making a relatively big table (90 million records) with MyISAM.
All the databases with Innodb should not be very big anyway.

**Comment by tatarsky** [comment]
Yeah I see that. I'm not sure what all the messages are about in the mysql log. I'm looking.

**Comment by hirokomatsui** [comment]
Ok, I'll just wait till tomorrow. It will be usually calm later, hopefully.

**Comment by tatarsky** [comment]
Is it retina2? Are you sure its MyISAM?
As all the tables are type InnoDB....

```
 3 | hiroko | localhost | retina2 | Query   |  453 | executing | load data local infile
        '/projects/retina/analysis/SCAP/scap3i_v1_0.txt' into table scap igno |
```

**Comment by tatarsky** [comment]
Whoops, that got cut off
```
mysql> show table status
    -> ;
+----------------------+--------+---------+------------+-----------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| Name                 | Engine | Version | Row_format | Rows      | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation         | Checksum | Create_options | Comment |
+----------------------+--------+---------+------------+-----------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-------------------+----------+----------------+---------+
| _cnv_enhancer        | InnoDB |      10 | Dynamic    |      3085 |             53 |      163840 |               0 |            0 |         0 |           NULL | 2018-07-10 15:58:31 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| _cnv_epd             | InnoDB |      10 | Dynamic    |       166 |             98 |       16384 |               0 |            0 |         0 |           NULL | 2018-07-10 15:57:53 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| _snv_enhancer        | InnoDB |      10 | Dynamic    |    119975 |             48 |     5783552 |               0 |            0 |         0 |           NULL | 2018-07-10 15:57:08 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| _snv_epd             | InnoDB |      10 | Dynamic    |       282 |             58 |       16384 |               0 |            0 |         0 |           NULL | 2018-07-10 15:56:16 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| biogrid              | InnoDB |      10 | Dynamic    |    245089 |             40 |     9977856 |               0 |            0 |         0 |           NULL | 2017-08-11 15:35:04 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
| cadd                 | InnoDB |      10 | Dynamic    |  28913681 |             51 |  1495269376 |               0 |            0 |         0 |           NULL | 2017-08-10 14:55:16 | NULL        | NULL       | latin1_swedish_ci |     NULL |                |         |
```
(etc)

None are MyISAM....

**Comment by hirokomatsui** [comment]
Oh, I thought the database's MyISAM. That's the sql I'm working on now anyway.

**Comment by tatarsky** [comment]
Where is the table create for the current file being loaded?
I think what you are seeing is InnoDB is going to be slower with that many rows being in-filed....its got to lock and stuff for every row as is its way....

**Comment by hirokomatsui** [comment]
I'm loading data to a temporary table, so it should be on memory or temporary file.

**Comment by tatarsky** [comment]
yeah, its got the local disks pegged at 100% on write.

**Comment by tatarsky** [comment]
Even though the end result is on lustre....

If you loaded it directly I wonder if the behavior would change...right now you are waiting on disk I/O of the boot disks in fl-hn1.

**Comment by hirokomatsui** [comment]
Using a regular table instead. retina2 is on Luster.
You're right, temporary table will go to the local drive.

**Comment by tatarsky** [comment]
I also definitely see its an InnoDB format table...

/frazer01/mysql/retina2/scap.ibd

Thats the InnoDB format. Which may also be a bit slower on in file.

but try removing the temp table....

**Comment by tatarsky** [comment]
So watching scap rows:

858973

(wait 30 seconds)

888677

(etc) And the mysqld log is not spewing...


Seems better?

**Comment by tatarsky** [comment]
We should get a couple of SSDs for Mysql data on local drives. There are slots in that server. They are so cheap now.

**Comment by hirokomatsui** [comment]
Good idea. I will note that for the next update.

**Comment by tatarsky** [comment]
No, its crashing Mysql...

InnoDB: ###### Diagnostic info printed to the standard error stream
2019-03-06T23:35:48.052160Z 0 [ERROR] [FATAL] InnoDB: Semaphore wait has lasted > 600 seconds. We intentionally crash the server because it appears to be hung.
2019-03-06 15:35:48 0x7fcabb3fa700  InnoDB: Assertion failure in thread 140508701632256 in file ut0ut.cc line 916
InnoDB: We intentionally generate a memory trap.
InnoDB: Submit a detailed bug report to http://bugs.mysql.com.
InnoDB: If you get repeated assertion failures or crashes, even
InnoDB: immediately after the mysqld startup, there may be
InnoDB: corruption in the InnoDB tablespace. Please refer to
InnoDB: http://dev.mysql.com/doc/refman/5.7/en/forcing-innodb-recovery.html
InnoDB: about forcing recovery.
23:35:48 UTC - mysqld got signal 6 ;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.
Attempting to collect some information that could help diagnose the problem.
As this is a crash and something is definitely wrong, the information
collection process might fail.


I'll have to look at this with you. Thats not good. We may need to rev our Mysqld anyway. Its been awhile.

**Comment by tatarsky** [comment]
I can look at this with you tomorrow. I'm done for today. Only suggestion I would try is perhaps break it up a bit. Something is causing InnoDB to hang on write of the rows.

**Comment by hirokomatsui** [comment]
OK, thanks. Have a good night!

**Comment by tatarsky** [comment]
I can rev the Mysql. We are at 5.7.20 and the latest for that release is 5.7.25.

But I usually like to do that with everything shutdown mysql wise.

**Comment by tatarsky** [comment]
I propose in the morning I update to the latest Mysql patch level of that 5.7 release and when you get in we'll run your import in a shared "screen" as root so I can see whats going on.

**Comment by tatarsky** [comment]
I believe this is no longer an issue. If it is lets re-open and solve.
