### ISSUE TITLE
fl-hn2 crashed

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#275]
No time to review but if anything "interesting" done on it this evening please let me know.

**Comment by tatarsky** [comment]
Will schedule replacement of DIMM mentioned in #270 in case related. No proof of that at this time.

**Comment by tatarsky** [comment]
Crashed again. Ticket sent to AHPC. I would advise staying off the unit for anything important until we can resolve this. But remember it provides NFS to the old nodes that have no other way to get to Lustre as they are not on 10G

**Comment by tatarsky** [comment]
AHPC Ticket#1012362

**Comment by tatarsky** [comment]
Crash dumps however seem to point at NFS kernel module. Which would imply old node involvement possibly as thats the only NFS service on the unit. Although NFS is also very memory intensive so I'm still going to replace that DIMM.

Looking at jobs on old nodes.

**Comment by djakubosky** [comment]
Just wanted to provide context of this day- Seemed to me that there were some ram intensive jobs running on the old nodes, jobs writing a lot of files on the new nodes.  Personally though, I was experimenting with a new tool [dask](https://dask.org/) which can distribute data from a large file into chunks that live in ram on jobs on the cluster and allow manipulation of the (often larger than ram) data like a normal table.  I don't think this caused the crash, but maybe IO involved in doing dask operations could have contributed, just wanted you to be aware.

**Comment by tatarsky** [comment]
OK thanks. I'm still debugging but have also got a replacement DIMM coming. Next week we will likely shutdown and remove that from the equation.

**Comment by tatarsky** [comment]
Components may come today. If so we will need to shutdown fl-hn2 when they arrive. So best to avoid it most likely. This will also impact any Old Node jobs and Jupyter Hub items.If you need more precise scheduling I will have to coordinate with AHPC.

**Comment by tatarsky** [comment]
Components probably coming tomorrow. We have a disk in "pending fail" mode on one of the arrays so I've also issued the request for that to be replaced. That isn't a service interruption. The memory will be. I will confirm when they confirm they have the parts.

**Comment by tatarsky** [comment]
Replacement memory has arrived. Can we assume anytime is good for fl-hn2 shutdown or do we need to schedule it? Remember: this will stop all opt.q jobs as well.

**Comment by hirokomatsui** [comment]
Anytime will be fine for us. Thanks!

**Comment by tatarsky** [comment]
OK. I'm going to start them over there then. Thank you.

**Comment by tatarsky** [comment]
I am blocking further logins to fl-hn2.

**Comment by tatarsky** [comment]
Expecting arrival before noon your time. Will update when arrived.

**Comment by tatarsky** [comment]
Oh and the older Jupyter Hub will also go down. So save your work. The newer one on fl-hn1 will NOT.

**Comment by tatarsky** [comment]
Work is in progress. Drive already replaced. Working on bad DIMM.

**Comment by tatarsky** [comment]
Checking fl-hn2 post replacement. No logins yet.

**Comment by tatarsky** [comment]
OK. I've opened fl-hn2 for logins. And restarted the hub and NFS. Please advise of further issues and I'll be watching.

**Comment by hirokomatsui** [comment]
Great, thanks!
