### ISSUE TITLE
jobs in Eqw state

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#28]
Hi Paul, 
my jobs ended up in Eqw state after I submit them. Actually two of your jobs are also in the Eqw state. I tried using with or without '-l h_mem 4G', but neither works. Any idea why this might happen?

Thanks,

**Comment by tatarsky** [comment]
```
qstat -explain a -j 232

error reason          1:      can't get password entry for user "hel070". Either user does not exist or error with NIS/LDAP etc.

```

So this mornings efforts to complete NIS migration appears to have hit a snag. I will look in a moment.

**Comment by tatarsky** [comment]
Monitoring. For reasons not clear to me SGE is failing to looking names in NIS. If I have to I will revert to local /etc/passwd /etc/shadow until I figure it out. I don't use NIS much anymore.

**Comment by tatarsky** [comment]
I'm reverting back to local passwd/shadow for a bit. Something I don't understand is happening with NIS and SGE.

**Comment by hurleyLi** [comment]
The submission works fine now. Although there're still three old jobs (222,223,231) are in either in t or dt status, and occupied the cluster resources. Could you please remove these three jobs? 

Thanks!

**Comment by tatarsky** [comment]
Yeah I'm working on that...

**Comment by tatarsky** [comment]
Some similar threads from other folks on the same problem. I'll see if I can reproduce this elsewhere and let you run your jobs. But for now NIS and SGE appear to not be good friends.

**Comment by tatarsky** [comment]
Closing this but noting it was a problem under #1
