### ISSUE TITLE
Failed drive ZFS backup server

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#280]
A drive in fl-nas1 has failed. Ticket started with AHPC. Believe we have onsite until 9/2019.

**Comment by tatarsky** [comment]
AHPC ticket: 1013117

**Comment by tatarsky** [comment]
Drive replaced. Zpool rebuilding. Will close when complete.

**Comment by tatarsky** [comment]
This finished during my trip. All done.

**Comment by hirokomatsui** [comment]
Thanks!
________________________________
