### ISSUE TITLE
Ganglia cluster report

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#287]
Hi Paul, 

I was trying to check how my jobs are affecting the global memory use on ganglia (http://flh1.ucsd.edu/), but all the plots are empty (see the attached image: the same happens on all pages and on all nodes). Does anything need to be updated to show the plots?

Thank you!
![ganglia](https://user-images.githubusercontent.com/10120314/72485101-8354b480-37bb-11ea-9c3c-f7b323469405.png)

**Comment by tatarsky** [comment]
Looks like the gmetad didn't start right after the cluster move. Correcting...waiting 10 minutes to make sure its running.

**Comment by tatarsky** [comment]
Should be back gathering now but was down. Adding a check to Nagios to make sure its running properly.
