### ISSUE TITLE
sftp user account

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#288]
Hi Paul,

Is it easy to create a user account which can access only to the home directory?
We want our collaborator uploading some files on our cluster.
If it's not easy, never mind. I'll just can create a regular user account for a short time.

**Comment by tatarsky** [comment]
Different than `frazerguest1` ? 

We can do another of these if you wish. Just advise the username and the homedir! But we have that active. I do not recall the password ;)

```
# Support Upload
Match User frazerguest1
    ChrootDirectory /frazer01/home/sftp
    AllowTCPForwarding no
    X11Forwarding no
    ForceCommand internal-sftp
```

**Comment by tatarsky** [comment]
And we might have to check iptables as I believe we blocked ssh to campus awhile back. I'll look in the morning but just advise on re-use of `frazerguest1` or not.

**Comment by hirokomatsui** [comment]
Can you remove the user frazerguest1, as well as the home directory too. I've checked the files there.

The new user's on UCSD campus, so no need to change iptables.
The user name will be gaulton.

**Comment by hirokomatsui** [comment]
The password can be any random strings.

**Comment by tatarsky** [comment]
OK. Making a chroot sftp account called "gaulton"  with a random password which I'll send to you and a homedir of the same name. 

And removing the older frazerguest1 config.

**Comment by tatarsky** [comment]
Sent you an email with items provided! Advise if issues and note carefully the need to cd upload in the sftp as sshd chroot permissions got a little more strict. 

I'll do the same config on fl-hn2 if you want. Right now its just fl-hn1.

**Comment by tatarsky** [comment]
Did the same on fl-hn2.

**Comment by tatarsky** [comment]
frazerguest1 removed. homedir removed.

**Comment by hirokomatsui** [comment]
I've confirmed that works. Thanks!

**Comment by tatarsky** [comment]
Excellent! You are very welcome. Have a great weekend.
