### ISSUE TITLE
About to hit 100% full on Lustre

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#291]
The rate of fill over the weekend has reached the point where the Lustre is about to hit 100%.
If you have anything to clean, please do so and emails sent to current job runners.
I will be disabling the queues shortly.

**Comment by tatarsky** [comment]
SGE disabled

**Comment by hirokomatsui** [comment]
Sorry, that's me. Cleaning them up!

**Comment by tatarsky** [comment]
Noted ;)
We got real close ;) Re-enabling SGE queues in a moment...

```df -h /frazer01/
Filesystem                               Size  Used Avail Use% Mounted on
10.8.16.29@tcp:10.8.16.30@tcp:/frazer01  524T  497T  671G 100% /frazer01
```

**Comment by tatarsky** [comment]
Re-enabled SGE...might want to generically take a look at older items in /projects in case they are no longer needed. I don't know who user "1044" was but they are gone now so perhaps see if thats some items to free. 
```
drwxrwsr-x   4       1044 users  4096 Aug  9  2016 islet_eqtl
drwxrwsr-x   6       1044 users  4096 Dec 23  2015 T2D
```

**Comment by hirokomatsui** [comment]
1044 should be someone who've left the lab. I'll work on that. Thanks!

**Comment by tatarsky** [comment]
Yep! Might be worth it...I didn't do a du ;)

**Comment by tatarsky** [comment]
I'm running one actually to make sure its worth it!

**Comment by s041629** [comment]
Most of the data should be from Naoki. The "islet_eqtl" folder might be relevant for Jennifer, though: it is the 118 islet samples that we are trying to download from EGA, so wait before removing it

**Comment by s041629** [comment]
for the other folder, we should talk with Paola, who has done some analyses

**Comment by tatarsky** [comment]
Sure. I'm unlikely to remove anything as I don't know the players but if the data is in use we should chown the dir to somebody else just so we know who is the owner.

**Comment by tatarsky** [comment]
Looks like about 23TB or so if found no longer in use.

17T     T2D
5.4T    islet_eqtl
