### ISSUE TITLE
Getting alerts of some kind

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#292]
I am getting unclear alerts from the systems. I am attempting to gain access but cannot.
I will provide more information as I can.

**Comment by hirokomatsui** [comment]
I'm afraid I made too much interaction on Luster.

We've removed a lot of data from yesterday and today.
And I'm downloading files from AWS S3 with 3 processes.

**Comment by tatarsky** [comment]
OK. I'm trying to get support from Dell. Its down hard.

**Comment by hirokomatsui** [comment]
I believe SDSC still has stuff for 24/7, but we'll have to let them know to get in there. Please let me know. Thanks!

**Comment by s041629** [comment]
I was running something on FLH2 since this morning, but it should not be too computationally intensive. And the jobs I was running on qsub had been the same for a few days.

**Comment by tatarsky** [comment]
This appears to be hardware failure. But very severe hardware failure. No ETA.

**Comment by hirokomatsui** [comment]
Oh no. Fingers crossed!

**Comment by tatarsky** [comment]
We are down until we can investigate the unit closer. No ETA.

**Comment by tatarsky** [comment]
Well closing this one.
