### ISSUE TITLE
/software directory

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#295]
Can we mount flh2:/export/software from flh1, and available from the compute nodes as well.

**Comment by tatarsky** [comment]
Oops. I got ahead of myself and I need to rsync the software area off the single drive.

I've started it and I will advise when that is back.

**Comment by tatarsky** [comment]
Should be back! Please advise!

**Comment by hirokomatsui** [comment]
Confirmed it. Thanks!
