### ISSUE TITLE
jupyter notebook restarting

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#296]
It's not urgent, but when you have time.

**Comment by tatarsky** [comment]
It appears to be broken. I'm not sure why but will look in a bit.

**Comment by tatarsky** [comment]
The lab one starts. 

https://flh1.ucsd.edu:9000

The older one on fl-hn2 does not. So perhaps see if that is usable and I'll review the very old one as time permits.

Note clearly: I had to `mkdir .jupyterHubQueueLogs` as thats required and probably gone for people.

**Comment by hirokomatsui** [comment]
OK, thanks!

**Comment by tatarsky** [comment]
Yes, people need to make sure they make that dir.

```
error reason          1:      06/15/2020 11:21:35 [1026:15071]: error: can't open output file "/frazer01/home/matteo/.jupyterHubQueueLogs/": Is a directory
```

**Comment by s041629** [comment]
it works now. Thanks!

**Comment by tatarsky** [comment]
There may be other "parts" that were in homedirs like personal ipython engines and such.

**Comment by s041629** [comment]
everything seems to be working for me (I also set up the R kernel without any problem)

**Comment by tatarsky** [comment]
OK. Good to hear. thank you. I'll see if I can understand whats wrong with the old one but I would proceed as you can on this newer one. (lab code v.s. old hub code)

**Comment by tatarsky** [comment]
We are only going to support the newer Jupyterlab going forward. The other one is deprecated.
