### ISSUE TITLE
Jupyter lab "Service Unavailable"

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#297]
Hi Paul,

we are getting a "Service Unavailable" when we try to open jupyter lab jobs. Is it because you are working on this? Everything else seems to be working fine: I can SSH to flh1 and flh2 without any problems.

Thank you!

**Comment by tatarsky** [comment]
I am not working on it. I will check.

**Comment by tatarsky** [comment]
When the disk filled last night it made Jupyter mad. I've emailed on the topic but we'll need some cleanups of the root cause. I emailed Hiroko about it. Attempting to remediate.

**Comment by tatarsky** [comment]
Try again. I need Hiroko to take a look at the snapshot item that filled the disk. But I restarted the hub after clearing enough for it to write.

**Comment by s041629** [comment]
it works now, thanks.

**Comment by tatarsky** [comment]
Real fix we need to clean the disk up. Will wait for Hiroko response.
