### ISSUE TITLE
mysql account

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#30]
Paul or Hiroko, could you set up an account for my mysql account on flh1 or flh2?
I was logging in as follows in the old cluster:
mysql -u nnariai -p -h localhost

You don't have to copy the T2D tables in the old cluster to the new cluster at this point.
I will generate new tables from scratch.

Naoki

**Comment by tatarsky** [comment]
I believe @hirokomatsui is handling mysql accounts. The above I assume means you have your password in a `.my.cnf` or its blank ;)

**Comment by hirokomatsui** [comment]
i will create his accout

**Comment by cdeboever3** [comment]
Can I get an account as well Hiroko? It probably makes sense to go ahead make accounts for @djakubosky and @hurleyLi as well. Thanks

**Comment by hirokomatsui** [comment]
I've created the user accounts as your login account name. The password is same as for the shared drive. Once you log in to mysql, change the password with
mysql> SET PASSWORD = PASSWORD('your password');

For Naoki's T2D, I've create a database, t2d, having all privileges of Naoki's user account.
Right now, no one has "CREATE DATABASE" privileges. Please let me know the database name you want to use, then I'll create it and give the permission.

**Comment by nariai** [comment]
Hiroko, thanks!
I close this.
