### ISSUE TITLE
SGE setting and documentation

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#32]
Paul,

How is the SGE setting (queue prioritization) and documentation coming along?
We all need to test SGE as soon as possible, so that we can migrate our analysis
from old cluster to new cluster. This is urgent.

Please prioritize this issue as the highest for the moment.
Thanks!

Naoki

**Comment by tatarsky** [comment]
Is something wrong with the existing Git issue #24 for such statements? 

I am working on it. And at a high priority. 

And I don't like badgering crap like this so don't speak to me this way again.

**Comment by nariai** [comment]
Sorry about this. I meant to prioritize this over other issues. I'll close this thread.

Naoki
