### ISSUE TITLE
IMPORTANT read this carefully and comment

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#34]
As I monitor the cluster it is my opinion current that the submitted jobs are not really requiring 32 SMP processor slots. The CPU load average (run queue length) is not reaching the the level I would expect for a job submitted with 32 smp slots requested on a regular basis during its run. Ganglia pretty clearly shows this. 

My suggestion is that if people are trying to run test jobs BESIDES @hurleyLi that we do two things:
1. @hurleyLi should consider as a test running his jobs asking for 24 smp slots next batch
2. Others should backfill in some of other slots but simply issuing a qsub.

Alternately we can oversubscribe the slots on the nodes to say 40 and see if the run queue comes up to close to what I would expect for that many cores.

**Comment by cdeboever3** [comment]
I don't think there are any plans to run scheduled test jobs today. We can
work on optimizing what Hurley is doing (namely, alignments with BWA). Some
of the steps in these jobs are not threaded or known to not be threaded
efficiently. Perhaps running 4 or 8 jobs per node would be more efficient?

> Alternately we can oversubscribe the slots on the nodes to say 40 and see
> if the run queue comes up to close to what I would expect for that many
> cores.

If you think this is better, we can do this too. This requires you updating
the SGE params and Hurley requesting 40 threads per job, correct?

**Comment by tatarsky** [comment]
If there is not a competing need to get jobs into the cluster, then this is not needed. What I was trying to provide was some "extra slots" for people wanting to test things per #24 . Basically when you declare "-pe smp 32" you've pretty much allocated the whole node. Which is fine, but from the Ganglia graphs its not really being required.

> Perhaps running 4 or 8 jobs per node would be more efficient?

You might be able to push more jobs through, yes. Right now I feel from the Ganglia and atop runs on the nodes several are idle. Hop over to fl-n-1-3 as an example. Its basically using 1 core. 

```

 PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                
25990 hel070    20   0 4922m 4.0g 1388 D 58.0  3.1 189:35.09 sambamba                                                                                                                
25991 hel070    20   0  510m 463m 2496 S 53.4  0.4  31:29.76 bammarkduplicat        
```

**Comment by tatarsky** [comment]
What I see on these jobs is periods where it appears to reach about 20 cores and then it must hit something non-threaded for awhile. 

htop on node 3 right now shows it very well in the period of not needing 32 cores.

**Comment by tatarsky** [comment]
Other observation is this appears to be a phase involving local scratch I/O. The local drive is not being taxed overly heavily but that phase of the job. I'm showing it about 40% busy on average.

In other words you might be able to have two such jobs in the same state on the same node. 

Again, this is tuning observations only based on a belief others are trying to run jobs. If not the case, consider it for trying to maximize usage.

**Comment by cdeboever3** [comment]
I'll let @nariai and @hurleyLi coordinate. I don't know what testing needs to happen. @hurleyLi, I think that you could go to 4 or 8 jobs per node but given what Paul is saying about the local I/O above, you will probably want to use the lustre as temp space in this case. It would be nice to push one of the resources towards max use.

**Comment by tatarsky** [comment]
One item just to be clear the reason I suggested 24 slots is that SGE would place one of his jobs per node while leaving 8 slots free for others. 

You could also do something like 2 x 12 slot jobs as a test with similar results. Or bump to 2 x 14 to leave 4 slots. 

What we want to see on the Ganglia load average graphs if possible is a solid load (run queue) of 32. Meaning all the cpus are really doing something ;) Right now they aren't.

But we don't want to in the process blow the local drive out of the water with disk I/O or exceed memory. However I'm not showing memory issues at this time.

**Comment by hurleyLi** [comment]
It's really jut one process (BWA) uses thread efficiently (I gave it 27 threads, but it seems it only use 20 as Paul mentioned?) I wanted to separated the BWA process from others, but I'll just change to 8 cores per job, and run 4 jobs on each node?

**Comment by tatarsky** [comment]
There are two goals in this Git issue: 
1. To allow other users to run jobs. Which if I do not understand this mornings requests would require you to run with slot counts that do not add up to 32. (aka 4x8 = 32 which means you will still fill in entire nodes if you stack the queue)
2. If the above is not a priority, I would be curious if your compute throughput increases by doing the above (4x8). As I feel you are not stressing the cluster with the current qsubs.

**Comment by tatarsky** [comment]
Here is a way to think about it hopefully graphically if it comes through correctly. 

http://goo.gl/xCLImR

This is idle cpu time percents from collectl per node. 

In a perfectly loaded cluster (cpu load) the lines would all sit down at the bottom of the graph because there would be no idle cpu time.

**Comment by tatarsky** [comment]
Here is one without the head nodes and storage servers.

http://goo.gl/5DUkMF

**Comment by hurleyLi** [comment]
To let other users to run jobs is not a priority for now. We want to get these jobs done as fast as possible. I'll try 1) split jobs into small pieces 2) let it use more threads then requested threads 3) run multiple jobs per node. Hope this can speed up the whole processes

**Comment by tatarsky** [comment]
The above sounds good. Noted the priority statement. Your goal is to get all those processors pegged solid and we'll deal with the next bottleneck as it comes. But right now I'd say the cluster is about 30% active.

**Comment by cdeboever3** [comment]
I think if we first optimize what @hurleyLi is doing, then we can cut back
on the resources and allow others to get jobs on as needed.

> It's really jut one process (BWA) uses thread efficiently (I gave it 27
> threads, but it seems it only use 20 as Paul mentioned?) I wanted to
> separated the BWA process from others, but I'll just change to 8 cores per
> job, and run 4 jobs on each node?

Separating out the BWA call would work as well. Even if you were running
BWA alone I'd be interested to see if it's more efficient to run multiple
BWA jobs per node (perhaps oversubscribing the node as Paul mentioned).

**Comment by tatarsky** [comment]
Concur

**Comment by hurleyLi** [comment]
One question though, will the job be killed if it actually used more than what's been requested?

**Comment by tatarsky** [comment]
At this time: no. We have no attempts yet at any limits. And SGE opensource cannot actually enforce slot overruns. Just memory and runtime.

**Comment by tatarsky** [comment]
And to be super clear: memory limits are ready to deploy but NOT activated with the final command. (Per #24 )

**Comment by tatarsky** [comment]
I oversubscribed one node with an extra slot just to allow some waiting test jobs to run. Just FYI. Not a permanent thing but trying to move everybody along.

**Comment by tatarsky** [comment]
This BTW looks much much better. All the nodes have run queues that are reasonable and keeping their cpus 100% busy. So I'm curious if your job throughput improves over the weekend! 

![stacked](https://cloud.githubusercontent.com/assets/6439722/11015337/72477a3a-8520-11e5-9a4c-c0e0bd22058e.png)

**Comment by tatarsky** [comment]
Idle cpu percents also way down. So congrats, you are officially pushing the cpus ;)

**Comment by hurleyLi** [comment]
Yes good to see this! It's definitely more efficiently than before. I have separated the multiple-thread-friendly steps from the less-friendly steps, and these are the more efficient steps. I'll see how does it look when I run the less friendly steps. For the current step, I run three jobs per node, and for the less efficient steps, I plan to run 8 jobs per node. The bottleneck for that one would be I/O, coz it's basically just writing. So I would monitor the network for that step as well. I'm sure the overall job throughput will be improved. Cheers!

**Comment by tatarsky** [comment]
So far I've not seen anything straining the Lustre or the network. You are definitely _using_ Lustre however. I am working a bit today on getting the Intel Management console exposed to at least UCSD so you can see it. Its not part of Ganglia.

**Comment by tatarsky** [comment]
I believe generically the job throughput is looking pretty good and this advice thread can be closed for now. I will continue to watch for idle'd resources as we go forward.
