### ISSUE TITLE
Deploy 10G links

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#35]
I will work with SDSC on bringing up the 10G links. There may be a brief outage when we do so. I will however start with the secondary head node to validate it is correct. ETA is Monday.

**Comment by tatarsky** [comment]
Fiber is in. Waiting on attachment and IP range confirmation.

**Comment by tatarsky** [comment]
Attached on our side but still requires their 10G side. Just updating from ticket as we talked of sending somebody over to do our part but the operators did it as I requested this early morning.

**Comment by tatarsky** [comment]
Please stand clear of head node two. I would like to bring up the 10G as a test there first.
I show @djakubosky and @hurleyLi currently on the system.

**Comment by hurleyLi** [comment]
I'm logging off

**Comment by tatarsky** [comment]
I am proceeding here as I don't see anything except shells. Sorry, I need to get this confirmed working with SDSC.

**Comment by tatarsky** [comment]
OK, head node 2 is now 10G connected. 

```
ixgbe 0000:02:00.1: eth3: NIC Link is Up 10 Gbps, Flow Control: RX/TX
```

To do the same for head node 1 its probably best people stand clear or if you have screen in use you can resume your shells in case the drop. 

Running jobs will not be impacted but if concerned I can wait. I am reasonably confident the SDSC side is ready.

**Comment by cdeboever3** [comment]
All my stuff is in screens

**Comment by tatarsky** [comment]
Checking on others...

**Comment by tatarsky** [comment]
Everybody else looks like a screen or just bash. I'm going to cut it over as I have SDSC's attention.

**Comment by tatarsky** [comment]
OK, please test access. Head node 1 is 10G now as well.

```
ixgbe 0000:02:00.1: eth3: NIC Link is Up 10 Gbps, Flow Control: RX/TX
```

**Comment by tatarsky** [comment]
Believed done. Looks good on all my tests.

**Comment by tatarsky** [comment]
Corrected matter with outbound NAT from wrong interface on nodes.
