### ISSUE TITLE
CPAN, DBI and DBD::mysql modules

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#36]
I want to use a perl script to access mysql database.

In my script, test_sql.pl, I wrote:

use DBI;
use DBD::mysql;

However, there is a error message as below:

bash-4.1$ ./test_sql.pl
Can't locate DBD/mysql.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at ./test_sql.pl line 6.
BEGIN failed--compilation aborted at ./test_sql.pl line 6.

I guess we need to install CPAN and the DBD::mysql module?
Can somebody tell me how we can install CPAN and DBD::mysql modules?

Naoki

**Comment by hirokomatsui** [comment]
I think the library can be installed on the system not local.
Paul, can you install it or let me know if want me do.

**Comment by tatarsky** [comment]
This is best from the yum repos. One sec.

**Comment by tatarsky** [comment]
Please retry. Both DBI and DBD-Mysql perl modules were installed for system perl via yum. On all nodes and headnodes.

**Comment by tatarsky** [comment]
BTW: Please do not use CPAN without talking to me about other options as it makes sync'ing the perl config to multiple nodes problematic if you add to RPM install perl with CPAN.

While you are welcome to build a custom perl tree for the above, I've seen the system perl from RPM get horribly broken by trying to layer CPAN over it.

I have options for literally hundreds of the common perl modules even if you don't see it in Yum based on custom RPMS I do for people. Just FYI.

**Comment by nariai** [comment]
Now, my perl script is working correctly. Thanks!
I will not use CPAN and install modules by myself.

I will close this issue.

**Comment by tatarsky** [comment]
To be clear on one this. CPAN with overwrite of SYSTEM modules (/usr/lib64/perl5) is the main concern. You can do your own perl trees all you want ;)

Similar to Python and such. Try to leave the RPM installed stuff "as it comes" and use alternate locations for custom items. Trying to "customize the canned items" can lead to sadness.
