### ISSUE TITLE
connect to mysql server from compute node

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#37]
When I try to connect to mysql server from compute node, it ends with an error:

bash-4.1$ less insert_variants.sh.e386
Fri Nov  6 14:04:20 PST 2015
Executing: ./create_variants_table.pl 22 ./vcf/1KGP_chr22_SNPs.recode.vcf
DBI connect('t2d:localhost:3306','nnariai',...) failed: Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2) at ./create_variants_table.pl line 28
Can't call method "prepare" on an undefined value at ./create_variants_table.pl line 34.
Fri Nov  6 14:04:20 PST 2015

I guess I need to specify the correct host name, instead of "localhost"?
Please advise how to fix this.

Naoki

**Comment by tatarsky** [comment]
Correct. Localhost assumes the mysql server is on the host in question. The name of the mysql system is fl-hn1 but also aliases to hn1 and h1. If you would like some other alias let me know!

**Comment by tatarsky** [comment]
A good test for confirmation the mysql account has the proper "host" column value from a node is to just try the command line client like this after manually ssh'ing to the node:

```
somenode$ mysql --user=(someuser) --password='(removed)' --host=h1
```

If you want to interactively debug a job in the same environment as qsub, consider typing:

```
qlogin
```

Which will run a shell on a node in the context of SGE.

**Comment by nariai** [comment]
Here is the error I'm getting after modification:

bash-4.1$ less insert_variants.sh.e388
Fri Nov  6 14:16:05 PST 2015
Executing: ./create_variants_table.pl 22 ./vcf/1KGP_chr22_SNPs.recode.vcf
DBI connect('t2d:fl-hn1:3306','nnariai',...) failed: Host 'fl-n-1-15' is not allowed to connect to this MySQL server at ./create_variants_table.pl line 28
Can't call method "prepare" on an undefined value at ./create_variants_table.pl line 34.
Fri Nov  6 14:16:05 PST 2015

Is there any permission setting on mysql server?

Naoki

**Comment by tatarsky** [comment]
Looks that way. I did not make your account but the host table should have the proper node entry or '%'

**Comment by tatarsky** [comment]
Table should read column. The mysql.user entry has a component for the allowed hosts. That message is a result of that not being listed or wildcarded.

**Comment by tatarsky** [comment]
And I'd look but mysql root is changed. So I would check with @hirokomatsui

**Comment by nariai** [comment]
Hiroko, can you take a look at this?

**Comment by nariai** [comment]
After qlogin,

-bash-4.1$ mysql -u nnariai -p -h fl-hn1
Enter password:
ERROR 1130 (HY000): Host 'fl-n-1-1' is not allowed to connect to this MySQL server

**Comment by tatarsky** [comment]
Yes, thats the same issue as above. Qlogin is just a different way to get a shell.
I can see from the datafile that all the accounts that have been added have "localhost" as their allowed host field. My suggestion is that should be '%' for now which is a wildcard that allows any host. 

And I cannot change it properly without the mysql root password which I do not seem to have anymore. Which is fine but requires somebody that does have it correct it.

Do not forget to 'flush privileges' when changed.

**Comment by tatarsky** [comment]
And to be clear, the password I provided @hirokomatsui does not appear to be the current mysql root password. So without that changed password I cannot assist you. I would be happy to do so, but cannot.

**Comment by hirokomatsui** [comment]
You have access only from localhost, it's basically same but MySQL cannot resolve that.
Because your MySQL user name is the same as your account's, and default host name is localhost,
you only have to do
$ mysql -p

**Comment by tatarsky** [comment]
This doesn't seem to be accurate for what he is trying to do. Given its late here do you mind if I just call and work on this with you? He's trying to make a network connection from the node.

**Comment by tatarsky** [comment]
or you can call me 608-271-6817

**Comment by tatarsky** [comment]
Thank you @hirokomatsui for sharing the Mysql root password. I would like to for @nariai change the following column in his Mysql.user account:

From:

```
| Host      | User       
| localhost | nnariai   
```

To:

```
| Host      | User       
| % | nnariai   
```

That allows network connections from a node to the headnode per the above.

Are you OK with that?

**Comment by nariai** [comment]
Paul, I talked with Hiroko, and now she understood what I want to do here. Don't worry. She will handle this issue. Have a nice weekend.

**Comment by nariai** [comment]
You can change that, if you can, thanks!

**Comment by tatarsky** [comment]
Done. Please see if your node -> head node code works now.

**Comment by tatarsky** [comment]
Looks like it did:

```
mysql> show processlist;
+-----+---------+----------------+-------+---------+-------+----------+------------------+
| Id  | User    | Host           | db    | Command | Time  | State    | Info             |
+-----+---------+----------------+-------+---------+-------+----------+------------------+
|  34 | root    | localhost      | mysql | Sleep   | 20827 |          | NULL             |
|  53 | nnariai | localhost      | t2d   | Sleep   |  5178 |          | NULL             |
|  95 | root    | localhost      | mysql | Sleep   |  1744 |          | NULL             |
| 103 | root    | localhost      | mysql | Query   |     0 | starting | show processlist |
| 105 | nnariai | fl-n-1-1:59691 | NULL  | Sleep   |     7 |          | NULL             |
+-----+---------+----------------+-------+---------+-------+----------+------------------+
```

I can explain this more if desired. I changed only the account for @nariai for now.

**Comment by nariai** [comment]
Now it works!!
Thank you. Have a nice weekend.
I'll close this.

**Comment by tatarsky** [comment]
Please however remember this for others!
