### ISSUE TITLE
Node 8 scratch drive failed. Ticket opened.

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#39]
The /scratch drive may have had a short life on node 8.
I am disabling SGE on this node.

**Comment by tatarsky** [comment]
Yep. We have our first hardware call to Advanced HPC. 4TB drive died on node8. Queues are disable on node. Jobs already there will finish assuming they don't need /scratch.

**Comment by tatarsky** [comment]
This brings up a valuable item to discuss. In order to keep computing on a node with a failed scratch area, should we simply symlink /scratch to some unique "tmpscratch" out in Lustre?

**Comment by tatarsky** [comment]
Advanced HPC ticket opening...

**Comment by nariai** [comment]
Yes, let's do that below, so that jobs can keep runnning:

> This brings up a valuable item to discuss. In order to keep computing on a node with a failed scratch > area, should we simply symlink /scratch to some unique "tmpscratch" out in Lustre?

**Comment by cdeboever3** [comment]
Sounds good to me

**Comment by tatarsky** [comment]
Will do a link in a little bit.

**Comment by tatarsky** [comment]
I have added a link on node 8 to an area on the lustre filesystem for a temp workaround. If you want to check it manually I won't put it back in the queue for a few minutes as busy with something else.

**Comment by tatarsky** [comment]
Node 8 back in pool with Lustre scratch drive. Advanced HPC drive likely Monday (NBD)

**Comment by tatarsky** [comment]
So Advanced HPC is going to bring a drive and I am trying to work with SDSC Colo on replacing it. There is a possibility that I may require some hands on help besides that group if they and Advanced HPC can't do it which would surprise me. BUT I am mentioning just in case. This again is node 8.

**Comment by tatarsky** [comment]
We will be attempting this hopefully in a little bit this afternoon. I am going to have the person attempt it hot. As it should be doable hot. But I am disabling the SGE queue in case of problems. Running jobs on node 8 will be left running.

**Comment by tatarsky** [comment]
Drive replaced. Formatting. Will NOT change /scratch link to it until jobs drain.

**Comment by tatarsky** [comment]
Jobs drained. /scratch remounted from local drive. Queues enabled.
