### ISSUE TITLE
hook up email alert in sge

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#4]
Also the format of running sge (e.g. reserve memory, specify node, turn on parallel computing, etc) would be super helpful. 

Thanks!

**Comment by tatarsky** [comment]
Will do the email item and will add some howtos on SGE to wiki shortly.

**Comment by tatarsky** [comment]
Part of this is done. More details on its use shortly.

**Comment by tatarsky** [comment]
Confirmed ready and working but leaving open issue to remind me to document.

**Comment by tatarsky** [comment]
Attempt at some documentation in a section still in development:

https://github.com/frazer-lab/cluster/wiki#having-email-alerts-come-from-jobs
