### ISSUE TITLE
Error installing macs2

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#40]
I'm trying to install the macs2 python package as follows:

```
cd /frazer01/home/cdeboever/sandbox/macs2_install
pip install macs2 > macs2_install.out 2> macs2_install.err
```

Seems to be some kind of gcc error. Maybe I need a newer version for this?

**Comment by tatarsky** [comment]
Hmm. I have no idea what revision added "-Ofast". Can you simply remove that? Google seems to imply its a way to say "-O3"

But if a newer gcc is needed I can build as a module.

**Comment by tatarsky** [comment]
Looks like gcc 4-8 added that. Let me look around for the various options compared to the joy of a gcc build ;)

**Comment by tatarsky** [comment]
There are a few canned options as part of the RHEL devtools concept. I'm testing on hn2 first.

**Comment by tatarsky** [comment]
Bleah. I've remembered why I don't like the RHEL devtools concept ;)
I'll likely just build a gcc module but it might be a bit.

**Comment by cdeboever3** [comment]
That's fine, it's not urgent. I was going around installing things I know
we'll need at some point in the next week or so. Thanks

**Comment by tatarsky** [comment]
Well, if you wish to first confirm it is indeed a gcc version issue, try the following and its probably not the way I'm going to add gcc. 

Login to the second head node

```
fl-hn2 [~]$ scl enable devtoolset-2 bash
fl-hn2 [~]$ gcc -v
gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC) 
```

Try your build.

"scl" is a odd idea from RH sort of like modules. Only not as convenient I feel.

**Comment by cdeboever3** [comment]
That worked on flh2.

**Comment by tatarsky** [comment]
OK. I will build a recent gcc but as a module.

**Comment by tatarsky** [comment]
Building building....

**Comment by tatarsky** [comment]
OK. Quite the collection gcc has become. I am doing some test builds to make sure I include all its libraries.

**Comment by tatarsky** [comment]
Well, lets have you test and see if I've got it right. I didn't add a few things like ISL and 32-bit binary support. 

```
module add gcc
```

**Comment by cdeboever3** [comment]
Install worked like a charm on flh1, thanks. I don't have data to test
functionality right now but I'm assuming it will work since it compiled.
We'll test soon enough but this is closed for now.

**Comment by tatarsky** [comment]
I built a couple of things and they seemed to run ;) Advise if you have any odd errors. Gcc now carries around a stack of infrastructure libraries.
