### ISSUE TITLE
Accounting script cleanup and release

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#42]
I have a script for qacct -j parsing but I'd like to update it a notch before use. Reminding myself to do so.

**Comment by tatarsky** [comment]
Goal of script is assisting with h_vmem reduction.

**Comment by tatarsky** [comment]
I have forgotten to work on this and will do so today.

**Comment by tatarsky** [comment]
OK, the basics are done and time to ask what format do people prefer this? 

It was an epilog script another site to place these stats and email if they were a low ratio. I frankly am not a fan of that but its what I was asked at that site. I could try this but I can assure you it was not popular with some of the users (the PIs asked for it however)

Currently I have it in a mode where its just dumping for all jobs in `qacct -j` by all users and I'm picking on @cdeboever3 for a moment here just randomly to show four particular cases of interest:

```
user cdeboever job 41516 requested 4096 MB on cores 2 used 3330 MB ratio 40% 
user paul job 41691 requested 2048 MB on cores 1 used 2 MB ratio 0% 
user cdeboever job 41519 requested 4096 MB on cores 2 used 6678 MB ratio 81% 
user cdeboever job 41478 requested 4096 MB on cores 2 used 8456 MB ratio 103% killed
```

The above show in order a pretty good try to guess that could be better, a terrible guess by me (was just my test job), an excellent guess, and coming up short and having the job killed. 

Currently the script dumps output like the above for all jobs and all users. 

I can add various argument options or whatever.

Important disclaimer: much of the "used" column comes from a `qacct -j` field called `maxvmem` which gives in my opinion a "pretty good" estimate of a jobs maximum memory use but since its something SGE I believe _samples_ at some rate its not always 100% perfect. You can monitor a jobs vmem counter during its run with qstat.

Example below with the more interesting parts left in:

```
qstat -f -j 41651

hard resource_list:         h_vmem=4G

parallel environment:  smp range: 2

usage         1:            cpu=00:21:46, mem=1080.56931 GB s, io=76.48054 GB, vmem=3.072G, maxvmem=5.752G
```

Above you can see on a running job that asked for 2 cores x 4G of vmem that its hovering near 3G at the moment and at one point SGE saw it at 5.7G.

**Comment by tatarsky** [comment]
Ah, and I may need to fix an item for array jobs I'm seeing before I give people an actual path to the script ;) So mull the above while I work on that.

**Comment by tatarsky** [comment]
And please note carefully, the word `killed` can indicate any limit based kill of a job. SGE does not state which one in the logs. So it can represent a wall time kill as well. I can add walltime data to the output if desired. 
Full `qacct -j` line when SGE kills a job on purpose:

```
failed       37  : qmaster enforced h_rt, h_cpu, or h_vmem limit
```

**Comment by cdeboever3** [comment]
Hi @tatarsky the above looks good. I think having a path to the script that outputs 

```
user cdeboever job 41516 requested 4096 MB on cores 2 used 3330 MB ratio 40% 
user paul job 41691 requested 2048 MB on cores 1 used 2 MB ratio 0% 
user cdeboever job 41519 requested 4096 MB on cores 2 used 6678 MB ratio 81% 
user cdeboever job 41478 requested 4096 MB on cores 2 used 8456 MB ratio 103% killed
```

would be sufficient for our purposes. Perhaps by default the script can just show jobs from all users for the last 24 hours with an option for going further back? We can grep by username. It may also be nice to include the job name in addition to the job ID if that's available.

Can I have early access to the script before you fix the array issue? I have several thousand jobs to run over the next few days and need a better way to monitor their memory usage ;) These aren't array jobs.

**Comment by tatarsky** [comment]
You will probably re-write it in a few seconds after seeing the gist but its in my homedir: `sge_audit_vmem`. It basically just grabs lines from the rather long output of qacct -j.

**Comment by tatarsky** [comment]
I'll throw it somewhere else and see if I can do the above items BTW.

**Comment by tatarsky** [comment]
So the script will be in `/usr/local/bin/sge_audit_vmem` for now unless other ideas desired. It will be on the hn1 system for now as thats the SGE master. I will add some additional items to it shortly.

**Comment by tatarsky** [comment]
Minor tweaks to only show one day worth by default and add jobname and also the queue. 
Will add a few more items for adding arguments.

**Comment by tatarsky** [comment]
If there remains interest in this I will update it further. Until then it remains in 

`/usr/local/bin/sge_audit_vmem`
