### ISSUE TITLE
latency on flh1

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#43]
Currently experiencing some latency on flh1. For instance, when I write a file with vim it will hang for up to 30 seconds. Not sure if we are hitting some bottleneck but just wanted to point it so @tatarsky could maybe check to see if he sees any issues.

**Comment by tatarsky** [comment]
Noted. But not seeing obvious cause at moment and dealing with drive swap. Will look later today.

**Comment by tatarsky** [comment]
Note that sadly the tool I use to narrow this down I had killed during the re-mount effort. I am monitoring however but was unable to determine a precise cause of this. Feel free to toss further instances here.

**Comment by cdeboever3** [comment]
Experienced the problem with vim that I described on the call earlier (upon saving a file, vim seems to lock up then not be synced with what's on my screen). I've attached two screens shots. The first shows what it looks like after I save (:w) and this happens. The second shows what happen when I seek down the file after the lock up (you can see the line that starts with "general.py" is just floating in the middle where it shouldn't be). I'm using /frazer01/software/vim-20151105/bin/vim.

![screen shot 2015-11-18 at 2 01 16 pm](https://cloud.githubusercontent.com/assets/755960/11255936/df2adcb0-8dfd-11e5-9f09-d0c32ffeffde.png)
![screen shot 2015-11-18 at 2 02 53 pm](https://cloud.githubusercontent.com/assets/755960/11255935/df2a1316-8dfd-11e5-84e1-a841bc5d9d4b.png)

**Comment by tatarsky** [comment]
OK. Nothing leaping to mind but I'll look around for any known bugs with vim and Lustre. I assume you are editing a file located on Lustre as well.

**Comment by cdeboever3** [comment]
Yes I'm editing files on Lustre. I haven't been editing files that aren't
on Lustre so I don't have a comparison unfortunately.

**Comment by tatarsky** [comment]
I'm guessing its Lustre related but I don't really know for sure. One thing if its fairly easy to reproduce that might be interesting is try the same vi on a node which currently does NOT have the added flock support. Whenever I see issues involving some lag on a file write I assume locking may be involved....

**Comment by tatarsky** [comment]
Only other item with weird tty items is it could actually be TERM oddities. Is this via mosh?

**Comment by tatarsky** [comment]
TERM or LANG actually.

**Comment by cdeboever3** [comment]
This is via mosh. I can try working through SSH and see if the problem
appears. It's fairly infrequent though.

**Comment by tatarsky** [comment]
Yeah, I understand. I'll try to reproduce myself in SSH as I usually have to work via it for firewall reasons. Whenever I see status lines in places where they aren't supposed to be I assume some chunk of tty escape sequence didn't make it correctly.

**Comment by tatarsky** [comment]
So one thing I do not grasp is why samtools seems to be doing some I/O to the local drives on HN01. It is routinely in the top write percents on the sda/sdb disks (which are a RAID1)

Which is odd as I show it being configured to run from Lustre and outputing to Lustre.

Is there some tmp use I don't see?

Reason I mention this is the boot drives are very busy. Partly from Mysql (See #62) but partly apparently from samtools.

**Comment by djakubosky** [comment]
I don't think it should be doing any local I/O

On Thursday, November 19, 2015, tatarsky notifications@github.com wrote:

> So one thing I do not grasp is why samtools seems to be doing some I/O to
> the local drives on HN01. It is routinely in the top write percents on the
> sda/sdb disks (which are a RAID1)
> 
> Which is odd as I show it being configured to run from Lustre and
> outputing to Lustre.
> 
> Is there some tmp use I don't see?
> 
> Reason I mention this is the boot drives are very busy. Partly from Mysql
> (See #62 https://github.com/frazer-lab/cluster/issues/62) but partly
> apparently from samtools.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/43#issuecomment-158149612.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
Its very odd as atop things samtools is. I'm trying to dig into it.

**Comment by tatarsky** [comment]
Ah, although I note that @nariai is also using samtools.

**Comment by nariai** [comment]
It might be a case that ROSE software, which is a python package that internally uses samtools might be using some local space. I will take a look at this.

**Comment by tatarsky** [comment]
I don't see it with lsof.

**Comment by tatarsky** [comment]
So I'm not sure what I'm seeing. But some load is being added to the local drives by something besides mysql. I'm just trying to chase down latency issues on the head node so not critical but if you spot something let me know.

**Comment by tatarsky** [comment]
Don't forget BTW the head nodes have a 4TB scratch area....on a separate disk.

**Comment by tatarsky** [comment]
So I made one minor change recently that I don't know if it was involved or not but I'm noting I did it. The Ganglia `gmetad` was doing fairly constant write of its RRD files due to the fairly large metric collection I'm attempting. I configured what is called the `rrdcached` to stagger and journal those writes.

While the writes are to the _local_ filesystem I'm just marking in this that I did it.

**Comment by tatarsky** [comment]
Re-open if still an issue. I've let this sit as a placeholder but am cleaning.
