### ISSUE TITLE
install pandoc

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#47]
http://pandoc.org/installing.html 

I imagine this would be useful systemwide but I can install in a module if need be.

**Comment by tatarsky** [comment]
This guy seems to have an RPM build for pandoc:

https://petersen.fedorapeople.org/pandoc-standalone/README.html

Do you want to try it?

**Comment by cdeboever3** [comment]
Sure let's try that.

**Comment by tatarsky** [comment]
Added to head node one only:

```
 pandoc        x86_64        1.12.4.2-1          pandoc-standalone        7.1 M
```

**Comment by tatarsky** [comment]
(Advise if it works and will go to all)

**Comment by tatarsky** [comment]
Checking if it worked on head node and will add to all.

**Comment by cdeboever3** [comment]
I was able to install pypandoc on the headnode but I'm still working on
getting the code working to actually test it. Might be a couple days.

**Comment by tatarsky** [comment]
I'll probably start the process of pushing it around anyway. Just checking. Not a rush. A bit buried myself.

**Comment by tatarsky** [comment]
This software was deployed. Re-open if not found to be working.
