### ISSUE TITLE
Java job quit due to unable allocate memory

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#49]
Hi @tatarsky, I had this error when I run java jobs. 
My script is at

```
/frazer01/projects/CARDIPS/pipeline/WGS/script/WGS_pipeline_GATK_v02_20151104.sh
```

Basically I reserved memory for 8 cores using 

```
-l h_vmem=4G
-pe smp 8
```

Theoretically I should have 32G memory to use
And in the java command, I specified:

```
java -Xms30g -Xmx30g
```

However, I always got this error:

```
Error occurred during initialization of VM
Unable to allocate 988352KB bitmaps for parallel garbage collection for the requested 31627264KB heap.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Similarly, if I reserve 4 cores for the job, I can only explicitly use 12G in java (instead of the expected 16G). 
Any idea why this might happen?

Thanks!

**Comment by tatarsky** [comment]
Its complaining about the heap which if I recall correctly is not the same as the virtual memory we are making folks request via h_vmem. Java has some complex methods of allocation.

Give me a bit this morning to clear the Monday entropy and I'll review as I've seen this before.

**Comment by tatarsky** [comment]
I'll have to wait for an open node to debug a notch further. There is a debug option to Java which shows to calculated memory requirements. There are numerous examples of this class of debug out on the net for Java code we can take a look at.

**Comment by nariai** [comment]
It might be a case that the 32GB reserve in memory is not enough to run Java program with 30GB heap size.
Maybe 32GB reserve can only accommodate Java program with 20GB heap size, or something like that.
If you want to use the 30GB heap size in your Java program, maybe you should reserve, say, 42GB in total in SGE when submitting a job.

**Comment by hurleyLi** [comment]
Yes, it looks like the case. coz when I do -l h_vmem=6G (for 8 cores), the job won't crash when I specify 30G in Java. I guess it's a general problem for java program?

**Comment by nariai** [comment]
Yes, I had a similar experience in the SGE in the past.

**Comment by tatarsky** [comment]
I actually see the same in many schedulers that enforce the virtual memory limit. There is a debug flag to java to cast some light on the heap sizes but I've been too busy today to dig it up. Basically the strategy discussed above is correct but IIRC that debug flag can assist in deciding the requested memory. Maybe more time tomorrow.

**Comment by tatarsky** [comment]
So I've reviewed this a chunk but would need to experiment a bit to give you real advice. One of my old methods was using `jmap` or `jcmd` which can I believe talk to a running Java process and get some live memory stats. 

But the basic gist is going to remain that the heap should be some percentage less than the requested h_vmem. 

When the queues clear a bit I'll give a couple of examples if I get the syntax right.

**Comment by tatarsky** [comment]
So some brief playing based on old notes and Google hits leads me back to I believe this discussion if you want a gory answer:

http://stackoverflow.com/questions/18708085/sge-h-vmem-vs-java-xmx-xms

If I follow its directives of using for a qlogin similar to yours I believe:

```
 > qlogin -l h_vmem=4G -pe smp 8
n6> java -Xms30g -Xmx30g -version
Error occurred during initialization of VM
Unable to allocate 988352KB bitmaps for parallel garbage collection for the requested 31627264KB heap.
```

So then we cut the GCThreads per that writeup:

```
n6> java -XX:ParallelGCThreads=1  -Xms30g -Xmx30g -version
OpenJDK Runtime Environment (rhel-2.5.1.2.el6_5-x86_64 u65-b17)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)
```

Aka it can allocate the heap when only doing one thread. 
I was able to walk that up to 8 GCthreads and then it can't allocate.

I don't recall the impact of playing with those thread counts. I don't do much Java.

I believe this is a good rule of thumb compared to all that:

Moderately increased the SGE memory requests by 10% or so

**Comment by cdeboever3** [comment]
It seems that allowing more GCthreads should speed up garbage collection
(although using more than one GCthread will use multiple processors).
Should we limit garbage collection to the number of threads requested for
the job?

**Comment by tatarsky** [comment]
I honestly have no idea. I would I guess experiment a notch. I suspect it depends on just how much of the actual code needs that GC...

**Comment by cdeboever3** [comment]
Yep, we are going to experiment some. Thanks

**Comment by tatarsky** [comment]
And adding `-XX:+PrintFlagsFinal` I have noted but without much details as to why ;)

**Comment by cdeboever3** [comment]
> And adding -XX:+PrintFlagsFinal I have noted but without much details as to why ;)

@tatarsky, missing word there? I don't understand.

For posterity, we've found that by default, java parallelGC uses [5/8 of available threads when # threads > 8](https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/parallel.html). We think that if a program doesn't need much GC, cutting the GC threads won't affect the run time much (whereas running 4 java programs on a node where they each want 20 threads for GC might be bad). We are going to try decreasing to 1 thread and walking up from there. When we have a better understanding, we'll write up some points on the wiki.

**Comment by nariai** [comment]
It might be worth checking the -XX:+UseSerialGC as well..

**Comment by tatarsky** [comment]
The java flag `-XX:+PrintFlagsFinal` produces copious extra output as to the final settings the JVM used to do the run.  I have that noted in some old items on this topic to debug Java matters.

```
java -XX:ParallelGCThreads=1 -XX:+PrintFlagsFinal -Xms30g -Xmx30g -version
[Global flags]
    uintx AdaptivePermSizeWeight                    = 20              {product} 

    uintx AdaptiveSizeDecrementScaleFactor          = 4               {product} 

    uintx AdaptiveSizeMajorGCDecayTimeScale         = 10              {product} 

(copious copious output of flag final settings)
```

**Comment by cdeboever3** [comment]
Ah ok thank you. `java -XX:+PrintCommandLineFlags -version` gives some of
the default parameters as well.

**Comment by hurleyLi** [comment]
It looks like when I use 

```
-XX:ParallelGCThreads=1
```

I can give more memory to java, and it won't crash, and the job will run faster.
I'll close this issue

**Comment by cdeboever3** [comment]
Added some [text](https://github.com/frazer-lab/cluster/wiki#using-java) to the wiki about using Java.
