### ISSUE TITLE
Default modules path

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#5]
Use /frazer01/repos/environments/modulefiles as default path where modules looks for modulefiles.

**Comment by tatarsky** [comment]
This is now in test on hn1 only. Soon all nodes/headnodes

```
$ module avail

-------------------------------------------------------- /frazer01/repos/environments/modulefiles ---------------------------------------------------------
EPACTS/3.2.6(default) git/2.6.2(default)
```

I am likely to recompile git to confirm to having the version in the top level path rather than down a subdir to be similar to the others per #17

**Comment by tatarsky** [comment]
Now on all nodes/headnodes.
