### ISSUE TITLE
Generic Statement of Scope Process

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#50]
I am declaring the scope of work line item that involved the building of the cluster to be complete. Unless anyone disagrees. 

There are basically three parts to my work scope:
1. Coordinate the install and get jobs running on the cluster with some level of software builds to confirm operational. This does not mean all software needed will be built in this phase or that all tuning will be completed. Such items are handled via the maintaining line item that I list next.
2. Maintain the cluster. I have allocated 20 hours per month under my "UC discount" rate and terms to ongoing support. Basically this is a class of support in which I do my best to be responsive as part of the greater goal of genome research started by my time at UCSC. Git issues will be processed as received during my regular work hours (M-F 8:00AM -5:00PM CST)
3. Migrate the old cluster to the new one. This is a separate line item and you will see the start of some requests on that topic to SDSC today.

**Comment by tatarsky** [comment]
Kelly request for a discussion of item three in todays call noted.

**Comment by hirokomatsui** [comment]
For the item three:
- Hiroko is going to SDSC to check the compatibility with the switch and the cable in this week.
- Paul will request to SDSC to run the cable.
  Our plan is to connect the old and new cluster with the internal network by the end of the first week of December.

**Comment by tatarsky** [comment]
I think we're good on this and basically tracking item 3 above via #33
