### ISSUE TITLE
1G link to old cluster

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#51]
We will attempt to get a 1G link in some form between the switches in K36 over to our new cluster in CC36.

**Comment by tatarsky** [comment]
SDSC ticket request made to determine our options.

**Comment by tatarsky** [comment]
SDSC responded and copper (CAT5) is an option. Which is far far cheaper. We still have to purchase a cable but its very low cost. 

However, I need to confirm with @hirokomatsui that the old cluster data switch has a free copper (CAT5) port. We looked at it together and I noted it had free fiber ports (SFP) but I do not recall if there was a free CAT5 port.

Can we perhaps check that?

**Comment by hirokomatsui** [comment]
I'll have to go there to see, let you know.

**Comment by tatarsky** [comment]
You might if there is an open CAT5 port just ask if SDSC can order whatever length/color cable the prefer and just recharge us.

**Comment by hirokomatsui** [comment]
![img_1101](https://cloud.githubusercontent.com/assets/15457142/11283673/ba5c58ec-8eba-11e5-8e41-9000326c983b.JPG)
![img_1102](https://cloud.githubusercontent.com/assets/15457142/11283672/ba5b4f42-8eba-11e5-94cf-08d4dc181085.JPG)

We have two switches, one for the system maintenance (top with the red cables, 3COM Baseline Switch 2824 sCBLUG24A) and the other for the internal network (bottom with the blue cables, Cisco SG 102-24 24-Port Gigabit Switch). If I remember it correctly, we will use the bottom switch to connect to the new cluster system.
I went to the Cisco web site but can't find exactly the cable compatibility:
http://www.cisco.com/c/en/us/support/switches/sg102-24-compact-24-port-gigabit-switch/model.html

Maybe you have better idea?

**Comment by tatarsky** [comment]
So it looks like to me the next to the SFP ports (far right) there are two free combo copper ports (they share the same port number with the SFP) to the immediate right of the last blue copper cables.

Those are just "standard" CAT5E or CAT6 cables. Any source of them is fine. Boils down to getting the right length. Jeff said 100ft. 

So we just need to ask SDSC if they can pull the cable and if they simply want to recharge us for one they purchase to the proper length (to reduce back and forth). I suspect they have such cables available from past dealings. More than happy to order but want to confirm length.

Do you wish to directly ask them or should I attempt via ticket? (Not sure if you are still down there)

**Comment by hirokomatsui** [comment]
Can you send them a ticket? I think they need it anyway. Thanks!

**Comment by tatarsky** [comment]
Underway!

**Comment by tatarsky** [comment]
Request made. Approval given to them to recharge for cable. Assume that is OK.

**Comment by tatarsky** [comment]
I've seen no confirmation that my request was seen...might be worth somebody else asking "Just checking if this was in progress"

**Comment by hirokomatsui** [comment]
I'll send a ticket too.

**Comment by tatarsky** [comment]
Looks like the cable is run and they are offering to plug it in for us.

Are we reasonably confident to try that remotely or do you want to coordinate it personally with you onsite?

The worst that could happen would be unexpected IP address conflict from something that wasn't obvious in the old cluster configs. 

The "cure" would be rapidly unplugging the cable or disabling the port (assuming the switch IP itself was not in conflict)

I do not know your folks schedule this Thanksgiving week but I could attempt to draft a response to Tim if you want me to try remotely.

**Comment by tatarsky** [comment]
I will get them to plug one end of it in on the new cluster side so that is ready and wait for response on schedule for other side. Just being careful.

**Comment by hirokomatsui** [comment]
I think Paul and I can schedule to plug them either tomorrow or after Thanksgiving (anytime for me). I'll be there to plug the other end and in the case we need unplugging.
Although I think the risk that we lose the connection to the servers are low, please let us know if anyone has any critical problem.

**Comment by tatarsky** [comment]
My gut feeling is just to wait until after the holiday. I have relatives coming today and while I agree I doubt there is going to be a problem you know computers and the way they like to disprove that. If you feel its important to get done tomorrow I will work with you to do so however so just advise!

**Comment by hirokomatsui** [comment]
I totally agree with you. Just let me know when's good time for you after the holiday.
Happy holiday!

**Comment by tatarsky** [comment]
I'll do some more checks to make sure nothing is lurking as an IP conflict on old and new. Anytime good for you is fine BTW.

**Comment by tatarsky** [comment]
I don't see anything obvious that will occur when these two networks connect. If you can give me a rough time range when you think you want to attempt this it would be helpful as I still have relatives here for a bit today ;)

**Comment by tatarsky** [comment]
I have to go fix a tire matter on my wife's car but will be back before 10:00AM your time.

**Comment by tatarsky** [comment]
Its going to be closer to 11:00AM before I am back. Just FYI.

**Comment by hirokomatsui** [comment]
I'll go there tomorrow at 11am. Or anytime tomorrow is fine.

**Comment by tatarsky** [comment]
Sounds good. I am also now back for the rest of the day. Tires being replaced.

**Comment by tatarsky** [comment]
Holding the 11:00AM your time slot for today if still desired.

**Comment by hirokomatsui** [comment]
Yes, I'm running there soon.

**Comment by tatarsky** [comment]
Sounds good. My belief it you will want to attach the other end of the cable (which I hope they've left hanging obviously) into one of those end ports on the Cisco. Possibly useful picture with circled suggested port attached! Feel free to call my office 608-271-6817

![cable](https://cloud.githubusercontent.com/assets/6439722/11509911/86d20ce0-9826-11e5-84b6-b5e5bfc9d4f8.JPG)

**Comment by hirokomatsui** [comment]
it's plugged.

**Comment by tatarsky** [comment]
Checking...

**Comment by tatarsky** [comment]
I can see old cluster nodes from new cluster.

**Comment by hirokomatsui** [comment]
Cool!

**Comment by tatarsky** [comment]
And NFS exports.

```
fl-hn1 [~]$ showmount -e 10.0.0.200
Export list for 10.0.0.200:
/exports/raid2 10.0.0.0/24,169.228.63.71
/exports/raid  10.0.0.0/24,169.228.63.71
/exports/home  10.0.0.0/24,169.228.63.71
/exports       10.0.0.0/24,169.228.63.71
```

**Comment by tatarsky** [comment]
So I believe the link is good. I am looking for any conflicts.

**Comment by tatarsky** [comment]
I have double confirmed by SSH'ing to flc from the hn1 system:

```
fl-hn1 [~]$ ssh 10.0.0.200
paul@hn:~> 
```

So we are on the same 1G network OK.

**Comment by tatarsky** [comment]
Confirmed OK so far. Next steps would involve re-install of desired old nodes with CentOS and assignment of either same IP or a new one in same 1G subnet. But the basics are there. 

As a side benefit if it is desired to make some NFS mounts between old and new they do not require external IP allows. Some /etc/exports mods may be required.

**Comment by hirokomatsui** [comment]
Nice. Can we update /etc/hosts on the both servers to use the local IP address with the hostnames?

**Comment by tatarsky** [comment]
Yep.

**Comment by tatarsky** [comment]
I will add a puppet rule to do so after lunch. All systems? Or just head nodes?

**Comment by tatarsky** [comment]
Note BTW I am using an internal DNS server as well but will make things consistent.

**Comment by tatarsky** [comment]
Speeds seem reasonable.

**Comment by hirokomatsui** [comment]
It might be better to update all the nodes in the case they see the old node disks.
flh1 is the DNS server and flc is as the client?

**Comment by hirokomatsui** [comment]
Checking the DVD drives on the old compute nodes.

**Comment by tatarsky** [comment]
I would not attempt to merge DNS at this time between old and new. Only noting that when I do things on new its via an internal DNS server. We can talk about host naming merges eventually but for now keep them separate.

**Comment by tatarsky** [comment]
Sounds good on DVD...

**Comment by tatarsky** [comment]
I'll write up next steps when I get back from lunch. If you confirm we can use a CentOS DVD thats one item but in theory if we can't we could rig a network PXE install.

**Comment by hirokomatsui** [comment]
Not merging DNS's totally fine.
They have DVD drives. Pushing old compute nodes to the new cluster will affect to all the project. We'll discuss and schedule it.
BTW, they set the network cable so nicely, which is running under the floor!

**Comment by tatarsky** [comment]
Sounds like a good Skype call but we have all the ingredients it sounds like to merge when ready!

SDSC's Tim does nice work!

**Comment by tatarsky** [comment]
This link looks solid. Additional items for node migration going back to #33 and some announcement of internal DNS changes in a moment.
