### ISSUE TITLE
something is wrong with .bashrc

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#52]
I have .bashrc with just 3 lines:

export PATH="/frazer01/home/matteo/software/R-3.2.2/bin:$PATH"
export PATH="/frazer01/home/matteo/software/anaconda3/bin:$PATH"
export PATH="/frazer01/home/matteo/software/anaconda3/bin/python:$PATH"

But if I run "which R" or "which python" I stil get: /usr/bin/python or /usr/bin/R

Is there anything I am doing wrong?

Thanks!

Matteo

**Comment by cdeboever3** [comment]
Make a .bash_profile file and add "source .bashrc" to the first line. Sign
out and sign back in. Does that work as expected?

**Comment by tatarsky** [comment]
Correct. The bash man page has details of the execution order.

In general to make various distro bash assumptions cleaner I tend to do:

.bash_profile

```
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
```

If we wish to make that a default for people we can create skeleton dotfiles.

**Comment by cdeboever3** [comment]
Yes can we make skeleton .bash_profiles please? I'd say for current users
that don't already have a .bash_profile, you can make the one you've posted
here and you can do it automatically for new users. thanks

**Comment by s041629** [comment]
it works. Thanks!

**Comment by tatarsky** [comment]
The skel default files are in /etc/skel. I've copied for those that didn't have .bash_profile the skel version. The user accounts were not created with adduser (they were copied from /etc/passwd and /etc/shadow) so there were no default dotfiles made. No `.bashrc` was copied for people. 

Future accounts I assume will be made with adduser.

**Comment by cdeboever3** [comment]
Cool thanks. Matteo wasn't the first one with that problem.

**Comment by tatarsky** [comment]
Believed resolved going forward with a skel template on account add.
