### ISSUE TITLE
installing IRKernel to create create R Jupyter notebooks

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#55]
I am trying to install IRKernel on R. 
On my local machine, I simply ran 
install.packages(c(rzmq,'repr','IRkernel','IRdisplay'), repos = c('http://irkernel.github.io/', getOption('repos')))
IRkernel::installspec()

And everything worked fine. On flh1 I am continuously getting errors
g++ -std=c++0x -I/home/matteo/software/R-3.2.2/lib64/R/include -DNDEBUG -I../inst/cppzmq -I/usr/local/include    -fpic  -g -O2 -c interface.cpp -o interface.o
interface.cpp:22:17: error: zmq.h: No such file or directory

So I downloaded rzmq and installed it manually: install.packages("~/software/rzmq_0.7.7.tar.gz", repos = NULL, type="source"), but I got the same error.
I am sure there is a simple explanation why this is happening.

Thanks!

Matteo

**Comment by tatarsky** [comment]
Where is zmq.h in your include path?

**Comment by tatarsky** [comment]
On your local machine to be clear. What I am asking is are you getting those header files from something you built or a system install?

`locate zmq.h` might be useful if your local system has mlocate installed.

**Comment by tatarsky** [comment]
libzmq from EPEL is version 2.2. There is a repo for a more recent version if you need that. Please confirm if you want these development libraries at a system level or you are building them and having trouble setting includes to your locally built version.

**Comment by s041629** [comment]
I have found zmq.h in:
./software/anaconda3/pkgs/zeromq-4.1.3-0/include/zmq.h
./software/anaconda3/include/zmq.h

I have tried to copy it into ./software/R-3.2.2/lib64/R/include, which was the error I got before, but now I get a new error:
g++ -std=c++0x -shared -L/home/matteo/software/R-3.2.2/lib64/R/lib -L/usr/local/lib64 -o rzmq.so interface.o -lzmq -L/home/matteo/software/R-3.2.2/lib64/R/lib -lR
/usr/bin/ld: cannot find -lzmq

I am just trying to download the R packages needed to set the jupyter notebook with R.

**Comment by s041629** [comment]
I don't know if this answers your last question...

**Comment by tatarsky** [comment]
Thats probably not it. Thats a python glue item. Let me load version 3 zeromq at the system level on head node one and see if that resolves it for you. One moment.

**Comment by tatarsky** [comment]
I would remove the item you copied and see if you can now compile and link. I have added zeromq3-devel to the head nodes.

**Comment by s041629** [comment]
It works! I get other errors due to dependencies but I think it will just be a matter of installing the dependencies manually. Thanks!

**Comment by tatarsky** [comment]
So the basic gist here is as follows:

We load system level development libraries when it makes sense compared to everyone building their own copy. While I have tried to pre-load many common items, if you encounter such a thing, just drop me a note and I can usually locate the needed RPM fairly quickly.

I normally load devel (library and includes) on the head nodes for compilation and runtime (libraries only) on nodes.

Hope that makes sense.

**Comment by tatarsky** [comment]
And by "drop me a note" I mean a Git issue (sorry for confusion)

**Comment by s041629** [comment]
I installed all the dependencies and now the notebook works fine. Thanks!

**Comment by tatarsky** [comment]
Coolz. Closing.
