### ISSUE TITLE
Perl module XML/Simple.pm installation (for running MEME)

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#56]
I guess we need Perl module XML/Simple.pm to be installed.

/software/meme_4.10.2/bin/meme-chip -oc cC3_200 -index-name meme-chip.html -order 1 -db /software/meme_4.10.2/db/motif_databases/MULTI/jolma2013.meme -meme-mod zoops -meme-minw 6 -meme-maxw 30 -meme-nmotifs 3 -dreme-e 0.10 -centrimo-score 5.0 -centrimo-ethresh 10.0 cC3_200.fa
Can't locate XML/Simple.pm in @INC (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /software/meme_4.10.2/bin/meme-chip line 101.
BEGIN failed--compilation aborted at /software/meme_4.10.2/bin/meme-chip line 101.

**Comment by tatarsky** [comment]
Added to head nodes and nodes. See if that does it!

**Comment by nariai** [comment]
Now it is working! Thanks.

**Comment by tatarsky** [comment]
Note that n6 and n16 are in progress. They are rather busy....so soon.
