### ISSUE TITLE
ImageMagick and Ghostscript installation

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#57]
When running meme, I got the error message below:

Starting meme: meme cC3_200/seqs-sampled -oc cC3_200/meme_out -dna -mod zoops -nmotifs 3 -minw 6 -maxw 30 -bfile cC3_200/background -revcomp -nostatus
Warning: Can not convert EPS file to PNG as no install of Image Magick or Ghostscript is usable.

I guess both ImageMagick and Ghostscript are standard tools, and hence it will be convenient for us to have them installed in the head nodes / compute nodes (i.g. convert command). Thanks!

**Comment by tatarsky** [comment]
Ghostscript was already there but added ImageMagick which adds convert.

Can you verify on Head Node 1 only that you have all the items? Then I'll push as a larger batch if others come up needed.

**Comment by tatarsky** [comment]
Eh, never mind, pushed the above to all the nodes. Feel free to just tack on other items this code needs here and I'll catch them.

**Comment by tatarsky** [comment]
Similar note some nodes are quite  busy but on head nodes.

**Comment by tatarsky** [comment]
OK now done on all nodes ;)

**Comment by nariai** [comment]
Yes, I confirmed that MEME now generates PNG files!
(I had to modify config.h and re-compile the MEME suite.)
