### ISSUE TITLE
Install mosh

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#6]
https://mosh.mit.edu/

May require a little magic for centos.

**Comment by tatarsky** [comment]
Built a mostly recent version of mosh from an existing RPM spec file. Please test to head node 1 only. Would like to try to keep it as an RPM just for simplicity. Remember currently SSH is restricted to on campus IPs until I validate vendor installs are safe for exposure to big bad Internet.

**Comment by cdeboever3** [comment]
mosh works testing from outside the UCSD network. Thanks

**Comment by tatarsky** [comment]
Cool. SSH is now open to "the world" and as such so will mosh. 

Added to second head node. Re-open if that doesn't work but should be good to go.
