### ISSUE TITLE
NIS restart

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#60]
Somehow, my home directory was set up as 
/frazer01home/hiroko
instead of 
/frazer01/home/hiroko
in the /etc/passwd. I've changed the file on flh1.
Paul, if it's easy for you, can you restart NIS server on flh1 and the slave on flh2, also overwrite the /etc/passwd on the compute nodes? I don't think it will affect anyone's working.

**Comment by tatarsky** [comment]
Ah, thats my mistake then. NIS does not need to be restarted to update and currently NIS is not in actual use as it broke something with SGE. I'm checking for consistency and I intend to replace NIS (which is obsolete) with puppet now that I am done with puppet.

**Comment by tatarsky** [comment]
Correcting.

**Comment by hirokomatsui** [comment]
I think flh2's still NIS slave, looking at flh1's setting?

**Comment by tatarsky** [comment]
Yes for now.

**Comment by hirokomatsui** [comment]
Can I restart NIS slave on flh2? My home directory's not corrected on flh2.

**Comment by tatarsky** [comment]
Just a moment. I am correcting another item.

**Comment by tatarsky** [comment]
NIS not being consulted for now. I'm going to replace it due to SGE matter.

**Comment by tatarsky** [comment]
(With puppet based sync...)

**Comment by tatarsky** [comment]
Would you like me to clear error state on 2233 and 2234?

**Comment by hirokomatsui** [comment]
I'll work on that. Thanks!
