### ISSUE TITLE
Experiment with Mysql data on Lustre

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#62]
I'm noting a fair level of I/O from mysql to the HN01 boot drives. I'd like to setup Mysql on HN02 as a test of using Lustre for its data areas. This won't happen probably this week but this is to remind me it would be good to understand if this is possible or if we should consider some separate disk for Mysql.

**Comment by nariai** [comment]
We can try running Mysql on HN02 using Lustre data area, although it might not be the best configuration  considering I/O speed (local disk vs. Lustre).

**Comment by tatarsky** [comment]
Agreed. Perhaps a symlink of a database area. I'll mull this one over but won't interrupt the HN01 mysql.

**Comment by tatarsky** [comment]
Experiment is now in #114
