### ISSUE TITLE
Just checking if having a call today

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#64]
I don't have much except on Monday I believe we will attempt the 1G connection to the old cluster.
Might want to update Dr. Frazer on that status and that the ball is in our court. 

I am around if Skype desired but also happy to say "Happy Thanksgiving!"

**Comment by cdeboever3** [comment]
I don't need a call. Someone can send a quick email to Kelly about the
migration but I think she knows it's happening within the timeframe we
discussed last week. Have a good Thanksgiving.

**Comment by nariai** [comment]
We can skip a call today, since neither of us (Hiroko, Hurley, and I) has anything to discuss face-to-face.
Happy Thanksgiving!

Naoki

**Comment by tatarsky** [comment]
Sounds good! Happy Thanksgiving to all and see you next week!
