### ISSUE TITLE
Shapeit-2.20 install

### ISSUE THREAD

**Issue by nariai** [frazer-lab/cluster#65]
I tried to install an executable binary of Shapeit-2.20 https://mathgen.stats.ox.ac.uk/genetics_software/shapeit/shapeit.html#download
under the directory:
/software/shapeit-2.20/

However, after I extracted the executable, I got an error as below:
[/s/s/bin]fl-hn1 $ ./shapeit
./shapeit: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./shapeit)
./shapeit: /frazer01/software/gcc-4.8.5/lib64/libstdc++.so.6: version`CXXABI_1.3.8' not found (required by ./shapeit)
./shapeit: /frazer01/software/gcc-4.8.5/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./shapeit)

Could you instruct me how I can get around this?

Naoki

**Comment by cdeboever3** [comment]
Does loading the gcc module (load module gcc) fix it?

**Comment by nariai** [comment]
No, I still get the same error message..

**Comment by tatarsky** [comment]
Not possible to run. Glibc is too new. See if version compiled for RHEL 6.X.

Paul Tatarsky
paul@clusterguys.com

**Comment by nariai** [comment]
Unfortunately, it looks like there is no other binary version or source code available.
Maybe I need to run Shapeit on the old cluster in the mean time..

**Comment by tatarsky** [comment]
If thats the way they distribute it you have no real options. Old versions?

**Comment by tatarsky** [comment]
I show on that page a glibc 2.12 download. While I am remote and cannot test, that should work...

I will be back shortly and can check if you do not beat me to it.

**Comment by nariai** [comment]
It is working now!! Thanks. I thought that the link was for an older version of the Shapeit.
I'll close this.

Naoki

**Comment by tatarsky** [comment]
Excellent! Happy Thankgiving!
