### ISSUE TITLE
HW alert

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#66]
There are some orange/red lights on on the servers. Do we need to report to HLI?

fl-mdt1
Probably this is normal, I've just notice the orange...
![img_1109](https://cloud.githubusercontent.com/assets/15457142/11512715/59b67d6a-9824-11e5-9f60-a8c3b894d461.JPG)
![img_1112](https://cloud.githubusercontent.com/assets/15457142/11512724/6233d668-9824-11e5-90a2-3657f8f2e820.JPG)

fl-ost2
The exclamation mark is lighting orange
![img_1110](https://cloud.githubusercontent.com/assets/15457142/11512778/a706e582-9824-11e5-8549-0b3a55665c55.JPG)

fl-n-8
I don't see any error for this
![img_1115](https://cloud.githubusercontent.com/assets/15457142/11512869/320ee918-9825-11e5-8d84-3ae2ab1bf272.JPG)

**Comment by tatarsky** [comment]
I am aware of all of these and they are lower level warnings based on what is called a multipath preference of the SAS controllers.

I am looking into the proper way to tell Intel's Lustre to use the same preferred path of the array controllers. Right now basically from my looking at it they are reversed on a couple of luns. 

It is not a performance or redundancy problem but I would prefer to determine a solution as I would also prefer the light as orange. I run into it from time to time and I believe the tweek is in the IEEL config which I am learning slowly. 

Its on my list for a conversation with AHPC but I believe will end up being an Intel question.

**Comment by tatarsky** [comment]
Sorry "I would prefer the orange light to not be on" ;)

**Comment by tatarsky** [comment]
Oh and for fl-n-8 thats the red identity light I turned on for AHPC to locate the drive to replace.

Believe I turned it off a moment ago.

**Comment by tatarsky** [comment]
And I have confirmed all SAS paths are redundant and active. Its just a matter of seeing if I can tell IEEL to follow the same controller preference as the array. I have a guess but its something I want to do only in consultation with Intel. I've asked AHPC what the process is for getting a ticket.

**Comment by tatarsky** [comment]
Intel has provided a suggested fix to the orange light matter. I will deploy it shortly after I review it.

**Comment by tatarsky** [comment]
This matter is now resolved. The added configuration changes the multipath to better communicate with the Dell array controller so that its view of the preferred path is given priority. All lights are showing green at least from the console. If on your next trip you see otherwise please advise. I will be adding email alerts as part of Nagios #59
