### ISSUE TITLE
Java error with GenePattern

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#69]
I am trying to run a R script that connects to GenePattern via rJava and I get this error when I use big input files (with input file >1MB, but it works with a small 50kb file):

Error in run.analysis(gp, "urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00270:6", : ; nested exception is: 
    java.net.ConnectException: Connection timed out: ; nested exception is: 
    java.net.ConnectException: Connection timed out

Is there a solution to avoid connection time out?

Thanks!

Matteo

**Comment by tatarsky** [comment]
Is there a way to test that the service it is connecting to is actually up? The above suggests to me it is not. Do you know what sort of connection is made? (http/ftp/something else)

**Comment by tatarsky** [comment]
Oh, wait you said it works with small....is there an option to increase timeouts?

**Comment by tatarsky** [comment]
Or schedule a time in which you run the application with the timing out sized file and I will look at the network packets. I am around today we just need to coordinate what system and when.

**Comment by s041629** [comment]
I am having one running now. It wasn't working with a 3MB input file but it seems to be working now with a 1.3MB file. It's a jupyter notebook called kataegis.SSGSEA.run

**Comment by tatarsky** [comment]
I don't show any obvious open connections to what I assume would be `broad.mit.edu`. Basically it could also be load on their service if you see variations of connect size. There is no magic solution here. I would look for options that allow you to alter default timeout windows or email them for suggestions. 

If you can confirm the host that provides the service I can graph latency to it and packet loss.

**Comment by tatarsky** [comment]
Does the jupyter notebook BTW use an Apache style POST to get the INPUT file? I don't know the notebook network parameter options. 

Aka the does the timeout perhaps come between your remote Notebook client and the python running on HN01 or is it definitely involving broad?

**Comment by s041629** [comment]
I tried also directly from R, but the problem remains. I asked one of developers: if they know how to solve it I will let you know. Thanks!

**Comment by tatarsky** [comment]
Do you have an example of the above? Debugging R networking is easier than Java.

**Comment by s041629** [comment]
here is the code (you can find it also at /projects/breast_cancer/kataegis/scripts/gsea/kataegis.SSGSEA.run.r)

home = "/frazer01/projects/breast_cancer/kataegis"

setwd(home)
suppressPackageStartupMessages(library(GenePattern))

username      = "s041629"
password      = "GenePattern"
servername    = "http://genepattern.broadinstitute.org/gp"
gct_file      = paste(home, "gsea/expression_kataegis.gct", sep = "/") # don't know why we need absolute path
ssgsea_folder = paste(home, "gsea/ssgsea"                 , sep = "/")
msigdb_folder = "/publicdata/MSigDB_20151201"

runSSGSEA = function(gct_file, gene_set_name, gene_set_file, msigdb_folder, ssgsea_folder, username, password, servername)
{
    cat("Running", gene_set_name, "...")

```
gp <- gp.login(servername, username, password)

gene_set_db_file = paste(msigdb_folder, gene_set_file, sep = "/")
out_folder       = paste(ssgsea_folder, gene_set_name, sep = "/")

if (file.exists(out_folder) == FALSE)
{
    ssGSEAProjection.result <- run.analysis(gp, 
                                            "urn:lsid:broad.mit.edu:cancer.software.genepattern.module.analysis:00270:6", 
                                            input.gct.file               = gct_file, 
                                            output.file.prefix           = gene_set_name, 
                                            gene.sets.database           = gene_set_file, 
                                            gene.sets.database.file      = gene_set_db_file, 
                                            gene.sets.database.list.file = "", 
                                            gene.symbol.column           = "Name", 
                                            gene.set.selection           = "ALL", 
                                            sample.normalization.method  = "rank", 
                                            weighting.exponent           = "0.75", 
                                            min.gene.set.size            = "10", 
                                            combine.mode                 = "combine.add")

    download.directory <- as.character(job.result.get.job.number(ssGSEAProjection.result))
    process.out.files  <- job.result.download.files(ssGSEAProjection.result, download.directory)
    processed.out.file <- as.character(process.out.files[1])
    file.rename(download.directory, out_folder)
    cat("Done!\n")
}else
{
    cat("Analysis exists.\n")
}
```

}

gene_sets_name = c("Hallmark", "C2", "C3", "IPA_regulators", "MYC_and_NRF2")
gene_sets_file = c("h.all.v5.0.symbols.gmt", "c2.all.v5.0.symbols.gmt", "c3.all.v5.0.symbols.gmt", "IPA_regulators.gmt", "MYC_and_NRF2.gmt")

gene_sets = data.frame(File = gene_sets_file, Name = gene_sets_name, stringsAsFactors = FALSE)
ii = 2
gene_set_name = gene_sets$Name[[ii]]
gene_set_file = gene_sets$File[[ii]]

runSSGSEA(gct_file, gene_set_name, gene_set_file, msigdb_folder, ssgsea_folder, username, password, servername)

**Comment by tatarsky** [comment]
OK, so basically from that code this is an HTTP based download wrapper to 

`genepattern.broadinstitute.org`

Which can also be graphed but see what they say in terms of their usage patterns for it and its load.

**Comment by s041629** [comment]
I will let you know. I have a meeting now and will be back in two hours.

**Comment by s041629** [comment]
I am in contact with Pablo Tamayo (the developer of GenePattern) for this project and he suggested to run directly on the server. Since I don't have many jobs to run, I will simply run them on the server.

Thanks

**Comment by tatarsky** [comment]
OK. Closing for now. Can still graph if desired. Re-open if so.
