### ISSUE TITLE
Install newer git version

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#7]
We are currently at git version 1.8.3.1 but 1.8.5 has some submodule management stuff that would be nice to have. If you can push it forward to 2.something that would be great.

**Comment by tatarsky** [comment]
Noted. Will get to shortly.

**Comment by tatarsky** [comment]
Just as an object lesson in modules please test the following:

```
fl-hn1 [git]$ module add git
fl-hn1 [git]$ git --version
git version 2.6.2.367.g80980a1
```

head node only for now. Will start module replication per #5 shortly.
I will elaborate on the proper way to add to bash scripts shortly.

**Comment by cdeboever3** [comment]
That works:

[~]fl-hn1 $ git --version

git version 1.8.3.1

[~]fl-hn1 $ module add git

[~]fl-hn1 $ git --version

git version 2.6.2.367.g80980a1

**Comment by tatarsky** [comment]
So to make it permanent add to your preferred bash init script:

```
module load git
```

Once you have that line, you can use from then on the `module initadd` command to alter that line for you.
