### ISSUE TITLE
Newer version of zlib?

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#71]
I'm seeing this when I run vcftools:

```
Using zlib version: 1.2.3
Versions of zlib >= 1.2.4 will be *much* faster when reading zipped VCF files.
```

We do a lot of stuff with zipped VCF files. Does it make sense to upgrade zlib?

**Comment by tatarsky** [comment]
The RHEL system zlib sticks with 1.2.3 and there is no clean way to update it "in place".

But a zlib module could be made which sets the LD_LIBRARY_PATH or you can rebuild vcftools with the run path defined to the same area as the module so people don't have to remember to use the module.

**Comment by tatarsky** [comment]
So I've not made a module yet that would basically export LD_LIBRARY_PATH to its lib dir but if you wanted to test/compare speeds:

```
fl-hn1 [~]$ ldd /software/vcftools-0.1.14/bin/vcftools 
        linux-vdso.so.1 =>  (0x00007ffc34951000)
        libz.so.1 => /lib64/libz.so.1 (0x0000003718c00000)
     ...
export LD_LIBRARY_PATH=/software/zlib-1.2.8/lib
fl-hn1 [~]$ ldd /software/vcftools-0.1.14/bin/vcftools 
        linux-vdso.so.1 =>  (0x00007fff70d9b000)
        libz.so.1 => /software/zlib-1.2.8/lib/libz.so.1 (0x00007f7e668dd000)
...
```

That in theory should use the latest zlib. Which unless there are huge differences should be drop in replacement capable via the above method.

**Comment by cdeboever3** [comment]
Thanks I will test.

**Comment by tatarsky** [comment]
I believe this is done. If not just re-open.
