### ISSUE TITLE
Luster allocation

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#73]
Hi Paul,

Do you have any estimate cost for the Luster allocation?
We are going to have the next project which will use ~200TB during the analysis.

**Comment by tatarsky** [comment]
Sorry, are you asking if the currently Lustre can handle 200TB?

 Or the cost of adding more Lustre servers and arrays?

For the first your current Lustre filesystem has 376TB free.

10.8.16.29@tcp0:10.8.16.30@tcp0:/frazer01
                      524T  122T  376T  25% /frazer01

I can guess the costs to add to Lustre based on the past quotes from Advanced HPC. We would be adding only what are called "OSS/OSTs" which represent data storage systems. And in theory we could add just arrays to the existing servers OR servers and arrays to get increased parallel performance. 

We have plenty of metadata systems and space. 

The key item with such an item is if it had to go to bid again. Clarify the above and I can try to carve out the data only costs from the last quote.

**Comment by tatarsky** [comment]
Sorry, that cut/paste of df was not what I wanted. Here is the space on Lustre:

```
df -h 
Filesystem            Size  Used Avail Use% Mounted on
10.8.16.29@tcp0:10.8.16.30@tcp0:/frazer01
                      524T  122T  376T  25% /frazer01
```

**Comment by hirokomatsui** [comment]
This is for the future, but we'd like to know the rough cost to talk with our collaborator.
Realistically adding 500TB will be more reasonable though.

**Comment by tatarsky** [comment]
OK. I can take a guess at it from the bid but it of course is not a binding item and assumes Advanced HPC as the vendor. I could ask for a quote, but if you had to use another bid process it would mess that up. So I'll start with the guess.

**Comment by nariai** [comment]
Yes, I guess a rough estimate of adding arrays (250, 500, or 750 TB) will be good for the moment. Thanks!

**Comment by tatarsky** [comment]
OK, so you don't need another 10G switch at this time as you have two free ports but then we would need to plan/prepare for another 10G switch if additional systems were desired. 

Each OSS server needs a 10G link. There are two 40G links on the switch however which can be split out with a specific cable or you could consider a 40G server link if it was needed. 

The servers if you wanted to add servers and gain parallel performance and redundancy (strongly recommend):

$11,800 each

That included the hardware and I believe the IEEL (Intel Lustre) licenses for that server to operate. We might need to double check that reality on the licenses with the vendor. These line items were a package deal from them and I cannot guarantee it would remain the same but its a rough guide.

The arrays if you got them to attach to a new server were when fully populated with 60x6TB drives:

$34,000.00 each

Each array once configured with six RAID6 LUNS added roughly 260TB per array to the Lustre filesystem. 

If you didn't get two more servers I believe there is a slightly cheaper model of the array designed for SAS chaining. I do not have a price for that array. So assume its roughly the same. I believe you can chain up to three more arrays from the "smart" array we have already. You CANNOT however then add servers later and have the "extension" array work alone...

Does that help?

**Comment by tatarsky** [comment]
Oh, and the above assumes this new usage isn't going to add zillions of inodes. But you are in good shape so far in that category on the MDT (Metadata storage)

```
fl-hn1 [~]$ lfs df -h
UUID                       bytes        Used   Available Use% Mounted on
frazer01-MDT0000_UUID      552.6G        4.9G      510.7G   1% /frazer01[MDT:0]
frazer01-OST0000_UUID       43.6T       10.5T       30.9T  25% /frazer01[OST:0]
frazer01-OST0001_UUID       43.6T        9.6T       31.8T  23% /frazer01[OST:1]
frazer01-OST0002_UUID       43.6T        9.5T       31.9T  23% /frazer01[OST:2]
frazer01-OST0003_UUID       43.6T       10.0T       31.4T  24% /frazer01[OST:3]
frazer01-OST0004_UUID       43.6T       11.0T       30.4T  27% /frazer01[OST:4]
frazer01-OST0005_UUID       43.6T       10.6T       30.8T  26% /frazer01[OST:5]
frazer01-OST0006_UUID       43.6T        9.5T       31.9T  23% /frazer01[OST:6]
frazer01-OST0007_UUID       43.6T       10.2T       31.3T  25% /frazer01[OST:7]
frazer01-OST0008_UUID       43.6T        9.4T       32.0T  23% /frazer01[OST:8]
frazer01-OST0009_UUID       43.6T       10.3T       31.1T  25% /frazer01[OST:9]
frazer01-OST000a_UUID       43.6T       12.0T       29.4T  29% /frazer01[OST:10]
frazer01-OST000b_UUID       43.6T       10.6T       30.8T  26% /frazer01[OST:11]

filesystem summary:       523.3T      123.2T      373.9T  25% /frazer01
```

**Comment by nariai** [comment]
One data server ($11.8K) + 360TB drives ($34K) = $45.8K?

Sounds realistic to me.

**Comment by tatarsky** [comment]
Yeah, except if you add "one server" just remember you aren't getting redundancy.

Right now either OSS server can serve up BOTH arrays if one fails. I strongly recommend you consider that pattern and always try to grow in pairs.

**Comment by tatarsky** [comment]
And I don't think Dell is shipping 8TB drives and if they do I suspect they will be SMR drives which have performance constraints.

**Comment by tatarsky** [comment]
Oh, and we might have to figure out rack space. Which there is 12RU at the top (arrays are 4RU and the servers were 2RU) I don't know if there was enough power. We did ask SDSC to beef up the power. Only main issue is those arrays are really really heavy.

**Comment by nariai** [comment]
I see. In order to keep the redundancy of data servers:
Two data servers ($23.6K) + Two 260TB (effective) arrays ($68K) = $91.6K
will be recommended.

**Comment by tatarsky** [comment]
Yep. That was the original proposal scope to always build out data storage in pairs. Otherwise if a server (OSS) goes down that is the only way to access that OST (the array) any file with blocks on that array cannot be accessed. Which given all files are split by stripe across all OSTs in Lustre pretty much means a down filesystem.

**Comment by nariai** [comment]
Due to the current budget, we don't think we can get the two data servers with full arrays.
Is the following possible, with the future extension capability?

Two data servers ($23.6K) + Two 100TB (effective) arrays ($26K) = $50K

**Comment by tatarsky** [comment]
This is where you need to ask a vendor. The problem with partial drive filling with most of the vendors is adding the other drives later is not from my experience a very good deal. They tend to ding you for adding drives later. 

The key item here I would bump to whoever you are talking about to get that answer is: does this require a bid process or can we talk directly to the vendor we got the current equipment from.

**Comment by tatarsky** [comment]
I am closing this as it appears to have migrated to an email thread with Kelly. If you would like further data on the prices of the cluster components just continue that thread.
