### ISSUE TITLE
missing account

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#74]
We have a missing account, paola, from the old cluster. Can you make that on the new cluster?

**Comment by hirokomatsui** [comment]
Actually I saw the account in the /etc/passwd but the home directory.

**Comment by tatarsky** [comment]
Made homedir and gave it default skel bash config files! Advise of issues. Double checking all the accounts.

**Comment by tatarsky** [comment]
Missed `cbarrett` as well. Must have gotten sidetracked. Added skel bash items to folks that didn't have them or signs of login yet to avoid confusion.

**Comment by tatarsky** [comment]
Believed resolved. May take another look at NIS issue shortly.
