### ISSUE TITLE
Install of vcflib

### ISSUE THREAD

**Issue by djakubosky** [frazer-lab/cluster#76]
I want to experiment with this software but can't get it to make completely (there are a few errors).  

https://github.com/ekg/vcflib#vcflib

This is low priority but wanted to bring it to attention.  I think it contains its dependencies. 

Errors in make:
src/dumpContigsFromHeader.cpp:11: error: ‘vcf’ is not a namespace-name
src/dumpContigsFromHeader.cpp:11: error: expected namespace-name before ‘;’ token
src/dumpContigsFromHeader.cpp: In function ‘int main(int, char**)’:
src/dumpContigsFromHeader.cpp:17: error: ‘VariantCallFile’ was not declared in this scope
src/dumpContigsFromHeader.cpp:17: error: expected ‘;’ before ‘variantFile’
src/dumpContigsFromHeader.cpp:19: error: ‘variantFile’ was not declared in this scope

**Comment by tatarsky** [comment]
So I get the same error using the process they define. 

Numerous Git issues for that project discuss compiler needs and problems compiling it. 

But even with the newer gcc (`module add gcc`) I get the same error for that particular file (`dumpContigsFromHeader.cpp`). 

The rest compile clean (`make -k`)

I consider items like this something the author should be contacted. But be sure if you do to consider at least the newer gcc as a reporting compiler for a Git issue. 

If I have time I will scan the issues/google for similar errors or I suspect somebody more C++ versed than I might spot the problem. 

Its a short file.

**Comment by djakubosky** [comment]
Don't worry about it, thanks for looking into it, we don't have to use this
tool.  I was hoping it was something stupid/easy you would be able to
easily resolve- if it's a big headache we can just close out the issue and use
a different thing :)

On Tuesday, December 15, 2015, tatarsky notifications@github.com wrote:

> So I get the same error using the process they define.
> 
> Numerous Git issues for that project discuss compiler needs and problems
> compiling it.
> 
> But even with the newer gcc (module add gcc) I get the same error for
> that particular file (dumpContigsFromHeader.cpp).
> 
> The rest compile clean (make -k)
> 
> I consider items like this something the author should be contacted. But
> be sure if you do to consider at least the newer gcc as a reporting
> compiler for a Git issue.
> 
> If I have time I will scan the issues/google for similar errors or I
> suspect somebody more C++ versed than I might spot the problem.
> 
> Its a short file.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/76#issuecomment-164775423.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
Well, its a C++ bug in one file that is only a few lines long. Any C++ wizards? I don't write enough code to spot its complaint.

**Comment by djakubosky** [comment]
Well, thats good to know- I will ask @hirokomatsui in the future- when all of us are less busy.

**Comment by tatarsky** [comment]
I might be able to ask a fellow genome person if they spot something.

**Comment by tatarsky** [comment]
The error we both have was reported by another person to that projects Git issues.

**Comment by tatarsky** [comment]
Forgot link.
https://github.com/ekg/vcflib/issues/119

**Comment by tatarsky** [comment]
Looks like some patches to fix the item in question...attempting compile.

**Comment by tatarsky** [comment]
So it compiles now and has a set of binaries which I can make a module for but is there some test that can be done to see if it actually does what you seek? Its currently at:

```
/software/vcflib-20151228
```

Where the date is the date of the `git pull` I did aka today. 

There is a bin dir so I would make a module if it worked that added `/software/vcflib-20151228/bin` to the path I suppose....

**Comment by djakubosky** [comment]
Thanks Paul, I will definitely try out some of these functions, I'm excited
to have this tool.

On Mon, Dec 28, 2015 at 2:55 PM, tatarsky notifications@github.com wrote:

> So it compiles now and has a set of binaries which I can make a module for
> but is there some test that can be done to see if it actually does what you
> seek? Its currently at:
> 
> /software/vcflib-20151228
> 
> Where the date is the date of the git pull I did aka today.
> 
> There is a bin dir so I would make a module if it worked that added
> /software/vcflib-20151228/bin to the path I suppose....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/76#issuecomment-167641212.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
Closing for now. Re-open if not to your liking.
