### ISSUE TITLE
MOODS compilation

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#77]
I'm trying to compile and install the python versions of this software MOODS: http://www.cs.helsinki.fi/group/pssmfind/. I'd like to try compile both the [1.0.2.1 version](http://www.cs.helsinki.fi/group/pssmfind/MOODS-1.0.2.1.tar.gz) as well as the [1.9.0 version on github](https://github.com/jhkorhonen/MOODS). I'm getting errors for both even if I use the `gcc` module. @tatarsky, can you see if you can get them to compile? Thank you.

**Comment by tatarsky** [comment]
What errors did you get on the 1.0.2.1 version?

 I was able to follow all the steps except clearly noting their python step includes `install` which by default wants to place things in the system python libs. (Which I would like to avoid). 

I'll try 1.9.0 in a sec. We will have to hack it up a bit to re-path some of it. I can make a stab at it.

**Comment by tatarsky** [comment]
The git version is a mess or I haven't groked their build process yet. I'll cycle back to it shortly.

**Comment by cdeboever3** [comment]
If I can get 1.0.2.1 working that's fine. It seems 1.9 is an intermediate
release so I was hesitant about using it anyway. I'll post my output
shortly.

**Comment by cdeboever3** [comment]
Sorry I made a mistake when I was installing. I have 1.0.2.1 working now. `python setup.py install` installed into my Anaconda python. Thanks
