### ISSUE TITLE
Advise if chat needed today

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#78]
Happy to chat but not much going on which I view as a good thing ;)

I am trying to do some cleanup of issues for items as I believe we are heading into the UC closure and the holidays. 

I do not know the schedule of folks over that period but I am mostly around during it.

**Comment by tatarsky** [comment]
OK suspecting folks are busy so I'm heading to lunch. If a call is needed just drop me a note. Have a good Wednesday!

**Comment by nariai** [comment]
Sorry for the late reply. We are still waiting for our colleagues to finish their jobs on the old cluster before initiating the merging process. We will keep you updated on this. Otherwise, we don't have an urgent issue at the moment.

**Comment by tatarsky** [comment]
Not a problem!
