### ISSUE TITLE
Failed drive in one of the arrays

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#79]
I have opened a ticket with Advanced HPC to start the process. I believe I can get SDSC to do the drive replacement if its a shipment only.

**Comment by hirokomatsui** [comment]
That's right. SDSC will do that.

**Comment by tatarsky** [comment]
Advanced HPC ticket number: 1006797
Provided array support bundle to them as they will contact Dell and get the RMA going.

**Comment by tatarsky** [comment]
Drive replaced. LUN rebuilding.

**Comment by tatarsky** [comment]
This BTW rebuilt without incident.
