### ISSUE TITLE
can't log in outside campus

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#8]
can't log in using 
ssh hel070@flh1.ucsd.edu

But I can log in directly to fl1, and log from fl1 to flh1

**Comment by tatarsky** [comment]
This is correct behavior for now. Until I review all the vendor installed items for security, ssh to something else first on campus (such as the existing cluster).

I do not want any security issues until I validate the systems.

**Comment by hurleyLi** [comment]
I see. That's a quick respond :)
And by the way, I run three rsync jobs, two on flh1, one on flh2, but all of them are stopped with error:

```
Killed by signal 1.
rsync error: unexplained error (code 255) at rsync.c(546) [generator=3.0.6]
rsync error: received SIGINT, SIGTERM, or SIGHUP (code 20) at rsync.c(546) [receiver=3.0.6] 
```

I remembered you mentioned rsync jobs might be interrupted at some point today, so I assume that's the reason? 

Thanks,

**Comment by tatarsky** [comment]
Nope, the above is not via me.

**Comment by tatarsky** [comment]
Checking version of rsync on old cluster. Sometimes thats a result of version incompat.

**Comment by tatarsky** [comment]
Also in the future the remote access will return. I just need to validate the vendor didn't leave any weak passwords or configurations somewhere.

**Comment by tatarsky** [comment]
See if your rsync has issues again. Moved the head node rsync version to a closer revision to old cluster. (3.1.1 compared to 3.0.6).

**Comment by hurleyLi** [comment]
The old cluster use rsync version 3.1.1, the new cluster use version 3.0.6. 
Each rsync jobs copy multiple files from old cluster to new cluster, they all successfully copied one file, but error occurred when copy the second file. Weird thing is they all stopped at exactly the same time.

**Comment by hurleyLi** [comment]
I'm restarting these rsync jobs, and will let you know if this issue comes up again

**Comment by tatarsky** [comment]
Sounds good. Advise your full command if it does it again and I'll take a look. I can assure you its not being done by me ;) But rsync has some interesting issues sometimes with files.

**Comment by tatarsky** [comment]
I note you are using compression (z flag). Rsync is notorious for odd problems with compression. You might try the same rsync if it crashes again without it. For a short haul network path its of debatable value.

**Comment by hurleyLi** [comment]
All right. so far it looks normal.

**Comment by tatarsky** [comment]
Generically the only other rsync advice I have is as follows and is not critical:
1. Consider using rsync in a `screen` session to reduce any impact from a dropped connection. Can elaborate.
2. Use the -P flag to allow a partially rsync'd file to be restarted and provide some progress/stats.
3. If it really large file you could consider using a weaker ssh encryption ala:

```
rsync -avP -e "ssh -c arcfour" somehost:/somedir/ /mynewplace/ 
```

This can reduce CPU impact on both sides and result in a quicker transfer. Assumes security of data is not that important coming over the network.

**Comment by hurleyLi** [comment]
Got it! I'll try this when I rsync next time.

**Comment by tatarsky** [comment]
The restriction on external access has been removed. Please try again.

**Comment by tatarsky** [comment]
I believe you are all set with this. Re-open if not the case!
