### ISSUE TITLE
Trouble getting qlogin job

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#80]
I'm running into some behavior I don't understand. I'm trying to grab a whole node using `qlogin` as follows:

```
[~]fl-hn2 $ qlogin -pe smp 32 -l h_vmem=4
Your job 74709 ("QLOGIN") has been submitted
waiting for interactive job to be scheduled ...Your "qlogin" request could not be scheduled, try again later.
[~]fl-hn2 $ qlogin -l short -pe smp 32 -l h_vmem=4
Your job 74710 ("QLOGIN") has been submitted
waiting for interactive job to be scheduled ...Your "qlogin" request could not be scheduled, try again later.
```

As far as I can tell n3 should be open: `qstat | grep n-1-3` returns nothing. @tatarsky, do you understand why the above is not working? I feel like I've used the same qlogin command before and it worked. It also doesn't work if I request a smaller h_vmem.

**Comment by tatarsky** [comment]
Have you used it before with the `-pe smp` ? I'm showing the same so give me a moment to determine if I need to instruct the nodes to honor interactive parallel execution requests. Right now if I run that with `-now n` (to keep it sitting there waiting) and then ask for an explain of its status I show:

```
scheduling info:            cannot run in PE "smp" because it only offers 0 slots
```

**Comment by cdeboever3** [comment]
I'm pretty sure I have run it with -pe smp because I've been able to get 32
cores for a qlogin job before and my -pe knowledge is pretty much limited
to smp at this point.

**Comment by tatarsky** [comment]
I am suspecting at the moment its the lack of units on the h_vmem line.

```
qlogin -pe smp 32 -l h_vmem=4
(waits)
```

But if you add the units (SGE can be insanely picky sometimes)

```
qlogin -pe smp 32 -l h_vmem=4G
Your job 74727 ("QLOGIN") has been submitted
waiting for interactive job to be scheduled ...
Your interactive job 74727 has been successfully scheduled.
Establishing builtin session to host fl-n-1-3 ...
fl-n-1-3 [~]$ 
```

Please try that.

**Comment by cdeboever3** [comment]
Ugh. Too early. Thanks. Closed.

**Comment by tatarsky** [comment]
I hear ya. SGE is annoying about its units and doesn't really tell you anything useful in this one. When I get back to writing I'll make a note of it in the wiki.

**Comment by cdeboever3** [comment]
Thanks, I just added some stuff to the wiki (I've been filling it out as I
learn things), but feel free to amend and add.
