### ISSUE TITLE
Can't make .bashrc

### ISSUE THREAD

**Issue by Terciera** [frazer-lab/cluster#82]
This is my first time playing around on the cluster. I managed to make a directory (/frazer01/repos/enviroment/modulefiles/VTE) and a file (/frazer01/repos/environment/modulefiles/VTE/VTE.mod1).

I tried to make a .bashrc file in /frazer01/home/tsolomon and I can't. The error message from vi is 
       E138: Can't write viminfo file /frazer01/home/tsolomon/.viminfo!  

I also tried to set up git config using:
      git config --global user.email "tsolomon@ucsd.edu"
and got the following error:
      error: could not lock config file /frazer01/home/tsolomon/.gitconfig: Permission denied

Any help?

**Comment by tatarsky** [comment]
Checking perms.

**Comment by tatarsky** [comment]
Logout/login. Must have missed this account homedir perm correction.
