### ISSUE TITLE
Discuss old cluster and 10G and RAM upgrade for it 

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#83]
So these nodes are quad socket and I believe can also be upgraded in RAM and have added PCI-E cards and they are full 1RU form factor. 

My recommendation looking at bit at the overall game plan and also noting clearly that a single 1G link is going to bottleneck up really well the following:
1. Upgrade the memory a bit. I show with dmidecode additional slots. Will have to review motherboard manual for proper density and placement options. 
2. Purchase a 24 10G switch with either SFP+ or CAT6 connections. Nothing fancy.
3. Purchase basic 10G PCI-E cards for all nodes. Single port probably fine but see what the price difference is for dual port. 
4. Upgrade the cross switch link from 1G to 10G. While still a bit bottlenecked it would reduce complexity with Lustre and also handle periodic I/O bursts better. We could consider 40G. 

The labor in the above could be probably handled creatively. 

I feel this would really make the more complete use of these old nodes and probably would not be that expensive.  While I don't know the budget, the above seems a something to consider.

**Comment by cdeboever3** [comment]
I think this makes sense. @tatarsky, in case you didn't know, @kafrazer isn't subscribed to automatic email for these issues, so if we want her to see something, we should @ mention her. This seems relevant to her. I'm working remotely this and next week, but perhaps as a group we can discuss on a 1/6 phone call. @kafrazer, do we need a price estimate?

**Comment by kafrazer** [comment]
Can someone fill me in.

Kelly A. Frazer, Ph.D.
Director, Institute for Genomic Medicine
Professor of Pediatrics
Chief, Division of Genome Information Sciences

Leichtag
9500 Gilman Drive #0761
La Jolla, CA 92093-0761

Telephone: (858) 246-0208
kafrazer@ucsd.edumailto:kafrazer@ucsd.edu
http://frazer.ucsd.eduhttp://frazer.ucsd.edu/

**Comment by tatarsky** [comment]
I'll move this over to email. I'm on errands for a bit.

**Comment by nariai** [comment]
Yes, I think this is the topic we can discuss face-to-face, including Kelly.
Let's try to arrange a Skype call on Jan 6.

Naoki

2015-12-22 6:13 GMT-08:00 tatarsky notifications@github.com:

**Comment by tatarsky** [comment]
Do we wish to discuss this tomorrow on the Skype call?

**Comment by kafrazer** [comment]
Can we have a Skype call at 9 am tomorrow?

Kelly A. Frazer, Ph.D.
Director, Institute for Genomic Medicine
Professor of Pediatrics
Chief, Division of Genome Information Sciences

Leichtag
9500 Gilman Drive #0761
La Jolla, CA 92093-0761

Telephone: (858) 246-0208
kafrazer@ucsd.edumailto:kafrazer@ucsd.edu
http://frazer.ucsd.eduhttp://frazer.ucsd.edu/

**Comment by tatarsky** [comment]
@kafrazer I'm fine with that. 9:00AM PST/11:00AM CST.

**Comment by kafrazer** [comment]
I am sorry Paul - can we change to 10 am PST?

Kelly A. Frazer, Ph.D.
Director, Institute for Genomic Medicine
Professor of Pediatrics
Chief, Division of Genome Information Sciences

Leichtag
9500 Gilman Drive #0761
La Jolla, CA 92093-0761

Telephone: (858) 246-0208
kafrazer@ucsd.edumailto:kafrazer@ucsd.edu
http://frazer.ucsd.eduhttp://frazer.ucsd.edu/

**Comment by tatarsky** [comment]
No worries @kafrazer . 10:00AM PST also free.

**Comment by kafrazer** [comment]
Naoki, Hiroko, Hurley and David need to attend this.  Anyone else is welcome.  We will meet in my office.

**Comment by nariai** [comment]
I'll be on the call tomorrow.

**Comment by tatarsky** [comment]
Details for call of interest that I will go over. The generic goal is get more for these older nodes in terms of perform and use. They still have some life in them and they were quad socket units. 

The old nodes are a SuperMicro H8QG6 quad socket board.
That board will take from its manual up to 1TB of ram. 
There are 32 memory slots. 
16 are currently filled with 4GB DDR3 1333Mhz sticks. 
We could add 16 more 16 x 4GB sticks to bring them to 128GB. Rough guess $50/stick. $800 per node.

But you could also move memory from some nodes into other nodes and refill the empty slots with higher density memory. 

To reach 256GB 32x8GB sticks could be used. Rough guess $70/stick for the cheaper ecc
To reach 512GB 32x16GB sticks could be used. Rough guess $180/stick 
To reach 1TB 32x32GB sticks would be used. This would be expensive. Rough guess $300/stick. 

All those prices are 30 second googles and for the cheapest "value" class ecc memory. 

Then the nodes also have open PCI-E slots. I propose adding a 10G card to them and not mess around with 1G and Lustre.

Rough price: $150 for an SFP+ model per node. 

Then the final item is a 24 port 10G switch over on the old rack and connecting it. I would almost see if you could locate this used. I am looking around. There would be a intra-switch link of 10G or maybe two 10G as the last step.

**Comment by tatarsky** [comment]
So I will draw a diagram if I can today of the two choices we discussed. If I don't get it today I will try to get it when I get to D.C. on Friday. 
1. Current situation is all old nodes are 1G per node but sharing a single 1G to new storage.
2. Add a switch with 1G ports connected to nodes but with 10G uplink over to the Lustre 10G switch. Nodes could be single attached or dual attached to give per node bandwidth of 1G or 2G. No new node hardware required. Maximum all node bandwidth would be 10G (single cable from old rack to new). Estimated cost $2000 or so for switch. No node network cards needed. Some config work needed. Relatively easy. 
3. A switch with all 10G ports connected to nodes and either a 10G or 40G connection to the Lustre 10G switch. Nodes would be upgraded with a 10G card. This is debatable if the nodes could actually manage 10G use if that old (6-7 years). Estimated cost $150 per node + $3000-$4000 for a 24 port 10G switch. Plus SDSC cable pull and fiber cable to do so. 40G would add cost as the optics are more expensive. 

I'll try to gather up rough estimates but it sounds like #1 matches your needs more closely given the age of the old nodes. I did not realize they were that old. 

I have activated scrounger mode and sent a few emails about old lower density ram trading.

**Comment by nariai** [comment]
Thanks for the call today. Is it possible for the following option?
1. A new 24 port 10G switch with all 10G ports connected to old nodes and either a 10G or 40G connection to the Lustre 10G switch. Each old node will use the existing 1G card, or with an additional 1G card (in total, 2G per node).

The rationale here is that we might need the new 24 port 10G switch anyhow in the future.

**Comment by tatarsky** [comment]
Sure. I understand basically drop in a 10G switch in the new rack and connect to a 1G switch with the old nodes and also provide 10G Lustre options for future systems in the old rack. 

One option there is if that switch is a CAT6 based 10G switch it may be able to take the 1G connections as they are now (copper). Compared to an SFP+ connection. I'll try to elaborate in the document after I look at the options. 

Thats a good idea.

**Comment by tatarsky** [comment]
Confirming you feel 16 nodes are the final count. I have 17 alive now. Two we had issues with kickstarting. (cn12 and cn7). Just trying to get proper port counts.

**Comment by tatarsky** [comment]
Something like the Dell N4032 10G copper switch would I believe allow you to connect the old nodes to 10G ports that auto-sense down to 1G. And also add 10G copper systems at full speed on the same switch. 

But it would be an expensive short term method (lists at $7K). You would really want to be sure you had something needing 10G in the older rack fairly soon compared to the 1G switch with 10G uplinks. But I will document all this out in pros/cons/costs.

Generically all 10G switches are about to "rev" a generation apparently as the 25/50/100G versions of the technology is coming and many vendors gear is starting to appear. (compared to 10G/40G). But the first ones are really pricey from what I've seen.

**Comment by tatarsky** [comment]
http://www.dell.com/us/business/p/networking-n4000-series/pd?oc=bcct151&model_id=networking-n4000-series

**Comment by tatarsky** [comment]
Netgear has some cheaper 10G BASE-T switches. Never used them. Placing this here for reference.
Claims it will downspeed link to 1G.

http://www.amazon.com/Netgear-ProSAFE-10-Gigabit-Ethernet-XS728T-100NES/dp/B0147FL4BW

**Comment by tatarsky** [comment]
Didn't quite complete the writeup due to needing to pack. But I will hopefully shortly after I get settled into my hotel in D.C. 

I am pretty convinced the older rack (which I think I'll just call KK36) should use 10G over copper for at least one of its 10G media types to allow the old and new transition easier. (Compared to the SFP+ format which I still prefer but doesn't have as much compatibility with existing cards)

**Comment by tatarsky** [comment]
I have emailed the following document as part of an email thread with Kelly. But am also placing it here for others to review. 
[KK3610G.pdf](https://github.com/frazer-lab/cluster/files/98145/KK3610G.pdf)

**Comment by tatarsky** [comment]
This was tabled for now in a conversation with Kelly. I will however continue to monitor for used or cast off 10G copper switches. I will close this for now and we can reopen if needed.
