### ISSUE TITLE
module on flh2

### ISSUE THREAD

**Issue by hurleyLi** [frazer-lab/cluster#84]
I just noticed all the modules seems only available on flh1, but not flh2. Is there any easy way to also populate them on flh2?

**Comment by cdeboever3** [comment]
I can load modules from flh2. What isn't working?

**Comment by tatarsky** [comment]
No, he's right. An effort this morning to automate the module path didn't work quite as planned. One sec.

**Comment by hurleyLi** [comment]
when I do 'module avail', it only returns me one module

python/2.7/pysam/0.8.3

**Comment by tatarsky** [comment]
Logout/back in.

**Comment by tatarsky** [comment]
Bug in my puppet line....

**Comment by hurleyLi** [comment]
now it works! Thanks!!

**Comment by tatarsky** [comment]
Pardon my missing "comma" ;)
