### ISSUE TITLE
libicuuc.so.42: cannot open shared object file on cn nodes

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#85]
I'm getting this error when trying to run some R code on the new nodes:

```
/software/R-3.2.2-cardips/lib64/R/bin/exec/R: error while loading shared libraries: libicuuc.so.42: cannot open shared object file: No such file or directory
```

I can't tell if this happened for all of my jobs on the new nodes but it looks like it did.

**Comment by tatarsky** [comment]
Yeah I saw that library in my rpm checks. One sec, I suspect I typed its name wrong in the puppet list.

**Comment by tatarsky** [comment]
Ah, found the matter and it should self-fix shortly (puppet runs hourly but I am pushing it along on a few where I had a dependency error)

**Comment by tatarsky** [comment]
OK, I think the `libicu` rpm is out there now correctly. 
It provides:

```
rpm -q -l libicu                       
/usr/lib64/libicudata.so.42
/usr/lib64/libicudata.so.42.1
/usr/lib64/libicui18n.so.42
/usr/lib64/libicui18n.so.42.1
/usr/lib64/libicuio.so.42
/usr/lib64/libicuio.so.42.1
/usr/lib64/libicule.so.42
/usr/lib64/libicule.so.42.1
/usr/lib64/libiculx.so.42
/usr/lib64/libiculx.so.42.1
/usr/lib64/libicutu.so.42
/usr/lib64/libicutu.so.42.1
/usr/lib64/libicuuc.so.42
/usr/lib64/libicuuc.so.42.1
```

Let me know if you find others.

**Comment by cdeboever3** [comment]
Thanks I'll try the code again.

**Comment by tatarsky** [comment]
Just checking this is all good. I show that library on all "old nodes"

**Comment by cdeboever3** [comment]
Yeah my code ran with no problems so this is probably fine. I'll close.
