### ISSUE TITLE
installing png package for R

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#87]
I am trying to install the png package for R (I need id to be able to run EBImage) and I get this error:

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/frazer01/home/matteo/software/R-3.2.2/lib64/R/library/png/libs/png.so':
  libpng16.so.16: cannot open shared object file: No such file or directory

I get the same error by installing directly from CRAN: install.packages("png", repos = c("http://cran.us.r-project.org"))

Or after downloading the source. 
I found that I can solve the problem by running:
yum install libpng-devel then install.packages("png")

But I don't have root permissions.

Thanks!

**Comment by s041629** [comment]
apparently a similar problem exists also for tiff and fftwtools: I should run sudo yum install libtiff-devel fftw-devel to solve this problem but I don't have the permissions. This solution should solve also the problem with the png package and I found it on the help for EBImage: https://github.com/aoles/EBImage/issues/2

**Comment by tatarsky** [comment]
So to summarize you are asking for:

```
libpng-devel
libtiff-devel
fftw-devel
```

Please test on the `fl-hn1` headnode where I added the last two (the libpng-devel was there) but the packages were added to the puppet master list.

**Comment by s041629** [comment]
Now I managed to install tiff and fftwtools. So only png does not work. 
Thanks

**Comment by tatarsky** [comment]
Sorry, I'm confused here what you are asking for from me. 

Above you asked for some system versions of libraries (yum installs rpms at the system level)

The `libpng` was already there at the system level.
But its version is ".12" and you noted you need a `libpng16.so.16` which RHEL does not provide. 

The libpng from RHEL is:

```
/usr/lib64/libpng12.so.0
```

Which I believe is version 1.2.49

So I suspect you are asking for a newer libpng. Version 16 to be precise if I'm reading your item above.

Which I believe would be best for you to install to the software tree you are building rather than depend on system libs. Similar to whatever you just did with tiff/fftw.

The latest libpng is I believe here:

http://sourceforge.net/projects/libpng/files/

Unless you are asking for a module for libpng...

**Comment by djakubosky** [comment]
I also need this package, in R/1.1.1 (or any other R).  would be great to have a module with this in it (is needed for Genome STRiP

**Comment by tatarsky** [comment]
Your R tree is world writable BTW. But I was able to build the png package using the libpng12 version the system has available. 

I chown'd it to you...can you see if that works for you?

```
> install.packages("png",repos = c("http://cran.us.r-project.org"))
trying URL 'http://cran.us.r-project.org/src/contrib/png_0.1-7.tar.gz'
Content type 'application/x-gzip' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package 'png' ...
** package 'png' successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/home/matteo/software/R-3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include    `libpng-config --cflags` -fpic  -g -O2  -c read.c -o read.o
gcc -std=gnu99 -I/home/matteo/software/R-3.2.2/lib64/R/include -DNDEBUG  -I/usr/local/include    `libpng-config --cflags` -fpic  -g -O2  -c write.c -o write.o
gcc -std=gnu99 -shared -L/home/matteo/software/R-3.2.2/lib64/R/lib -L/usr/local/lib64 -o png.so read.o write.o -L/usr/lib64 -lpng12 -lz -lm -L/home/matteo/software/R-3.2.2/lib64/R/lib -lR
installing to /frazer01/home/matteo/software/R-3.2.2/lib64/R/library/png/libs
```

You may want to uninstall/re-install that module and check your permission ;)

**Comment by tatarsky** [comment]
If you list which versions of R you are using, I can work with whoever maintains them to have the needed modules. But if you intend you maintain your own R tree, (and that might be wise as you said this was tied to a pipeline) you should be able to just proceed adding to your own. 

@cdeboever3 may have some suggestions given his efforts at tying pipelines to modules.

**Comment by s041629** [comment]
it works now. Thanks!

**Comment by tatarsky** [comment]
Was the first one you listed BTW perhaps a binary download instead of a source build? That might explain why its looking for a libpng16 which is newer than RHEL but I believe a default on some other distros....

**Comment by cdeboever3** [comment]
I'll work with @djakubosky to see if we can get this going. We'll ping if
run into trouble.

**Comment by tatarsky** [comment]
Cool. I'm happy to assist with what I call "R Wrangling" but I'm very careful to not step on somebody else's source tree (in particular yours!)

Because R tends to like to update things at the drop of a hat and that might impact something else....

System R we may just want to remove to force people to think about what R they need....

**Comment by djakubosky** [comment]
Hi Paul, Just wondering, are you planning to help with install of png to module R/3.1.1 or are you suggesting I produce a new R tree?  I'm stuck at getting the png to load- perhaps because I'm it cant find the libpng-devel but I'm not sure why.  To be clear- I need R/3.1.1 because another package cannot be installed to R/3.2.2

**Comment by cdeboever3** [comment]
Sorry for the confusion. I wasn't exactly clear on what @djakubosky was trying to do. He needs to install png in the R module R/3.1.1 (e.g. `install.packages("png")`). Can you try your hand at it @tatarsky? Thanks

**Comment by tatarsky** [comment]
Sure.

**Comment by tatarsky** [comment]
BTW @djakubosky are you using the R/3.1.1 module?

**Comment by cdeboever3** [comment]
Yes he is.

**Comment by tatarsky** [comment]
Okey doke. One sec

**Comment by djakubosky** [comment]
Yes, I am using this module, but I can use my own R if need be (but I can't
get png there either unfortunately).

On Mon, Dec 28, 2015 at 2:28 PM, tatarsky notifications@github.com wrote:

> BTW @djakubosky https://github.com/djakubosky are you using the R/3.1.1
> module?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/87#issuecomment-167633890.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
So all I've done here is on `fl-hn1`

```
# module add R/3.1.1
[root@fl-hn1 R-3.1.1]# R

R version 3.1.1 (2014-07-10) -- "Sock it to Me"
> install.packages("png",repos = c("http://cran.us.r-project.org"))

(compiles)

installing to /frazer01/software/R-3.1.1/lib64/R/library/png/libs
```

Can you see if that does it for you?

**Comment by tatarsky** [comment]
@cdeboever3 eventually should decide on owner for the R tree...I'll chown to you however. I did the above as root.

**Comment by tatarsky** [comment]
How about we add it for consistency to the R default tree as well? (I recognize the other module he needs does not work with 3.2.2).

**Comment by tatarsky** [comment]
BTW, I added `tiff` and `fftwtools` as well to the R/3.1.1 tree....

**Comment by djakubosky** [comment]
Yes this worked for me, I'm testing to see if anything additional is
required, looks ok

On Monday, December 28, 2015, tatarsky notifications@github.com wrote:

> BTW, I added tiff and fftwtools as well to the R/3.1.1 tree....
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/frazer-lab/cluster/issues/87#issuecomment-167637092.

## 

__________________________________

_David Jakubosky_
Biomedical Sciences Graduate Program
Laboratory of Kelly A. Frazer, PhD
Institute for Genomic Medicine,
University of California at San Diego

---

**Comment by tatarsky** [comment]
Just let me know!
