### ISSUE TITLE
Error in queue request

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#88]
Somebody I believe @s041629 has not issued a set of queue items correctly for `short.q`

While a bit confusing we control queue selection with a resource in order to do the stacked queues we are using.

So the jobs asking for `-q short.q` _without_ the needed `-l short` are never going to run.

I would replace this line in the submit script:

```
#$ -q short.q
```

With 

```
#$ -l short
```

**Comment by s041629** [comment]
It's me (Matteo). I was wondering why my jobs were not starting. I copied "short.q" from the wiki page. Now I deleted that line and the jobs started.

**Comment by cdeboever3** [comment]
I added a [line to the wiki](https://github.com/frazer-lab/cluster/wiki#queues-currently-configured) on how to request queues. I also added a description of the opt queue. @tatarsky, what is all.q?

**Comment by tatarsky** [comment]
`all.q` is the default queue. You actually defined it ;)

https://github.com/frazer-lab/cluster/issues/24#issuecomment-155622476

If you don't ask for a resource you get that queue and its a lower priority `short.q` IIRC. (aka your jobs can be bypassed by `short.q` entries....

Note carefully its still with a 48 hour wallclock. If I read #24 correctly. 

When he resubmitted he didn't add `-l short`

I'll double check all the current state of the queues and their documentation shortly.

**Comment by tatarsky** [comment]
And not to confuse Git requests since you are looking at this one:

I note also that while we changed the name `all2.q` to `opt.q` I have not yet implemented this item:

"Maximum wall time of the `opt.q` will be seven days"

Is that still desired? `opt.q` is only the Opteron nodes. I can set a 7 day wallclock limit...

**Comment by cdeboever3** [comment]
I think seven days is reasonable, go ahead and set it.

**Comment by cdeboever3** [comment]
Thanks for the reminder, that seems like ages ago. I updated the wiki with a description of all.q and some words on choosing queues.

**Comment by tatarsky** [comment]
Sounds good. I'll close this for now. Added tracking of the `opt.q` settings to #24
