### ISSUE TITLE
Error: Could not create the Java Virtual Machine.

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#89]
I am trying to run this:

/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.65.x86_64/bin/java -Xmx32g -jar /software/GenomeAnalysisTK-3.5/GenomeAnalysisTK.jar \
 -T              MuTect2 \
 -L              MT \
 -R              /publicdata/gatk_bundle_2.8/b37/human_g1k_v37_decoy_Sendai.fasta \
 --dbsnp         /publicdata/dbsnp144_20151104/00-All.vcf.gz \
 -I:normal       /projects/CARDIPS/analysis/ipsc_wgs/scratch/ipsc_wgs.P0351.MT/germline.MT.bam \
 -I:tumor        /projects/CARDIPS/analysis/ipsc_wgs/scratch/ipsc_wgs.P0351.MT/ipsc.MT.bam \
 -o              /projects/CARDIPS/analysis/ipsc_wgs/scratch/ipsc_wgs.P0351.MT/P0351.MT.vcf

And it works fine when I simply run it via command line.
I tried to run it with qsub (the SH file is /frazer01/projects/CARDIPS/analysis/ipsc_wgs/pipeline/subjects/P0351/SH/P0351.mutect.chrMT.sh) and I get the error:

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I tried changing java: 
java-1.7.0
java-1.7.0-openjdk-1.7.0.65.x86_64
java-1.7.0-openjdk.x86_64

But the problem is not solved. Do you know what may cause this problem?

Thanks!

Matteo

**Comment by tatarsky** [comment]
Check your h_vmem size. Java requests a good chunk of ram. Test the chosen size in an interactive qlogin instead of a qsub.

Also review a past Git issue on the topic.

https://github.com/frazer-lab/cluster/issues/49

If that doesn't solve it I'll have some time later today. I am on a project this morning.

**Comment by s041629** [comment]
I increased the ram and it works now.
Thanks

**Comment by cdeboever3** [comment]
Added some [text](https://github.com/frazer-lab/cluster/wiki#using-java) to the wiki about using Java.
