### ISSUE TITLE
Arial font for matplotlib

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#90]
I'm trying to make plots in matplotlib using Arial font. I deleted the matplotlib font cache (`~/.cache/matplotlib/fontList.cache`) so that it would be rebuilt and tried to plot something like this (in an IPython notebook):

```
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['font.sans-serif'] = ['Arial']
plt.scatter([1,2,4], [4,5,7])
```

and matplotlib gives me the following warning:

```
/frazer01/home/cdeboever/software/anaconda/envs/cie/lib/python2.7/site-packages/matplotlib/font_manager.py:1287: UserWarning: findfont: Font family [u'sans-serif'] not found. Falling back to Bitstream Vera Sans
  (prop.get_family(), self.defaultFamily[fontext]))
```

Do we have Arial font available?

**Comment by tatarsky** [comment]
IIRC Arial is a TrueType font that you load via ttfmkfont or something from its Microsoft original TTF font. I'll review it Monday.

**Comment by tatarsky** [comment]
So I found a nicer "do the work for you" writeup. And ran it on hn1 and hn2. Please see if that provides access to the so-called "Microsoft" fonts. 

http://mscorefonts2.sourceforge.net/

If needed on the nodes, advise.

**Comment by cdeboever3** [comment]
Thanks, works at least on hn2. I think it makes sense to propagate to the nodes. For future reference, anyone who has already been using matplotlib must delete their font cache (`rm ~/.cache/matplotlib/fontList.cache` for me) so that it will be rebuilt and the new fonts are found.

**Comment by tatarsky** [comment]
I'm trying to determine the best way to get this onto the nodes.

**Comment by tatarsky** [comment]
Its a bit odd but I think I automated it. But before I release it to a bunch of other nodes do you mind seeing if on `n1` if your python works?

**Comment by cdeboever3** [comment]
I verified that it is working on hn1, hn2, and n1.

**Comment by tatarsky** [comment]
OK. Seeing if I can release it to all the nodes...

**Comment by tatarsky** [comment]
Based on the presence of

```
/usr/share/fonts/msttcore/arial.ttf
```

I believe its out there on all systems.

**Comment by tatarsky** [comment]
Just checking this is all good before I turn into a driving machine for a day...

**Comment by cdeboever3** [comment]
I'll test on all nodes when I get a chance but as long as it's working on
hn2 (which it is) then I'm happy for now. Thanks

**Comment by tatarsky** [comment]
Cool. Just making sure you aren't waiting on me as I roll east....no rush.

**Comment by tatarsky** [comment]
Closing for now. Re-open if found not there.
