### ISSUE TITLE
Connecting IPython parallel engines running on scheduled nodes to controller 

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#91]
I'm trying to make an "IPython cluster" by running an ipcontroller on flh2 and ipengines on the compute nodes as described in [the "SGE Parallel Computing" part of a guide I put together a month ago](https://github.com/frazer-lab/cluster/blob/master/IPython%20Parallel%20Computing%20Guide.ipynb). This worked when I put the guide together but now it doesn't. Some of the relevant IPython documentation is [here](https://ipyparallel.readthedocs.org/en/latest/process.html). Basically, this involves starting a controller on the flh2 which listens for connections from engines:

```
(cie)[~]fl-hn2 $ ipcontroller --profile=parallel
2016-01-03 15:03:09.526 [IPControllerApp] Hub listening on tcp://*:57850 for registration.
```

I can set the port that the controller listens on as well a lot of other stuff (see *py files in `/frazer01/home/cdeboever/.ipython/profile_parallel`). When I launch engines on the nodes (e.g. `ipengine --profile=parallel`, I get a timeout error:

```
2016-01-03 15:06:27.116 [IPEngineApp] Loading url_file u'/frazer01/home/cdeboever/.ipython/profile_parallel/security/ipcontroller-engine.json'
2016-01-03 15:06:27.136 [IPEngineApp] Registering with controller at tcp://169.228.63.175:57850
2016-01-03 15:06:32.142 [IPEngineApp] CRITICAL | Registration timed out after 5.0 seconds
```

I currently listen for connections from all IP addresses ([see "Set up" section of "SGE Parallel Computing](https://github.com/frazer-lab/cluster/blob/master/IPython%20Parallel%20Computing%20Guide.ipynb)), so maybe we need to open the port or something? Also, is there a more restricted set of IP addresses that I should listen to for security?

**Comment by tatarsky** [comment]
It looks to me in the above you are binding to the external (UCSD network) address: `169.228.63.175`. 

Which doesn't make sense for use from items within the cluster but would if you need to talk to it from outside the cluster. 

I would attempt to use only internal IP addresses for the "node to controller" part.. For HN2 the 1G interface is: 10.0.16.11. The 10G interface is 10.8.16.11. Try one of those...

**Comment by tatarsky** [comment]
BTW, `ifconfig` or `ip addr` is generically useful for determining the IP addresses of a host. Only the head nodes have 169.228..X.X addresses as they are attached to UCSD networks. 

Depending on the performance needs of this app I would use either 1G or 10G. Bear in mind the older `cnX` nodes only currently have 1G....

I'm off to dinner now but happy to assist tomorrow if the above does not make sense.

**Comment by cdeboever3** [comment]
Thanks, this seems to be working from the opt nodes and new nodes after adding changing 

```
c.HubFactory.engine_ip = '*'
c.HubFactory.ip = '*'
```

to

```
c.HubFactory.engine_ip = '10.0.16.11'
c.HubFactory.ip = '10.0.16.11'
```

in my `ipcontroller_config.py` IPython configuration file. It also works with the 10G interface from the new new nodes if I change the IP addresses accordingly. I'll update my guide to include this info. 

The 1G and 10G interfaces for hn1 are 10.0.16.10 and 10.8.16.10 right? eth3 (169.228.63.174) is the connection to the external internet?

**Comment by tatarsky** [comment]
That is correct. 

Anything that starts with:

10.0  is 1G. 
10.8  is 10G
169.228 is UCSD network space

**Comment by cdeboever3** [comment]
Great thanks. Guide updated.
