### ISSUE TITLE
new member

### ISSUE THREAD

**Issue by s041629** [frazer-lab/cluster#93]
Hi Paul,
we have a new group member (Bill Greenwald, billgreenwald@eng.ucsd.edu) who needs to access the cluster.
What information do you need to add him?

Thanks!

**Comment by s041629** [comment]
Bill has just been added to this github group (billgreenwald)

**Comment by tatarsky** [comment]
I just need a suggested username and UID. I am using puppet to make accounts (which I will explain shortly and document as I make this account)

**Comment by tatarsky** [comment]
To be clear, what username do folks want for Bill? I'm waiting for that question to be answered...

**Comment by hirokomatsui** [comment]
bill is ok. Can you set the password arbitrarily, say his email or ones we use in common, then he will reset is as he wants. We'll ask you to run puppet if needed after changing the password.

**Comment by tatarsky** [comment]
Yep. One moment.

**Comment by tatarsky** [comment]
Have him login to the head node 1 and change his password.
Username: bill
Password: his email address before the @ sign. All lowercase.

**Comment by hirokomatsui** [comment]
Can you make another account, patrick

**Comment by tatarsky** [comment]
Got a full name? Just to fill it in.

**Comment by hirokomatsui** [comment]
Patrick Fiaux

**Comment by tatarsky** [comment]
Account `patrick` made with a password of the name above with capitals as typed but NO SPACE.
Have him login asap and change password on HN1 with passwd command.

**Comment by tatarsky** [comment]
Noted Bill changed password. Refining part of this process....

**Comment by hirokomatsui** [comment]
Bill had, and Patrick had changed right now. Thanks!

**Comment by tatarsky** [comment]
OK. I noticed a slight race condition if they happen to change it when puppet is running its hourly change. So I'll fix that and I remembered I have to make sure the accounts exist on the Metadata servers as well so I'm adding puppet to those machines carefully....

So I'm close to a NIS replacement but found those bugs.

I've attempted in this creation to make sure the so-called "skel" or skeleton bash files exist. 

useradd is the command used. More once I fix the above condition...

**Comment by tatarsky** [comment]
Note: leaving this open to remind me to script the process.

**Comment by hirokomatsui** [comment]
Hi Paul, I've just added a new account, aga, using useradd and done the passwd command. Could you puppet it?

**Comment by tatarsky** [comment]
Done. Puppet runs hourly. If you need it faster advise. I have to automate one more part of this.

**Comment by tatarsky** [comment]
For my reminder: the metadata servers require the same entry and should be carefully added to puppet with a specific set of rules that only modify a few items.

**Comment by hirokomatsui** [comment]
I see. Thanks!

**Comment by tatarsky** [comment]
And I forced the puppet run anyway so `aga` should be all set. Advise if not and I'll finish the docs up for the puppet step. I'd like to automate the process so that `useradd` triggers the puppet part. I think I can do so.

**Comment by tatarsky** [comment]
Final stages of testing this process....just FYI.
