### ISSUE TITLE
Power matters SDSC

### ISSUE THREAD

**Issue by tatarsky** [frazer-lab/cluster#94]
I am hearing from other groups I support there is some kind of power incident going on at SDSC. I don't show any problems at the moment on the frazer cluster but keep reading. 

The SDSC status page is stating a partial outage but due to UPS failure. 

Which we are not on.

http://status.externsdsc.org/2016/01/05/sdsc-outage-notification-datacenter-partial-power-loss-1610-1-jan-2016/

I am monitoring the situation. At the moment I believe we will be non-impacted but if you hear otherwise please let me know.

**Comment by hirokomatsui** [comment]
I'm asking them that. 10G network seems fine, but 1G.

**Comment by tatarsky** [comment]
Ah. I see that. The external ports for your old head node are down.

You can get from the frazer head nodes over to flc however. So that link is up.

**Comment by tatarsky** [comment]
Ah, but its hanging I assume over NFS mounts to that other device.

**Comment by tatarsky** [comment]
Yep. Confirmed the eth1 on `flc` is down. Which is its external network tap. 
Which means SDSC networking is on that UPS. So you are indeed impacted in that way. 

```
[11945608.206100] e1000e: eth1 NIC Link is Down
```

**Comment by tatarsky** [comment]
I show the external interface of `flc` just came back up. So something is being repaired.

**Comment by tatarsky** [comment]
Appears the matter is resolved. Not seen any further issues.
