### ISSUE TITLE
Jobs Won't Start

### ISSUE THREAD

**Issue by billgreenwald** [frazer-lab/cluster#95]
I created a job a few hours ago and it still hasn't started (in the long queue).  According to the queue, there are enough cores available in the queue.  Any ideas?

**Comment by tatarsky** [comment]
long.q is two nodes (fl-n-1-14 and fl-n-1-15). 

But its a stacked queue per previous request with short.q and all.q sharing the same total core count on the node. (no more than 32 slots for **all** queues)

I show you've asked for 32 cores and to use that long queue. 

Right now node fl-n-1-15 has one job also in long.q for 16 cores. So it can't fit there. 

fl-n-1-16 has a short.q job on it for 13 cores. So it can't fit there. 

When the short.q job exists you'll get fl-n-1-16.

Do you really need the walltime of long.q ?

**Comment by billgreenwald** [comment]
I dont need the walltime of long queue, but we were trying to have david's jobs run on short and run our jobs on long since he has many small jobs that we didnt want to interfere with.

**Comment by tatarsky** [comment]
Try running yours on default queue...short.q will still get priority and you will get a larger pool of nodes for a 32 slot request.

**Comment by tatarsky** [comment]
Or even week.q. 
all.q (default) has a 48 hour wall clock limit without the priority of short
week.q (-l week) has a 7 day wall clock limit.
Both can stack on all nodes.

**Comment by s041629** [comment]
We are trying to figure out the best way to run some analyses.  So we  are trying long and week queue with different parameters. We asked you just because looking at qstat -g c we see that long.q has 48 cores available.

Thanks!

**Comment by tatarsky** [comment]
I don't show that with qstat -g -c:

```
 qstat -g c 
CLUSTER QUEUE                   CQLOAD   USED    RES  AVAIL  TOTAL aoACDS  cdsuE  
--------------------------------------------------------------------------------
long.q                            0.28     48      0     16     64      0      0 
```

I show 16 cores available. And with that command its a total summary and since you are asking for a block of 32 cores it _must_ fit on a node. (pe smp requires your job take a node)

**Comment by tatarsky** [comment]
I'd give it a try with `week.q`....note that we can adjust these rules but try to check the long discussion in #24 to make sure the history is known.

**Comment by tatarsky** [comment]
Aka `qsub -l week`

**Comment by tatarsky** [comment]
One thing I sometimes see BTW over time is the long.q nodes are removed from being able to run shorter jobs....but we talked about that and didn't want them idle. But its doable. Just mull over your patterns ;)

**Comment by tatarsky** [comment]
Folks good? Reason I'm checking is I will be mostly offline for the next day as I drive to D.C.

**Comment by billgreenwald** [comment]
Yea its working now for some reason

**Comment by tatarsky** [comment]
His short.q job that was holding 16 of the 32 slots on the one node exited. 
Remember when you ask for 32 slots you are a "whole node" job and it not always easy to find a node with no other job on it. While I don't know your requirements it a whole lot easier to process jobs with say 8 or 16 slot smp requests....SGE will do its best to accommodate you at 32 but you will wait.

**Comment by tatarsky** [comment]
Also remember the command: `qstat -explain a -j (jobid)` which will try in SGE's way to try to tell you why you are waiting. Its a bit hard to read but its in there ;)
