### ISSUE TITLE
mount frazer-share

### ISSUE THREAD

**Issue by hirokomatsui** [frazer-lab/cluster#97]
I've got a request to mount frazer-share.ucsd.edu on the new cluster. It's a NAS on campus network. Do you think there's any problem to do that? The old system has that, the setting is in the file:
flc.ucsd.edu:/etc/fstab

**Comment by tatarsky** [comment]
To be clear I can mount it on the head nodes as they have external IPs trivially. 

But from nodes its something we need to discuss as NAT'ing NFS can cause odd locking matters depending on the NFS server (nfsv4 nat's a little better with some extra config but we should test). I show the NAS in question appears to be exporting v4. 

So I can make the mount on fl1 and fl2 but for the nodes we need to test and I may need to make a setting change. 

I don't know if you need it from the nodes so just clarify.

Do you want the same mount point of `/nas`?

**Comment by tatarsky** [comment]
I made a test mount but I'm showing lots of uids for numbers that do not exist on the new cluster.
So take a look at `/nas` on flhn1 and confirm thats what you expect and answer the question about the nodes and we'll proceed with a more final config.

I am in and out all day tomorrow again as well per #92

**Comment by tatarsky** [comment]
I also added it on `flhn2` to be consistent. The final mount method will be via automount which I will configure when I have more time at JHU.

**Comment by hirokomatsui** [comment]
Yes, that's exactly what we needed. Thanks!

**Comment by tatarsky** [comment]
Cool. I will add the final config to automount when I get to a more usable bandwidth situation

**Comment by hirokomatsui** [comment]
Hi Paul, could you please check the mounting?

**Comment by tatarsky** [comment]
The mount for some reason is now saying 

df: `/nas': Permission denied

Attempting to remount....fl-hn1 system is fine...no crashes seen.

**Comment by tatarsky** [comment]
Please check that the NAS system is happy....it is denying the mount. 

``` mount -t nfs frazer-share.ucsd.edu:/shares/Public /nas
mount.nfs: access denied by server while mounting frazer-share.ucsd.edu:/shares/Public
```

showmount -e frazer-share.ucsd.edu
rpc mount export: RPC: Unable to receive; errno = Connection refused

**Comment by tatarsky** [comment]
And even on the older "flc" server:

paul@hn:~> ls /nas
ls: cannot access /nas: Stale file handle

So something is sad on that NAS unit export....

**Comment by hirokomatsui** [comment]
Mmm, it looks fine for me.
https://frazer-share.ucsd.edu
username:admin, password as the same as the other root user.
You can also ssh with the same account.
I can map that from my PC. Actually the nas is located in our office, and other servers at SDSC. Maybe some (virtual) network issue?

**Comment by tatarsky** [comment]
When you say "map that" do you mean an NFS mount? Because its NFS exports are broken.
Network seems fine, but the NFS (which is not the same as SMB) isn't working anymore. All the mounts from our systems are dead. I'm looking at its logs. 

Is there a way to "restart NFS" on this system?

**Comment by tatarsky** [comment]
If I had to guess a program called "mountd" in some form has died....

**Comment by tatarsky** [comment]
On the NAS....I'll look at the web gui in a moment.

**Comment by hirokomatsui** [comment]
I meant mapping as a SMB client.
I'm not sure if we can restart only the NFS. I will everyone to restart the system it self in the case.
Thanks!

**Comment by tatarsky** [comment]
OK. I'm around for a bit more so just let me know when restarted and I can redo the mounts on the fl-hn1/fl-hn2 and flc!

**Comment by hirokomatsui** [comment]
It's restarted!

**Comment by joreynajr** [comment]
Thanks Hiroko and Paul!

**Comment by joreynajr** [comment]
Sorry I thought you meant the NAS was restarted :P. In any case thanks for working on this!

**Comment by tatarsky** [comment]
Remaking mounts!

**Comment by tatarsky** [comment]
Working now.

**Comment by hirokomatsui** [comment]
Thanks!

**Comment by tatarsky** [comment]
Did we have this mount on fl-hn2? I forget ;)

**Comment by tatarsky** [comment]
We must have at some point. made.

**Comment by joreynajr** [comment]
Thanks!

**Comment by tatarsky** [comment]
No prb. happy friday.

**Comment by hirokomatsui** [comment]
I was trying to mount frazer-share to /nas, then got
[root@fl-hn1 ~]# mount -t nfs frazer-share.ucsd.edu:/Public /nas
Job for rpc-statd.service failed because the control process exited with error code. See "systemctl status rpc-statd.service" and "journalctl -xe" for details.
mount.nfs: rpc.statd is not running but is required for remote locking.
mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
mount.nfs: an incorrect mount option was specified

Can you check it? Please let me know if I have to re-start NFS server on frazer-share which sometime needed because it's on other VLAN.

**Comment by tatarsky** [comment]
One moment!

**Comment by tatarsky** [comment]
Be aware please that /nas is an automount now....so thats one item. But checking what is wrong with the mount. I am showing similar issues to last time in that it is not responding....

**Comment by tatarsky** [comment]
Also checking though that I added NFS client to fl-hn1....

**Comment by tatarsky** [comment]
Check now. Forgot to enable rpcbind!

**Comment by tatarsky** [comment]
```l-hn1 etc]# ls /nas
Admin_FRAZER                 Illumina_BeadChip   Posters
Admin_IGM Review and Delete  iPSC Recharge Unit  Presentation_Figures
adobe.dmg                    Lab_photos          Projects
CONTACTS                     laptop_dump         Sample_Locations
copy.cmd                     Nero LIVEBackup
Course materials             Personal folders
```

**Comment by hirokomatsui** [comment]
Find it, thanks!

**Comment by tatarsky** [comment]
I will also add an automount for the fl-nas1.

**Comment by tatarsky** [comment]
OK. That is also now back mounted as /backup01.

There automounts trigger when you access them. So you don't have to manually mount them. Just cd to them:

```
cat /etc/auto.frazer-headnode 
/nas            frazer-share.ucsd.edu:/shares/Public
/backup01       fl-nas1:/backup01
```
Let me know if you need others! (NFS that is...)

**Comment by tatarsky** [comment]
Do you need /backup01 on fl-hn2?

**Comment by hirokomatsui** [comment]
No, only flh1 is fine.

**Comment by tatarsky** [comment]
Okey doke!
