### ISSUE TITLE
Resource temporarily unavailable problem

### ISSUE THREAD

**Issue by cdeboever3** [frazer-lab/cluster#99]
I'm seeing this when I try to run `pdsh`.

```
$ pdsh -g n "if [ -d "/dev/shm/ENSG00000213760.6" ]; then rm -r /dev/shm/ENSG00000213760.6 ; fi ; if [ -d "/dev/shm/ENSG00000263020.1" ]; then rm -r /dev/shm/ENSG00000263020.1 ; fi"
pdsh@fl-hn2: pipecmd: fork: Resource temporarily unavailable
pdsh@fl-hn2: pthread_create fl-n-1-15: Resource temporarily unavailable
pdsh@fl-hn2: pipecmd: fork: Resource temporarily unavailable
```

I think it's been like this all morning although I just noticed it now.

**Comment by tatarsky** [comment]
Hmm. Can we try to confirm the error is just coming from n15?

**Comment by tatarsky** [comment]
I don't get the error on regular pdsh of a basic command.

**Comment by tatarsky** [comment]
I think the error actually came from hn2. Being unable to fork usually implies a process limit situation. Is it still doing this for you? You do have a fair number of processes running. Is this via the same parent shell?

**Comment by cdeboever3** [comment]
This is a fresh login. I do see the same problem on n13 if I keep trying to
run that command. I actually ran into a weird fork error last night. I have
to go out for a minute but let me see if I can get my processes under
control and make this go away.

**Comment by tatarsky** [comment]
I suspect its actually a file limit. You have a considerable number of open files on fl-hn02.

**Comment by tatarsky** [comment]
We can up the default BTW. I believe its 1024 per user.

**Comment by tatarsky** [comment]
It may also be the nproc limit default. I've removed that for now. Try a fresh shell and see if your `ulimit -a` output max user processes is > 1024.

**Comment by tatarsky** [comment]
I'll adjust open files next if that wasn't it.

**Comment by cdeboever3** [comment]
That makes sense. I've been having several weird problems and was wondering
what was going on. I'll close some files and see if it clears up. If I keep
bumping the limit maybe we can up it.

**Comment by tatarsky** [comment]
"Resource temporarily unavailable" usually means "some ulimit was hit. We're not going to tell you which one but what you asked for we were told you shouldn't have". Linux is cagey that way.

**Comment by tatarsky** [comment]
All our limits are defaults. We can tune to need.

**Comment by tatarsky** [comment]
python BTW loves to open zillions of files.

**Comment by tatarsky** [comment]
I will also be back in a moment...small errand.

**Comment by cdeboever3** [comment]
I closed some notebooks and the problem went away. It was probably open
files. pybedtools leaves files open all over the place. I try to
periodically restart my notebooks to remedy this. I don't think I need any
limit changes for now, thanks.
